### DISCUSSION TITLE
Received successful OpenID Connect callback but user is not registered (identity exist)

### DISCUSSION THREAD

**Discussion by TaSiya** [ory/kratos#1002] [Q&A] [answered]
**Describe bug**

When I login with an existing identity in kratos, I get that the `user already exist`. I get this because it goes through the registration flow after successful login with hydra but kratos says `Received successful OpenID Connect callback but user is not registered`, then registration hook starts the registration flow.

**Reproducing the bug**

- Login using hydra as the provider
- fill form in consent app
- login and accept the consent scopes

**Expected behavior**

I expect to be logged in as the *user/identity* instead of trying to create the identity again. I do get the correct values from the claims requested. 

**Configuration**

I always have the email for testing purposes

oidc.hydra.jsonnet
```jsonnet
local claims = {
  email_verified: false
} + std.extVar('claims');

{
  identity: {
    traits: {
      email: claims.email
    },
  },
}
```

kratos.yml
```yml
#...
methods:
    password:
      enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: hydra
            provider: generic
            mapper_url: file:///etc/config/kratos/oidc.hydra.jsonnet
            client_id: client-id
            client_secret: this-is-the-secret
            scope:
              - profile
              - openid
            issuer_url: http://my-issuer.com/
            requested_claims:
              userinfo:
                email:
                  essential: true
#...
```
