### DISCUSSION TITLE
Proper way to configure OIDC with email verification?

### DISCUSSION THREAD

**Discussion by marcinkoziej** [ory/kratos#1045] [Q&A] [answered]
Hi!
I have confiured the OIDC with Google, and it works, however, the `verifiable_emails` array contains the email with `verified: false` and `status: "pending"`.
I'd like the email fetched via OIDC be treated as verified because Google has verified it already

My config is as follows:

Kratos:
```
selfservice:
(..._
  methods:
(....) 
   oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: generic
            client_id: "..............................................apps.googleusercontent.com"
            client_secret: "........................................................."
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://oauth2.googleapis.com/token
            mapper_url: file:///ory/kratos/google.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                email_verified:

```

`google.jsonnet` is [i thought the `email_verified: true` at line 2 makes the it true by default]:

```
local claims = {
  email_verified: true
} + std.extVar('claims');

{
  identity: {
    traits: {
      [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
			first_name: claims.given_name,
			last_name: claims.family_name,
    },
  },
}
```

The identity spec contains traits: email, first_name, last_name:

```
{
  "$id": "https://fixthestatusquo.com/schemas/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "first_name": {
          "type": "string",
          "title": "First name",
          "minLength": 1
        },
        "last_name": {
          "type": "string",
          "title": "Last name",
          "minLength": 1
        }
      },
      "required": [
        "first_name",
        "last_name",
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```
