### DISCUSSION TITLE
How to add DB certificates to a Kratos helm deploy

### DISCUSSION THREAD

**Discussion by ajunca** [ory/kratos#1111] [Q&A] [answered]
Hi,

I'm trying to deploy Kratos in Kubernetes. I already have a distributed cockroachdb running in secure mode inside the cluster. One of the problems that I'm trying to solve now (I say one of the problems, because ory stack is fairly complicated to deploy and helm documentation is very minimal, so more issues will arise for sure) is how to deal with database certificates.

An example on cockroachdb git page [example-app-secure.yaml](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/example-app-secure.yaml) does this in three steps:
1- An init container is executed before the actual pod and asks for csr certificates
2- Manually approving the certificate
3- On the actual pod, mount the volume that the init container ask for with the certificates and voilà

How can I reproduce this using Kratos helm chart? I tried to attach an InitContainer without success. I'm fairly lost, Kratos documentation on helm deploy is very little. As a workaround I tried to connect Kratos using an insecure database connection (using user and password already created inside the db), cockroachdb refuse the connection because is not secure, so this doesn't seems an option.

Any help would be very appreciated as I been trying this for days without success.

**Comment by ajunca** [comment]
I've been digging more and I think I just answered my self: I can use helm post-renderer (aka Kustomize) and apply some modification to the generated helm resource before it is applied to the API server. So I guess I could add an init container and mount the certificate volume afterwards to the kratos container. 

I'm still confused about other init container that kratos helm has. Particularly the one is checking that the dns connection is OK(?) I'm guessing I will have to remove this check as I'm not sure how I can give the certificates to that init container... 

Tomorrow I will try this but I'm still quite confused. Any more suited/easy solution will be welcomed.

**Comment by aeneasr** [comment, marked as answer]
@tricky42 you can probably answer this :)

**Reply by tricky42** [reply]
Sure and sorry @junky89 to hear you got stuck on this for several day.
Can you share how you deployed the CockroachDB Cluster, then we can give more specific advise. 

In order to automate the steps you mentioned before the Kratos Helm chart needs to be extended to support 
- extraInitContainer(s) to be configured via values.yaml similar to e.g. the [Postgres Chart](https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/postgresql/templates/statefulset.yaml#L73). 

Once this is available you need to 
- configure the initContainer using values.yaml to ask for cert as described in the Cockroach example
- configure the the volumeMount using values.yaml / `.Values.deployment.extraVolumeMounts`

>I'm still confused about other init container that kratos helm has. Particularly the one is checking that the dns connection is OK(?) I'm guessing I will have to remove this check as I'm not sure how I can give the certificates to that init container...
The initContainer is not only checking the DSN connection, it is applying any needed schema migrations before the "normal" pods are being started. 

In order to unblock yourself and if you are familiar with Helm Chart templating you can checkout the Kratos Helm chart and change `https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/deployment.yaml` to support the definition of extraInitContainers basically copying the solution in the PostgreSQL chart. 

If you want to give it a try, that would be great and we can support you on your way. In this case I would suggest to connect in our Slack so we can help you more quickly.

**Reply by ajunca** [reply]
First of all, thank you for the fast response. 

> Can you share how you deployed the CockroachDB Cluster, then we can give more specific advise

I deployed cockroachdb inside a kubernetes cluster with rancher using this helm values (attached at the end of the message).

> extraInitContainer(s) to be configured via values.yaml similar to e.g. the Postgres Chart.

As I understand this functionality is desired for the main project? (question linked to the next paragraph)

> In order to unblock yourself and if you are familiar with Helm Chart templating you can checkout the Kratos Helm chart and change https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/deployment.yaml to support the definition of extraInitContainers basically copying the solution in the PostgreSQL chart.

To be honest I'm not really familiar with Helm (nor with kubernetes), just begin using it for this project. I can try to go this route, but just thinking that I will have to maintain a fork of the original helm with the changes it really turns me off. Do you think that If I make the appropriated changes (with your help of this community in slack) to add this functionality, then the changes can be pushed to the master branch? I ask because if not, I will probably try the post-renderer route as I don't have to maintain a fork of the chart. 

Thanks again, I really appreciated the help. 

Cockroachdb helm:
```
clusterDomain: cluster.local
conf:
  attrs: []
  cache: 25%
  cluster-name: ''
  disable-cluster-name-verification: false
  http-port: 8080
  join: []
  locality: ''
  logtostderr: INFO
  max-sql-memory: 25%
  port: 26257
  single-node: false
  sql-audit-dir: ''
image:
  credentials: {}
  pullPolicy: IfNotPresent
  repository: cockroachdb/cockroach
  tag: v20.2.5
ingress:
  annotations: {}
  enabled: false
  hosts: []
  labels: {}
  paths:
    - /
  tls: []
init:
  affinity: {}
  annotations: {}
  labels:
    app.kubernetes.io/component: init
  nodeSelector: {}
  resources: {}
  tolerations: []
labels: {}
networkPolicy:
  enabled: false
  ingress:
    grpc: []
    http: []
service:
  discovery:
    annotations: {}
    labels:
      app.kubernetes.io/component: cockroachdb
  ports:
    grpc:
      external:
        name: tcp
        port: 26257
      internal:
        name: grpc-internal
        port: 26257
    http:
      name: http
      port: 8080
  public:
    annotations: {}
    labels:
      app.kubernetes.io/component: cockroachdb
    type: ClusterIP
serviceMonitor:
  annotations: {}
  enabled: false
  interval: 10s
  labels: {}
statefulset:
  annotations: {}
  args: []
  budget:
    maxUnavailable: 1
  env: []
  labels:
    app.kubernetes.io/component: cockroachdb
  nodeAffinity: {}
  nodeSelector:
    db-storage: "true"
  podAffinity: {}
  podAntiAffinity:
    topologyKey: kubernetes.io/hostname
    type: soft
    weight: 100
  podManagementPolicy: Parallel
  priorityClassName: ''
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  secretMounts: []
  tolerations: []
  topologySpreadConstraints:
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
storage:
  hostPath: ''
  persistentVolume:
    annotations: {}
    enabled: true
    labels: 
      db-storage: "true"
    size: 100Gi
    storageClass: local-storage
tls:
  certs:
    clientRootSecret: root-secret
    nodeSecret: node-secret
    provided: false
    tlsSecret: true
  enabled: true
  init:
    image:
      credentials: {}
      pullPolicy: IfNotPresent
      repository: cockroachdb/cockroach-k8s-request-cert
      tag: '0.4'
  serviceAccount:
    create: true
    name: ''
```
