### DISCUSSION TITLE
[OIDC] LINE login use unsupported algorithm HS256 instead of expected ES256

### DISCUSSION THREAD

**Discussion by vacharanon** [ory/kratos#1116] [Q&A] [answered]
Hello,

While I was trying to integrate [LINE](https://developers.line.biz/en/docs/line-login/integrate-line-login/#making-an-authorization-request) with Kratos' OIDC, I was presented with error : "oidc: id token signed with unsupported algorithm, expected ["ES256"] got "HS256""

LINE specifically told is in their document with no way to change the algorithm
![image](https://user-images.githubusercontent.com/818187/109810487-2a184080-7c5c-11eb-923e-8f9187d39dcf.png)

Is there anywhere I can make Kratos understand HS256? Here is my current configuration.

```yaml
- id: line
  provider: generic
  client_id: ...
  client_secret: ...
  mapper_url: file:///etc/config/kratos/oidc.line.jsonnet
  scope:
    - email
  issuer_url: https://access.line.me
  auth_url: https://access.line.me/oauth2/v2.1/authorize
  token_url: https://api.line.me/oauth2/v2.1/token
```
