### DISCUSSION TITLE
How to set the `client_secret` in kratos.yml for an OIDC provider?

### DISCUSSION THREAD

**Discussion by johanforssell** [ory/kratos#1186] [Q&A] [answered]
Hello!

According to [the docs](https://www.ory.sh/kratos/docs/reference/configuration/) I can set `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS` as an environment variable, but as that represents the whole block, I don't really see how

```
        providers:
          - id: google
            provider: google
            client_id: ''
            client_secret: ''
            mapper_url: file://path/to/oidc.jsonnet
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://www.googleapis.com/oauth2/v4/token
            scope:
              - offline_access
            tenant: common
            requested_claims:
              id_token:
                email:
                email_verified:
            issuer_url: https://accounts.google.com
```

I just want to pick the `client_secret` from the environment - should I specify `SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_google_client_secret` or what? (I guess not).

Could I get an example?
