### DISCUSSION TITLE
Basic Kind setup : error msg=The provided configuration is invalid

### DISCUSSION THREAD

**Discussion by leorolland** [ory/kratos#1453] [Q&A] [answered]
**Describe the bug**

After working for few months with the ory.sh suite in docker-compose, I decided to switch to the k8s, I am a beginner with k8s.
I followed both the instructions from https://k8s.ory.sh/helm/kratos.html and cloning/installing chart from this repository. Every try fails to this error.

```bash
$ k logs mykratos-6fbb65d576-qcprs
time=2021-06-22T09:30:25Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos.yaml service_name=kratos service_version=
time=2021-06-22T09:30:25Z level=error msg=The provided configuration is invalid and could not be loaded. Check the output below to understand why. audience=application config_file=/etc/config/kratos.yaml service_name=kratos service_version=

identity: <nil>
          ^-- one or more required properties are missing

selfservice.default_browser_return_url: <nil>
                                        ^-- one or more required properties are missing

courier.smtp.connection_uri: <nil>
                             ^-- one or more required properties are missing

time=2021-06-22T09:30:25Z level=fatal msg=The services failed to start because the configuration is invalid. Check the output above for more details. audience=application service_name=kratos service_version=
```

Note that i am using a Kind cluster with 3 worker nodes and 1 control pane node.
The kind cluster seems to work well for other charts like kubeview, postgres, pgadmin but not kratos.

**To Reproduce**

1. create a values.yaml with following content :
```yaml
kratos:
  config:
    dsn: sqlite://./db.sqlite?_fk=true
    secrets:
      session:
        - dolore occaecat nostrud Ut
        - sit et commodoaute ut voluptate consectetur Duis
```

2. Install chart with `helm install mykratos -f values.yaml ory/kratos`

**Environment**

Helm : 3.6.0
Kind : v0.11.1 go1.16.5 linux/amd64

**Additional context**
Kind default image doc : https://kind.sigs.k8s.io/docs/design/node-image
I am using NGINX ingress controller and i install it by default when creating my cluster by running the command specified in the Kind documentation :
```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s% 
```

Debug output with an updated values.yaml where i added missing values
```bash
helm install mykratos -f values.yaml ory/kratos --dry-run --debug
```
<details>
  <summary>Click to see output</summary>
values.yaml :

```
kratos:
  config:
    dsn: sqlite://./db.sqlite?_fk=true
    secrets:
      session:
        - dolore occaecat nostrud Ut
        - sit et commodoaute ut voluptate consectetur Duis
  identity: kratos
  selfservice:
    default_browser_return_url: http://google.fr/
  courier:
    smtp:
      connection_uri: none
```

Output

```
NAME: mykratos
LAST DEPLOYED: Tue Jun 22 11:57:14 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
USER-SUPPLIED VALUES:
kratos:
  config:
    dsn: sqlite://./db.sqlite?_fk=true
    secrets:
      session:
      - dolore occaecat nostrud Ut
      - sit et commodoaute ut voluptate consectetur Duis
  courier:
    smtp:
      connection_uri: none
  identity: kratos
  selfservice:
    default_browser_return_url: http://google.fr/

COMPUTED VALUES:
affinity: {}
automountServiceAccountToken: false
deployment:
  annotations: {}
  environmentSecretsName: null
  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []
  labels: {}
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
  tracing:
    datadog:
      enabled: false
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: oryd/kratos
  tag: v0.5.5-alpha.1-sqlite
imagePullSecrets: []
ingress:
  admin:
    annotations: {}
    enabled: false
    hosts:
    - host: kratos.admin.local.com
      paths:
      - /
    tls: []
  public:
    annotations: {}
    enabled: false
    hosts:
    - host: kratos.public.local.com
      paths:
      - /
    tls: []
job:
  annotations: {}
kratos:
  autoMigrate: false
  config:
    courier:
      smtp: {}
    dsn: sqlite://./db.sqlite?_fk=true
    secrets:
      session:
      - dolore occaecat nostrud Ut
      - sit et commodoaute ut voluptate consectetur Duis
    serve:
      admin:
        port: 4434
      public:
        port: 4433
  courier:
    smtp:
      connection_uri: none
  development: false
  identity: kratos
  selfservice:
    default_browser_return_url: http://google.fr/
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
secret:
  enabled: true
  secretAnnotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 100
service:
  admin:
    annotations: {}
    enabled: true
    port: 80
    type: ClusterIP
  public:
    annotations: {}
    enabled: true
    port: 80
    type: ClusterIP
tolerations: []

HOOKS:
---
# Source: kratos/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mykratos
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.14.1
    app.kubernetes.io/instance: mykratos
    app.kubernetes.io/version: "0.6.3-alpha.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
type: Opaque
data:
  dsn: "c3FsaXRlOi8vLi9kYi5zcWxpdGU/X2ZrPXRydWU="
  # Generate a random secret if the user doesn't give one. User given secret has priority
  secretsDefault: "dXkxbGo0SUg5bDhEekpyd0xuRmx0TVZXblYycFRYNzg="
  secretsCookie: "ek5hNGpEMVJvbzBnRlVSYUM0c2JkTFRoUjg0S1ZJcUQ="
---
# Source: kratos/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "mykratos-test-connection"
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.14.1
    app.kubernetes.io/instance: mykratos
    app.kubernetes.io/version: "0.6.3-alpha.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['mykratos:80/health/ready']
  restartPolicy: Never
MANIFEST:
---
# Source: kratos/templates/configmap-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mykratos-config
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.14.1
    app.kubernetes.io/instance: mykratos
    app.kubernetes.io/version: "0.6.3-alpha.1"
    app.kubernetes.io/managed-by: Helm
data:
  # Render the kratos config:
  "kratos.yaml": |
    courier:
      smtp: {}
    serve:
      admin:
        port: 4434
      public:
        port: 4433
  # Render the identity schemas to disk:
---
# Source: kratos/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: mykratos-admin
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.14.1
    app.kubernetes.io/instance: mykratos
    app.kubernetes.io/version: "0.6.3-alpha.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: mykratos
---
# Source: kratos/templates/service-public.yaml
apiVersion: v1
kind: Service
metadata:
  name: mykratos-public
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.14.1
    app.kubernetes.io/instance: mykratos
    app.kubernetes.io/version: "0.6.3-alpha.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-public
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: mykratos
---
# Source: kratos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykratos
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.14.1
    app.kubernetes.io/instance: mykratos
    app.kubernetes.io/version: "0.6.3-alpha.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos
      app.kubernetes.io/instance: mykratos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos
        helm.sh/chart: kratos-0.14.1
        app.kubernetes.io/instance: mykratos
        app.kubernetes.io/version: "0.6.3-alpha.1"
        app.kubernetes.io/managed-by: Helm
      annotations:
    spec:
      volumes:
        - name: kratos-config-volume
          configMap:
            name: mykratos-config
      automountServiceAccountToken: false
      containers:
        - name: kratos
          image: "oryd/kratos:v0.5.5-alpha.1-sqlite"
          imagePullPolicy: IfNotPresent
          command: ["kratos"]
          args: [
            "serve",
            "all",
            "--config",
            "/etc/config/kratos.yaml"
          ]
          volumeMounts:
            - name: kratos-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: mykratos
                  key: dsn
            - name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: mykratos
                  key: secretsDefault
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: mykratos
                  key: secretsCookie
          ports:
            - name: http-admin
              containerPort: 4434
              protocol: TCP
            - name: http-public
              containerPort: 4433
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http-admin
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http-admin
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100

NOTES:
The ORY Kratos HTTP Public API is available via:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=kratos,app.kubernetes.io/instance=mykratos" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:80 to use your application"
  kubectl port-forward $POD_NAME 80:4433
  export KRATOS_PUBLIC_URL=http://127.0.0.1:80/


If you have the ORY Kratos CLI installed locally, you can run commands
against this endpoint:

  kratos ... $KRATOS_PUBLIC_URL

The ORY Kratos HTTP Admin API is available via:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=kratos,app.kubernetes.io/instance=mykratos" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:80 to use your application"
  kubectl port-forward $POD_NAME 80:4434
  export KRATOS_ADMIN_URL=http://127.0.0.1:80/

If you have the ORY Kratos CLI installed locally, you can run commands
against this endpoint:

  kratos ... $KRATOS_ADMIN_URL

```
</details>

### Update 
I have also tried in Minikube and experienced the same issue.
