### DISCUSSION TITLE
How to run Ory kratos with postgres database?

### DISCUSSION THREAD

**Discussion by Dannybrown2710** [ory/kratos#1471] [Q&A] [answered]
Hi team,
I really appreciate the effort spent in developing such an amazing framework.
I was trying to implement kratos it in 2 production projects.
I am trying to dockerise kratos with postgres database. The database is not dockerised but situated on the host machine.
I am getting error TCP dial error, connection timeout in the logs. How to construct DSN for this scenario.?

![image](https://user-images.githubusercontent.com/24778151/123898627-4a92a600-d983-11eb-99a7-2bab11f959f8.png)
[skymed-quickstart-postgres.txt](https://github.com/ory/kratos/files/6737859/skymed-quickstart-postgres.txt)

**Comment by Benehiko** [comment, marked as answer]
Hi @Dannybrown2710 

Sorry for the late reply! :)

Could you please provide more information?
This is usually just a configuration mistake with docker itself and not with kratos, unless the DSN you specified is incorrect - e.g. the ip address of the DB is not reachable by the host.

**Reply by vinckr** [reply]
Hey @Dannybrown2710 , just checking in if your problem still persists. 
I will mark this as answered for now, but feel free to come back to the discussion any time.
Thanks a ton :bee:

**Reply by TB-Development** [reply]
I can confirm that it is possible to connect to a remote postgres database using the quickstart `docker-compose` command.

It's possible that he's not allowed to connect to the remote postgres database by whatever service he is using.  Hence the `connection refused` issue.  Danny, You should verify that your IP address is permitted to access the remote database.  I use AWS RDS, so my ip has to be added to a security group in order to allow access to the database.  

A postgres DSN is formatted like this:

`postgres://user:pass@host/database`

When attempting to connect with this, you need to be sure you can connect to it outside of Kratos first.

So try running a command like this:

`psql -d database_name -h host_name -p port_name -U user_name`

and enter the password if there is one.

If you get a successful connection, then you need to review what information you are giving Kratos in the yml file.
If it still doesn't work, make sure the order you are passing in your yml files is correct.

This quickstart.yml is a combined version of quickstart.yml and quickstart-postgres.yml

```
version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.8.0-alpha.3
    environment:
      - DSN=postgres://user:pass@host/database
    volumes:
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://user:pass@host/database
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    networks:
      - intranet

networks:
  intranet:

```

This is standalone API ^.  No mailer, no self-service ui node.
