### DISCUSSION TITLE
Should I send a CSRF header along with csrf and session cookie?

### DISCUSSION THREAD

**Discussion by frederikhors** [ory/kratos#1521] [Q&A] [answered]
I have all Kratos and Oathkeeper workin good (v0.6.3-alpha-1 and v0.38.12-beta.1).

I have made it working all flows related to login/recovery: it works!

Now the problem:

I'm using grpc in my webapp (SPA).

The cookie is there.

I call oathkeeper (method: POST, with ory_kratos_session cookie set after the login and csrf cookie) but oathkeeper does not authorize the call because kratos says:

```
debug: message:The request was malformed or contained invalid parameters reason:CSRF token is missing or invalid. status:Bad Request status_code:400
```

Should I send within each POST call to my grpc server an header like `X-CSRF-Token` or something? Isn't the csrf cookie enough?

I read all docs: nothing is there for this issue.

### ALTERNATIVE QUESTION

Can we disable CSRF at all with a config option? CSRF is not a problem today with new browsers and correct cookies.

**Comment by frederikhors** [comment]
```
time=2021-07-10T23:58:30Z level=warning msg=A request failed due to a missing or invalid csrf_token value func=github.com/ory/kratos/x.NewCSRFHandler.func1 file=/home/ory/x/nosurf.go:130 audience=application expected_token=ArkOcM9YHZioiBuccmvPtqowUkOX91E3WsZlpk5KVoVSTpP4vgYds/dEz4REJjzcUp/ZBdsPUwBOrzEBJ8pmeQ== received_cookies=[aHR0cDovL2xvY2FsaG9zdDo0NDMzLw_csrf_token=UPediHFeACtfzNQYNk3zavivi0ZM+AI3FGlUp2mAMPw= ory_kratos_session=MTYyNTk1ODg1M3xEdi1CQkFFQ180SUFBUkFCRUFBQVJfLUNBQUVHYzNSeWFXNW5EQThBRFhObGMzTnBiMjVmZEc5clpXNEdjM1J5YVc1bkRDSUFJRlJETkc4eVkwZE1lRkJVT1Voc05GRTVkMHhXV0dzMFRFTnVWVEpzY0ZCMXwd6c9_dsC3WoAmWanvgxGZQ0erivPA9iPEDAxQYQG7Pw==] received_token_body= received_token_form= result=false service_name=Ory Kratos service_version=v0.6.3-alpha.1
```

I'm using this simple fetch:

```ts
fetch("/myApi", {
  method: "POST",
  credentials: "include",
}).then();
```

**Where am I doing wrong?**

**Comment by frederikhors** [comment]
@aeneasr can you help me understand what is going on? Why cannot I authenticate my POST requests?

**Comment by frederikhors** [comment, marked as answer]
I was able to fix this adding the below missing line in `oathkeeper.yml` config file below:

```yml
preserve_path: true
```

under `authenticators > cookie_session > config`, like this:

```yml
access_rules:
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml

authenticators:
  anonymous:
    enabled: true
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      only:
        - ory_kratos_session
  noop:
    enabled: true

errors:
  fallback:
    - redirect
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: http://localhost:5000
        when:
          - request:
              header:
                accept:
                  - text/*

authorizers:
  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User: "{{ print .Subject }}"
  noop:
    enabled: true

log:
  level: debug
  leak_sensitive_values: true

serve:
  proxy:
    port: 4455
  api:
    port: 4456
```
