### DISCUSSION TITLE
config working in 0.6.3-alpha.1 gives error in 0.7.0-alpha.1

### DISCUSSION THREAD

**Discussion by Eifoen** [ory/kratos#1583] [Q&A] [answered]
I have a config.yml which works fine for 0.6.3-alpha.1 but give the error

`level=warning msg=Configuration key serve.public.base_url was left empty. Optimistically guessing the server's base URL. Please set a value to avoid problems with redirects and cookies. audience=application service_name=Ory Kratos service_version=v0.7.0-alpha.1`

in 0.7.0-alpha.1 

Encoding is UTF-8 I tried with CRLF and LF endings. Both did work in 0.6.3 but not in 0.7.0
The config file is the following:

```yaml
version: v0.6.3-alpha.1

## serve ##
#
serve:
  ## public ##
  #
  public:
    ## Base URL ##
    #
    # The URL where the endpoint is exposed at. This domain is used to generate redirects, form URLs, and more.
    #
    # Examples:
    # - https://my-app.com/
    # - https://my-app.com/.ory/kratos/public
    #
    # Set this value using environment variables on
    # - Linux/macOS:
    #    $ export SERVE_PUBLIC_BASE_URL=<value>
    # - Windows Command Line (CMD):
    #    > set SERVE_PUBLIC_BASE_URL=<value>
    #
    base_url: http://auth.kratos.local:8080/
    cors:
      enabled: true

selfservice:
  default_browser_return_url: http://accounts.kratos.local:8080/

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://accounts.kratos.local:8080/error

    settings:
      ui_url: http://accounts.kratos.local:8080/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://accounts.kratos.local:8080/recovery

    verification:
      enabled: true
      ui_url: http://accounts.kratos.local:8080/verify
      after:
        default_browser_return_url: http://accounts.kratos.local:8080/

    logout:
      after:
        default_browser_return_url: http://accounts.kratos.local:8080/auth/login

    login:
      ui_url: http://accounts.kratos.local:8080/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://accounts.kratos.local:8080/auth/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```
It's just a basic demo file.
Any ideas on that?

Greetings
Eifoen
