### DISCUSSION TITLE
Missing session_token cookie on authorization

### DISCUSSION THREAD

**Discussion by kwalczi16** [ory/kratos#1630] [Q&A] [answered]
We are trying to follow login flow on deployed SPA React application. When submitting the form we get 200 and redirect back to target page, but we don't receive `session_token` cookie which should be set on successful authorization. We can only see `redirect_to` and `csrf_token` cookies. 

**Steps to reproduce**

1. Send a GET request from a Client to Ory Kratos to get flowId,
2. Render HTML login form,
3. Submit filled out form as POST request with credentials and flowId in endpoint query,

**Expected behaviour**

Authorization should return cookie with `session_token`.

**Environment**

Ory Kratos:  v0.7.1-alpha.1

**Additional context:**

kratos.yml

```
replicaCount: 1

database:
  connectionName: <myconnectionname>
environment:
  name: my-stage-env
ingress:
  dnsName: <my-dns>

kratos:
  config:
    log:
      level: info
    secrets:
      cookie:
        # This is an example; secret must be this length (32 chars).
        - deVuA0F46ZWFh3v4wGPVEQDlVXMbLKzG
      session:
        # Change this to values such as '1s', '1m', etc. to see how Kratos handles invalidating a session.
        lifespan: 1h
    serve:
      public:
        base_url: https://my-backend-url.com/
        cors:
          allowed_origins:
            - http://localhost:5000
            - https://my-frontend-url.com
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
          exposed_headers:
            - Content-Type
            - Set-Cookie
          enabled: true
    selfservice:
      methods:
        password:
          enabled: true

      default_browser_return_url: https://my-frontend-url.com/
      whitelisted_return_urls:
        - http://localhost:5000/
        - https://my-frontend-url.com
      flows:
        login:
          ui_url: https://my-frontend-url.com/login-confirm
          after:
            default_browser_return_url: http://localhost:5000/
```
