### DISCUSSION TITLE
How to enable 'same_site: None' for cookies in the Quickstart?

### DISCUSSION THREAD

**Discussion by jwebstar** [ory/kratos#1675] [Q&A] [answered]
Hi, I have the quickstart running locally via the guide [Clone Ory Kratos and Run it in Docker](https://www.ory.sh/kratos/docs/quickstart#clone-ory-kratos-and-run-it-in-docker).

But I haven't been able to set cookies as SameSite: None. I added the following to kratos.yml but they are still set as SameSite: Lax. Is there something else I need to do?

```
// kratos\contrib\quickstart\kratos\email-password\kratos.yml
session:
  cookie:
    same_site: None

cookies:
  same_site: None
```

I'm trying to load the SecureApp https://127.0.0.1:4455/ in an iframe in Electron (I enabled ssl for kratos-selfservice-ui-node in the quickstart.yml with TLS_KEY_PATH and TLS_CERT_PATH). But it can't set the cookie due to SameSite: Lax which triggers a redirection loop. So I was hoping to get it to load by using https and changing the cookie to SameSite: None.

Ultimately I want to test whether I could register a user in Electron using an API interaction flow with _our-app.com_ and for that user to then be logged in already when opening _our-app.com_ in an iframe in Electron.
