### DISCUSSION TITLE
How to get registration flow payload with server-side request using Golang ?

### DISCUSSION THREAD

**Discussion by benjivu** [ory/kratos#1688] [Q&A] [answered]
I am using kratos-go-client package to play around with Kratos.

I successfully browsed a registration's flow id and redirect my request back to my UI registration path with an ID param.

Now I want to get the registration payload to have the csrf_token value to fill in my form. Here the problem comes, I can not make a GET request to `/self-service/registration/flows?id=<flow-id>`. I got connection refused.

I guess it relates to cookies so I did get the cookie from my browser request and pass it in my request on the server-side, but it still does not work.

It is quite similar to https://github.com/ory/kratos/discussions/1683#discussion-3538620 but I don't know how to make it work with Golang.

My demo code, stuck in line `Got ERROR` :(
```go
func (u *Users) GetRegistration(w http.ResponseWriter, r *http.Request) {
	flow := r.URL.Query().Get("flow")
	if flow == "" {
		http.Redirect(w, r, KratosPublicBaseURL+"/self-service/registration/browser", http.StatusFound)
		return
	}
	cookies := r.Header.Get("Cookie")
	log.Println("Cookie: ", cookies)
	flowObject , res , err := u.kratosClient.GetRegistrationFlow(context.Background(), flow, cookies)
	if err != nil {
		log.Println("Got ERROR", err)
		return
	}
	if res == nil {
		log.Println("Empty response")
		return
	}
	if res.StatusCode != http.StatusOK {
		log.Println("Response status is not 200. Status: ", res.StatusCode)
		return
	}
	kratos.PrintJSONPretty(flowObject)
	u.RegistrationView.Render(w, r, nil)
}
```

Thanks for all of your supports!!

Update: I am using Kratos v0.7.1-alpha.1, I don't know if the change about **CSRF countermeasures for fetching all self-service flows** was tested on `kratos-go-client` package? I do add the cookie to request but it still does not work !

```go
func (c *Client) GetRegistrationFlow(ctx context.Context, flowID string, cookie string) (*kratosClient.SelfServiceRegistrationFlow, *http.Response, error) {
	return c.API.V0alpha1Api.GetSelfServiceRegistrationFlow(ctx).Cookie(cookie).Id(flowID).Execute()
}
```

**Comment by benjivu** [comment, marked as answer]
Figured out the cause, it's my bad!

I configured the APIClient using host `127.0.0.1`, but it should be `oathkeeper ` because I calling it in the docker network.
```go
cfgKratos = kratosClient.Configuration{
		Host:   "oathkeeper:4455",
		Scheme: "http",
		Debug:  true,
		Servers: []kratosClient.ServerConfiguration{
			{
				URL: "/.ory/kratos/public",
			},
		},
	}
```
Then I need to update Oathkeeper rules also to allow my requests.
```yaml
-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://oathkeeper:4455/.ory/kratos/public/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    -
      handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
```
If you guys have a better suggestion, pls let me know :D

Thanks.
