### DISCUSSION TITLE
Kratos Quickstart with GCP Cloud SQL (PostgreSQL)

### DISCUSSION THREAD

**Discussion by jwebstar** [ory/kratos#1709] [Show and tell]
I got stuck trying to get the kratos quickstart working with PostgreSQL running on GCP Cloud. In case it helps anyone else, this worked for me in the end:

```
version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.7.3-alpha.1
    environment:
      - DSN=postgres://DB_USER:DB_PASSWORD@cloud-sql-proxy:5432/DB_NAME?sslmode=disable&max_conns=20&max_idle_conns=4

  kratos:
    image: oryd/kratos:v0.7.3-alpha.1
    environment:
      - DSN=postgres://DB_USER:DB_PASSWORD@cloud-sql-proxy:5432/DB_NAME?sslmode=disable&max_conns=20&max_idle_conns=4
  
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.21.0
    volumes:
      - ./gcloud/service-act-creds.json:/service-act-creds.json
    ports:
      - 5432:5432
    command: /cloud_sql_proxy -instances=INSTANCE_CONNECTION_NAME=tcp:0.0.0.0:5432 -credential_file=/service-act-creds.json
    networks:
      - intranet
```

Configuration: set _DB_USER_, _DB_PASSWORD_, _DB_NAME_ and _INSTANCE_CONNECTION_NAME_ as appropriate and adjust the local path to your service account credentials (_./gcloud/service-act-creds.json_ in this example). Then run:

`docker-compose -f quickstart.yml -f quickstart-standalone.yml -f quickstart-gcp-cloud-sql.yml up --build --force-recreate`

\* Assumes the yml file was saved to kratos/quickstart-gcp-cloud-sql.yml. [Official docs on using the Cloud SQL Auth proxy](https://cloud.google.com/sql/docs/postgres/connect-admin-proxy#connecting-docker).
