### DISCUSSION TITLE
relation "networks" does not exist at character 67

### DISCUSSION THREAD

**Discussion by minebea-as** [ory/kratos#1813] [Q&A] [answered]
**Describe the bug**

If starting a clean docker-compose with postgres & kratos leads into the following error message:
`
postgresd_1       | ERROR:  relation "networks" does not exist at character 67
postgresd_1       | STATEMENT:  SELECT networks.created_at, networks.id, networks.updated_at FROM networks AS networks ORDER BY created_at ASC LIMIT 1
`

**Reproducing the bug**

docker compose -fkratos-compose.yml up --remove-orphans

_Server logs_

```
postgresd_1       | ERROR:  relation "networks" does not exist at character 67
postgresd_1       | STATEMENT:  SELECT networks.created_at, networks.id, networks.updated_at FROM networks AS networks ORDER BY created_at ASC LIMIT 1
kratos_1          | time=2021-10-05T10:02:13Z level=warning msg=Unable to determine network, retrying. func=github.com/ory/kratos/driver.(*RegistryDefault).Init.func1 file=/home/ory/driver/registry_default.go:537 audience=application error=map[message:ERROR: relation "networks" does not exist (SQLSTATE 42P01) trace:
kratos_1          | github.com/ory/x/sqlcon.HandleError
kratos_1          | 	/go/pkg/mod/github.com/ory/x@v0.0.272/sqlcon/error.go:88
kratos_1          | github.com/ory/x/networkx.(*Manager).Determine
kratos_1          | 	/go/pkg/mod/github.com/ory/x@v0.0.272/networkx/manager.go:42
kratos_1          | github.com/ory/kratos/persistence/sql.(*Persister).DetermineNetwork
kratos_1          | 	/home/ory/persistence/sql/persister.go:77
kratos_1          | github.com/ory/kratos/driver.(*RegistryDefault).Init.func1
kratos_1          | 	/home/ory/driver/registry_default.go:535
kratos_1          | github.com/cenkalti/backoff.RetryNotify
kratos_1          | 	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37
kratos_1          | github.com/cenkalti/backoff.Retry
kratos_1          | 	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
kratos_1          | github.com/ory/kratos/driver.(*RegistryDefault).Init
kratos_1          | 	/home/ory/driver/registry_default.go:476
kratos_1          | github.com/ory/kratos/driver.New
kratos_1          | 	/home/ory/driver/factory.go:14
kratos_1          | github.com/ory/kratos/cmd/serve.NewServeCmd.func1
kratos_1          | 	/home/ory/cmd/serve/root.go:33
kratos_1          | github.com/spf13/cobra.(*Command).execute
kratos_1          | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856
kratos_1          | github.com/spf13/cobra.(*Command).ExecuteC
kratos_1          | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
kratos_1          | github.com/spf13/cobra.(*Command).Execute
kratos_1          | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
kratos_1          | github.com/ory/kratos/cmd.Execute
kratos_1          | 	/home/ory/cmd/root.go:48
kratos_1          | main.main
kratos_1          | 	/home/ory/main.go:35
kratos_1          | runtime.main
kratos_1          | 	/usr/local/go/src/runtime/proc.go:225
kratos_1          | runtime.goexit
kratos_1          | 	/usr/local/go/src/runtime/asm_amd64.s:1371] service_name=Ory Kratos service_version=v0.7.4-alpha.1
```

```yaml
version: '3.7'


networks:
  intranet:

services:
  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet
  
  kratos-migrate:
      depends_on:
        - postgresd
      image: oryd/kratos:v0.7.4-alpha.1
      environment:
        - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4 

  kratos:
      depends_on:
        - kratos-migrate
      image: oryd/kratos:v0.7.4-alpha.1
      ports:
        - '4433:4433' # public
        - '4434:4434' # admin
      environment:
        - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
        - LOG_LEVEL=trace
      volumes:
        - type: bind
          source: ./configs
          target: /etc/config/kratos
      command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
      networks:
        - intranet

```

**Expected behavior**

I want kratos just to startup.. I try to do quickstart by my own step by step with own application and fit it to our infrastrucutre.
