### DISCUSSION TITLE
ERROR - additionalProperties "link" not allowed

### DISCUSSION THREAD

**Discussion by vsumit89** [ory/kratos#1867] [Q&A] [answered]
I am trying to use the recovery flow in kratos. for that I am setting the link method = enabled. But because of that I am getting the error "additionalProperties "link" not allowed".

config.yml :
```yml
...
  methods:
    oidc:
      enabled: true
    password:
      enabled: true
    link: 
      enabled: true
```
