### DISCUSSION TITLE
OIDC Login with already registered account failing

### DISCUSSION THREAD

**Discussion by matthewmcneely** [ory/kratos#1870] [Q&A] [answered]
Kratos Version: 0.7.6

When attempting to login via Google OIDC with an existing Kratos identity (created via 'password' flow), I see this error in the logs and the registration flow gets activated.

```msg=Received successful OpenID Connect callback but user is not registered. Re-initializing registration flow now.```

Relevant section of the kratos.yaml
```
    oidc:
      #
      config:
        providers:
          - id: google
            provider: google
            client_id: <snip>
            client_secret: <snip>
            mapper_url: file:///home/ory/oidc.google.jsonnet
            scope:
              - openid
              - profile
              - email
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name:
                  essential: true
```

The JSONNET file:
```
local claims = std.extVar('claims');

{
  identity: {
    traits: {
      email: claims.email,
      firstName: claims.given_name,
      lastName: claims.family_name,
      picture: claims.picture,
    },
  },
}
```

Anyone able to login via Google OIDC with existing identities in 0.7.6?
