### DISCUSSION TITLE
Accessing SelfServiceSettingsFlowWithoutBrowser using `id_token` mutator in Oathkeeper

### DISCUSSION THREAD

**Discussion by viters** [ory/kratos#1879] [Q&A] [answered]
Hey,

I am working on a microservice, where one of it's responsibilities will be updating user's identity on behalf of a user. In other words, user calls this microservice when he is logged in, and it performs update on his identity using `SelfServiceSettingsFlowWithoutBrowser` API.

What should I send as `xSessionToken` to authorize request on behalf of the user?

My oathkeeper config:

```yaml
mutators:
  id_token:
    enabled: true
    config:
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }

authenticators:
  cookie_session:
    enabled: true
    config:
      preserve_path: true
      extra_from: '@this'
      subject_from: 'identity.id'
      only:
        - ory_kratos_session
 ```
