### DISCUSSION TITLE
Missing OIDC group in my self-service settings response

### DISCUSSION THREAD

**Discussion by trobinpl** [ory/kratos#1997] [Q&A] [answered]
I'm trying to implement linking/unlinking external providers accounts in my app and the documentation states, that in the self-service settings flow I should get necessary UI nodes if I have the OIDC provider configured and enabled (as per [Link and Unlink from Google, Facebook, GitHub, ..., OpenID Connect / OAuth 2.0](https://www.ory.sh/kratos/docs/self-service/flows/user-settings#link-and-unlink-from-google-facebook-github--openid-connect--oauth-20)).
My configuration does have the Slack OIDC provider configured
```
selfservice:
    methods:
        link:
            enabled: true
        password:
            enabled: true
        oidc:
            enabled: true
            config:
                providers:
                    - id: slack
                      provider: slack
                      client_id: "qwerty"
                      client_secret: qwerty
                      scope:
                          - identity.basic
                          - identity.email
                          - identity.avatar
                      mapper_url: file:///etc/config/kratos/oidc.slack.jsonnet
```
However when I initialize a new settings flow I can't see the `oidc` group inside the response body

![obraz](https://user-images.githubusercontent.com/3727358/143625206-2894307f-dded-40aa-980f-383ddaecaa37.png)

Not sure if it's a bug or I'm just missing something

**Comment by kszafran** [comment]
It looks correct as far as I can tell. Are you sure the configuration file was read correctly, etc.? I just got OIDC login to work yesterday with a similar config (with Google as the IdP):
```
selfservice:
  ...
  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google-test
            provider: google
            mapper_url: file:///path/to/oidc.google.jsonnet
            client_id: the-id
            client_secret: the-secret
            scope:
              - openid
              - email
              - profile
```
