### DISCUSSION TITLE
How to avoid csrf error when posting login flow from React SPA

### DISCUSSION THREAD

**Discussion by peteole** [ory/kratos#2046] [Q&A] [answered]
Hi, I am trying to build a React SPA with kratos. From a developer perspective, it is important to my team to really have a SPA, so we want to avoid redirects at all cost.

I am having the following client side code:
```js
import React from 'react';
import { Configuration, V0alpha2Api } from '@ory/kratos-client'
export const AuthDemo: React.FC = () => {
    return (
        <div>
            <h1>Auth Demo</h1>
            <button onClick={async () => {
                console.log('login');
                const config = new Configuration({ basePath: 'http://127.0.0.1:8090' });
                const api = new V0alpha2Api(config);
                const resp = await api.initializeSelfServiceRegistrationFlowForBrowsers()
                console.log(resp.data);
                if (!resp) return
                const registrationFlowId = resp.data.id;
                const csrf_token = resp.data.ui.nodes[0].attributes.value as string;

                const registrationResponse = await api.submitSelfServiceRegistrationFlow(registrationFlowId, {
                    method: "password",
                    password: "1234",
                    traits: {
                        email: "ole.petersen@go4more.de"
                    },
                    csrf_token: csrf_token
                })
                console.log(registrationResponse.data);
            }}>Login</button>
        </div>
    )
}
```
The first api call works perfectly, however the second call always fails with the following error:

```json

{
  "error": {
    "id": "security_csrf_violation",
    "code": 403,
    "status": "Forbidden",
    "reason": "The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues.",
    "details": {
      "docs": "https://www.ory.sh/kratos/docs/debug/csrf",
      "hint": "The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token).",
      "reject_reason": "The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow."
    },
    "message": "the request was rejected to protect you from Cross-Site-Request-Forgery"
  }
}
```
Is there a way to solve this without using a plain html form?

**Comment by aeneasr** [comment, marked as answer]
Could you show the HTTP request in the developer console in the network tab for `await api.submitSelfServiceRegistrationFlow(registrationFlowId,`? Because it looks like `csrf_token` might not be sent correctly.

edit://

Solution was missing `includeCredentials` option:

```patch
 const config = new Configuration({
   basePath: 'http://127.0.0.1:8090',
+  baseOptions: {
+    withCredentials: true
+  }
 });
```

**Reply by peteole** [reply]
Thanks for your answer! This is how it looks like:
![image](https://user-images.githubusercontent.com/56505957/145484378-00837161-cf7b-4c30-9f25-e20f39844670.png)
![image](https://user-images.githubusercontent.com/56505957/145484443-3d4f72b7-d951-4485-8cb4-d7984bf5f4b1.png)

And here you have my kratos config (it's running in kubernetes using the helm chart by the way, the url is localhost since it is port-forwarded for testing):
```yaml
kratos:
  config:
    courier:
      smtp:
        connection_uri: smtps://my-username@my-mail-provider.com:my-pwd@smtp.myprovider.com
        from_address: no-reply@ory.kratos.sh
    dsn: postgres://kratos:my-pwd@psql-postgresql:5432/kratos
    identity:
        default_schema_url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9leGFtcGxlLmNvbS9yZWdpc3RyYXRpb24uc2NoZW1hLmpzb24iLAogICIkc2NoZW1hIjogImh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsCiAgInRpdGxlIjogIlBlcnNvbiIsCiAgInR5cGUiOiAib2JqZWN0IiwKICAicHJvcGVydGllcyI6IHsKICAgICJ0cmFpdHMiOiB7CiAgICAgICJ0eXBlIjogIm9iamVjdCIsCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJlbWFpbCI6IHsKICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAiZm9ybWF0IjogImVtYWlsIiwKICAgICAgICAgICJvcnkuc2gva3JhdG9zIjogewogICAgICAgICAgICAiY3JlZGVudGlhbHMiOiB7CiAgICAgICAgICAgICAgInBhc3N3b3JkIjogewogICAgICAgICAgICAgICAgImlkZW50aWZpZXIiOiB0cnVlCiAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAidXNlcm5hbWUiOiB7CiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgIm9yeS5zaC9rcmF0b3MiOiB7CiAgICAgICAgICAgICJjcmVkZW50aWFscyI6IHsKICAgICAgICAgICAgICAicGFzc3dvcmQiOiB7CiAgICAgICAgICAgICAgICAiaWRlbnRpZmllciI6IHRydWUKICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICAgIH0KICAgICAgICB9CiAgICAgIH0KICAgIH0KICB9Cn0=
        schemas: []
    selfservice:
      default_browser_return_url: https://huddle.ridilla.eu/ui
    serve:
      public:
        cors:
          enabled: true
          allowed_origins:
            - "*"
            - http://*
            - https://*
  autoMigrate: true
```
