### DISCUSSION TITLE
How to pass smtpConnectionURI via existing secret

### DISCUSSION THREAD

**Discussion by peteole** [ory/kratos#2077] [Q&A] [answered]
Hi,

I am using the kratos helmfile and woud like to pass some credentials via existing secrets instead of the helm deployment. Therefore I have set the environmentSecretsName in the helm config:
```yaml

deployment:
  environmentSecretsName: secret-kratos
```
Also the secret "secret-kratos" does exist and looks as follows:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-kratos
stringData:
  DSN: my-postgres-dsn
  COURIER_SMTP_CONNECTION_URI: my-mail-dsn
```
Also, the secret seems to be referenced in the deployment:
```yaml
...
    envFrom:
    - secretRef:
        name: secret-kratos
...
```
Anyways, it seems like kratos wants to get the smtp string from the secret it manages itself anyways:

```yaml
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-19T17:45:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-19T17:45:35Z"
    message: 'containers with unready status: [kratos]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-19T17:45:35Z"
    message: 'containers with unready status: [kratos]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-19T17:45:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: oryd/kratos:v0.8.0-alpha.3
    imageID: ""
    lastState: {}
    name: kratos
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: couldn't find key smtpConnectionURI in Secret default/kratos
        reason: CreateContainerConfigError
...
```
Have I done something wrong or is this an error?

**Comment by Demonsthere** [comment, marked as answer]
Hello there!
The variable you are trying to use 

```yaml
deployment:
  environmentSecretsName: secret-kratos
```

is not correct, we do not support such a config option in the helm charts. If you want to use a custom secret, please try the following:

```yaml
secret:
  # -- switch to false to prevent creating the secret
  enabled: false
  # -- Provide custom name of existing secret, or custom name of secret to be created
  nameOverride: "my-custom-secret"
```

But remember that in this case, You are responsible for supplying the required values, which need to be in the same format that the created secret uses. For more details please take a look [here](https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/secrets.yaml#L15)
