### DISCUSSION TITLE
Custom Subjects in Emails are ignored

### DISCUSSION THREAD

**Discussion by MKlingner** [ory/kratos#2138] [Q&A] [answered]
Hi there,

i have a problem with the email templates of kratos. The custom email body gets utilized by ory but not the subject. 
As far as I see is everything correctly configured. Does anyone had the same problem?

The kratos config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-kratos
  namespace: dev
data:
  identity.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }

  kratos.yaml: |-
    version: v0.6.3-alpha.1

    identity:
      default_schema_url: file:///etc/config/kratos/identity.schema.json

    serve:
      public:
        base_url: https://dev-auth.example.com/.ory/kratos/public
        cors:
          enabled: true
      admin:
        base_url: http://ory-svc-kratos:4434

    selfservice:
      default_browser_return_url: https://dev.example.com
      whitelisted_return_urls:
        # to redirect to auth/hydra/login
        - https://dev-auth.example.com
        - https://dev.example.com
        
      methods:
        password:
          enabled: true

      flows:
        error:
          ui_url: https://dev-auth.example.com/error

        settings:
          ui_url: https://dev-auth.example.com/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: https://dev-auth.example.com/recovery

        verification:
          enabled: true
          ui_url: https://dev-auth.example.com/verify
          after:
            default_browser_return_url: https://dev-auth.example.com

        logout:
          after:
            default_browser_return_url: https://dev.example.com

        login:
          ui_url: https://dev-auth.example.com/auth/login
          lifespan: 60m

        registration:
          lifespan: 60m
          ui_url: https://dev-auth.example.com/auth/registration
          after:
            password:
              hooks:
                - hook: session

    log:
      level: debug
      format: text
      leak_sensitive_values: false

    secrets:
      cookie:
        - TopSecret

    hashers:
      argon2:
        parallelism: 1
        memory: 128MB
        iterations: 2
        salt_length: 16
        key_length: 16

    courier:
      smtp:
        from_address: info@example.com
```

The email templates config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-kratos-email-verification-valid
  namespace: dev
data:
  email.subject.gotmpl: >
    Registrierung erfolgreich

  email.body.gotmpl: |
    <div style="font-family: Calibri">
      Hallo, 

      <p> Um deine Registrierung abzuschließen, klicke bitte auf den Link <a href="{{ .VerificationURL }}">{{ .VerificationURL }}</a>.</p>      
    </div>

  email.body.plaintext.gotmpl: |
    Hallo,

    Um deine Registrierung abzuschließen, klicke bitte auf den Link {{ .VerificationURL }} .
    
---
```

The kratos courier deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-svc-kratos-courier
  namespace: dev
  labels:
    app: ory-svc-kratos-courier
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-svc-kratos-courier
      version: "1.0"
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ory-svc-kratos-courier
        version: "1.0"
    spec:
      containers:
        - name: ory-kratos-courier-container
          image: oryd/kratos:v0.8
          imagePullPolicy: Always
          volumeMounts:
            - name: ory-kratos-config-volume
              mountPath: /etc/config/kratos
            - name: ory-kratos-email-verification-valid
              mountPath: /conf/courier-templates/verification/valid
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_db_connection_string
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_smtp_connection_url
            - name: COURIER_TEMPLATE_OVERRIDE_PATH
              value: /conf/courier-templates
          command: ["kratos"]
          args: ["courier", "watch", "-c", "/etc/config/kratos/kratos.yaml"]
      volumes:
        - name: ory-kratos-config-volume
          configMap:
            name: ory-kratos
        - name: ory-kratos-email-verification-valid
          configMap:
            name: ory-kratos-email-verification-valid
```

The kratos deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-svc-kratos
  namespace: dev
  labels:
    app: ory-svc-kratos
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-svc-kratos
      version: "1.0"
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ory-svc-kratos
        version: "1.0"
    spec:
      initContainers:
        - name: ory-kratos-init-container
          image: oryd/kratos:v0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 4455
              name: ory-kratos
              protocol: TCP
          volumeMounts:
            - name: ory-kratos-config-volume
              mountPath: /etc/config/kratos
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_db_connection_string
          command: ["kratos"]
          args: ["migrate", "sql", "-e", "--yes"]
      containers:
        - name: ory-kratos-container
          image: oryd/kratos:v0.8
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health/alive
              port: 4433
            periodSeconds: 30
            initialDelaySeconds: 10
          ports:
            - containerPort: 4433
              name: public-port
              protocol: TCP
            - containerPort: 4434
              name: admin-port
              protocol: TCP
          volumeMounts:
            - name: ory-kratos-config-volume
              mountPath: /etc/config/kratos
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_db_connection_string
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_smtp_connection_url
          command: ["kratos"]
          args:
            [
              "serve",
              "all",
              "--config",
              "/etc/config/kratos/kratos.yaml",
            ]
      volumes:
        - name: ory-kratos-config-volume
          configMap:
            name: ory-kratos
```

**Comment by MKlingner** [comment, marked as answer]
I can answer myself: I forgot to add the templates to kratos and not only to kratos-courier:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-svc-kratos
  namespace: dev
  labels:
    app: ory-svc-kratos
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ory-svc-kratos
      version: "1.0"
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ory-svc-kratos
        version: "1.0"
    spec:
      initContainers:
        - name: ory-kratos-init-container
          image: oryd/kratos:v0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 4455
              name: ory-kratos
              protocol: TCP
          volumeMounts:
            - name: ory-kratos-config-volume
              mountPath: /etc/config/kratos            
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_db_connection_string
          command: ["kratos"]
          args: ["migrate", "sql", "-e", "--yes"]
      containers:
        - name: ory-kratos-container
          image: oryd/kratos:v0.8
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health/alive
              port: 4433
            periodSeconds: 30
            initialDelaySeconds: 10
          ports:
            - containerPort: 4433
              name: public-port
              protocol: TCP
            - containerPort: 4434
              name: admin-port
              protocol: TCP
          volumeMounts:
            - name: ory-kratos-config-volume
              mountPath: /etc/config/kratos
# was missing >
            - name: ory-kratos-email-verification-valid
              mountPath: /conf/courier-templates/verification/valid          
# < was missing
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_db_connection_string
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: ory-secrets
                  key: ory_smtp_connection_url
# was missing >
             - name: COURIER_TEMPLATE_OVERRIDE_PATH
               value: /conf/courier-templates
# < was missing
          command: ["kratos"]
          args:
            [
              "serve",
              "all",
              "--config",
              "/etc/config/kratos/kratos.yaml",
            ]
      volumes:
        - name: ory-kratos-config-volume
          configMap:
            name: ory-kratos
# was missing >
        - name: ory-kratos-email-verification-valid
          configMap:
            name: ory-kratos-email-verification-valid
# < was missing
```
