### DISCUSSION TITLE
working with kratos on different subdomains

### DISCUSSION THREAD

**Discussion by charlie-whight** [ory/kratos#2235] [Q&A] [answered]
Hi - I'm having some trouble getting kratos working with a ui hosted on a different subdomain.

I am running Kratos at https://sub1.example.com

And the UI is hosted at https://sub2.example.com

My cookie domain config is as below:

```
session:
  cookie:
    domain: example.com

cookies:
  domain: example.com
```
  
But the csrf token is being set with a domain of `sub1.example.com` - and I'm subsequently getting stuck in a redirect loop when I try to start a login flow.

I'm sure I'm missing something simple so hoping someone can help out, thanks.

**Comment by Benehiko** [comment]
Hi @charlie-whight 

What is your baseUrl set to? and are you running Kratos behind a reverse proxy or Oathkeeper?

Maybe you could share your Kratos configs (**please replace sensitive information**)

**Reply by charlie-whight** [reply]
Thanks - I'm running Kratos and the UI in kubernetes, with an ingress configured for each service. 

Note that if i configure the ingress to host the UI at `sub1.example.com/app` and Kratos at `sub1.example.com/public` it works fine, and with the cookie settings as below I can see the session cookie gets set with the domain as `example.com` but the csrf cookies are set to `sub1.example.com`

```
serve:
  public:
    base_url: https://sub1.example.com/public
    cors:
      allowed_origins:
        - https://sub1.example.com
        - https://sub2.example.com
  admin:
    base_url: https://sub1.internal.example.com/

selfservice:
  default_browser_return_url: https://sub2.example.com
  whitelisted_return_urls:
    - https://sub2.example.com
  
  ...
  ...

session:
  cookie:
    domain: example.com

cookies:
  domain: example.com
  ```

**Reply by Benehiko** [reply]
Sorry for the late response, please take a look at this from our documentation https://www.ory.sh/docs/kratos/debug/csrf.

@senitsgh I would be cautious of setting the cookie `same_site` attribute to `Lax` in a production environment. That is why we have the `--dev` flag on Kratos when developing locally so you do not ever need to set this to `Lax` in the config.

**Reply by vinckr** [reply]
Hey @charlie-whight  ,
Just checking in if your question was answered or if there was still something unclear.
I will mark this as answered for now, but feel free to come back to the discussion any time.

Thanks a ton! 🐝

**Comment by senitsgh** [comment, marked as answer]
I had the similar issue. Your cookie setting should be set as 

```
cookies:
  domain: example.com
  path: /
  same_site: Lax
```
 
With this setting your csrf cookies will be passed between subdomains.
