### DISCUSSION TITLE
How to custom configure kratos?

### DISCUSSION THREAD

**Discussion by lucrus73** [ory/kratos#2281] [Q&A] [answered]
Hello everybody,

I'm new to kratos (new to Ory in general) and I'm trying to setup my first self hosted kratos with with some custom settings. In particular I'd like it to use MySQL instead of SQLite and I'd like docker to store everything under /srv instead of /var/lib or /etc.

Is there any document that describes how to customise the [quickstart.yml](https://github.com/ory/kratos/blob/master/quickstart.yml) for those and possibly other similar needs?

**Comment by vinckr** [comment, marked as answer]
Hello @lucrus73 
Sure, happy to help
At the bottom of the quickstart guide, you can find some [next steps](https://www.ory.sh/docs/kratos/quickstart#next-steps)

Specifically for MySQL you need:

`docker-compose -f quickstart.yml -f quickstart-standalone.yml -f quickstart-mysql.yml up --build --force-recreate`

I am not sure how to change the docker directory, may I ask what is the reason for using `/srv`?

Please feel free to add some feedback on how we can improve the next steps section 🙏

**Reply by lucrus73** [reply]
> I am not sure how to change the docker directory, may I ask what is the reason for using `/srv`?

Because the host system has /srv mounted on a dedicated LVM volume and I need to store docker images there, e.g.:

    # docker volume create --driver local -o o=bind -o type=none -o device=/srv/ory ory

**Reply by gen1us2k** [reply]
You can easily change this directory under services.kratos-related-containers.volumes.source and put your quickstart.yml file to /srv folder.
Let's have this folder structure
```
/srv/
/srv/kratos/
/srv/kratos/kratos.yaml
/srv/kratos/identity.schema.json
/srv/quickstart.yml # or you can use docker-compose.yml for that purpose
```
You can have this configuration for your volumes settings

```
services:
  kratos:
    volumes:
      - type: bind
        source: /srv/kratos/ # Just setup the path to your kratos config directory
        target: /etc/config/kratos
```

**Reply by lucrus73** [reply]
Sorry for the delay, but I and my colleagues spent some time trying things and figuring out what we think we need. 

We ended up with the decision of not using `docker`, but to install `kratos` (and maybe `keto` too) manually.

I then started from [this document](https://www.ory.sh/docs/kratos/install), installed kratos on Linux (quite easy) and moved on to the "[Configuring](https://www.ory.sh/docs/kratos/configuring)" step... that in turn led me to the "[Configuration](https://www.ory.sh/docs/kratos/reference/configuration)" reference, where you can find a long list of possibly deprecated configuration settings, that does not state which ones are actually deprecated... and it suggests to use the quickstart as a better starting point for the configuration, which in turn uses `docker`, and I am back to the beginning...

So, assuming a manual install on Linux without `docker`, is there a starter configuration anywhere that can be used as a base for the current `kratos` release?

**Reply by gen1us2k** [reply]
Hello. You can use [contrib/quickstart](https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password) example configuration and copy it to `/etc/config/kratos` folder. You need to copy `kratos.yml` and `identity.schema.json`

**Reply by lucrus73** [reply]
Thanks @gen1us2k that's exactly what I'm looking for. Only one last doubt: it starts with `version: v0.7.1-alpha.1`, while the most recent `kratos` release is `v0.8.2-alpha.1`. Is that ok?

**Reply by gen1us2k** [reply]
You can change the version and set `v0.8.2-alpha.1`.

**Reply by lucrus73** [reply]
[Here is what I get](https://gist.github.com/lucrus73/acbb6417f762c738f5cddfbe771ef940), regardless of changing the version string or not. Google does not seem to have anything to offer for that error string ("identity: map" "validation failed" kratos). I even tried compiling from sources, just to try something, with same results.

**Reply by gen1us2k** [reply]
I found that you need to change identity section in kratos.yml from 
```
identity:
  default_schema_id: default
  schemas:
    - id: default
      schema: file:///etc/config/kratos/identity.schema.json
```

to

```
identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json # insert your path to identity schema here
```
