### DISCUSSION TITLE
Session lifespan for multiple schemas/devices

### DISCUSSION THREAD

**Discussion by amzu-dev** [ory/kratos#2409] [Q&A] [answered]
Hi,
      I have a requirement where users need to log in from mobile devices as well as from the web portal. Is there a way to configure session.lifespan for two different devices in the same Kratos config? since session.lifespan is at the higher level of the YAML, I presume we can have only one lifepan set, so can have a separate Kratos instance for mobile devices with a longer session.lifespan set? and one for browsers to have a shorter session.lifespan and point to the same database?

Also is it possible to have the session lifespan at the schema level so that I can have one schema for mobile devices and one for web/browsers and configure different session lifespans in the same Kratos instance?

Thank you for the help.

**Comment by vinckr** [comment, marked as answer]
You are right currently you can have only one lifespan set.

Both workarounds you proposed are possible: 

>a separate Kratos instance for mobile devices with a longer session.lifespan set? and one for browsers to have a shorter session.lifespan and point to the same database?

This works.

>one schema for mobile devices and one for web/browsers and configure different session lifespans in the same Kratos instance?

This also works.
You can configure different identity schemas, e.g.:

```yaml
schemas:
  - id: customer
    url: base64://ewogICIkc2NoZW1hIjogImh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsCiAgInR5cGUiOiAib2JqZWN0IiwKICAicHJvcGVydGllcyI6IHsKICAgICJiYXIiOiB7CiAgICAgICJ0eXBlIjogInN0cmluZyIKICAgIH0KICB9LAogICJyZXF1aXJlZCI6IFsKICAgICJiYXIiCiAgXQp9
  - id: employee
    url: https://foo.bar.com/path/to/employee.traits.schema.json
  - id: employee-v2
    url: file://path/to/employee.v2.traits.schema.json
```

So when you e.g. [submit a registration flow](https://www.ory.sh/docs/kratos/reference/api#operation/submitSelfServiceRegistrationFlow), you can specify which schema it should use.
