### DISCUSSION TITLE
Use variables in config file

### DISCUSSION THREAD

**Discussion by halvardssm** [ory/kratos#2443] [Q&A] [answered]
Hi! I am trying to implement an after hook for registration in the Kratos config file, but I would need access to the token. How can I access the session token from the registration payload for use in the hook?

```
...
    registration:
      lifespan: 20m
      ui_url: http://localhost:8080/register
      after:
        password:
          hooks:
            - hook: session
            - hook: web_hook
              config:
                url: http://localhost/after-registration-hook
                method: POST
                auth:
                  type: api_key
                  config:
                    name: session-token
                    value: THE TOKEN FROM THE previous step
                    in: header
...
```
