### DISCUSSION TITLE
CORS doesn't appear to be working

### DISCUSSION THREAD

**Discussion by auctumnus** [ory/kratos#2493] [Q&A] [answered]
I have a Kratos instance running to do auth for another API. Kratos runs on a different domain (which I recognise might cause some issues? worst case, I can try to finagle an NGINX config together, but in my experience it was unreasonably slow), with the relevant config being:
```yaml
serve:
  public:
    base_url: http://127.0.0.1:4433/
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - 'http://localhost:1337'
        - 'http://localhost:3333'
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
```
but when the browser sends a request from `localhost:3333`, I get an error in the console about the `Access-Control-Allow-Origin` header being missing. The request headers and relevant error are in the image below:
![image](https://user-images.githubusercontent.com/37276280/170797052-6577945c-a07b-4347-9ed2-f86d6a6a9e96.png)

**Comment by lilstafe** [comment, marked as answer]
@auctumnus I had a similar issue with ory cloud here is the answer from it https://github.com/ory/cloud/discussions/86.

You probably need to enable ```withCredentials ```

If you are using javascript axios it would look something like this ```const axiosClient = axios.create({
  headers: {
    "Content-type": "application/json",
  },
  withCredentials : true
});``` Then this client can send request that contain all the necessary details without getting blocked by cors as long as the server enables it.


[More info](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials)

Hopefully this helps.

**Reply by lilstafe** [reply]
Since you are working on local I am also not sure if you need to set up your cookie domain. But I would try that a as well. 

cookies:
  domain: example.com

**Reply by auctumnus** [reply]
Enabled this and it got me at least part of the way through. I'm still convinced there are some major issues with CORS, given that I'm currently having to run Kratos behind a CORS proxy in order to have it work correctly.

(If anyone comes across this thread trying to get their own CORS proxy to work, my config is https://pastebin.com/aJpSPHmL.)

**Reply by vinckr** [reply]
If you haven't already, check out the "[Common Cookie and CSRF Pitfalls](https://www.ory.sh/docs/kratos/debug/csrf)"
Also see the new "[Security Model](https://www.ory.sh/docs/security-model#http-cookies)" document, especially the Cookie part - hope that makes it clearer!

**Reply by winston0410** [reply]
@auctumnus I encountered similar issue, and I believe this is indeed a bug. This is my config on serve:

```yaml
---
version: v0.10.1
# log:
#   level: debug
serve:
  public:
    base_url: http://0.0.0.0:4433
    cors:
      enabled: true
      allowed_origins:
        - https://example.org
        - https://*.example.org
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Access-Control-Allow-Origin
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://0.0.0.0:4434
```

I found out that setting `serve.public.cors.allowed_origins` would make all CORS-related headers disappear. Only setting `serve.public.cors.enabled` would be fine. I am using `oryd/kratos:v10.0.1` right now @vinckr  I can provide more info if needed
