### DISCUSSION TITLE
Dockerfile configuration with ECS

### DISCUSSION THREAD

**Discussion by alexedwardjones** [ory/kratos#2502] [Q&A] [answered]
Hey, I love the project and the quickstart guide is great for playing around locally.

I've moved on to trying to deploy Kratos on to ECS via the AWS CDK and I'm having problems with the configuration.

I can securely provide a database secret from secrets manager to ECS, this will be a string containing a json object that has the `engine`,  `username`, `password`, `host`, `port` and `dbname` fields.

I can also copy across a `kratos` directory containing `identity.schema.json` and `kratos.yml` files but I'm not sure how to specify this as the config.

```
# syntax=docker/dockerfile:1

FROM oryd/kratos:v0.10

COPY kratos kratos/
```

1. How would I construct the DSN from the provided database secret?
2. How would I specify the kratos.yml as the configuration file?

**Comment by vinckr** [comment]
Hello @alexedwardjones 
Apologies for the late answer. 
We have recently released [a guide how to deploy Kratos to production on a VM](https://www.ory.sh/docs/kratos/guides/deploy-kratos-example), maybe that helps as example? 
Let me know if you are still stuck on this!

**Comment by zepheiryan** [comment, marked as answer]
I'm about to do the same.  Whenever I see database configuration as a DSN in an application, it means I have to wrap the original entrypoint in a script that assembles the DSN from RDS secrets (you might need to escape your password for the shell in case you didn't limit the pool of viable characters to eliminate quotes) since everything has to happen through CloudFormation for me, and I try to avoid interacting with AWS services within the container if that isn't already something it's doing.  You may have other alternatives if your deploy infrastructure differs - you could create IAM and add a script to your image to pull from Secrets Manager directly, for instance.

As I understand it, Kratos will look for `/home/ory/kratos.yml` if it isn't given an explicit config path at invocation.  You can either COPY everything to that location and adjust schema, etc. file paths accordingly, or you can provide the `-c <path>` part in the `Command`setting  in an ECS task definition.  You already need to at least set this to `serve`, so `serve -c <path>` should get you started.  There may be other flags of interest to you depending on your mail setup, etc.  Since you're making your own image, you could also override the entrypoint to be `kratos serve -c <path>` instead of just `kratos` and leave it out of the task definition altogether, but this might makes it less useful to you overall, especially if you're running the courier portion in a separate container.

I'll try to come back and post specific excerpts once I have something up.

**Reply by zepheiryan** [reply]
I have it running.  You asked solely about the ECS part, and I'll put some edited excerpts of ECS CloudFormation after this, but the full solution for Kratos in AWS ECS should involve several other pieces in addition to an RDS database and its attached Secrets Manager secret: Secrets Manager secrets for the application, running database migrations whenever Kratos is updated, application load balancer(s) and target groups, certificates, DNS entries, along with Parameter Store parameters for OIDC services if you're connecting to any, and, as usual with AWS, appropriate IAM to access all of those services.  I've also opted to run the public API and the admin API plus courier separately with one behind a public load balancer and the other behind an internal load balancer, and I'll soon be placing Ory Oathkeeper in front of the admin API.  Finally, you'll probably want to run your UI solution separately.

The Task CloudFormation for Fargate:
```yaml
  KratosTask:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: (fill this in, should have Secrets Manager read access and a CMK key policy allowing it in)
      Family: kratos
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Cpu: 512
          Essential: true
          Image: (fill this in)
          Command:
            - serve
            - -c
            - /etc/config/kratos/config.yml
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: (fill this in)
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: kratos
          Memory: 1024
          Name: kratos
          PortMappings:
            - ContainerPort: 4433
              HostPort: 4433
              Protocol: tcp
          Secrets:
            - Name: DB_HOST
              ValueFrom: !Sub
                - '${ARN}:host::'
                - ARN: !ImportValue KratosDBARN
            - Name: DB_PORT
              ValueFrom: !Sub
                - '${ARN}:port::'
                - ARN: !ImportValue KratosDBARN
            - Name: DB_NAME
              ValueFrom: !Sub
                - '${ARN}:dbname::'
                - ARN: !ImportValue KratosDBARN
            - Name: DB_USER
              ValueFrom: !Sub
                - '${ARN}:username::'
                - ARN: !ImportValue KratosDBARN
            - Name: DB_PASSWORD
              ValueFrom: !Sub
                - '${ARN}:password::'
                - ARN: !ImportValue KratosDBARN
```

If you're using RDS, you may need to add the RDS certificate to your image so the Kratos DB driver can verify the secure connection (honestly, I didn't check if it was even necessary or not - at this point, I always add it if RDS is in the picture).  This is an excerpt of the Dockerfile and the entrypoint script:

```Dockerfile
FROM oryd/kratos:v0.10.1

USER root
RUN mkdir -p /etc/config/kratos && \
    mkdir -p /home/ory/.postgresql
COPY config.yml /etc/config/kratos/config.yml
COPY /jsonnet /etc/config/kratos/jsonnet
COPY /schemas /etc/config/kratos/schemas
COPY entrypoint.sh /entrypoint.sh
ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /home/ory/.postgresql/root.crt
RUN chown -R ory:ory /home/ory && \
    chmod a+r /home/ory/.postgresql
USER ory

ENTRYPOINT ["/entrypoint.sh"]
```

The script takes the constituent parts of the secret as injected in the task's `Secrets` block and assembles the DSN.  You could take the JSON instead and break it down and reassemble it in the script.  This seemed simpler.  As noted above, if you haven't restricted available characters in `DB_PASSWORD`, you may also need to URL escape it before passing it through.

```shell
#!/bin/sh

export DSN="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=verify-full&sslrootcert=/home/ory/.postgresql/root.crt"

/usr/bin/kratos "$@"
```
