### DISCUSSION TITLE
Help with converting config value to env var

### DISCUSSION THREAD

**Discussion by auctumnus** [ory/kratos#2625] [Q&A]
Hello! Quick question: I have a config file that provides hooks for before and after registration, but I can't seem to get it to be overridden by an environment variable. The relevant section is:
```
selfservice:
  flows:
    registration:
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://example.com/hooks/kratos/before_registration
```
which I was pretty sure would be configured with `SELFSERVICE_FLOWS_REGISTRATION_BEFORE_HOOKS_0_CONFIG_URL`, but Kratos is still trying to ping the URL in the config file instead of the environment variable. (I want it to vary based on the environment (prod vs dev), so it made sense to use an environment variable for this.)

**Comment by zepheiryan** [comment]
This isn't an answer, I +1'd the question but wanted to supply another data point.  I ran into something similar trying to set the client ID and secret for an OIDC provider as environment variables (via a .env file for Docker Compose).  It didn't work at first, using the placeholder values in the config as if the envvars didn't exist.  I happened to upgrade to 0.10.1 from 0.10.0 and run the migrations in between tries, after which it started to work.  I chalked this up to the version update, but I then added another OIDC provider, and the new one failed to work in the same way - while the existing one continued to work.  So I currently have one set of environment variables for provider credentials working and one set not, the only difference in .env being the index number in the envvar name.  If I switch tacks and embed the credentials into the config, it then works.

config.yml:

```
selfservice:
  methods:
    oidc:
      enabled: true
      config:
        providers:
        - id: [WorkingProvider]
          provider: [cut]
          client_id: placeholderwrong
          client_secret: placeholderwrong
          mapper_url: [cut]
          issuer_url: [cut]
          scope:
          - email
        - id: [UnusedProvider]
          provider: [cut]
          client_id: placeholderwrong
          client_secret: placeholderwrong
          mapper_url: [cut]
          scope:
          - email
        - id: [NotWorkingProvider]
          provider: [cut]
          client_id: placeholderwrong
          client_secret: placeholderwrong
          mapper_url: [cut]
          scope:
          - email
```

.env:

```
SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID=working
SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET=working
SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_ID=notworking
SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_SECRET=notworking
```
