### DISCUSSION TITLE
Is there any errors with the config yaml parser?

### DISCUSSION THREAD

**Discussion by negarciacamilo** [ory/kratos#2889] [Q&A]
I'm trying to create a docker-compose file so I could set up Ory Kratos.

This is my docker-compose:
```yml
version: '3.7'

services:
  kratos:
    image: oryd/kratos:v0.10.1
    ports:
      - '4433:4433'
      - '4434:4434'
    environment:
      - LOG_LEVEL=info
    volumes:
      - type: bind
        source: ./kratos-config.yaml
        target: /config/kratos-config.yaml
      - type: bind
        source: ./identity-schemas
        target: /etc/kratos/identity-schemas
    command: serve -c /config/kratos-config.yaml --dev
    networks:
      - intranet
    restart: unless-stopped

networks:
  intranet:
volumes:
  kratos:
```

And this is a part of my config:

```yml
identity:
  schemas:
    - id: default
      url: file:///etc/kratos/identity-schemas/user.schema.json
  default_schema_id: "default"
```

Reading some examples I found that files path should be something like `file:/// `(three slashes), but if I run that I get the following error
```
level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:invalid character '/' looking for beginning of object key string] service_name=Ory Kratos service_version=v0.10.1
```

Then I remove one slash and I get this error:
```
level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:open etc/kratos/identity-schemas/user.schema.json: no such file or directory] service_name=Ory Kratos service_version=v0.10.1
```

I am doing something wrong?

**Comment by aeneasr** [comment]
```
identity:
  schemas:
    - id: default
      url: file:///etc/kratos/identity-schemas/user.schema.json
  default_schema_id: "default"
```

looks correct, this error is probably related to some other config field!
