### DISCUSSION TITLE
Profile update issues

### DISCUSSION THREAD

**Discussion by uit2712** [ory/kratos#2933] [Q&A]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi team,
I am very happy when I find Ory Kratos for my company project, thank you for this great open source.

I use method email/password to authenticate and I have some problem when I apply Self-service user flows: profile updates. When I update profile, if I have another trait property (but email) such as display_name, I just want to update display_name (keep same email), but I get the error "An account with the same identifier (email, phone, username, ...) exists already."

I want to ask you: is there something I can do to update partial of profile only? Or maybe I missed something.
Sorry for my bad English.

### Reproducing the bug

1. Init settings flow by go to this url: http://accounts.etv.local/self-service/settings/browser
2. Update profile
2.1. I just want to update **display_name** only, but I get error: "_An account with the same identifier (email, phone, username, ...) exists already._"
2.2. If I update email, it keeps old identifier contains old email in table **identity_credential_identifiers** 

### Relevant configuration

```yml
This is my identity traits schema
{
    "id": "subscriber",
    "title": "Subscriber",
    "type": "object",
    "properties": {
        "traits": {
            "type": "object",
            "properties": {
                "user_email": {
                    "title": "Email",
                    "type": "string",
                    "format": "email",
                    "ory.sh/kratos": {
                        "credentials": {
                            "password": {
                                "identifier": true
                            }
                        },
                        "verification": {
                            "via": "email"
                        },
                        "recovery": {
                            "via": "email"
                        }
                    }
                },
                "display_name": {
                    "title": "Họ tên",
                    "type": "string"
                }
            }
        }
    }
}
```

### Version

Kratos self-hosting: v0.10.1
Kratos ory/client (php): v1.0.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Other
