### DISCUSSION TITLE
CSRF Violation with Oathkeeper/Kratos in AWS Cloud

### DISCUSSION THREAD

**Discussion by Aphex187** [ory/kratos#2981] [Q&A] [answered]
Hello ory team and merry christmas!

I've been using oathkeeper and kratos inside an AWS Cloud and can't get CSRF to work properly.

I have a frontend running on `portal.dev.mydomain.com` sending requests to `api.cportal.mydomain.com`, which is hosted by AWS ECS.

When trying the browser login flow, I get following responses:

### Kratos Get Login Flow Logs

```json
{
  "http_request": {
    "headers": {
      "accept": "application/json",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "cache-control": "no-cache",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "pragma": "no-cache",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-forwarded-for": "91.205.21.120, 10.192.220.150",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
      "x-user-id": ""
    },
    "host": "api.cportal.mydomain.com",
    "method": "GET",
    "path": "/self-service/login/browser",
    "query": null,
    "remote": "10.196.205.122:41822",
    "scheme": "http"
  },
  "level": "info",
  "msg": "started handling request",
  "time": "2022-12-24T10:35:59.819781303Z"
}
```
```json
{
  "http_request": {
    "headers": {
      "accept": "application/json",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "cache-control": "no-cache",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "pragma": "no-cache",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-forwarded-for": "91.205.21.120, 10.192.220.150",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
      "x-user-id": ""
    },
    "host": "api.cportal.mydomain.com",
    "method": "GET",
    "path": "/self-service/login/browser",
    "query": null,
    "remote": "10.196.205.122:41822",
    "scheme": "http"
  },
  "http_response": {
    "headers": {
      "cache-control": "private, no-cache, no-store, must-revalidate",
      "content-type": "application/json; charset=utf-8",
      "set-cookie": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
      "vary": "Cookie"
    },
    "size": 1521,
    "status": 200,
    "text_status": "OK",
    "took": 7673004
  },
  "level": "info",
  "msg": "completed handling request",
  "time": "2022-12-24T10:35:59.82747127Z"
}
```
### Kratos POST Login Logs
```json
{
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "content-length": "182",
      "content-type": "application/json",
      "cookie": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-csrf-token": "GkTbjg7nwZwdu7XgIrxooR77e3SG2Qv90DyXH9Ws/n626QNtZZ5F94OTaSNg3dN+1SKGvzHKcDS0FdcVnHzePQ==",
      "x-forwarded-for": "91.205.21.120, 10.192.220.150",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
      "x-user-id": ""
    },
    "host": "api.cportal.mydomain.com",
    "method": "POST",
    "path": "/self-service/login",
    "query": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
    "remote": "10.196.205.122:41822",
    "scheme": "http"
  },
  "level": "info",
  "msg": "started handling request",
  "time": "2022-12-24T10:35:59.904838995Z"
}
```
```json
{
  "audience": "application",
  "error": {
    "debug": "",
    "details": {
      "docs": "https://www.ory.sh/kratos/docs/debug/csrf",
      "hint": "The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token).",
      "reject_reason": "The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow."
    },
    "message": "the request was rejected to protect you from Cross-Site-Request-Forgery",
    "reason": "Please retry the flow and optionally clear your cookies. The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues.",
    "status": "Forbidden",
    "status_code": 403
  },
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "content-length": "182",
      "content-type": "application/json",
      "cookie": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-csrf-token": "GkTbjg7nwZwdu7XgIrxooR77e3SG2Qv90DyXH9Ws/n626QNtZZ5F94OTaSNg3dN+1SKGvzHKcDS0FdcVnHzePQ==",
      "x-forwarded-for": "91.205.21.120, 10.192.220.150",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
      "x-user-id": ""
    },
    "host": "api.cportal.mydomain.com",
    "method": "POST",
    "path": "/self-service/login",
    "query": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
    "remote": "10.196.205.122:41822",
    "scheme": "http"
  },
  "http_response": {
    "status_code": 403
  },
  "level": "info",
  "msg": "An error occurred while handling a request",
  "service_name": "Ory Kratos",
  "service_version": "v0.11.0",
  "time": "2022-12-24T10:35:59.913660167Z"
}
```

### Oathkeeper Get Login Flow Log

```json
{
  "http_request": {
    "headers": {
      "accept": "application/json",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-forwarded-for": "90.201.21.121",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https"
    },
    "host": "api.cportal.mydomain.com",
    "method": "GET",
    "path": "/kratos-portal-customer/self-service/login/browser",
    "query": null,
    "remote": "10.195.221.100:23678",
    "scheme": "http"
  },
  "level": "info",
  "msg": "started handling request",
  "time": "2022-12-24T10:28:13Z"
}
```

```json
{
  "audience": "application",
  "granted": true,
  "http_host": "api.cportal.mydomain.com",
  "http_method": "GET",
  "http_url": "http://kratos-portal-customer.ecs.cportal.mydomain.com:4433/self-service/login/browser",
  "http_user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
  "level": "warning",
  "msg": "Access request granted",
  "service_name": "ORY Oathkeeper",
  "service_version": "v0.40.0",
  "subject": "",
  "time": "2022-12-24T10:28:14Z"
}
```

```json
{
  "http_request": {
    "headers": {
      "accept": "application/json",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-forwarded-for": "90.201.21.121",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https"
    },
    "host": "api.cportal.mydomain.com",
    "method": "GET",
    "path": "/kratos-portal-customer/self-service/login/browser",
    "query": null,
    "remote": "10.195.221.122:23678",
    "scheme": "http"
  },
  "http_response": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "https://portal.dev.mydomain.com",
      "access-control-expose-headers": "Content-Type",
      "cache-control": "private, no-cache, no-store, must-revalidate",
      "content-length": "1523",
      "content-type": "application/json; charset=utf-8",
      "date": "Sat, 24 Dec 2022 10:28:14 GMT",
      "set-cookie": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
      "vary": "Origin"
    },
    "size": 1523,
    "status": 200,
    "text_status": "OK",
    "took": 143284895
  },
  "level": "info",
  "msg": "completed handling request",
  "time": "2022-12-24T10:28:14Z"
}
```
### Oathkeeper Preflight Request and Login POST

```json
{
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "access-control-request-headers": "content-type,x-csrf-token",
      "access-control-request-method": "POST",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-forwarded-for": "90.201.21.121",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https"
    },
    "host": "api.cportal.mydomain.com",
    "method": "OPTIONS",
    "path": "/kratos-portal-customer/self-service/login",
    "query": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
    "remote": "10.195.221.122:23678",
    "scheme": "http"
  },
  "http_response": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-headers": "Content-Type, X-Csrf-Token",
      "access-control-allow-methods": "POST",
      "access-control-allow-origin": "https://portal.dev.mydomain.com",
      "vary": "Origin"
    },
    "size": 0,
    "status": 204,
    "text_status": "No Content",
    "took": 272770
  },
  "level": "info",
  "msg": "completed handling request",
  "time": "2022-12-24T10:28:14Z"
}
```
`[cors] 2022/12/24 10:28:14 Preflight response headers: map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Headers:[Content-Type, X-Csrf-Token] Access-Control-Allow-Methods:[POST] Access-Control-Allow-Origin:[https://portal.dev.mydomain.com] Vary:[Origin Access-Control-Request-Method Access-Control-Request-Headers]]`
`[cors] 2022/12/24 10:28:14 Handler: Preflight request`

```json
{
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "access-control-request-headers": "content-type,x-csrf-token",
      "access-control-request-method": "POST",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-forwarded-for": "90.201.21.121",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https"
    },
    "host": "api.cportal.mydomain.com",
    "method": "OPTIONS",
    "path": "/kratos-portal-customer/self-service/login",
    "query": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
    "remote": "10.195.221.122:23678",
    "scheme": "http"
  },
  "level": "info",
  "msg": "started handling request",
  "time": "2022-12-24T10:28:14Z"
}
```
`[cors] 2022/12/24 10:28:14 Actual response added headers: map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Origin:[https://portal.dev.mydomain.com] Access-Control-Expose-Headers:[Content-Type] Vary:[Origin]]`
`[cors] 2022/12/24 10:28:14 Handler: Actual request`

```json
{
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "content-length": "182",
      "content-type": "application/json",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-csrf-token": "kLyGIohaton7zpWlFPFkhbLTQ+ICCo9gm0lOKuKI5TJ1yrC+ekP4LV/MZvEJIw0iOfv5UoVlu9cxIUtrHvY0Jg==",
      "x-forwarded-for": "90.201.21.121",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https"
    },
    "host": "api.cportal.mydomain.com",
    "method": "POST",
    "path": "/kratos-portal-customer/self-service/login",
    "query": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
    "remote": "10.195.221.122:23678",
    "scheme": "http"
  },
  "level": "info",
  "msg": "started handling request",
  "time": "2022-12-24T10:28:14Z"
}
```

```json
{
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.5",
      "content-length": "182",
      "content-type": "application/json",
      "dnt": "1",
      "origin": "https://portal.dev.mydomain.com",
      "referer": "https://portal.dev.mydomain.com/",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-site",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
      "x-csrf-token": "kLyGIohaton7zpWlFPFkhbLTQ+ICCo9gm0lOKuKI5TJ1yrC+ekP4LV/MZvEJIw0iOfv5UoVlu9cxIUtrHvY0Jg==",
      "x-forwarded-for": "90.201.21.121",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https"
    },
    "host": "api.cportal.mydomain.com",
    "method": "POST",
    "path": "/kratos-portal-customer/self-service/login",
    "query": "Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
    "remote": "10.195.221.122:23678",
    "scheme": "http"
  },
  "http_response": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "https://portal.dev.mydomain.com",
      "access-control-expose-headers": "Content-Type",
      "cache-control": "private, no-cache, no-store, must-revalidate",
      "content-length": "794",
      "content-type": "application/json",
      "date": "Sat, 24 Dec 2022 10:28:14 GMT",
      "vary": "Origin"
    },
    "size": 794,
    "status": 403,
    "text_status": "Forbidden",
    "took": 10855936
  },
  "level": "info",
  "msg": "completed handling request",
  "time": "2022-12-24T10:28:14Z"
}
```

```json
{
  "audience": "application",
  "granted": true,
  "http_host": "api.cportal.mydomain.com",
  "http_method": "POST",
  "http_url": "http://kratos-portal-customer.ecs.cportal.mydomain.com:4433/self-service/login?flow=f1731004-331e-4c63-905f-4af8ccd21b27",
  "http_user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
  "level": "warning",
  "msg": "Access request granted",
  "service_name": "ORY Oathkeeper",
  "service_version": "v0.40.0",
  "subject": "",
  "time": "2022-12-24T10:28:14Z"
}
```

#### Get Login Flow Response
```json
{
  "id": "57162f61-1c17-4a08-af43-aaa8e9402419",
  "oauth2_login_challenge": null,
  "type": "browser",
  "expires_at": "2022-12-24T10:45:59.82015554Z",
  "issued_at": "2022-12-24T10:35:59.82015554Z",
  "request_url": "https://api.cportal.mydomain.com/self-service/login/browser",
  "ui": {
    "action": "https://api.cportal.mydomain.com/kratos-portal-customer/self-service/login?flow=57162f61-1c17-4a08-af43-aaa8e9402419",
    "method": "POST",
    "nodes": [
      {
        "type": "input",
        "group": "default",
        "attributes": {
          "name": "csrf_token",
          "type": "hidden",
          "value": "GkTbjg7nwZwdu7XgIrxooR77e3SG2Qv90DyXH9Ws/n626QNtZZ5F94OTaSNg3dN+1SKGvzHKcDS0FdcVnHzePQ==",
          "required": true,
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {}
      },
      {
        "type": "input",
        "group": "default",
        "attributes": {
          "name": "identifier",
          "type": "text",
          "value": "",
          "required": true,
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1070004,
            "text": "ID",
            "type": "info"
          }
        }
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "password",
          "type": "password",
          "required": true,
          "autocomplete": "current-password",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1070001,
            "text": "Password",
            "type": "info"
          }
        }
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "method",
          "type": "submit",
          "value": "password",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1010001,
            "text": "Sign in",
            "type": "info",
            "context": {}
          }
        }
      }
    ]
  },
  "created_at": "2022-12-24T10:35:59.822603Z",
  "updated_at": "2022-12-24T10:35:59.822603Z",
  "refresh": false,
  "requested_aal": "aal1"
}
```
#### POST Login Request

`POST to https://api.cportal.mydomain.com/kratos-portal-customer/self-service/login?flow=57162f61-1c17-4a08-af43-aaa8e9402419`

##### Request Headers:

```json
{
  "Request Headers (794 B)": {
    "headers": [
      {
        "name": "Accept",
        "value": "*/*"
      },
      {
        "name": "Accept-Encoding",
        "value": "gzip, deflate, br"
      },
      {
        "name": "Accept-Language",
        "value": "en-US,en;q=0.5"
      },
      {
        "name": "Connection",
        "value": "keep-alive"
      },
      {
        "name": "Content-Length",
        "value": "182"
      },
      {
        "name": "Content-Type",
        "value": "application/json"
      },
      {
        "name": "Cookie",
        "value": "csrf_token_acc8c4fc52eee13ce4c2c2db298d0d3c77426960e3b1fd261cfefe711eb6b5da=wvi7QJ4jRZ+zd+D6IQRK9qSQedKZg0qfERpuuMAfJ/U="
      },
      {
        "name": "DNT",
        "value": "1"
      },
      {
        "name": "Host",
        "value": "api.cportal.mydomain.com"
      },
      {
        "name": "Origin",
        "value": "https://portal.dev.mydomain.com"
      },
      {
        "name": "Referer",
        "value": "https://portal.dev.mydomain.com/"
      },
      {
        "name": "Sec-Fetch-Dest",
        "value": "empty"
      },
      {
        "name": "Sec-Fetch-Mode",
        "value": "cors"
      },
      {
        "name": "Sec-Fetch-Site",
        "value": "same-site"
      },
      {
        "name": "TE",
        "value": "trailers"
      },
      {
        "name": "User-Agent",
        "value": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0"
      },
      {
        "name": "X-CSRF-Token",
        "value": "GkTbjg7nwZwdu7XgIrxooR77e3SG2Qv90DyXH9Ws/n626QNtZZ5F94OTaSNg3dN+1SKGvzHKcDS0FdcVnHzePQ=="
      }
    ]
  }
}
```

##### Request Body:

```json
{
  "password": "testpassword",
  "identifier": "mymail@mydomain.de",
  "csrf_token": "GkTbjg7nwZwdu7XgIrxooR77e3SG2Qv90DyXH9Ws/n626QNtZZ5F94OTaSNg3dN+1SKGvzHKcDS0FdcVnHzePQ==",
  "method": "password"
}
```

#### Oathkeeper configuration

```yaml
version: "v0.38.20-beta.1"

serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - "https://portal.dev.mydomain.com"
      allow_credentials: true
      debug: true
      allowed_headers:
        - Authorization
        - Content-Type
        - X-CSRF-Token
      exposed_headers:
        - Content-Type
  api:
    port: 4456

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User-ID: "{{ print .Subject }}"
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

authenticators:
  noop:
    enabled: true
  bearer_token:
    enabled: true
    config:
      check_session_url: http://kratos-app-public/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
```

#### Oathkeeper rules

```yaml
- id: "ory:kratos-portal-customer:public"
  version: v0.40.0
  upstream:
    preserve_host: true
    url: http://kratos-portal-customer-public/
    strip_path: /kratos-portal-customer
  match:
    url: https://<[a-zA-Z0-9.\-_]*(:[0-9]*)?>/kratos-portal-customer/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: header
```

#### Kratos configuration

```yaml
version: v0.11.0

dsn: memory

serve:
  public:
    base_url: http://portal.dev.mydomain.com/kratos-portal-customer/ 
    cors:
      enabled: false
  admin:
    base_url: http://kratos-portal-customer-admin/

selfservice:
  default_browser_return_url: http://localhost/ # TBD

  methods:
    code:
      enabled: true
      config:
        lifespan: 1h
    password:
      enabled: true
      config:
        min_password_length: 6
        identifier_similarity_check_enabled: true

  flows:
    settings:
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost/recovery # TBD
      after:
        default_browser_return_url: http://localhost/ # TBD
      use: code

    verification:
      enabled: false

    login:
      lifespan: 10m
      ui_url: http://localhost/login # TBD
      after:
        password:
          default_browser_return_url: http://localhost/ # TBD

    logout:
      after:
        default_browser_return_url: http://localhost/ # TBD

    registration:
      enabled: false

    error:
      ui_url: http://localhost/error # TBD

cookies:
  domain: mydomain.com

session:
  lifespan: 1h

secrets:
  cookie:
    - MYCOOKIESECRET
  cipher:
    - MYCIPHER

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 12

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/custom.schema.json

courier:
  smtp:
    connection_uri: smtp://test:test@localhost
```

I notice the Anti-CSRF Token in the request body and in the request header are not the same as the one set in the Set-Cookie Response from the server, which seems kinda illogical to me.

I've tried different configurations, sending the CSRF set in the cookie inside the request body and many other unsuccessful things.

Any help would be greatly appreciated!
