### DISCUSSION TITLE
Link expiration and flow expiration are needlessly complicated

### DISCUSSION THREAD

**Discussion by Sytten** [ory/kratos#3034] [Q&A]
Hi there!
Took me a long time to dig up in the code to understand why the expiration of verification links was not the same as the expiration of the flow so I figured I would comment it somewhere. Basically you need to set:
```yaml
 methods:
    link:
      config:
        lifespan: 24h
  flows:
    verification:
      lifespan: 24h
```
But this also sets the link lifetime for the other flows (like recovery) but it is safe since kratos should first check if the flow is expired before proceeding to check the token. 

I just don't understand the need for a different configuration, AFAIK it is not explained anywhere in the code and it's just confusing without really adding any benefit that I can think of.
