### DISCUSSION TITLE
Ory Kratos quickstart example with webauthn flow

### DISCUSSION THREAD

**Discussion by SangI762** [ory/kratos#3322] [Q&A]
Hello, I'm new to Ory Kratos solutions. I just tried to launch locally this quickstart example as it described here: https://www.ory.sh/docs/kratos/quickstart and it works as expected. However I'm interested in WebAuthn (PassKey) flow for registration and login instead of password. Is it possible to achieve that on this quickstart example, does self-service support that? How can I enable it? What I need to change in compose configuration? Read a lot of docs, but didn't find clear way how to do it. Thanks a lot for any help.

**Comment by vinckr** [comment]
Hello @SangI762 
apologies for the late answer. 

You are in luck, there is actually a docker-compose for a quickstart with WebAuthn, check it out: 
- docker-compose: https://github.com/ory/kratos/blob/master/quickstart-webauthn.yml
- https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/webauthn/kratos.yml

To enable WebAuthn in your self-hosted Kratos instance, you need to add the webauthn method to selfservice.methods in the Ory Kratos configuration file. Here is an example of how to do it:

```
selfservice:  
 methods:  
 webauthn:  
 config:  
 passwordless: false  
 rp:  
 display_name: SAMPLE_NAME  
 # Set 'id' to the top-level domain.  
 id: loginpage.com  
 # Set 'origin' to the exact URL of the page that prompts the user to use WebAuthn. You must include the scheme, host, and port.  
 origin: https://loginpage.auth.com:4455  
 enabled: true
```

Pay special attention to the origin URL, as it has to match the scheme, host, and port of the page you're starting the flow from.

Please let me know if that helped!
