### DISCUSSION TITLE
Can not get settings after hook to update identity

### DISCUSSION THREAD

**Discussion by bernessco** [ory/kratos#3334] [Q&A] [answered]
I ran in to the problem that I'm unable to update identity with settings after hook, seems that it ignores the response.

Ory documentation says it should work:

> Modifying the identity is currently only possible during the registration and settings flows.

https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#modify-identities

Did i mess up configuration or is it a bug?

Kratos settings:

```yaml
...
 settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://localhost:4000/webhook/settings/before
              method: POST
              body: base64://ZnVuY3Rpb24oY3R4KSB7IGN0eDogY3R4IH0=
              response:
                parse: true
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://localhost:4000/webhook/settings/after/password/pre-persist
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7IGN0eDogY3R4IH0=
                response:
                  parse: true
            - hook: web_hook
              config:
                url: http://localhost:4000/webhook/settings/after/password/post-persist
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7IGN0eDogY3R4IH0=
                response:
                  parse: false
        profile:
          hooks:
            - hook: web_hook
              config:
                url: http://localhost:4000/webhook/settings/after/profile/pre-persist
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7IGN0eDogY3R4IH0=
                response:
                  parse: true
            - hook: web_hook
              config:
                url: http://localhost:4000/webhook/settings/after/profile/post-persist
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7IGN0eDogY3R4IH0=
                response:
                  parse: false
```
Handler code:

```typescript
    @Post('/settings/after/password/pre-persist')
    @HttpCode(200)
    async afterSettingsPasswordPrePersistHook () {
        this.logger.debug('Received Webhook: After Settings Pre Persist Password')

        return { identity: {
            metadata_public: {
                test: 1
            }
        } }
    }
  ```
