### DISCUSSION TITLE
Kratos - Hydra integration with selfservice ui and invalid login challenge

### DISCUSSION THREAD

**Discussion by trautonen** [ory/kratos#3339] [Q&A] [answered]
I've tried to set up the Kratos - Hydra integration along with the latest consent page addition to selfservice ui, but for some reason when I try to initiate the login flow, Kratos eventually responds with:

```
msg=An error occurred and is being forwarded to the error user interface. audience=application error=map[debug: message:The request was malformed or contained invalid parameters reason:the login_challenge parameter is present but invalid or zero UUID stack_trace:
  github.com/ory/kratos/hydra.GetLoginChallengeID
    /project/hydra/hydra.go:56
  ...
```

I'm using kratos v0.13.0, hydra v2.2.0 and selfservice ui from this commit https://github.com/ory/kratos-selfservice-ui-node/commit/9a7abdcc95b609137a253090dcdbc893e3258f84

I don't have anything special in the config, basic docker-compose setup from the examples with Kratos config like
```
    ...
    oidc:
      enabled: true
      config:
        providers:
          - id: hydra
            provider: generic
            mapper_url: file:///etc/config/kratos/oidc.hydra.jsonnet
            client_id: clientid
            client_secret: clientsecret
            scope:
              - openid
            issuer_url: http://hydra:4444/
            auth_url: http://127.0.0.1:4444/oauth2/auth
            token_url: http://127.0.0.1:4444/oauth2/token
            requested_claims:
              id_token:
                email:

oauth2_provider:
  url: http://hydra:4445
```
and hydra urls pointing to the corresponding selfservice ui pages for login, logout and consent.

Everything looks correct to me and I can see from the logs that Kratos receives the login_challenge parameter and it looks some encrypted payload to me, but for some reason Kratos does not like it. I'm a bit lost what goes wrong and where.
