### DISCUSSION TITLE
Redirect to /self-service/registration hangs

### DISCUSSION THREAD

**Discussion by aaberg** [ory/kratos#3353] [Q&A]
Hi,

I'm setting up Kratos to run locally with a web application. I have a problem with the `/self-service/registration` endpoint. Whenever I post a valid form to it, the browser doesn't get any reply and hangs. With an invalid request, it works fine, I get a 302 back to the signup page. But with a valid request, the redirect never happens, and the page times out after a time.

I've tried to totally remove docker images and let docker compose reinstall everything. I've tried different browsers and to delete all cookies. Not sure what else to try...

Any suggestions on what might be the cause for this?

Please look at the screenshot below for an example recorded by Chrome devtools. Here I first post an invalid form (missing password) which returns as expected. The valid request times out (though the user is created, so I can successfully log in afterwards).

![image](https://github.com/ory/kratos/assets/651812/080cb9af-f9d0-49d1-8d88-1b09fdf7503f)

My `kratos.yml` file looks like this:
``` yml
version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:5173/
  allowed_return_urls:
    - http://127.0.0.1:5173

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:5173/auth/error

    settings:
      ui_url: http://127.0.0.1:5173/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:5173/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:5173/auth/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:5173/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:5173/

    login:
      ui_url: http://127.0.0.1:5173/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:5173/auth/signup
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - xxx
  cipher:
    - xxx

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

```
