### DISCUSSION TITLE
A valid Ory Session Cookie or Ory Session Token is missing | Unauthorized status_code:401 | Self Hosted Pixie

### DISCUSSION THREAD

**Discussion by miryalasaigoutham** [ory/kratos#3375] [Q&A] [answered]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi Team,

I'm seeing the below error while users are redeeming the invitation in the self hosted pixie

`

time=2023-07-06T04:18:10Z level=info msg=An error occurred while handling a request func=github.com/ory/x/logrusx.(*Logger).ReportError file=/go/pkg/mod/github.com/ory/x@v0.0.392/logrusx/logrus.go:226 audience=application error=map[debug: message:The request could not be authorized reason:A valid Ory Session Cookie or Ory Session Token is missing. stack_trace: status:Unauthorized status_code:401] http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.9 connection:close cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". referer:https://<<URL>> sec-ch-ua:"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"macOS" sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 x-forwarded-for:73.223.43.32 x-forwarded-host:<<host_name>> x-forwarded-port:443 x-forwarded-proto:https x-forwarded-scheme:https x-real-ip:<<IP_Address>> x-request-id:5daf8a46490c7575ea1f63f70eb04f7b x-scheme:https] host:kratos.plc.svc.cluster.local:4433 method:GET path:/self-service/settings/flows query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:1<<IP_Address>>:34738 scheme:https] http_response=map[status_code:401] service_name=Ory Kratos service_version=v0.10.1

`

Below are my config

`

/etc/config/kratos $ cat kratos.yml
# All URLS must be set in the environment variables instead of config.
selfservice:
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    link:
      enabled: true
  flows:
    verification:
      enabled: false

    recovery:
      enabled: true

    settings:
      privileged_session_max_age: 15m

    registration:
      after:
        password:
          hooks:
            -
              hook: session
log:
  level: trace
hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
/etc/config/kratos $ cat identity.schema.json
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "User",
  "type": "object",
  "properties": {
    "traits":{
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            }
          }
        }
      },
      "required": [
        "email"
      ]
    }
  },
  "additionalProperties": false
}
/etc/config/kratos $

`

### Reproducing the bug

Follow the Self Hosted Pixie deployment documentation

### Relevant log output

```shell
time=2023-07-06T04:18:10Z level=info msg=An error occurred while handling a request func=github.com/ory/x/logrusx.(*Logger).ReportError file=/go/pkg/mod/github.com/ory/x@v0.0.392/logrusx/logrus.go:226 audience=application error=map[debug: message:The request could not be authorized reason:A valid Ory Session Cookie or Ory Session Token is missing. stack_trace: status:Unauthorized status_code:401] http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.9 connection:close cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". referer:https://<<URL>> sec-ch-ua:"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"macOS" sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 x-forwarded-for:73.223.43.32 x-forwarded-host:<<host_name>> x-forwarded-port:443 x-forwarded-proto:https x-forwarded-scheme:https x-real-ip:<<IP_Address>> x-request-id:5daf8a46490c7575ea1f63f70eb04f7b x-scheme:https] host:kratos.plc.svc.cluster.local:4433 method:GET path:/self-service/settings/flows query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:1<<IP_Address>>:34738 scheme:https] http_response=map[status_code:401] service_name=Ory Kratos service_version=v0.10.1
```

### Relevant configuration

```yml
/etc/config/kratos $ cat kratos.yml
# All URLS must be set in the environment variables instead of config.
selfservice:
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    link:
      enabled: true
  flows:
    verification:
      enabled: false

    recovery:
      enabled: true

    settings:
      privileged_session_max_age: 15m

    registration:
      after:
        password:
          hooks:
            -
              hook: session
log:
  level: trace
hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
/etc/config/kratos $ cat identity.schema.json
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "User",
  "type": "object",
  "properties": {
    "traits":{
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            }
          }
        }
      },
      "required": [
        "email"
      ]
    }
  },
  "additionalProperties": false
}
/etc/config/kratos $
```

### Version

service_name=Ory Kratos service_version=v0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes
