### DISCUSSION TITLE
How to use Mail API courier with sendgrid

### DISCUSSION THREAD

**Discussion by a-damian** [ory/kratos#3394] [Q&A] [answered]
Hello,
I'm trying to setup the configuration for my courier using the `delivery_strategy: http` on Kratos v1.0.0
I've checked the [docs](https://www.ory.sh/docs/kratos/self-hosted/email-http) but I can't figure out how to configure this section to work with sendgrid.

(body jsonnet has the default value)
```yaml
courier:
  delivery_strategy: http
  http:
    request_config:
      url: https://api.sendgrid.com/v3/mail/send
      method: POST
      body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgcmVjaXBpZW50OiBjdHguUmVjaXBpZW50LAogIHRlbXBsYXRlX3R5cGU6IGN0eC5UZW1wbGF0ZVR5cGUsCiAgdG86IGlmICJUZW1wbGF0ZURhdGEiIGluIGN0eCAmJiAiVG8iIGluIGN0eC5UZW1wbGF0ZURhdGEgdGhlbiBjdHguVGVtcGxhdGVEYXRhLlRvIGVsc2UgbnVsbCwKICByZWNvdmVyeV9jb2RlOiBpZiAiVGVtcGxhdGVEYXRhIiBpbiBjdHggJiYgIlJlY292ZXJ5Q29kZSIgaW4gY3R4LlRlbXBsYXRlRGF0YSB0aGVuIGN0eC5UZW1wbGF0ZURhdGEuUmVjb3ZlcnlDb2RlIGVsc2UgbnVsbCwKICByZWNvdmVyeV91cmw6IGlmICJUZW1wbGF0ZURhdGEiIGluIGN0eCAmJiAiUmVjb3ZlcnlVUkwiIGluIGN0eC5UZW1wbGF0ZURhdGEgdGhlbiBjdHguVGVtcGxhdGVEYXRhLlJlY292ZXJ5VVJMIGVsc2UgbnVsbCwKICB2ZXJpZmljYXRpb25fdXJsOiBpZiAiVGVtcGxhdGVEYXRhIiBpbiBjdHggJiYgIlZlcmlmaWNhdGlvblVSTCIgaW4gY3R4LlRlbXBsYXRlRGF0YSB0aGVuIGN0eC5UZW1wbGF0ZURhdGEuVmVyaWZpY2F0aW9uVVJMIGVsc2UgbnVsbCwKICB2ZXJpZmljYXRpb25fY29kZTogaWYgIlRlbXBsYXRlRGF0YSIgaW4gY3R4ICYmICJWZXJpZmljYXRpb25Db2RlIiBpbiBjdHguVGVtcGxhdGVEYXRhIHRoZW4gY3R4LlRlbXBsYXRlRGF0YS5WZXJpZmljYXRpb25Db2RlIGVsc2UgbnVsbCwKICBzdWJqZWN0OiBjdHguU3ViamVjdCwKICBib2R5OiBjdHguQm9keQp9Cg==
      headers:
        'Content-Type': 'application/json'
        # 'Authorization': 'Bearer SENDGRID_API_KEY'
      auth:
        type: api_key
        config:
          name: Authorization
          value: Bearer SENDGRID_API_KEY
          in: header
```

I kept getting a 401 response from sendgrid, for me is unclear if the name of the API key under `auth.config.name`, should be `Authorization` since its passed as a header.

Any help is appreciated, many thanks!.

**Comment by vinckr** [comment]
Hello @a-damian 

It seems like you're on the right track with your configuration. However, there are no docs on configuring the courier for HTTP delivery strategy with SendGrid, so I am not sure what the issue is.

The `auth.config.name` field under auth should indeed be Authorization if it's being passed as a header. The `value` field also checks out.
However, the 401 response from SendGrid indicates an authorization error. Can you check the API key, and in devtools that the request is sent correctly?

**Reply by a-damian** [reply, marked as answer]
Hello @vinckr 
Thanks for the response, you were right, the config in place was configured correctly, I was getting 400 or 401 status codes from SendGrid since I was using the default body `jsonnet`, to solve the issue I adjusted the `jsonnet` file to match SendGrid specifications.
Here is the SendGrid API V3 docs in case some one need them. [docs](https://docs.sendgrid.com/api-reference/mail-send/mail-send) 

Finally here is an example of how my config ended:
```yaml
courier:
  delivery_strategy: http
  http:
    request_config:
      url: https://api.sendgrid.com/v3/mail/send
      method: POST
      body: base64://BASE_64_JSONNET_PERSONALIZED_TO_MATCH_SENDGRID_BODY
      headers:
        'Content-Type': 'application/json'
      auth:
        type: api_key
        config:
          name: Authorization
          value: Bearer YOUR_SENDGRID_API_KEY
          in: header
```

Thanks!

**Reply by vinckr** [reply]
Thanks for sharing your fix @a-damian !
I'll make a note to add it to the docs somewhere.

**Reply by nihalgurjar47** [reply]
I am using the same configuration, but it's not working for me.
I am a bit confused about Jsonnet; could you provide more information on Jsonnet?

my configuration is
courier:
  delivery_strategy: http
  http:
    request_config:
      url: https://api.sendgrid.com/v3/mail/send
      method: POST
      body: base64://BASE_64_JSONNET_PERSONALIZED_TO_MATCH_SENDGRID_BODY
      headers:
        'Content-Type': 'application/json'
      auth:
        type: api_key
        config:
          name: Authorization
          value: Bearer sendgrid_api_key
          in: header


I am getting connection_uri error please check in below screenshot.
![Screenshot from 2024-01-02 19-14-33](https://github.com/ory/kratos/assets/104414738/d6ecb3a8-4a9b-4870-8599-9a2125c8df7c)

**Reply by a-damian** [reply]
Plase check sendgrid docs (https://docs.sendgrid.com/api-reference/mail-send/mail-send) to review what type of info you need to send to that API and your sendgrid email template: https://www.ory.sh/docs/kratos/self-hosted/email-http maybe you can send the email verify code in the body of sendgrid, under `perzonalizations.substitutions` to inject that value (and others) into your sendgrid template.
Also for the Jsonnet you can find in the next doc page a sample of what values the `ctx` object has inside and build your jsonnet with that info. Check the slidedown.
![image](https://github.com/ory/kratos/assets/56703361/7784fa83-7665-4df5-9db4-4db8e21656c2)
https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks
Lastly I recommend you use this playground check your jsnoet writing
https://jsonnet.org/
Just remember to simulate/hardcode the `ctx` value to test the outputs of the jsonet.

Hope this helps you!

**Reply by nihalgurjar47** [reply]
Hii @vinckr @a-damian

There is a another way to configure ory kratos with sendgrid.

Configuration:-
smtp://apikey:<sendgrid_api_key>@smtp.sendgrid.net:<sendgrid_port>/?skip_ssl_verify=true

for username use hard coded value apikey and for password use the generated apikey

**Reply by hiltpold** [reply]
@a-damian Thank you for providing some information on how to use the http delivery mode. I'm currently at your stage, but i cannot provide a working jsonnet. Could you provide an example with all the values correctly set? Thank you! The simplest example that somehow works for me is, providing a simple `mail.template.jsonnet` in the following format:
```
{
  "personalizations": [
    {
      "to": [
        {
          "email": "example@to.com"
        }
      ]
    }
  ],
  "from": {
    "email": "example@from.com"
  },
  "subject": "Account Verification",
  "content": [
    {
      "type": "text/plain",
      "value": "Ory Kratos Sendgrid integration"
    }
  ]
}
```
and this can then by provided in the `kratos.yaml`:
```
courier:
  delivery_strategy: http
  http:
    request_config:
      url: https://api.sendgrid.com/v3/mail/send
      method: POST
      body: file:///etc/config/kratos/mail.template.jsonnet
      headers:
        "Content-Type": "application/json"
      auth:
        type: api_key
        config:
          name: Authorization
          value: Bearer API_KEY
          in: header
```
I would be particularly interested in understanding how you configured it to have the equivalent of [documentation](https://www.ory.sh/docs/kratos/self-hosted/email-http) that works for all flows.
