### DISCUSSION TITLE
transient payload in registration form (server-side, browser)

### DISCUSSION THREAD

**Discussion by akhayyat** [ory/kratos#3414] [Q&A]
I'm trying to get additional data in the registration form in my server-side web application using transient payload, as documented in https://www.ory.sh/docs/kratos/bring-your-own-ui/custom-ui-basic-integration and  https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks.

I have an HTML form input like this:

```html
<input type="text" name="transient_payload.my_field" required="" id="id_transient_payload.my_field">
```

However, this results in a `transient_payload` value of `{}` (empty object).

I've also tried setting the name of the HTML `input` to just `transient_payload`:

```html
<input type="text" name="transient_payload" required="" id="id_transient_payload">
```
which results in the error: `Error: Unable to decode JSON payload`. Also, this would not allow me to control the name of the input, or adding additional inputs to be picked up by my webhook.

So, how do I pass additional inputs in the registration form to be picked up by a webhook during registration, without persisting them in Ory?

**Comment by vinckr** [comment]
Hello @akhayyat 

you are using the right feature, that is exactly what transient_payload field is designed for. 

To pass additional data to the flow using the optional transient_payload field, you need to include it in the POST request payload when submitting the registration form. This data gets forwarded to webhooks without being persisted by Ory like identity traits do.

If the object is empty or there is a JSON decode error there is probably some issue in your code. 
Can you share the full example with steps to reproduce maybe? 
I suspect you have some minor issue in your frontend code there. 

For example from our tests:

```
updateRegistrationFlowBody: {
                  method: "password",
                  transient_payload: testPayload,
                },
```

**Reply by akhayyat** [reply]
I'm not using a client-side frontend. My form is an html form rendered by the server and submitted using a form POST.

The values submitted by my form are the values of the html form input elements, e.g. text entered in a text box, not json. HTML forms don't send json values.

I'll share an example in a bit.

**Reply by akhayyat** [reply]
Let's say, for the sake of this example, that first name and last name are to be passed to the application and are not a part of the user's identity in Ory.

## HTML Form

This is the server-side rendered HTML form:

```html
<form action="http://127.0.0.1:4433/self-service/registration?flow=5557af13-2d15-4d61-8683-f7dd29e16a10" method="POST">
    <div>
        <label for="id_traits.email">E-Mail:</label>
        <input type="text" name="traits.email" required="" id="id_traits.email">
    </div>
    <div>
        <label for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password">
    </div>
    <div>
        <label for="id_transient_payload.first_name">First Name:</label>
        <input type="text" name="transient_payload.first_name" required="" id="id_transient_payload.first_name">
        <input type="hidden" name="csrf_token" value="iasjjOEXpCwT2TXxnQ8nuXXiWmCB2A8Epn5uM6BQ+BU38BMu1h6qsByxew45gc4i4Iwt4oqw2hwCXpqTij+ZLQ==" id="id_csrf_token">
    </div>
    <div>
        <label for="id_transient_payload.last_name">First Name:</label>
        <input type="text" name="transient_payload.last_name" required="" id="id_transient_payload.last_name">
        <input type="hidden" name="csrf_token" value="iasjjOEXpCwT2TXxnQ8nuXXiWmCB2A8Epn5uM6BQ+BU38BMu1h6qsByxew45gc4i4Iwt4oqw2hwCXpqTij+ZLQ==" id="id_csrf_token">
    </div>
    <button name="method" type="submit" value="password">Join </button>
</form>
```

## kratos.yml

```yaml
    ...
    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:1234/users/join/
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
            - hook: web_hook
              config:
                url: http://172.17.0.1:1234/users/
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7IHVzZXJfaWQ6IGN0eC5pZGVudGl0eS5pZCwgZW1haWw6IGN0eC5pZGVudGl0eS50cmFpdHMuZW1haWwsIGZpcnN0X25hbWU6IHsgbmFtZTogY3R4LmZsb3cudHJhbnNpZW50X3BheWxvYWQgfSB9
                response:
                  parse: true
```

The `body` jsonnet template above is the base64-encoded version of this function:

```js
function(ctx) { user_id: ctx.identity.id, email: ctx.identity.traits.email, first_name: { name: ctx.flow.transient_payload } }
```

This results in a `transient_payload` (and `first_name`)  value of `{}`.

What do I need to change to get Ory to pass both `first_name` and `last_name` form field values from the registration form to my application?

Also, this results in `user_id` being set to `"00000000-0000-0000-0000-000000000000"`! Why am I not getting a real user ID?

**Reply by vinckr** [reply]
How are you running Ory Kratos and what version are you on?

**Reply by akhayyat** [reply]
`docker compose -f quickstart.yml up --build --force-recreate` using a slightly modified version of the `quickstart.yml` docker compose config in the kratos repository.

`image: oryd/kratos:v0.13.0`

## `quickstart.yml`:

```yaml
version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos-config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
    networks:
      - intranet
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos-config
        target: /etc/config/kratos
    networks:
      - intranet
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
```

Note: I'm *not* using `kratos-selfservice-ui-node`.
