### DISCUSSION TITLE
CORS Issue With Self Hosted Kratos

### DISCUSSION THREAD

**Discussion by GautDel** [ory/kratos#3583] [Q&A]
Hello all,

I have a home server on which I run a VM running debian where I do all my dev work from. I then ssh into the machine and access any endpoints from my personal computer's browser. (This may play into the issue?)

I have an instance of kratos self hosted as well as a server and frontend all running on the same domain, but using different ports.

Every time I try to make any sort of request to the kratos server instance from my frontend app, I am met with a CORS error. However, if I make a direct request using the search bar, there are no issues.

Here is the current error:

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://(ipaddress of server):4455/sessions/whoami (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404."

The request is coming from http://(ipaddress of server):5173 where the frontend react app lives,

I've tried adding the react address to the kraken.yml config file under "allowed_origins", but nothing... I'm lost and in need of a bit of direction, if anyone is willing to spend the time?

Any ideas?

Thank you!

**Comment by vinckr** [comment]
Hello @GautDel 
Cross-Origin Resource Sharing (CORS) errors are a common issue when making requests from a different domain, protocol, or port.

Here are a few steps you can take to resolve this issue:

- Configure CORS in Ory Kratos: Ory Kratos' Public API supports CORS out of the box. You need to set the following values in your configuration file (kratos.yml):
```

serve:  
 public:  
 cors:  
 enabled: true  
 allowed_origins:  
 - http://your-ip-address:5173
 allowed_methods:  
 - POST  
 - GET  
 - PUT  
 - PATCH  
 - DELETE  
 allowed_headers:  
 - Authorization  
 - Cookie  
 - Content-Type  
 exposed_headers:  
 - Content-Type  
 - Set-Cookie
```

Replace http://your-ip-address:5173 with the actual address of your frontend react app. This configuration allows CORS requests from your frontend app to the Ory Kratos server.
- Ensure your UI and Ory Kratos are on the same top-level domain: Ory Kratos and your UI must be hosted on the same top-level domain. You cannot host Ory Kratos and your UI on separate top-level domains.
- Use Ory Tunnel for local development: This is a tool for Ory Network, but I think it should also work for self-hosted Ory Kratos. To solve CORS errors during local development, you can use Ory Tunnel. In production, you should add your domain to the Ory Project so that all requests from your frontend can be made to Ory under the same domain.

If you've done all these and you're still encountering the issue, it might be helpful to read more about [CORS on Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
I hope this helps!
