### DISCUSSION TITLE
How to get current logged in user (identity) id in kratos config (yaml)?

### DISCUSSION THREAD

**Discussion by heyhusen** [ory/kratos#3747] [Q&A]
Hi all,

I want to use webhook after updating profile. But, I need the user id as a parameter to use that endpoint. Is it possible to get the current logged in user id in kratos configuration? Any ideas to do that?

My configuration looks like below:

```yaml
selfservice:
  flows:
    settings:
      after:
        profile:
          hooks:
            - hook: web_hook
              config:
                url: http://backend:3000/users/{ identityId }
                method: PATCH
                body: file:///etc/config/kratos/hooks/after-profile-setting.jsonnet
                response:
                  ignore: true
                  parse: false
```

Thank you!
