### DISCUSSION TITLE
403 forbidden CSRF tokens not equal in registration flow self-hosted

### DISCUSSION THREAD

**Discussion by fraschm1998** [ory/kratos#3760] [Q&A] [answered]
I'm trying to setup user registration using ory kratos using a SSR custom UI.

I first access /register which checks whether or not the uri containers a flow id (/register?flow=id). If it does and it's valid (not expired) render the registration, ui. Otherwise redirect to /self-service/registration/browser which then redirects to /register with csrf_token set.

I extract the headers for the csrf_token via:

`
        let cookie_header = headers.get("cookie").and_then(|hv| hv.to_str().ok());
`

The issue arrises when I try and do a post request to the update_registration flow. I get the following error message:

`{"error":{"id":"security_csrf_violation","code":403,"status":"Forbidden","reason":"Please retry the flow and optionally clear your cookies. The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues.","details":{"docs":"https://www.ory.sh/kratos/docs/debug/csrf","hint":"The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token).","reject_reason":"The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow."},"message":"the request was rejected to protect you from Cross-Site-Request-Forgery"}}`

I tested it in terminal as well to check whether it's an issue with the rust SDK using the following curl command:

```
curl -X POST "http://127.0.0.1:4433/self-serv
ice/registration?flow=5583f7d3-caa7-4af3-b959-0a2a1892767c" -H 'Content-Type: applic
ation/json' -H 'Accept: application/json' -H 'Cookie: csrf_token_vjGgpqYxgYm+3GolIGF
eMC+n4SSuiddj5ey9/CYve7oO2AjWGZsM3DtTeF8vsMfmkblrEXWGKq6V8X0bi682BQ==' -d '{
            
  "method": "password",                                                             
  "traits.email": "test@example.com",                                          
  "password": "Very-strong-Password",                                                        
  "traits.name.first": "Gordan",                                                   
  "traits.name.last": "Ramsey"                                                  
}'
```

However the error still persists.

docker-compose.yml:

```
version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos
        target:
          /etc/config/kratos
          #- type: bind
          #  source: ./contrib/quickstart/kratos
          #  target: /etc/config/kratos:z
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
      - PORT=4435
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
    networks:
      - intranet
    restart: unless-stopped

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/.ory/kratos/public/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos
        target:
          /etc/config/kratos
          #- type: bind
          #  source: ./contrib/quickstart/kratos
          #  target: /etc/config/kratos:z
    networks:
      - intranet

  admin_ui:
    image: ghcr.io/dfoxg/kratos-admin-ui
    ports:
      - "80:8080"
    restart: unless-stopped
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: unless-stopped
    networks:
      - intranet
    volumes:
      - ./contrib/quickstart/oathkeeper:/etc/config/oathkeeper

networks:
  intranet:

volumes:
  kratos-sqlite:
```

kratos.yml:

```
version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3013/
  allowed_return_urls:
    - http://127.0.0.1:3013
  #default_browser_return_url: http://127.0.0.1:4455/
  #allowed_return_urls:
  #  - http://127.0.0.1:4455

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:3013/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:3013/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:3013/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:3013/login

    login:
      ui_url: http://127.0.0.1:3013/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:3013/register
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

kratos/identity.schema.json:

```
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "title": "First Name",
              "type": "string"
            },
            "last": {
              "title": "Last Name",
              "type": "string"
            }
          }
        }
      },
      "required": [
        "email",
        "name"
      ],
      "additionalProperties": false
    }
  }
}
```
