### DISCUSSION TITLE
Courier Configuration: 'additionalProperties sms not allowed' Error in registration_code Template

### DISCUSSION THREAD

**Discussion by kvnsuryaa** [ory/kratos#4266] [Q&A]
## Issue Description
based of this #1570, I'm encountering an error while trying to implement SMS functionality in the registration_code template of Courier configuration. The error indicates that SMS is not an allowed property in this template.

## Error Description
While implementing phone-based registration using Kratos, the system fails to process the SMS template configuration.

#### Registration Flow Request
```
POST http://127.0.0.1:4433/self-service/registration?flow={flowId}
```

#### Request Body
```
{
    "method": "code",
    "traits": {
        "phone": "+62{rest_of_number}"
    }
}
```

#### HTTP Response
```
{
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "reason": "Expected sms template but got <nil>",
        "message": "An internal server error occurred, please contact the system administrator"
    }
}
```

#### Kratos Logs
```
kratos-kratos-1          | The configuration contains values or keys which are invalid:
kratos-kratos-1          | courier.templates.registration_code.valid: map[email:map[body:map[plaintext:file:///conf/courier-templates/registration_code/valid/sms.plaintext.gotmpl]] sms:map[body:map[plaintext:file:///conf/courier-templates/registration_code/valid/sms.plaintext.gotmpl]]]
kratos-kratos-1          |                                            ^-- additionalProperties "sms" not allowed
```

## Investigation Findings
After investigating using master branch, I found in the `config.schema.json` that SMS method is not included in the allowed properties for the registration_code template.

## Current Configuration
```
"registration_code": {
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "valid": {
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "email": {
          "$ref": "#/definitions/emailCourierTemplate"
        }
      },
      "required": ["email"]
    }
  }
},
```

## Expected Behavior
I expected to be able to configure SMS delivery method in the registration_code template, similar to how other notification methods work like login_code.

## Schema Definition Issue
The `config.schema.json` appears to be restrictive and doesn't include SMS as an allowed property for the registration_code template.

## Questions
1. Is this a known limitation of the registration_code template?
2. Is there a workaround to implement SMS functionality with this template?
3. If SMS is not supported in this template, how do i sign up using phone number with OTP?

## Environment
- Kratos Docker: latest
- Implementation: passwordless OTP Authentication with Twilio
- Attempted Method: SMS configuration

## Additional Context
- I have confirmed this is a schema restriction rather than an implementation error
- The error occurs specifically when trying to add SMS configuration to the template

**Comment by vinckr** [comment]
Hello @kvnsuryaa 

Which version of Kratos are you using?

**Reply by kvnsuryaa** [reply]
Hi @vinckr

Currently I'm using version 1.2.0, after some research I found that ory/kratos for integrate with twillio is paid feature, is that true?

**Reply by vinckr** [reply]
Hello @kvnsuryaa 

No SMS delivery is available in the free community version of Ory Kratos.

Here is how you configure it: 

```
courier:
  channels:
    - id: sms
      type: http
      request_config:
        url: https://api.twilio.com/2010-04-01/Accounts/AXXXXXXXXXXXXXX/Messages.json # Adjust your account ID
        method: POST
        body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgVG86IGN0eC5yZWNpcGllbnQsCiAgQm9keTogY3R4LmJvZHksCn0= # see below
        headers:
          Content-Type: application/x-www-form-urlencoded # defaults to application/json
        auth:
          type: basic_auth # or api_key
          config:
            user: AXXXXXXX # adjust your credentials
            password: XXXX # adjust your credentials
```

What gave you the impression that it is a paid feature?
