### DISCUSSION TITLE
Kratos docker ui-node

### DISCUSSION THREAD

**Discussion by benjamingb** [ory/kratos#917] [Q&A] [answered]
Hello
deployed kratos in docker, but I can’t view the kratos-selfservice-ui-node client.
I access localhost: 4433 and
displays the following message 404 page not found

this is my docker compose file

```
version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1
    environment:
      - DSN=postgres://postgres:postgres@192.168.10.71:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      -
        type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command:
      -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.5.0-alpha.1
    environment:
      - KRATOS_PUBLIC_URL=http://localhost:4433/
      - KRATOS_ADMIN_URL=http://localhost:4434/
    networks:
      - intranet
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:postgres@192.168.10.71:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command:
      serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      -
        type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:
```
