### DISCUSSION TITLE
how to configure Kratos to be hydra client

### DISCUSSION THREAD

**Discussion by TaSiya** [ory/kratos#937] [Q&A] [answered]
Hi everyone, I would like to have Kratos only use hydra for login. So basically I have hydra configured and the client is already created with the right details. Everything is running through `docker-compose` Now my problem is that I am getting a 500 error when I login with *hydra* after this post request ` http://127.0.0.1:4433/self-service/methods/oidc/auth/ee6a0aab-953a-4dea-8c49-f48bc12159ca` 

error:

```json
[
  {
    "code": 500,
    "reason": "Unable to initialize OpenID Connect Provider: Get \"http://127.0.0.1:4444/.well-known/openid-configuration\": dial tcp 127.0.0.1:4444: connect: connection refused",
    "status": "Internal Server Error",
    "message": "An internal server error occurred, please contact the system administrator"
  }
]
```

I currently have the following setup

**kratos.yml**

```yml
serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3000
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: hydra
            provider: generic
            mapper_url: file:///etc/config/kratos/oidc.hydra.jsonnet
            client_id: myClientId
            client_secret: this-is-the-secret
            scope:
              - profile
            issuer_url: http://127.0.0.1:4444/
            auth_url: http://127.0.0.1:4444/oauth2/auth
            token_url: http://127.0.0.1:4444/oauth2/token
            requested_claims:
              id_token:
                email:
identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json
```

**iodc.hydra.jsonnet**

```jsonnet
local claims = {
  email_verified: false
} + std.extVar('claims');

{
  identity: {
    traits: {
      [if "email" in claims then "email" else null]: claims.email,
    },
  },
}
```

**Comment by aeneasr** [comment]
Looks like you have problems figuring out [Docker (Compose) Networking](https://docs.docker.com/compose/networking/). `http://127.0.0.1:4444/` refers to your localhost on your host  machine, but you probably want to talk to hydra over the docker network, so setting up - for example (concrete value depends on your docker compose config) - `http://hydra:4444/`.

**Reply by TaSiya** [reply]
@aeneasr when I use `http://hydra:4444/`,  I get the following error:

```
"reason": "Unable to initialize OpenID Connect Provider: oidc: issuer did not match the issuer returned by provider, expected \"http://hydra:4444/\" got \"http://127.0.0.1:4444/\"",
```

**Reply by vinckr** [reply]
Hey, could you provide your docker-compose as well? 

I can try to reproduce your setup, maybe I help you figure it out. 

Docker Networking is not easy :D 

I think you have to change `http://hydra:4444/` to the provider specified in your docker-compose

**Reply by TaSiya** [reply]
@vinckr I manage to fix my setup, I figured out what I was doing wrong in my setup.

Thank you very much for your time.

**Reply by vinckr** [reply]
Just out of curiousity, what was the problem?

**Reply by TaSiya** [reply]
@vinckr base on my goal, I wanted to make kratos a hydra client. So, the behavior that I wanted was that when I visit any of the protected routes I will be redirected hydra consent app which will handle the login and registration. I manage to achieve this by removing login and registration from the [kratos UI example app](https://github.com/ory/kratos-selfservice-ui-node) to the hydra consent app. I am not sure if this is the right approach though. 

The problem that I made was that I added hydra as a oidc provider for Kratos which allowed me to have a hydra button that I can use to authorize. Hence, the problem which I actually did not resolve but achieved the behavior that I wanted.

**I will be more than happy to hear your thoughts if this is the right way to go about this**. Side note, I do not have much experience but assigned to get this working.

**Reply by vinckr** [reply]
Thanks for providing so many details, I am not sure if this the right way to go about this, I have to check some more. 
We do have an open issue for [Hydra integration with Kratos](https://github.com/ory/kratos/issues/273), which will be adressed next.

**Comment by TaSiya** [comment, marked as answer]
Solved!

**Reply by drgarcia1986** [reply]
@TaSiya could you provide your docker-compose? 
I want to test integration with hydra and kratos too.

**Reply by TaSiya** [reply]
@drgarcia1986  here is the docker-compose

```yml
version: "3"

services:
  # for now, we will use version 1.8.5 of hydra for development.

  # hydra migrations, run at startup only

  hydra-migrate:
    image: oryd/hydra:v1.8.5
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    restart: on-failure
    depends_on:
      - postgres

  hydra:
    image: oryd/hydra:v1.8.5
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      # - "5555:5555" # Port for hydra token user
    command: serve all --dangerous-force-http
    depends_on:
      - hydra-migrate
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444/
      - URLS_SELF_PUBLIC=http://hydra:4444/
      - URLS_CONSENT=http://127.0.0.1:3005/consent
      - URLS_LOGIN=http://127.0.0.1:3005/login
      - URLS_LOGOUT=http://127.0.0.1:3005/logout
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
      - SERVE_COOKIES_SAME_SITE_MODE=Lax
      - LOG_LEAK_SENSITIVE_VALUES=true
      - LOG_LEVEL=debug
    restart: unless-stopped


  kratos:
    image: oryd/kratos:latest
    depends_on:
      - kratos-migrate
    volumes:
      - type: bind
        source: ./kratos-config
        target: /etc/config/kratos
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    command: serve -c /etc/config/kratos/kratos.yml --dev
    environment:
      - LOG_LEVEL=trace
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: on-failure

  kratos-migrate:
    image: oryd/kratos:latest
    depends_on:
      - postgres
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    volumes:
      - type: bind
        source: ./kratos-config
        target: /etc/config/kratos

  # Database

  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - DATABASE_HOST=//127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./data/postgresData:/var/lib/postgresql/data:delegated

  kratos-ui:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - ./myAccount:/usr/src/app:delegated
    command: npm run dev
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - OAUTH2_CLIENT_ID=this-is-the-client-id
      - OAUTH2_CLIENT_SECRET=this-is-the-secret
      - OAUTH2_PROVIDER=http://127.0.0.1:4444
      - OAUTH2_CALLBACK_URL=http://localhost:3000/auth/callback
      - SCOPES=profile openid
      - INTERNAL_PROVIDER=http://hydra:4444
      - OAUTH2_TOKEN_TTL_SECONDS=3600
      - HYDRA_ADMIN_URL=http://hydra:4445

  consent:
    image: node:12
    working_dir: /usr/src/app
    volumes:
      - ./consent:/usr/src/app:delegated
    command: npm run dev
    ports:
      - 3005:3000
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - SECURITY_MODE=standalone

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
```
