### DISCUSSION TITLE
ERROR: relation "selfservice_errors" does not exist (SQLSTATE 42P01)]

### DISCUSSION THREAD

**Discussion by secoldPrivate** [ory/kratos#947] [Q&A] [answered]
Hi,

I'm trying to setup Kratos on a kubernetes cluster and use it to secure my app.
I've already deployed postgres and got Kratos to connect to it without throwing an error.

Kratos starts up fine as far as I can tell and responds to the /health/alive endpoint.
When I try to hit:

localhost:4433/self-service/registration/browser

I get 

```
{
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "message": "ERROR: relation \"selfservice_errors\" does not exist (SQLSTATE 42P01)"
    }
}
```

I'm not sure how to even begin to debug this. Checking the logs of the server, it shows the same thing:

`An error occurred and is being forwarded to the error user interface. audience=application error=map[message:ERROR: relation "selfservice_registration_flows" does  ││ not exist (SQLSTATE 42P01)] http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br user-agent:PostmanRuntime/7.26.8] host:localhost:4433 method:GET path:/self-service/registration/browse ││ r query:<nil> remote:127.0.0.1:35688 scheme:http] service_name=kratos service_version= `

What am I missing here?

In order to deploy it I used the helm chart with the following set for the config:

```
  config:
    dsn: postgres://postgres:<postgrespw>@postgres-kratos-postgresql:5432/kratos?sslmode=disable
    identity:
      #is mounted via volume and is accessible from inside the container
      default_schema_url: file:///etc/userSchema/userSchema.json
    secrets:
      session:
        - <not sure what to write here so wrote a random string>
        - <not sure what to write here so wrote a random string>
    courier:
      smtp:
        connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
        from_address: <fromEmail>@gmail.com
    selfservice:
      default_browser_return_url: https://kratostest.com
      flows:
        logout:
          after:
            default_browser_return_url: https://kratostest.com/dashboard
    serve:
      public:
        port: 4433
      admin:
        port: 4434
```
