### DISCUSSION TITLE
Kratos not responding "Set-Cookie : csrf_token=..."

### DISCUSSION THREAD

**Discussion by NeitoFR** [ory/kratos#958] [Q&A] [answered]
We are building an Angular website (not SSR) and try to use Kratos to authenticate users, everything is running in Docker container.
We have a SSL enabled Nginx as a reverse proxy. On our subdomain "auth.XXX.com" we host the Kratos Public Endpoint and our Auth UI and Auth Server.

I'll break down the requests flow to explain the issue : 

## Request 1 (/register): 

When accessing https://auth.XXX.com/ui/register (the registration form page), we identify that there is no flow existing and we rediect to https://auth.XXX.com/.ory/kratos/public/self-service/registration/browser (Kratos public endpoint). 
At this point no cookie / csrf_token is set anywhere. 

## Request 2 (/self-service/registration/browser)

Kratos public API handle the request, sets up the flow id AND the CSRF token. 
When running the Kratos quickstart environment locally, we can see that when doing the request to `http://127.0.0.1:4433/self-service/login/browser` there is a Response Headers like this :
`Set-Cookie: csrf_token=QM9UASOUgjj+TTKR47Yo8ARm+/Hdfg7khFneiJ+ytIU=; Path=/; Domain=127.0.0.1; Max-Age=31536000; HttpOnly; SameSite=Lax`
From my understanding, this is where Kratos provide us the csrf_token to use in future requests.

But on our application this `Set-Cookie" response header is not present and we do not understand why. 

We tried to [check](https://www.ory.sh/kratos/docs/debug/csrf/) the CSRF Common Pitfall page with no chance. I can provide more logs / info but I do not know what is relevant.

Here is the Kratos config file : 
```yaml
version: v0.5.5

identity:
  default_schema_url: file:///schemas/customer.schema.json

serve:
  public:
    base_url: https://auth.XXX.com/.ory/kratos/public
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: https://auth.XXX.com/ui
  whitelisted_return_urls:
    - https://auth.XXX.com/ui
  flows:
    logout:
      after:
        default_browser_return_url: https://auth.XXX.com/ui/logout
    registration:
      lifespan: 1h
      ui_url: https://auth.XXX.com/ui/register
      after:
        password:
          hooks:
            - hook: session
          default_browser_return_url: https://auth.XXX.com/ui/register
        oidc:
          hooks:
            - hook: session
          default_browser_return_url: https://auth.XXX.com/ui/register
        default_browser_return_url: https://auth.XXX.com/ui/register
    login:
      lifespan: 1h
      # lifespan: 10s
      ui_url: https://auth.XXX.com/ui/login
      after:
        password:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https:/auth.XXX.com/ui/login
        oidc:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://auth.XXX.com/ui/login
        default_browser_return_url: https://auth.XXX.com/ui/login

session:
  lifespan: 24h
  cookie:
  #   persistent: false
  #   path: ''
    same_site: Lax # It was commented before and had the same problem
  #   domain: ''

secrets:
  cookie:
    - XXX
  default:
    - XXX
```

Here is the Docker Compose file (only kratos config) : 
```yaml
kratos:
    image: oryd/kratos:v0.5.5
    hostname: kratos
    container_name: kratos
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    restart: unless-stopped
    env_file: ./data/kratos/kratos-env.list
    command:
      serve -c /home/ory/.kratos.yaml --dev
    volumes:
      - ./data/kratos/kratos.yml:/home/ory/.kratos.yaml
      - ./data/kratos/db_cert:/dbcert
      - ./data/kratos/schemas:/schemas
```
Here is the Nginx conf

 ```nginx
# Later the UI and backend will be hosted by the same container
server {
    listen 443 ssl;
    server_name auth.XXX.com;
    
    ssl_certificate /etc/XXX/live/XXX/fullchain.pem;
    ssl_certificate_key /etc/XXX/live/XXX/privkey.pem;

    include /etc/XXX/options-ssl-nginx.conf;
    ssl_dhparam /etc/XXX/ssl-dhparams.pem;

    
    location ^~ /ui {
        proxy_set_header Host $host;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_pass http://auth-kratos-ui:4200/;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        rewrite ^/ui?(.*)$ $1 break;
    }

    location ^~ /backend {
        proxy_set_header Host $host;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_pass http://auth-kratos-server:4000/;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        rewrite ^/backend?(.*)$ $1 break;
    }

    location ^~ /.ory/kratos/public {
        proxy_set_header Host $host;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_pass http://kratos:4433/;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        rewrite ^/.ory/kratos/public(.*)$ $1 break;
    }
}
```
