### ISSUE TITLE
Mariadb: Table 'selfservice_profile_management_request_methods' already exists

### ISSUE THREAD

**Issue by rushairer** [ory/kratos#1023]
``` yaml

affinity: {}
deployment:
  annotations: {}
  extraEnv: []
  labels: {}
  nodeSelector: {}
  resources: {}
  tolerations: []
  tracing:
    datadog:
      enabled: false
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: oryd/kratos
  tag: v0.5.5-alpha.1
imagePullSecrets: []
ingress:
  admin:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - host: sso-admin.apigg.com
      paths:
      - /
    tls:
    - hosts:
      - sso-admin.apigg.com
      secretName: sso-admin.apigg.com-tls
  public:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - host: sso-next.apigg.com
      paths:
      - /
    tls:
    - hosts:
      - sso-next.apigg.com
      secretName: sso-next.apigg.com-tls
kratos:
  autoMigrate: true
  config:
    courier:
      smtp:
        connection_uri: .....
        from_address: ....
    dsn: mysql://root:xxxx@tcp(mariadb.database:3306)/kratos?max_conns=20&max_idle_conns=4
    secrets: {}
    serve:
      admin:
        port: 4434
      public:
        port: 4433
  development: false
nameOverride: ""
replicaCount: 1
secret:
  enabled: true
service:
  admin:
    annotations: {}
    enabled: true
    port: 80
    type: ClusterIP
  public:
    annotations: {}
    enabled: true
    port: 80
    type: ClusterIP


```

Connect to a Mariadb. Get that logs:

```
time=2021-01-30T05:01:36Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos.yaml service_name=kratos service_version=
The following migration is planned:

Version          Name                                      Status    
20191100000001   identities                                Applied   
20191100000001   identities                                Applied   
20191100000001   identities                                Applied   
20191100000002   requests                                  Applied   
20191100000002   requests                                  Applied   
20191100000002   requests                                  Applied   
20191100000003   sessions                                  Applied   
20191100000003   sessions                                  Applied   
20191100000003   sessions                                  Applied   
20191100000004   errors                                    Applied   
20191100000004   errors                                    Applied   
20191100000004   errors                                    Applied   
20191100000005   identities                                Applied   
20191100000006   courier                                   Applied   
20191100000006   courier                                   Applied   
20191100000006   courier                                   Applied   
20191100000007   errors                                    Applied   
20191100000007   errors                                    Applied   
20191100000007   errors                                    Applied   
20191100000008   selfservice_verification                  Applied   
20191100000008   selfservice_verification                  Applied   
20191100000008   selfservice_verification                  Applied   
20191100000009   verification                              Applied   
20191100000010   errors                                    Applied   
20191100000010   errors                                    Applied   
20191100000010   errors                                    Applied   
20191100000011   courier_body_type                         Applied   
20191100000011   courier_body_type                         Applied   
20191100000011   courier_body_type                         Applied   
20191100000012   login_request_forced                      Applied   
20191100000012   login_request_forced                      Applied   
20191100000012   login_request_forced                      Applied   
20200317160354   create_profile_request_forms              Pending   
20200317160354   create_profile_request_forms              Pending   
20200317160354   create_profile_request_forms              Pending   
20200401183443   continuity_containers                     Pending   
20200401183443   continuity_containers                     Pending   
20200401183443   continuity_containers                     Pending   
20200402142539   rename_profile_flows                      Pending   
20200402142539   rename_profile_flows                      Pending   
20200402142539   rename_profile_flows                      Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101057   create_recovery_addresses                 Pending   
20200519101058   create_recovery_addresses                 Pending   
20200601101000   create_messages                           Pending   
20200601101000   create_messages                           Pending   
20200601101000   create_messages                           Pending   
20200601101001   verification                              Pending   
20200605111551   messages                                  Pending   
20200605111551   messages                                  Pending   
20200605111551   messages                                  Pending   
20200607165100   settings                                  Pending   
20200607165100   settings                                  Pending   
20200607165100   settings                                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200705105359   rename_identities_schema                  Pending   
20200810141652   flow_type                                 Pending   
20200810141652   flow_type                                 Pending   
20200810141652   flow_type                                 Pending   
20200810161022   flow_rename                               Pending   
20200810161022   flow_rename                               Pending   
20200810161022   flow_rename                               Pending   
20200810162450   flow_fields_rename                        Pending   
20200810162450   flow_fields_rename                        Pending   
20200810162450   flow_fields_rename                        Pending   
20200812124254   add_session_token                         Pending   
20200812124254   add_session_token                         Pending   
20200812124254   add_session_token                         Pending   
20200812160551   add_session_revoke                        Pending   
20200812160551   add_session_revoke                        Pending   
20200812160551   add_session_revoke                        Pending   
20200830121710   update_recovery_token                     Pending   
20200830121710   update_recovery_token                     Pending   
20200830121710   update_recovery_token                     Pending   
20200830130642   add_verification_methods                  Pending   
20200830130642   add_verification_methods                  Pending   
20200830130642   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130643   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130644   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130645   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830130646   add_verification_methods                  Pending   
20200830154602   add_verification_token                    Pending   
20200830154602   add_verification_token                    Pending   
20200830154602   add_verification_token                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200830172221   recovery_token_expires                    Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   
20200831110752   identity_verifiable_address_remove_code   Pending   
An error occurred while connecting to SQL: error executing github.com/ory/kratos:/persistence/sql/migrations/sql/20200317160354_create_profile_request_forms.mysql.up.sql, sql: CREATE TABLE `selfservice_profile_management_request_methods` (
`id` char(36) NOT NULL,
PRIMARY KEY(`id`),
`method` VARCHAR (32) NOT NULL,
`selfservice_profile_management_request_id` char(36) NOT NULL,
`config` JSON NOT NULL,
`created_at` DATETIME NOT NULL,
`updated_at` DATETIME NOT NULL
) ENGINE=InnoDB;
ALTER TABLE `selfservice_profile_management_requests` ADD COLUMN `active_method` VARCHAR (32);
INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;
ALTER TABLE `selfservice_profile_management_requests` DROP COLUMN `form`;: Error 1050: Table 'selfservice_profile_management_request_methods' already exists
[POP] 2021/01/30 05:01:36 info - 0.0036 seconds

```
