### ISSUE TITLE
Hashtag in url converts to %23

### ISSUE THREAD

**Issue by Zippersk** [ory/kratos#1032]
**Describe the bug**

when `SELFSERVICE_FLOWS_LOGIN_UI_URL` is set to URL with a hashtag (`http://example.com/#/login`), the hashtag is converted to `%23` (and location header from kratos response become `http://example.com/%23/login`). Hybrid applications (based on electron, cordova, capacitor...), that needs to have a hash-based router, does not work correctly with the current implementation of rewriting `#`->`%23`.

My simplified kratos docker service.
```
  kratos:
    image: oryd/kratos:latest
    environment:
      - DSN=postgres://kratos:kratos@db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=${RETURN_TO}
      - SELFSERVICE_WHITELISTED_RETURN_URLS=${RETURN_TO}
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=${UI_BASE}/#/auth/registration
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=${UI_BASE}/#/auth
    command: serve -c /etc/config/kratos/kratos.yml
    volumes:
      - ./kratos:/etc/config/kratos
```

Request to `/self-service/login/browser` (`UI_BASE` is set to `http://localhost:9999` in this example)
```
:authority: kratos.*****
:method: GET
:path: /self-service/login/browser
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,sk-SK;q=0.8,sk;q=0.7,cs;q=0.6
cache-control: no-cache
cookie: csrf_token=HRYkllp56zy8XelKLX+8JpRcW5JMjybXAT8Rem+4e7I=
pragma: no-cache
referer: http://localhost:9999/
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: cross-site
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
```

Response:
```
cache-control: private, no-cache, no-store, must-revalidate
content-length: 95
content-type: text/html; charset=utf-8
date: Tue, 02 Feb 2021 11:50:25 GMT
location: http://localhost:9999/%23/auth?flow=7975af19-9171-4e3d-bd69-044fbccdf886
vary: Origin
vary: Cookie
```

Is there any reason why Kratos rewrites url and escapes `#`?
