### ISSUE TITLE
panic: a handle is already registered for path '/self-service/recovery/methods/link'

### ISSUE THREAD

**Issue by mbonnell-wish** [ory/kratos#1068]
**Describe the bug**

Sometimes our Kratos server fails with a panic related to the router.

**Reproducing the bug**

It seems to occur rather randomly on server startup.

_Server logs_

```
time=2021-02-02T19:50:17Z level=info msg=Software quality assurance features are enabled. Learn more at:
https://www.ory.sh/docs/ecosystem/sqa
audience=application service_name=kratos service_version= │
│ panic: a handle is already registered for path '/self-service/recovery/methods/link' │
│ goroutine 227 [running]: │
│ github.com/julienschmidt/httprouter.(*node).addRoute(0xc001018230, 0x16a5f19, 0x23, 0xc00101ea00) │
│ /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/tree.go:200 +0xb1f │
│ github.com/julienschmidt/httprouter.(*Router).Handle(0xc000ea9940, 0x166789a, 0x3, 0x16a5f19, 0x23, 0xc00101ea00) │
│ /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:236 +0xbf │
│ github.com/ory/kratos/x.(*RouterPublic).GET(0xc00000f468, 0x16a5f19, 0x23, 0xc000fdad60) │
│ /home/ory/x/router.go:27 +0x6f │
│ github.com/ory/kratos/selfservice/strategy/link.(*Strategy).RegisterPublicRecoveryRoutes(0xc000f97d70, 0xc00000f468) │
│ /home/ory/selfservice/strategy/link/strategy_recovery.go:44 +0xde │
│ github.com/ory/kratos/selfservice/flow/recovery.Strategies.RegisterPublicRoutes(0xc000fdacc0, 0x2, 0x2, 0xc00000f468) │
│ /home/ory/selfservice/flow/recovery/strategy.go:55 +0xaf │
│ github.com/ory/kratos/driver.(*RegistryDefault).RegisterPublicRoutes(0xc000cfa000, 0xc00000f468) │
│ /home/ory/driver/registry_default.go:160 +0x448 │
│ github.com/ory/kratos/cmd/daemon.servePublic(0x18c2060, 0xc000a5af00, 0xc000a66460, 0x232eb40, 0xc000d3a740, 0x0, 0x2) │
│ /home/ory/cmd/daemon/serve.go:66 +0x4a9 │
│ created by github.com/ory/kratos/cmd/daemon.ServeAll.func1 │
│ /home/ory/cmd/daemon/serve.go:206 +0xc9 │
│ stream closed
```

Pardon the pipes, I'm copy/pasting this from a Jira issue where the logs were quote-formatted.

_Server configuration_

```yaml
version: v0.5.5-alpha.1

dsn: redacted

serve:
  public:
    base_url: https://redacted.com/
    cors:
      enabled: true
  admin:
    base_url: http://redacted:4434/

session:
  cookie:
    persistent: true
    domain: redacted
    same_site: Lax
    path: '/'
  lifespan: 720h

selfservice:
  default_browser_return_url: https://redacted.com/
  whitelisted_return_urls:
    - [redacted]

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: redacted # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
            provider: generic
            client_id: redacted
            client_secret: redacted
            issuer_url: https://redacted.com/oidc/
            mapper_url: file:///home/ory/oidc.redacted.jsonnet
            scope:
              - user:email

  flows:
    error:
      ui_url: https://redacted.com/error

    settings:
      ui_url: https://redacted.com/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: https://redacted.com/recovery

    verification:
      enabled: true
      ui_url: https://redacted.com/verify
      after:
        default_browser_return_url: https://redacted.com/email

    logout:
      after:
        default_browser_return_url: https://redacted.com/auth/login

    login:
      ui_url: https://redacted.com/auth/login
      lifespan: 10m

    registration:
      ui_url: https://redacted.com/auth/registration
      after:
        default_browser_return_url: https://redacted.com/email
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - redacted
    - redacted

hashers:
  argon2:
    parallelism: redacted
    memory: redacted
    iterations: redacted
    salt_length: redacted
    key_length: redacted

identity:
  default_schema_url: file:///home/ory/identity.schema.json

courier:
  template_override_path: /home/ory/templates
  smtp:
    connection_uri: smtps://redacted
    from_address: redacted
```
-->

**Expected behavior**

**Environment**

- Version: v0.5.5-alpha1
- Environment: Docker, Kubernetes

**Additional context**
