### ISSUE TITLE
Routing library doesn't incorporate base_url

### ISSUE THREAD

**Issue by snoepkast** [ory/kratos#1152]
**Describe the bug**

As discussed in Slack.

I am running Kratos (and others) behind a proxy (Traefik) which is configured to serve the components from different paths:

```
localhost/kratos
localhost/kratos-self-service-ui
localhost/hydra
etc
```

I noticed that none of the paths seem to be recognised when running on anything other than / so I configured Traefik to strip the path prefix before forwarding the request, now Kratos will serve the request like it should, but when it redirects, it redirects to / instead of /kratos/.

In Slack it was explained to me that the urls from the configuration are only used for explicit redirects and not in the routing library, which also needs to take the base_url into account.

**Reproducing the bug**

You can reproduce by checking:

```
localhost/kratos/sessions/whoami  -> 404
localhost/kratos/sessions/whoami (with traefik stripping /kratos path prefix) -> 200
localhost/kratos/sessions/whoami/ (notice the trailing slash) -> redirects to: localhost/sessions/whoami -> 404
```

**Server configuration**

```yaml
serve:
  public:
    base_url: http://localhost/kratos/
```

**Expected behavior**

When setting the `base_url` I expect Kratos to serve it's endpoints relative to this, and also take the base_url into account when redirecting.

**Comment by aeneasr** [comment]
That would probably need some work with httprouter's APIs. It's a good issue to get into the code base if anyone's up for that!

**Comment by snoepkast** [comment]
I was just thinking about this issue and while it's good to take the base_url into account, for this particular case it might be better to ignore trailing slashes? I mean, does it really matter if there's a trailing slash or not? Instead of a redirect we could just serve the request?

**Comment by aeneasr** [comment]
Agreed, that's what I proposed here: https://github.com/ory/kratos/pull/1181#pullrequestreview-622991591

**Comment by redanvil** [comment]
i ran into this as well and as a band-aid did something like this with traefik:

```
  kratos:
    image: oryd/kratos:v0.10.1
    labels:
      
... rest of labels

      - "traefik.http.routers.sessions.entrypoints=web"
      - "traefik.http.routers.sessions.rule=PathPrefix(`/sessions`)"
      - "traefik.http.routers.sessions.middlewares=redirect@docker,kratos-strip-prefix@docker"
      - "traefik.http.routers.sessions.service=sessions"
      - "traefik.http.services.sessions.loadbalancer.server.port=4433"
    
      - "traefik.http.middlewares.redirect.redirectregex.regex=^/sessions/(.*)"
      - "traefik.http.middlewares.redirect.redirectregex.replacement=/kratos/sessions/$${1}"
      - "traefik.http.middlewares.redirect.redirectregex.permanent=true"
      ```
