### ISSUE TITLE
Login through Gitlab returns 500

### ISSUE THREAD

**Issue by vimal7016** [ory/kratos#1157]
**Describe the bug**

Login through Gitlab returns 500

**Reproducing the bug**

1. Follow exactly same [steps](https://www.ory.sh/kratos/docs/guides/sign-in-with-github-google-facebook-linkedin/#gitlab) 

_Server logs_

```
[
  {
    "code": 500,
    "status": "Internal Server Error",
    "reason": "Unable to initialize OpenID Connect Provider: Get \"/.well-known/openid-configuration\": unsupported protocol scheme \"\"",
    "message": "An internal server error occurred, please contact the system administrator"
  }
]
```

_Server configuration_

```yaml
selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  whitelisted_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true
    
    oidc:
      enabled: true
      config:
        providers:
          - id: gitlab # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
            provider: gitlab
            client_id: ... # Replace this with the OAuth2 Client ID provided by GitLab
            client_secret: ... # Replace this with the OAuth2 Client Secret provided by GitLab
            mapper_url: file:///etc/config/kratos/oidc.gitlab.jsonnet
            scope:
              - read_user
              - openid
              - profile
              - email
```

**Environment**

- Version: v3.7 (quickstart.yml)
- Environment: Docker
