### ISSUE TITLE
JSON Schema `ory.sh/kratos` keyword extension design document

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#118]
This document serves as a place to design the `ory.sh/kratos` keyword extension. The following features must be supported by that keyword (checked means implemented):

- Identity Traits
  - [x] We need to be able to declare that a field can be used as the "identifier" when logging in / signung up using the password method.
  - [ ] We need to use one or more fields as the "recovery" method.
  - [ ] We need to use one or more fields as the "verification" method.
- Social Sign In
  - [x] We need to be able to map fields from the provider to the Identity Traits (and possibly other fields).

```yaml
# Identity Traits
type: string
format: email
"ory.sh/kratos":
  credentials:
    password:
      # We need to be able to declare that a field can be used as the "identifier" when logging in / signung up using the password method.
      identifier: true|false
  
  verify:
    through: email|phone

  recover:
    type: email|phone
```

```yaml
# Social Sign In
type: string
format: email
"ory.sh/kratos":
  mappings:
    identity:
      traits:
        - path: foo.bar
        - path: baz.bar
```
