### ISSUE TITLE
Kratos Timeout/Crash

### ISSUE THREAD

**Issue by jaitaiwan** [ory/kratos#1201]
Hey Folks when performing the following request I'm getting a timeout and sometimes Kratos will entirely crash with no panics/logs etc:

```
POST /self-service/registration/methods/password?flow=<flowid> [formdata]
traits.email: dan@redacted.com
password: <redacted>
traits.name.first: Daniel
traits.name.last: Holmes
csrf_token: <csrftoken>
```

It won't always happen the first time but it seems to just crash with no warning.

Environment:
Kubernetes: 1.20 amd64 Linode
Helm: 3
Chart Version: 0.5.7
Kratos Version: v0.5.5-alpha.1
Build Commit: 83aedcb885acb96c5deb39fff675d5f0528af32d

Kratos.yml:
```
courier:
  smtp:
    from_address: auth@pm.ddc.host
identity:
  default_schema_url: file:///etc/config/identity.default.schema.json
selfservice:
  default_browser_return_url: https://auth.ddc.host/dashboard
  flows:
    login:
      ui_url: https://auth.ddc.host/auth/login
    registration:
      ui_url: https://auth.ddc.host/auth/registration
  methods:
    link:
      enabled: true
    oidc:
      enabled: false
    password:
      enabled: true
    profile:
      enabled: false
  whitelisted_return_urls:
  - https://auth.ddc.host/dashboard
  - /dashboard
serve:
  admin:
    port: 4434
  public:
    base_url: https://kratos.ddc.host/
    port: 4433
```
