### ISSUE TITLE
Gitlab oauth shows error 500

### ISSUE THREAD

**Issue by ramsy1980** [ory/kratos#1265]
**Describe the bug**

When configuring oath for Gitlab it throws an error 500.
This is related to https://github.com/ory/kratos/pull/1159

```
[
  {
    "code": 500,
    "reason": "Unable to initialize OpenID Connect Provider: Get \"/.well-known/openid-configuration\": unsupported protocol scheme \"\"",
    "status": "Internal Server Error",
    "message": "An internal server error occurred, please contact the system administrator"
  }
]
```

**To Reproduce**

Configure according to https://www.ory.sh/kratos/docs/guides/sign-in-with-github-google-facebook-linkedin

Github works, Gitlab doesn't

**Expected behavior**

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

Chart: v0.8.0
Image: oryd/kratos:v0.5.5-alpha.1

**Additional context**

**Comment by aeneasr** [comment]
Please show your config!

**Comment by ramsy1980** [comment]
```yaml
replicaCount: 3

image:
  repository: oryd/kratos
  tag: v0.5.5-alpha.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  admin:
    enabled: true
    type: ClusterIP
    port: 80
    annotations: {}
  public:
    enabled: true
    type: ClusterIP
    port: 80
    annotations: {}

secret:
  enabled: true

ingress:
  admin:
    enabled: false
  public:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      -
        host: redacted
        paths:
          - /

    tls:
      - hosts:
        - redacted
        secretName: redacted

kratos:
  development: false
  # autoMigrate is relying on a simple initContainer mechanism
  # Do not turn it on if the replicaCount > 1
  autoMigrate: false

#  You can add multiple identity schemas here
  identitySchemas:
    "identity.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "minLength": 3,
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "verification": {
                    "via": "email"
                  },
                  "recovery": {
                    "via": "email"
                  }
                }
              },
              "name": {
                "type": "object",
                "properties": {
                  "first": {
                    "type": "string"
                  },
                  "last": {
                    "type": "string"
                  }
                }
              }
            },
            "required": ["email"],
            "additionalProperties": false
          }
        }
      }
    "oidc.github.jsonnet": |-
      local claims = {
        email_verified: false
      } + std.extVar('claims');

      {
        identity: {
          traits: {
            // Allowing unverified email addresses enables account
            // enumeration attacks, especially if the value is used for
            // e.g. verification or as a password login identifier.
            //
            // Therefore we only return the email if it (a) exists and (b) is marked verified
            // by GitHub.
            [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
          },
        },
      }
    "oidc.gitlab.jsonnet": |-
      local claims = {
        email_verified: false
      } + std.extVar('claims');

      {
        identity: {
          traits: {
            // Allowing unverified email addresses enables account
            // enumeration attacks, especially if the value is used for
            // e.g. verification or as a password login identifier.
            //
            // Therefore we only return the email if it (a) exists and (b) is marked verified
            // by GitLab.
            [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
          },
        },
      }

  config:
    courier:
      smtp:
        connection_uri: redacted
        from_address: redacted
    dsn: redacted
    session:
      lifespan: 720h # 30 days
      cookie:
        domain: redacted
    secrets:
      cookie:
        - redacted
    identity:
      default_schema_url: file:///etc/config/identity.schema.json

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    serve:
      public:
        base_url: https://redacted
        cors:
          enabled: true
          allowed_origins:
            - https://*.redacted
            - http://localhost:3000
          allowed_methods:
            - DELETE
            - GET
            - PATCH
            - POST
            - PUT
          allowed_headers:
            - Authorization
            - Cookie
          exposed_headers:
            - Content-Type
            - Set-Cookie
          debug: true
      admin:
        base_url: http://kratos-admin/

    selfservice:
      default_browser_return_url: https://account.redacted
      whitelisted_return_urls:
        - https://redacted

      methods:
        password:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: github # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
                provider: github
                client_id: redacted # Replace this with the OAuth2 Client ID provided by GitHub
                client_secret: redacted # Replace this with the OAuth2 Client Secret provided by GitHub
                mapper_url: file:///etc/config/oidc.github.jsonnet
                scope:
                  - user:email
              - id: gitlab # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
                provider: gitlab
                client_id: redacted # Replace this with the OAuth2 Client ID provided by GitLab
                client_secret: redacted # Replace this with the OAuth2 Client Secret provided by GitLab
                mapper_url: file:///etc/config/oidc.gitlab.jsonnet
                scope:
                  - read_user
                  - openid
                  - profile
                  - email

      flows:
        error:
          ui_url: https://account.redacted/error

        settings:
          ui_url: https://account.redacted/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: https://account.redacted/recovery

        verification:
          enabled: true
          ui_url: https://account.redacted/verify
          after:
            default_browser_return_url: https://account.redacted/

        login:
          ui_url: https://account.redacted/auth/login
          lifespan: 10m

        logout:
          after:
            default_browser_return_url: https://account.redacted/auth/login

        registration:
          lifespan: 10m
          ui_url: https://account.redacted/auth/registration
          after:
            password:
              hooks:
                - hook: session
            oidc:
              hooks:
                - hook: session
    hashers:
      argon2:
        parallelism: 1
        memory: 65536
        iterations: 1
        salt_length: 16
        key_length: 16

resources: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  privileged: false

nodeSelector: {}

tolerations: []

deployment:
  extraEnv: []
  tracing:
    datadog:
      enabled: false
  labels: {}
  extraVolumes: []
  extraVolumeMounts: []
  annotations: {}
  environmentSecretsName:
affinity: {}
```
