### ISSUE TITLE
Support multiple links to the same OIDC/social provider

### ISSUE THREAD

**Issue by zikes** [ory/kratos#1276]
**Is your feature request related to a problem? Please describe.**

My application's use case involves Kratos verifying a person's ownership of various accounts, which may sometimes be multiple on one platform. I would like the ability to enable multiple links to one provider.

**Describe the solution you'd like**

As this is a somewhat unusual use-case I imagine the feature would be disabled by default. For instance, if the implementation involved the addition of a new field in the oidc providers configuration, it would be false by default. e.g.

```yaml
providers:
  - id: google
    provider: google
    ...
    allow_multiple: true # default false
```

Since [the current OIDC login strategy code](https://github.com/ory/kratos/blob/v0.5.5-alpha.1/selfservice/strategy/oidc/strategy_login.go#L39) uses the provider ID and subject ID pair to look up the credentials on login, I think it would already support this.

As far as I can tell, the majority of the changes would need to be in the form builder code for login and settings. In particular, when unlinking from one of the accounts associated with the a provider the exact account would need to be specified somehow in the form submit.

**Describe alternatives you've considered**

I think this could be implemented in a limited fashion in the current Kratos by creating a series of copies of a single provider, but with different provider IDs:

```yaml
providers:
  - id: google-1
    provider: google
    ...
  - id: google-2
    provider: google
    ...
  - id: google-3
    provider: google
    ...
```

The UI would need to take special care in presenting these, and I suspect that attempting to log in to e.g. `google-1` with the account associated to `google-5` would fail, so the login process would be difficult to navigate.

Another alternative would be to have them unlink and then re-link to the new account on the provider, storing that history outside of the credentials portion of their identity. This could work for my use-case, but would be cumbersome.
