### ISSUE TITLE
Fields in identity schema marked as identifier should be required

### ISSUE THREAD

**Issue by brumhard** [ory/kratos#1286]
**Describe the bug**

**Reproducing the bug**

1. Run kratos with the docker-compose file shown below
2. Initialize API registration flow:  `curl -s -X GET -H "Accept: application/json" http://127.0.0.1:4433/self-service/registration/api`
3. Try to complete registration flow with traits.username set to empty string: `curl "http://localhost:4433/self-service/registration/methods/password?flow=xxx" -X POST -d '{"password":"test1234@!","traits.email":"email@mail.com","traits.username":""}' -H 'Content-Type: application/json'`
4. Request fails with response: `{"error":{"code":500,"status":"Internal Server Error","reason":"Unable to create identity credentials with missing or empty identifier.","message":"An internal server error occurred, please contact the system administrator"}}`

**Expected behavior**

I would expect the server to handle an empty string just like the value not being set instead of returning an internal server error in case it's explicitly set to empty string. If I just no set the traits.username at all it will just work as expected and return a validation message.
Also all fields that are marked as identifier or are set as required in the json identity schema should probably also be set to required in the flow json object since that would make form rendering a lot easier and probably backend validation also.

**Environment**

- Version: v0.5.5-alpha.1
- Environment: Docker

**Additional context**

_docker-compose.yml_

```yaml
version: "3.7"

x-general-options: &general-options
  networks:
    - intranet

x-kratos-options: &kratos-options
  <<: *general-options
  depends_on:
    - postgresd
  image: oryd/kratos:v0.5.5-alpha.1
  environment:
    - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
  volumes:
    - type: bind
      source: ./config
      target: /etc/config/kratos

services:
  kratos-migrate:
    <<: *kratos-options
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos:
    <<: *kratos-options
    depends_on:
      - kratos-migrate
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    command: serve -c /etc/config/kratos/kratos.yml --dev
    restart: unless-stopped

  postgresd:
    <<: *general-options
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos

  mailslurper:
    <<: *general-options
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
      - "1025:1025"

networks:
  intranet:
```

_Identity Schema_

```yaml
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "username": {
          "type": "string",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            }
          }
        }
      },
      "required": [
        "email",
        "username"
      ],
      "additionalProperties": false
    }
  }
}
```
