### ISSUE TITLE
GitLab/GitHub oauth shows error 400

### ISSUE THREAD

**Issue by ramsy1980** [ory/kratos#1296]
Gitlab throws error 400

**Reproducing the bug**
Configure oAuth according to Docs

_Server reply_

```
[
  {
    "code": 400,
    "debug": "Resumable ID from cookie could not be found in the datastore: rid=\nerror=Unable to locate the resource\nreason=\ndetails=map[]\ndebug=\n\ngithub.com/ory/x/sqlcon.HandleError\n\t/go/pkg/mod/github.com/ory/x@v0.0.228/sqlcon/error.go:51\ngithub.com/ory/kratos/persistence/sql.(*Persister).GetContinuitySession\n\t/home/ory/persistence/sql/persister_continuity.go:28\ngithub.com/ory/kratos/continuity.(*ManagerCookie).container\n\t/home/ory/continuity/manager_cookie.go:112\ngithub.com/ory/kratos/continuity.(*ManagerCookie).Continue\n\t/home/ory/continuity/manager_cookie.go:64\ngithub.com/ory/kratos/selfservice/strategy/oidc.(*Strategy).validateCallback\n\t/home/ory/selfservice/strategy/oidc/strategy.go:215\ngithub.com/ory/kratos/selfservice/strategy/oidc.(*Strategy).handleCallback\n\t/home/ory/selfservice/strategy/oidc/strategy.go:259\ngithub.com/ory/kratos/selfservice/strategy.disabledWriter\n\t/home/ory/selfservice/strategy/handler.go:25\ngithub.com/ory/kratos/selfservice/strategy.IsDisabled.func1\n\t/home/ory/selfservice/strategy/handler.go:30\ngithub.com/ory/kratos/x.NoCacheHandler.func1\n\t/home/ory/x/nocache.go:18\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387\ngithub.com/ory/nosurf.(*CSRFHandler).handleSuccess\n\t/go/pkg/mod/github.com/ory/nosurf@v1.2.4/handler.go:199\ngithub.com/ory/nosurf.(*CSRFHandler).ServeHTTP\n\t/go/pkg/mod/github.com/ory/nosurf@v1.2.4/handler.go:156\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/kratos/x.glob..func1\n\t/home/ory/x/clean_url.go:12\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\ngithub.com/rs/cors.(*Cors).Handler.func1\n\t/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2069\ngithub.com/gorilla/context.ClearHandler.func1\n\t/go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2069\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2887\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1952\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371",
    "reason": "No resumable session could be found in the HTTP Header.",
    "status": "Bad Request",
    "message": "session is not resumable"
  }
]
```

**Expected behavior**

I expect the login to work

**Environment**

ory/kratos v0.6.0

**Additional context**

```yaml
replicaCount: 3

image:
  repository: oryd/kratos
  tag: v0.5.5-alpha.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  admin:
    enabled: true
    type: ClusterIP
    port: 80
    annotations: {}
  public:
    enabled: true
    type: ClusterIP
    port: 80
    annotations: {}

secret:
  enabled: true

ingress:
  admin:
    enabled: false
  public:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      -
        host: redacted
        paths:
          - /

    tls:
      - hosts:
        - redacted
        secretName: redacted

kratos:
  development: false
  # autoMigrate is relying on a simple initContainer mechanism
  # Do not turn it on if the replicaCount > 1
  autoMigrate: false

#  You can add multiple identity schemas here
  identitySchemas:
    "identity.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "minLength": 3,
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "verification": {
                    "via": "email"
                  },
                  "recovery": {
                    "via": "email"
                  }
                }
              },
              "name": {
                "type": "object",
                "properties": {
                  "first": {
                    "type": "string"
                  },
                  "last": {
                    "type": "string"
                  }
                }
              }
            },
            "required": ["email"],
            "additionalProperties": false
          }
        }
      }
    "oidc.github.jsonnet": |-
      local claims = {
        email_verified: false
      } + std.extVar('claims');

      {
        identity: {
          traits: {
            // Allowing unverified email addresses enables account
            // enumeration attacks, especially if the value is used for
            // e.g. verification or as a password login identifier.
            //
            // Therefore we only return the email if it (a) exists and (b) is marked verified
            // by GitHub.
            [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
          },
        },
      }
    "oidc.gitlab.jsonnet": |-
      local claims = {
        email_verified: false
      } + std.extVar('claims');

      {
        identity: {
          traits: {
            // Allowing unverified email addresses enables account
            // enumeration attacks, especially if the value is used for
            // e.g. verification or as a password login identifier.
            //
            // Therefore we only return the email if it (a) exists and (b) is marked verified
            // by GitLab.
            [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
          },
        },
      }

  config:
    courier:
      smtp:
        connection_uri: redacted
        from_address: redacted
    dsn: redacted
    session:
      lifespan: 720h # 30 days
      cookie:
        domain: redacted
    secrets:
      cookie:
        - redacted
    identity:
      default_schema_url: file:///etc/config/identity.schema.json

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    serve:
      public:
        base_url: https://redacted
        cors:
          enabled: true
          allowed_origins:
            - https://*.redacted
            - http://localhost:3000
          allowed_methods:
            - DELETE
            - GET
            - PATCH
            - POST
            - PUT
          allowed_headers:
            - Authorization
            - Cookie
          exposed_headers:
            - Content-Type
            - Set-Cookie
          debug: true
      admin:
        base_url: http://kratos-admin/

    selfservice:
      default_browser_return_url: https://account.redacted
      whitelisted_return_urls:
        - https://redacted

      methods:
        password:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: github # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
                provider: github
                client_id: redacted # Replace this with the OAuth2 Client ID provided by GitHub
                client_secret: redacted # Replace this with the OAuth2 Client Secret provided by GitHub
                mapper_url: file:///etc/config/oidc.github.jsonnet
                scope:
                  - user:email
              - id: gitlab # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
                provider: gitlab
                client_id: redacted # Replace this with the OAuth2 Client ID provided by GitLab
                client_secret: redacted # Replace this with the OAuth2 Client Secret provided by GitLab
                mapper_url: file:///etc/config/oidc.gitlab.jsonnet
                scope:
                  - read_user
                  - openid
                  - profile
                  - email

      flows:
        error:
          ui_url: https://account.redacted/error

        settings:
          ui_url: https://account.redacted/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: https://account.redacted/recovery

        verification:
          enabled: true
          ui_url: https://account.redacted/verify
          after:
            default_browser_return_url: https://account.redacted/

        login:
          ui_url: https://account.redacted/auth/login
          lifespan: 10m

        logout:
          after:
            default_browser_return_url: https://account.redacted/auth/login

        registration:
          lifespan: 10m
          ui_url: https://account.redacted/auth/registration
          after:
            password:
              hooks:
                - hook: session
            oidc:
              hooks:
                - hook: session
    hashers:
      argon2:
        parallelism: 1
        memory: 65536
        iterations: 1
        salt_length: 16
        key_length: 16

resources: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  privileged: false

nodeSelector: {}

tolerations: []

deployment:
  extraEnv: []
  tracing:
    datadog:
      enabled: false
  labels: {}
  extraVolumes: []
  extraVolumeMounts: []
  annotations: {}
  environmentSecretsName:
affinity: {}
```

**Comment by anonrig** [comment]
@aeneasr any possible solutions? I'm facing the same issue.

**Comment by yeouchien** [comment]
I'm facing same issue with Discord oauth. Google oauth is working fine.
Kratos config:
```
...
  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: discord
            provider: discord
            client_id: redacted
            client_secret: redacted
            mapper_url: file:///etc/config/kratos/oidc.discord.jsonnet
            scope:
              - identify
              - email
...
session:
  lifespan: 720h
  cookie:
    domain: abc.xyz
```
