### ISSUE TITLE
Problem with health checks performance

### ISSUE THREAD

**Issue by harnash** [ory/kratos#1337]
**Describe the bug**

While running Kratos on our DEV k8s cluster I've noticed that newest version `v0.6.0-alpha.2` is having problems with health checks. First I thought it was issue with the DB but after deeper investigation I've found that `health/ready` is timing out. I could also reproduce this locally with non-local DB.
I'm using MySQL as a SQL server.

I did small experiment and here are the results:
```
number of migrations: 235
took: 267 ms
took: 306 ms
took: 285 ms
took: 309 ms
took: 294 ms
took: 281 ms
took: 284 ms
took: 337 ms
took: 356 ms
took: 299 ms
```

Karatos is expected to check `235` migrations which amounts to `235` queries to a backend SQL server (`SELECT EXISTS...`). So roughly `300ms * 235 = 705s` to check all migrations! This is quite pessimistic scenario since I'm running Kratos locally and MySQL server is located overseas but even with 10ms we get over 2s for just a simple readiness probe and this time will increase as the number of migrations increases. Not to mention the unnecessarly increased load on SQL server. Kubernetes will check this endpoint by default every 10s and default timeout is 1s.

Possible solution:
1. Cache the status of migrations for a period of time and refresh it asynchronously (can be tricky and could lead to stale data). Perhaps keeping some timestamp in the migration table could be used to check if there are new records or newly modified?
2. Do not send single query per migration but rather use one query to fetch all of them (or at least in batches) (this will improve performance but still will be problematic for the SQL server as the number of migrations grows)

**Reproducing the bug**

Steps to reproduce the behaviour:

1. Run Kratos configured with MySQL that has significant connection lag 100ms
2. Check if `/health/ready` is responding correctly

_Server logs_

```
{"http_request":{"headers":{"accept":"*/*","accept-encoding":"gzip, deflate","user-agent":"HTTPie/0.9.9"},"host":"localhost:4434","method":"GET","path":"/health/ready","query":null,"remote":"[::1]:59083","scheme":"http"},"http_response":{"status":503,"text_status":"Service Unavailable","took":12938683039},"level":"info","msg":"completed handling request","time":"2021-05-13T14:01:13+02:00"}
```

_Server configuration_

```yaml
courier:
  smtp:
    connection_uri: smtp://kratos-maildev:1025/?skip_ssl_verify=false
hashers:
  argon2:
    iterations: 1
    key_length: 16
    memory: 512MB
    parallelism: 1
    salt_length: 16
identity:
  default_schema_url: file://.config/identity.default.schema.json
log:
  format: json
  leak_sensitive_values: true
  level: debug
selfservice:
  default_browser_return_url: /self-service/
  flows:
    error:
      ui_url: /self-service/error
    login:
      lifespan: 10m
      ui_url: /self-service/auth/login
    logout:
      after:
        default_browser_return_url: https://auth/self-service/auth/login
    recovery:
      enabled: true
      ui_url: https://auth/self-service/recovery
    registration:
      after:
        password:
          hooks:
            - hook: session
      lifespan: 10m
      ui_url: https://auth/self-service/auth/registration
    settings:
      privileged_session_max_age: 15m
      ui_url: https://auth/self-service/settings
    verification:
      after:
        default_browser_return_url: https://auth/self-service/
      enabled: true
      ui_url: https://auth/self-service/verification
  methods:
    link:
      enabled: true
    password:
      enabled: true
  whitelisted_return_urls:
    - https://auth/self-service
serve:
  admin:
    base_url: https://auth/kratos-admin/
    port: 4434
  public:
    base_url: https://auth/kratos/
    cors:
      enabled: true
    port: 4433
session:
  cookie:
    domain: .fandom-dev.pl
dsn: mysql://***:***@tcp(mysql:3306)/auth?max_conns=10&max_idle_conns=2
```

**Expected behavior**

Health checks responds in reasonable time (<2s)

**Environment**

- Version: v0.6.0-alpha.2
- Environment: Docker, k8s
