### ISSUE TITLE
Invalid courier template file called email.body.plaintext.gotmpl

### ISSUE THREAD

**Issue by anonrig** [ory/kratos#1351]
**Describe the bug**

I'm receiving an error on forgot password action, and even though I have the necessary templates, and it did work before the 0.6 release, it now throws an error:

open /conf/courier-templates/recovery/invalid/email.body.plaintext.gotmpl: no such file or directory 
 
**Reproducing the bug**

1. Deploy using the helm chart
2. Use v0.6.2-alpha.1

_Server logs_

```
time=2021-05-17T15:39:30Z level=info msg=Encountered self-service recovery error. audience=audit error=map[message:open /conf/courier-templates/recovery/invalid/email.body.plaintext.gotmpl: no such file or directory] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 accept-encoding:gzip accept-language:en-US,en;q=0.9,tr;q=0.8 cache-control:max-age=0 cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:https://WEB_DOMAIN_URL referer:https://WEB_DOMAIN_URL/ user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56 x-forwarded-for:XFORWARDEDFOR x-forwarded-proto:http] host:KRATOS_URL method:POST path:/self-service/recovery query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:10.244.0.187:58618 scheme:http] recovery_flow=&{afda7f1a-bda2-4b46-9c94-41b934002055 browser 2021-05-17 16:39:14.250301 +0000 UTC 2021-05-17 15:39:14.250301 +0000 UTC http://KRATOS_URL/self-service/recovery/browser 0xc000bac730 choose_method qHD1dh7UexjU1BNpuJl+RAwvqCcmvRcaKpvKViIV/zmgVAM3Ke7ltYeQwuHQYYLoVQoRk4aCiaNl4aNbcpgz+g== 2021-05-17 15:39:14.25136 +0000 UTC 2021-05-17 15:39:14.25136 +0000 UTC {00000000-0000-0000-0000-000000000000 false} 8f5b721e-862a-43c1-ba4f-6137567952c2} service_name=Ory Kratos service_version=v0.6.2-alpha.1
time=2021-05-17T15:39:30Z level=error msg=An error occurred and is being forwarded to the error user interface. audience=application error=map[message:open /conf/courier-templates/recovery/invalid/email.body.plaintext.gotmpl: no such file or directory] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 accept-encoding:gzip accept-language:en-US,en;q=0.9,tr;q=0.8 cache-control:max-age=0 cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:https://WEB_DOMAIN_URL referer:https://WEB_DOMAIN_URL/ user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.56 x-forwarded-for:XFORWARDEDFOR x-forwarded-proto:http] host:KRATOS_URL method:POST path:/self-service/recovery query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:10.244.0.187:58618 scheme:http] service_name=Ory Kratos service_version=v0.6.2-alpha.1
```

_Server configuration_

```yaml
  emailTemplates:
    recovery:
      valid:
        subject: Recover access to your account
        body: |-
          EMAIL
      invalid:
        subject: Account access attempted
        body: |-
          EMAIL
    verification:
      valid:
        subject: Please verify your email address
        body: |-
          EMAIL
      invalid:
        subject:
        body:
```

**Expected behavior**

It should send a proper password recovery email.

**Environment**

- Version: v0.6.2-alpha.1
- Environment: Helm

**Additional context**

I checked, /conf/courier-templates/recovery/invalid/email.body.plaintext.gotmpl file does not exist but email.body.gotmpl exists.

**Comment by aeneasr** [comment]
@mattbonnell ideas?

**Comment by aeneasr** [comment]
For clarification, you are supplying your own templates, right?

**Comment by aeneasr** [comment]
Can you please include your full config also? This looks like a helm config?

**Comment by anonrig** [comment]
Yes @aeneasr I'm using Helm. I'm only supplying my values, which is the following, and use `helm upgrade -f ./kratos.yaml kratos ory/kratos -n kratos` command to upgrade it.

```yaml
replicaCount: 1

image:
  repository: oryd/kratos
  tag: v0.6.3-alpha.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  admin:
    enabled: true
  public:
    enabled: true

secrets:
  cookie:
    - COOKIE_SECRET
  default:
    - COOKIE_DEFAULT 

ingress:
  admin:
    enabled: false
  public:
    enabled: true
    hosts:
    - host: "login.DOMAIN.com"
      paths:
      - /
    tls:
    - secretName: "kratos-tls"
      hosts:
      - "login.DOMAIN.com"

kratos:
  development: false
  autoMigrate: true
  
  identitySchemas:
    "github.jsonnet": |
      local claims = {
        email_verified: false
      } + std.extVar('claims');

      {
        identity: {
          traits: {
            [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
            [if "name" in claims then "name" else null]: claims.name,
            [if "picture" in claims then "picture" else null]: claims.picture
          }
        }
      }

    "identity.default.schema.json": |
      {
        "$id": "identity.default.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "User",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "minLength": 3,
                "title": "Email Address",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "verification": {
                    "via": "email"
                  },
                  "recovery": {
                    "via": "email"
                  }
                }
              },
              "name": {
                "type": "string",
                "minLength": 2,
                "title": "Name and Surname"
              },
              "picture": {
                "type": "string",
                "title": "Picture"
              }
            },
            "required": [
              "email",
              "name"
            ],
            "additionalProperties": true
          }
        }
      }

  emailTemplates:
    recovery:
      valid:
        subject: Recover access to your account
        body: |-
          EMAIL
      invalid:
        subject: Account access attempted
        body: |-
          EMAIL
    verification:
      valid:
        subject: Please verify your email address
        body: |-
          EMAIL
      invalid:
        subject:
        body:

  config:
    version: v0.6.3-alpha.1

    identity:
      default_schema_url: file:///etc/config/identity.default.schema.json

    dsn: "postgres://postgresql:5432/kratos"

    courier:
      template_override_path: /conf/courier-templates
      smtp:
        connection_uri: SMPTS_URL
        from_address: hello@DOMAIN.com
        from_name: DOMAIN

    serve:
      admin:
        port: 8080
        base_url: http://kratos-admin.kratos.svc.cluster.local:8080/
      public:
        base_url: https://login.DOMAIN.com
        cors:
          enabled: true
          allowed_origins:
            - https://web.DOMAIN.com
            - https://web-dev.DOMAIN.com
          allowed_methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
          allowed_headers:
            - Authorization
            - X-Session-Token
            - Cookie
            - Referer
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - DPR
            - Downlink
            - Origin
            - Vary

          exposed_headers:
            - Content-Type
            - Set-Cookie
            - Access-Control-Allow-Origin
            - Access-Control-Allow-Credentials
            - Access-Control-Allow-Headers
            - Access-Control-Allow-Methods
            - Access-Control-Max-Age
            - Vary

          max_age: 21600

    session:
      lifespan: 720h
      cookie:
        persistent: true
        same_site: Lax
        domain: DOMAIN.com
    
    log:
      leak_sensitive_values: false

    selfservice:
      default_browser_return_url: https://web.DOMAIN.com
      whitelisted_return_urls:
        - https://web.DOMAIN.com

      flows:
        verification:
          enabled: true
        recovery:
          enabled: true
        registration:
          after:
            password:
              hooks:
                - hook: session
            oidc:
              hooks:
                - hook: session

      methods:
        link:
          enabled: true
        password:
          enabled: true
        profile:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: github
                provider: github
                mapper_url: file:///etc/config/github.jsonnet
                client_id: "CLIENT_ID"
                client_secret: "CLIENT_SECRET"
                scope:
                  - user:email
                  - read:user
                requested_claims:
                  userinfo:
                    name:
                      essential: true
                    email:
                      essential: true
                    email_verified:
                      essential: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 100
  allowPrivilegeEscalation: false
  privileged: false

resources:
  limits:
   cpu: 500m
   memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

deployment:
  nodeSelector: {}
  extraEnv: []
  tracing:
    datadog:
      enabled: false
      service: ory/kratos
      useHostIP: true
  tolerations: []
  labels: {}
  annotations: {}
  environmentSecretsName:

affinity: {}
```
