### ISSUE TITLE
Public base url not updated after alteration when using a sql database

### ISSUE THREAD

**Issue by JeffreyThijs** [ory/kratos#1389]
**Describe the bug**

When configuring kratos `SERVE_PUBLIC_BASE_URL` the first time everything works, when requesting login & registration flow the provided action url is correct. However, after altering the config parameter the requested urls still use the old base_url. When deleting the database and creating it back again it worked as expected.

**Reproducing the bug**

Deploy helm chart with `kratos.kratos.config.serve.public.base_url` with `https://my.domain.org/.ory/kratos/public` then alter the base_url to `https://my.domain.org/ory/kratos/public` and reinstall the helm chart.

_Server logs_

Just received flows containing the old ``kratos.kratos.config.serve.public.base_url`.

_Server configuration_

```yaml
kratos:
  fullnameOverride: ory-kratos
  image:
    tag: v0.6.3-alpha.1

  deployment:
    extraVolumes:
      - name: kratos-identity-schema
        configMap:
          name: kratos-identity-schema
    extraVolumeMounts:
      - name: kratos-identity-schema
        mountPath: /etc/config/kratos

  kratos:
    development: false
    autoMigrate: true

    config:
      serve:
        public:
          base_url: https://my.domain.org/ory/kratos/public

      selfservice:
        default_browser_return_url: https://my.domain.org/
        whitelisted_return_urls:
          - https://my.domain.org/
          - https://my.domain.org/ory-ui/auth/hydra/login

        methods:
          password:
            enabled: true

        flows:
          settings:
            ui_url: https://my.domain.org/ory-ui/auth/settings

          verification:
            ui_url: https://my.domain.org/ory-ui/auth/verification
            enabled: false

          recovery:
            ui_url: https://my.domain.org/ory-ui/auth/recovery
            enabled: false

          logout:
            after:
              default_browser_return_url: https://my.domain.org/ory-ui/auth/login

          login:
            ui_url: https://my.domain.org/ory-ui/auth/login

          registration:
            ui_url: https://my.domain.org/ory-ui/auth/registration
            after:
              password:
                hooks:
                  -
                    hook: session
      log:
        level: debug

      hashers:
        argon2:
          parallelism: 1
          memory: 131072B
          iterations: 2
          salt_length: 16
          key_length: 16

      identity:
        default_schema_url: file:///etc/config/kratos/identity.schema.json
```

**Expected behavior**

Receive the flows with the altered action id.

**Environment**

- Environment: using ory k8s helm chart v 0.11.1 with image: v0.6.3-alpha.1

**Additional context**

/
