### ISSUE TITLE
Using same email with 2 different Social Login providers results in unexpected behaviour

### ISSUE THREAD

**Issue by JovanShandro** [ory/kratos#1392]
**Describe the bug**

In an app that I am working on, I have setup both github and google sign in as explained in the documentation and both work fine. However, If I try to sign up with github with say the email a@a.com, log out, and then try to login to a google account with the same email I get an error that a user with that email already exists, which is expected, however together with the message I also get back a form that has only one Email input (if I try to login to github after google), or one Email input and 2 additional inputs with traits.first_name and traits.last_name (if I try to login to google after github). The oidc part of the returned data is:

```json
{
    "action": "<url>/auth/<some_id>",
    "method": "POST",
    "fields": [
        {
            "name": "traits.email",
            "type": "text",
            "value": "<email>"
        },
        {
            "name": "csrf_token",
            "type": "hidden",
            "required": true,
            "value": "<token_value>"
        },
        {
            "name": "provider",
            "type": "submit",
            "value": "google"
        },
        {
            "name": "traits.first_name",
            "type": "text",
            "value": "<name>"
        },
        {
            "name": "traits.last_name",
            "type": "text",
            "value": "<surname>"
        }
    ],
    "messages": [
        {
            "id": 4000007,
            "text": "An account with the same identifier (email, phone, username, ...) exists already.",
            "type": "error",
            "context": {}
        }
    ]
}
```
What is the purpose of the sent form? Is this supposed to happen?
I tried entering a dummy email and pressing submit and the result was that it signed me in (also stored the email of the user in the identities database), however since I never typed a password I don't know how to login again as that user (if it is possible).

**Reproducing the bug**

In any kratos app, add both google and github sign up and try to sign up with both with accounts that have the same email.

**Expected behavior**

I initially expected only an error message to be shown and then allowing the user to login again maybe with a different sign in method, however I am not sure if this is the right way to handle this 'error'. 

**Environment**

I am using the kratos helm chart with version 0.7.0.
My configuration file looks as follows:

```yaml
# This is for adding the jsonnet files
deployment:
  extraVolumes:
    - name: oauth-configuration
      configMap:
        name: oauth-config
  extraVolumeMounts:
    - name: oauth-configuration
      mountPath: "/etc/oauth"
      readOnly: true

kratos:
  autoMigrate: true
  development: true
  identitySchemas:
    "kratos-email-password.traits.schema.json": |
      {
        "$id": "<id>",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                "verification": {
                  "via": "email"
                  },
                "recovery": {
                  "via": "email"
                  }
                }
              }
            }
          }
        }
      }
  config:
    selfservice:
      methods:
        password:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: github
                provider: github
                client_id: ...
                client_secret: ...
                mapper_url: file:///etc/oauth/oidc.github.jsonnet
                scope:
                  - user:email
              - id: google
                provider: google
                client_id: ...
                client_secret: ...
                mapper_url: file:///etc/oauth/oidc.google.jsonnet
                scope:
                  - email
                  - profile
                requested_claims:
                  id_token:
                    email:
                      essential: true
                    email_verified:
                      essential: true
                    given_name:
                      essential: true
                    family_name: null
                    hd: null
           
```

Above I have only pasted the methods configuration as the other part is not directly connected to this issue.
