### ISSUE TITLE
A request failed due to a missing or invalid csrf_token value

### ISSUE THREAD

**Issue by ms42Q** [ory/kratos#1413]
**Describe the bug**

I am currently trying to upgrade to 0.6 and I am experiencing some errors that I can't make sense of.
When submitting the recovery form the client is redirected to the error page. In the kratos logs i can find a stacktrace which indicates that the csrf token is not valid or not present. However the csrf token in the html form matches the one associated with the token. I can also confirm that the token is sent to the kratos server with the correct name and value. Am I missing something? Do I need to change the kratos config? I just reused the config from version 0.5 because i did not see any breaking changes with the new version.

**Reproducing the bug**

Submit recovery form

**Logs**

```
time=2021-06-11T20:58:15Z level=error msg=An error occurred and is being forwarded to the error user interface. func=github.com/ory/kratos/selfservice/errorx.(*Manager).Create file=/home/ory/selfservice/errorx/manager.go:42 audience=application error=map[debug: message:The requested action was forbidden reason:A request failed due to a missing or invalid csrf_token value. status:Forbidden status_code:403 trace:
github.com/ory/kratos/selfservice/flow.EnsureCSRF
	/home/ory/selfservice/flow/request.go:55
github.com/ory/kratos/selfservice/strategy/link.(*Strategy).recoveryHandleFormSubmission
	/home/ory/selfservice/strategy/link/strategy_recovery.go:417
github.com/ory/kratos/selfservice/strategy/link.(*Strategy).Recover
	/home/ory/selfservice/strategy/link/strategy_recovery.go:301
github.com/ory/kratos/selfservice/flow/recovery.(*Handler).submitFlow
	/home/ory/selfservice/flow/recovery/handler.go:303
github.com/ory/kratos/session.(*Handler).IsNotAuthenticated.func1
	/home/ory/session/handler.go:193
github.com/ory/kratos/x.NoCacheHandler.func1
	/home/ory/x/nocache.go:18
github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387
github.com/ory/nosurf.(*CSRFHandler).handleSuccess
	/go/pkg/mod/github.com/ory/nosurf@v1.2.4/handler.go:199
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP
	/go/pkg/mod/github.com/ory/nosurf@v1.2.4/handler.go:150
github.com/urfave/negroni.Wrap.func1
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/kratos/x.glob..func1
	/home/ory/x/clean_url.go:12
github.com/urfave/negroni.HandlerFunc.ServeHTTP
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/urfave/negroni.(*Negroni).ServeHTTP
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96
github.com/rs/cors.(*Cors).Handler.func1
	/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2069
github.com/gorilla/context.ClearHandler.func1
	/go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2069
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2887
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1952
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371] http_request=map[headers:map[accept:text/ht
```

**Expected behavior**

Successful recovery flow

**Environment**
kratos config:

```yaml
rsion: v0.4.6-alpha.1
", line 195, in recover
dsn: memory
  File "/home/case/openappstack/si
serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/
packages/flask/templating.py", lin
selfservice:
  default_browser_return_url: http://127.0.0.1:5000
  whitelisted_return_urls:
    - http://127.0.0.1:4455
    - http://127.0.0.1:5000
    - http://127.0.0.1:5000/login
    - http://127.0.0.1:5000/recover
    - http://127.0.0.1:5000/settins

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:5000/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:5000/recover

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verify
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/auth/login

    login:
      ui_url: http://127.0.0.1:5000/auth
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE


identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16
```
docker.io/oryd/kratos:v0.6.3-alpha.1-sqlite

**Additional context**

The html form looks fine to me

```html
 <form method="post" action="http://127.0.0.1:4433/self-service/recovery?flow=caaa54ed-6fe8-4c4f-b2c0-1fe6c3e2c21f">
    <input id="csrf_token" name="csrf_token" type="hidden" value="3nnsdWwA/udFj/NyqxsaQp0teyBPgAk0++KmLXBvqVqT2j2Pjg0xeZRc0N/EYsdeGGQzBdxEnGQocJerOzJEcQ==">
    <input autofocus id="email" name="email" placeholder="Email address" required type="text" value="">
    <input type="submit" value="link" name="method">
  </form>
```

This the corresponding flow:

```json
{
    "id": "caaa54ed-6fe8-4c4f-b2c0-1fe6c3e2c21f",
    "type": "browser",
    "expires_at": "2021-06-11T21:58:11.247995028Z",
    "issued_at": "2021-06-11T20:58:11.247995028Z",
    "request_url": "http://localhost:4433/self-service/recovery/browser",
    "ui": {
        "action": "http://127.0.0.1:4433/self-service/recovery?flow=caaa54ed-6fe8-4c4f-b2c0-1fe6c3e2c21f",
        "method": "POST",
        "nodes": [
            {
                "type": "input",
                "group": "default",
                "attributes": {
                    "name": "csrf_token",
                    "type": "hidden",
                    "value": "3nnsdWwA/udFj/NyqxsaQp0teyBPgAk0++KmLXBvqVqT2j2Pjg0xeZRc0N/EYsdeGGQzBdxEnGQocJerOzJEcQ==",
                    "required": true,
                    "disabled": false
                },
                "messages": null,
                "meta": {}
            },
            {
                "type": "input",
                "group": "link",
                "attributes": {
                    "name": "email",
                    "type": "email",
                    "required": true,
                    "disabled": false
                },
                "messages": null,
                "meta": {}
            },
            {
                "type": "input",
                "group": "link",
                "attributes": {
                    "name": "method",
                    "type": "submit",
                    "value": "link",
                    "disabled": false
                },
                "messages": null,
                "meta": {
                    "label": {
                        "id": 1070005,
                        "text": "Submit",
                        "type": "info"
                    }
                }
            }
        ]
    },
    "state": "choose_method"
}
```
