### ISSUE TITLE
Relative path in ui_url or default_browser_return_url cause runtime crash

### ISSUE THREAD

**Issue by zhming0** [ory/kratos#1446]
**Describe the bug**

When `selfservice.default_browser_return_url` or `selfservice.flows.XXX.ui_url`  is set to be relative path (`/foo/bar`), Kratos will crash whenever it access those setting.

**Reproducing the bug**

1. Setup the demo kratos server using demo config.
2. Change `selfservice.flows.login.ui_url` to `/login`
3. Try to access login page
4. See Kratos crashes with following log

<img width="957" alt="Screen Shot 2021-06-18 at 5 39 39 pm" src="https://user-images.githubusercontent.com/1054703/122525252-667d7a00-d05c-11eb-90cc-2f546e3c6440.png">

_Server configuration_

Just like the demo config: 

```yaml
serve:
  public:
    base_url: http://127.0.0.1:3001/kratos/
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3001/
  whitelisted_return_urls:
    - /

  methods:
    password:
      enabled: true

  flows:
    login:
      ui_url: /login
```

**Expected behavior**

It works just like v0.5 or it throws a proper error instead of crashing

**Environment**

- Version: v0.6.3
- Environment: Docker

**Additional context**

* It appears this new behavior was introduced in v0.6. 
* The same problem applies to the default_browser_return_url setting
