### ISSUE TITLE
Remove sqa-opt-out from config reference

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1514]
**Describe the bug**

Even if I use `sqa-opt-out: true` in `kratos.yml` in the logs it says: `Software quality assurance features are enabled.`

**Reproducing the bug**

1. Run `docker-compose up`

with `docker-compose.yml`:

```yaml
version: "3"

services:
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.6.3-alpha.1-sqlite
    ports:
      - "4433:4433"
      - "4434:4434"
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos/email-password
        target: /etc/config/kratos

volumes:
  kratos-sqlite:
```

_Server logs_

```
...
time=2021-07-09T14:37:01Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa func=github.com/ory/x/metricsx.New file=/go/pkg/mod/github.com/ory/x@v0.0.238/metricsx/middleware.go:174 audience=application service_name=Ory Kratos service_version=v0.6.3-alpha.1
...
```

_Server configuration_

```yaml
dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:4000/
  whitelisted_return_urls:
    - http://localhost:4000

  methods:
    password:
      enabled: true

  flows:
    login:
      ui_url: http://localhost:4000

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

sqa-opt-out: true
```

**Expected behavior**

It disable sqa

**Environment**

- Version: image: oryd/kratos:v0.6.3-alpha.1-sqlite
- Environment: Windows 10, Docker
