### ISSUE TITLE
Error during recovery from email link: "A valid session was detected and thus recovery is not possible."

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1548]
**Describe the bug**

I'm using `oryd/kratos:v0.7.0-alpha.1` for AJAX news.

I think something is broken or maybe it's just me.

When I open the link sent via email for recovery, Kratos correctly redirects me to the page I set for:

```yml
flows:
  settings:
    ui_url: http://localhost:4000/me/settings
```

But now I have in my browser two cookies:

1. ory_kratos_session	MTYyNjI...iBEag==	localhost	/	2021-07-15T18:49:49.037Z	234	✓		Lax		Medium	
1. aHR0cDovL2..........MzLw_csrf_token	Bhgns...pY5w=	localhost	/	2022-07-14T18:49:49.037Z	85	✓		Lax		Medium	

And my page in browser is: `http://localhost:4000/me/settings?flow=393d0ae1-7c4e-4b07-92c3-18d4f8c57d7d`.

The problem now:

1. I cannot fetch a `csrf_token` from `/self-service/settings/flows?id=${flowID}` anymore
1. I cannot fetch a `csrf_token` from `/self-service/settings/browser` because Kratos throws with: `The request was malformed or contained invalid parameters reason:A valid session was detected and thus recovery is not possible.`
1. I cannot set password because I don't have `csrf_token` to send along with cookie

**Am I wrong?**

_Server logs_

```
time=2021-07-14T17:55:03Z level=error msg=An error occurred while handling a request func=github.com/ory/herodot.DefaultErrorReporter.func1 file=/go/pkg/mod/github.com/ory/herodot@v0.9.6/error_reporter.go:24 audience=application error=map[debug: message:The request was malformed or contained invalid parameters reason:A valid session was detected and thus recovery is not possible. status:Bad Request status_code:400 trace:
github.com/ory/kratos/selfservice/flow/recovery.(*Handler).RegisterPublicRoutes.func1
        /home/ory/selfservice/flow/recovery/handler.go:70
github.com/ory/kratos/session.(*Handler).IsNotAuthenticated.func1
        /home/ory/session/handler.go:182
github.com/ory/kratos/x.NoCacheHandler.func1
        /home/ory/x/nocache.go:18
github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387
github.com/ory/nosurf.(*CSRFHandler).handleSuccess
        /go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:201
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP
        /go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:158
github.com/urfave/negroni.Wrap.func1
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/kratos/x.glob..func1
        /home/ory/x/clean_url.go:12
github.com/urfave/negroni.HandlerFunc.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/urfave/negroni.(*Negroni).ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96
github.com/gorilla/context.ClearHandler.func1
        /go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2069
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2887
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1952
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371] http_request=map[headers:map[accept:application/json accept-encoding:gzip, deflate, br accept-language:it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7 cookie:aHR0cDovL2xvY2FsaG9zdDo0NDMzLw_csrf_token=jbPgfO9LF4AYLvQvFbE0mrK24y03M1oV8ibOsAEgcZQ=; ory_kratos_session=MTYyNjI4NTIyN3xEdi1CQkFFQ180SUFBUkFCRUFBQVJfLUNBQUVHYzNSeWFXNW5EQThBRFhObGMzTnBiMjVmZEc5clpXNEdjM1J5YVc1bkRDSUFJSGRwT1VWaE0wTlJSRFJqV2pWWVVXTlRia05hUkd0eGVVcHNRV1pqY1VaTXyzPSLR3ENwS4P-10PQ6cjEQx821M69afpWqFCij5ajMQ== referer:http://localhost:4000/me/settings?flow=9db5ff95-e76e-4bc1-b780-cdfbd962395a user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 x-forwarded-for:172.23.0.1] host:localhost:4455 method:GET path:/self-service/recovery/browser query:<nil> remote:172.23.0.5:54556 scheme:http] http_response=map[status_code:400] service_name=Ory Kratos service_version=v0.7.0-alpha.1
```

_Server configuration_

```yaml
serve:
  public:
    base_url: http://localhost:4433/
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:4000/
  whitelisted_return_urls:
    - http://localhost:4000
  methods:
    password:
      enabled: true
    link:
      enabled: true

  flows:
    settings:
      ui_url: http://localhost:4000/me/settings

    error:
      ui_url: http://localhost:4000/me/error

    recovery:
      enabled: true
      ui_url: http://localhost:4000/me/recovery

    logout:
      after:
        default_browser_return_url: http://localhost:4000/login

    login:
      ui_url: http://localhost:4000/me/login

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: ...
```

**Expected behavior**

I think we should not authenticate the user just by the click on link.

Or maybe we have to detect if this is a regular session or a recovered one.

**Environment**

- Version: oryd/kratos:v0.7.0-alpha.1
- Environment: Docker

**Additional context**

I'm using it with Oathkeeper.
