### ISSUE TITLE
Discord shows an authorization screen on subsequent logins

### ISSUE THREAD

**Issue by avinashbot** [ory/kratos#1593]
**Describe the bug**

Discord shows the authorization screen on every login even if I've already authorized my application in the past. It looks like the reason is that Kratos assumes that `prompt=none` is the default, although the actual default value appears to be `prompt=consent`.

It's a tiny change, so I've already made it on GitHub's editor, but I wanted to make sure that this behavior isn't intended before I make it a PR ([my commit](https://github.com/avinashbot/kratos/commit/5fb91806be97f20df7dcf1045b79dd2db1170fdc)).

**Reproducing the bug**

1. Add a discord OIDC provider to the configuration
2. Sign in with Discord, and then click "Authorize" on the screen
3. Sign out
4. Sign in with Discord again, and you're not automatically redirected back even though you've authorized it previously.

_Server logs_

Omitting server logs since they don't seem to be relevant here.

_Server configuration_

<details>
  <summary>Collapsed for space</summary>

(Config is split across YAML and environment variables because env vars don't support nested configs yet)

YAML config:

```yaml
version: v0.7.1
selfservice:
  methods:
    oidc:
      config:
        providers: [{"id":"discord","provider":"discord","mapper_url":"...","client_id":"...","client_secret":"...","scope":["identify","email"]}]
  flows:
    registration:
      after:
        password:
          hooks: [{"hook":"session"}]
        oidc:
          hooks: [{"hook":"session"}]
```

Environment variables:

```
- DSN=postgres://postgres:postgres@postgres-kratos/kratos
- SERVE_PUBLIC_BASE_URL=http://localhost:3000/.ory/
- SERVE_ADMIN_BASE_URL=http://kratos:4434
- SELFSERVICE_FLOWS_LOGIN_UI_URL=http://localhost:3000/login
- SELFSERVICE_FLOWS_REGISTRATION_UI_URL=http://localhost:3000/signup
- SELFSERVICE_FLOWS_ERROR_UI_URL=http://localhost:3000/error
- SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=http://localhost:3000
- COURIER_SMTP_CONNECTION_URI=smtps://test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true
- SECRETS_COOKIE=ipsumipsumipsumi
- SECRETS_DEFAULT=ipsumipsumipsumi
- IDENTITY_DEFAULT_SCHEMA_URL=file:///home/ory/schemas/default.schema.json
- SELFSERVICE_METHODS_OIDC_ENABLED=true
- COURIER_TEMPLATE_OVERRIDE_PATH=/home/ory/email-templates
```

</details>

**Expected behavior**

I don't expect to see an authorization screen a second time.

**Environment**

- Version: v1.7.1
- Environment: Docker
