### ISSUE TITLE
Configuration files not recognised when using custom docker image

### ISSUE THREAD

**Issue by shivam-909** [ory/kratos#1619]
**Describe the bug**

Upon creating a custom docker image as described [here](https://www.ory.sh/kratos/docs/guides/docker/), and running the container, Kratos does not recognise the kratos.yml file supplied during the COPY step of the Dockerfile. The container exits immediately, telling me that the configuration file couldn't be instantiated and there were invalid keys and values. I know nothing is wrong with the configuration file, its taken straight from the quickstart ([here is the file](https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password/kratos.yml)); however, Kratos doesn't even acknowledge the existence of this file, no matter where I place it or what I name it as.

**Reproducing the bug**

1. Create a folder anywhere on your system, and in this folder create a file kratos.yml. Copy and paste the contents of the quickstart yaml provided [here](https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password/kratos.yml).
2. Create a Dockerfile in this same folder, with these contents (taken from [here](https://www.ory.sh/kratos/docs/guides/docker/), with a modified path).
```
FROM oryd/kratos:latest
COPY kratos.yml /home/ory
```
*NOTE: Including the identity.schema.json file and copying it to the path described in the configuration file does not change the behaviour observed.*

3. Build the image with `docker build -t {any name} .` - there should be no problems here.
4. Run the container with the image you just built `docker run {image you just built}`.
5. Container will exit almost immediately with an error.

_Server logs_

```
The configuration contains values or keys which are invalid:

The configuration contains values or keys which are invalid:

identity: <nil>

^-- one or more required properties are missing


The configuration contains values or keys which are invalid:

courier.smtp.connection_uri: <nil>

^-- one or more required properties are missing


The configuration contains values or keys which are invalid:

selfservice.default_browser_return_url: <nil>

^-- one or more required properties are missing


time=2021-08-02T20:23:28Z level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:I[#] S[#] validation failed

I[#] S[#/required] missing properties: "identity", "dsn"

I[#/courier/smtp] S[#/properties/courier/properties/smtp/required] missing properties: "connection_uri"

I[#/selfservice] S[#/properties/selfservice/required] missing properties: "default_browser_return_url"] service_name=Ory Kratos service_version=v0.7.1-alpha.1

```

_Server configuration_

```yaml
version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  whitelisted_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verify
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/auth/login

    login:
      ui_url: http://127.0.0.1:4455/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - {cookie secret}

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///home/ory/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true
```

**Expected behavior**

Kratos at least recognises the configuration file provided and the fields provided with them. 

**Environment**

- Version: v0.7.1-alpha.1
- Environment: Darwin (MacOS Monterey Beta), running Docker v20.10.7. 

**Additional context**

No additional context that seems relevant at the moment.
