### ISSUE TITLE
API Responses set-cookie with Insomnia/Postman

### ISSUE THREAD

**Issue by lucassimon** [ory/kratos#1684]
**Describe the bug**

API Responses set-cookie with Insomnia/Postman

**Reproducing the bug**

https://github.com/lucassimon/lab-ory-kratos

Plase visit the gif. Open in new tab to view on fullscreen

![Peek 2021-08-25 09-58](https://user-images.githubusercontent.com/355496/130804193-0de7c185-07cb-4a2a-a92b-829db496a89e.gif)

_Server logs_

``` 
iam-svc_1         | time=2021-08-25T13:22:51Z level=info msg=started handling request http_request=map[headers:map[accept:application/json user-agent:insomnia/2021.3.0] host:127.0.0.1:4433 method:GET path:/self-service/registration/api query:<nil> remote:192.168.112.1:42766 scheme:http]
iam-svc_1         | time=2021-08-25T13:22:51Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json user-agent:insomnia/2021.3.0] host:127.0.0.1:4433 method:GET path:/self-service/registration/api query:<nil> remote:192.168.112.1:42766 scheme:http] http_response=map[status:200 text_status:OK took:52.971µs]
iam-svc_1         | time=2021-08-25T13:22:59Z level=warning msg=A request failed due to a missing or invalid csrf_token value audience=application error=map[debug: details:map[docs:https://www.ory.sh/kratos/docs/debug/csrf hint:The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token). reject_reason:The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow.] message:the request was rejected to protect you from Cross-Site-Request-Forgery reason:The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues. status:Forbidden status_code:403] expected_token=sl9gGyRdbezoj0pupbjXbdo2gBBs03hbGNmArZZ00CaF6XjdVmJhih06NtFdgRguDdzFgU78GSc4lWJyiLA/xQ== received_cookies=[] received_token_body= received_token_form= received_token_header= result=false service_name=Ory Kratos service_version=v0.7.1-alpha.1
iam-svc_1         | time=2021-08-25T13:22:59Z level=error msg=An error occurred while handling a request audience=application error=map[debug: details:map[docs:https://www.ory.sh/kratos/docs/debug/csrf hint:The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token). reject_reason:The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow.] message:the request was rejected to protect you from Cross-Site-Request-Forgery reason:The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues. status:Forbidden status_code:403] http_request=map[headers:map[accept:application/json user-agent:insomnia/2021.3.0] host:127.0.0.1:4433 method:POST path:/self-service/registration/ query:<nil> remote:192.168.112.1:42766 scheme:http] http_response=map[status_code:403] service_name=Ory Kratos service_version=v0.7.1-alpha.1
iam-svc_1         | time=2021-08-25T13:22:59Z level=info msg=started handling request http_request=map[headers:map[accept:application/json user-agent:insomnia/2021.3.0] host:127.0.0.1:4433 method:POST path:/self-service/registration/ query:<nil> remote:192.168.112.1:42766 scheme:http]
iam-svc_1         | time=2021-08-25T13:22:59Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json user-agent:insomnia/2021.3.0] host:127.0.0.1:4433 method:POST path:/self-service/registration/ query:<nil> remote:192.168.112.1:42766 scheme:http] http_response=map[status:403 text_status:Forbidden took:43.994µs]
``` 

_Server configuration_

PLEASE OMIT SENSITIVE VALUES

```yaml
version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: ${GATEWAY_SVC_URL}/user-svc/public
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - ${GATEWAY_SVC_URL}
      allowed_methods:
        - GET
      allowed_headers:
        - Content-Type
        - Accept
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: ${GATEWAY_SVC_URL}/user-svc/admin
    port: 4434

selfservice:
  default_browser_return_url: ${GATEWAY_SVC_URL}/
  whitelisted_return_urls:
    - ${GATEWAY_SVC_URL}

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: ${GATEWAY_SVC_URL}/auth/error

    settings:
      ui_url: ${GATEWAY_SVC_URL}/auth/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: ${GATEWAY_SVC_URL}/auth/recovery

    verification:
      enabled: true
      ui_url: ${GATEWAY_SVC_URL}/auth/verify
      after:
        default_browser_return_url: ${GATEWAY_SVC_URL}/

    logout:
      after:
        default_browser_return_url: ${GATEWAY_SVC_URL}/auth/login

    login:
      ui_url: ${GATEWAY_SVC_URL}/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: ${GATEWAY_SVC_URL}/auth/register
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - strong-cookie
  default:
    - foobarfizzbuzzmarcopolo

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16
```

**Expected behavior**

The flows generated by  `type: api` cannot be responses a `Set-Cookie`

**Environment**

- Version: v0.7.1-alpha-1
- Environment: Docker

**Additional context**

...
