### ISSUE TITLE
Unable to initialize OpenID Connect Provider: oidc: issuer did not match the issuer returned by provider, expected "https://facebook.com" got "https://www.facebook.com"

### ISSUE THREAD

**Issue by meotimdihia** [ory/kratos#1686]
**Describe the bug**
I get this bug when login with Facebook. It worked in the past but the bug happens today. Did Facebook change something ?https://www.facebook.com/.well-known/openid-configuration/
"Unable to initialize OpenID Connect Provider: oidc: issuer did not match the issuer returned by provider, expected \"https://facebook.com\" got \"https://www.facebook.com\""

It seems this is the problem. But why can't I change issuer_url: https://github.com/ory/kratos/blob/master/selfservice/strategy/oidc/provider_facebook.go#L23

**Reproducing the bug**

facebook config: 
```yml
          - id: facebook
            provider: facebook
            client_id: ''
            client_secret: '' 
            mapper_url: file:///etc/config/kratos/oidc.facebook.jsonnet
            issuer_url: https://www.facebook.com # I tried with line or removed the line but not works
            scope:
              - email 
```

Kratos: 0.63
