### ISSUE TITLE
Facebook connect stopped working after update to 0.7.0

### ISSUE THREAD

**Issue by abador** [ory/kratos#1687]
**Describe the bug**

Facebook OIDC connect is broken. 

**Reproducing the bug**

1. Add facebook as an oidc provider
2. try to log in/register  using facebook connect
3. you can't log in/register and you are redirected to the log in screen 

_Server logs_

```
log=error "Unable to initialize OpenID Connect Provider: oidc: issuer did not match the issuer returned by provider, expected \"https://facebook.com\" got \"https://www.facebook.com\""
```

_Server configuration_

PLEASE OMIT SENSITIVE VALUES

```yaml
# $ kratos -c path/to/my/kratos/config.yml serve
selfservice:
  methods:
    oidc:
      enabled: true
      config:
        providers:
          - id: facebook # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
            provider: facebook
            client_id: .... # Replace this with the OAuth2 Client ID provided by Facebook app
            client_secret: .... # Replace this with the OAuth2 Client Secret provided by Facebook app
            mapper_url: file:///etc/config/kratos/oidc.facebook.jsonnet
            scope:
              - email # required for email and email_verified claims in the near future
                # other supported scopes: user_gender, user_birthday
```

**Expected behavior**

We are able to log in using facebook connect

**Environment**

- Version: forked v0.7.0, fixed in: https://github.com/Wikia/kratos/tree/PLATFOM-6245-oidc-experiment
- Environment: Docker

**Additional context**
