### ISSUE TITLE
0.7.3.alpha.1, docker, panic if SESSION_COOKIE_NAME is set in docker-compose.yml

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1695]
**Describe the bug**

Using v0.7.3.alpha.1 with `docker-compose.yml` if I set `SESSION_COOKIE_NAME` when I login (with SPA) it panics.

**Reproducing the bug**

- docker-compose.yml:

```yml
# ...
kratos:
  depends_on:
    - kratos-migrate
  image: oryd/kratos:v0.7.3-alpha.1
  env_file:
    - ../../.env
  ports:
    - "4433:4433" # public
    - "4434:4434" # admin
  restart: unless-stopped
  environment:
    - DSN=postgres://postgres:postgres@db/postgres?sslmode=disable
    - SESSION_COOKIE_NAME="myCustomTest"
  command: -c /etc/config/kratos/kratos.yml serve --dev --watch-courier
  volumes:
    - type: bind
      source: ./kratos.config
      target: /etc/config/kratos
# ...
```

_Server logs_

```
service_name=Ory Kratos service_version=v0.7.3-alpha.1
2021/08/29 14:37:13 http: panic serving 192.168.32.1:46462: runtime error: invalid memory address or nil pointer dereference
goroutine 180 [running]:
net/http.(*conn).serve.func1(0xc000d1ad20)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x155ab20, 0x230e640)
        /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/ory/kratos/session.(*ManagerHTTP).IssueCookie(0xc000f3d4e8, 0x19e3e78, 0xc000f51cb0, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af500, 0xc000b0a9a0, 0x1d, 0x1d)
        /home/ory/session/manager_http.go:58 +0x860
github.com/ory/kratos/session.(*ManagerHTTP).CreateAndIssueCookie(0xc000f3d4e8, 0x19e3e78, 0xc000f51cb0, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af500, 0xc000b0a9a0, 0x0, 0x0)
        /home/ory/session/manager_http.go:47 +0xd6
github.com/ory/kratos/selfservice/flow/login.(*HookExecutor).PostLoginHook(0xc000f4bcd0, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af500, 0xc000c76d00, 0xc000b6fc20, 0x0, 0x0)
        /home/ory/selfservice/flow/login/hook.go:115 +0x8a9
github.com/ory/kratos/selfservice/flow/login.(*Handler).submitFlow(0xc000e500f0, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af500, 0x0, 0x0, 0x0)
        /home/ory/selfservice/flow/login/handler.go:448 +0x325
github.com/ory/kratos/x.NoCacheHandler.func1(0x7fa21fef6d78, 0xc0003867a0, 0xc0003af500, 0x0, 0x0, 0x0)
        /home/ory/x/nocache.go:18 +0x83
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000e52000, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af500)
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e
github.com/ory/nosurf.(*CSRFHandler).handleSuccess(...)
        /go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:201
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP(0xc0003b40b0, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400)
        /go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:152 +0x7b0
github.com/urfave/negroni.Wrap.func1(0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400, 0xc0004150a0)
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc000e50090, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400, 0xc0004150a0)
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x19c09a0, 0xc000e50090, 0xc000e50420, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400)
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/ory/kratos/x.glob..func1(0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400, 0xc000415080)
        /home/ory/x/clean_url.go:12 +0x8b
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0x183d330, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400, 0xc000415080)
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x19c09a0, 0x183d330, 0xc000e50408, 0x7fa21fef6d78, 0xc0003867a0, 0xc0003af400)
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc000b9e030, 0x19dd778, 0xc000a42540, 0xc0003af400)
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xf1
net/http.serverHandler.ServeHTTP(0xc000e660e0, 0x19dd778, 0xc000a42540, 0xc0003af400)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000d1ad20, 0x19e3e78, 0xc000b68740)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b
```

_Server configuration_

```yaml
selfservice:
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false

    link:
      enabled: true

  flows:
    recovery:
      enabled: true

log:
  format: text
```

**Expected behavior**

It should work.

**Environment**

- Version: v0.7.3-alpha.1
- Environment: Docker
