### ISSUE TITLE
Can't log in with old cookies when upgrade from 0.6.3 to 0.7.3

### ISSUE THREAD

**Issue by meotimdihia** [ory/kratos#1696]
**Describe the bug**
I used Kratos 0.6.3. when I upgraded Kratos to 0.7.3, I got this error 'the request was rejected to protect you from Cross-Site-Request-Forgery', infinite loop, and redirects multiple times.

This is my localhost settings:  

```yaml
serve:
  public:
    base_url: https://auth.b.com

    cors:
      enabled: true
      allowed_origins:
        - https://b.com
        - https://*.b.com
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE        
      allowed_headers:
        - Authorization
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      
  admin:
    base_url: http://localhost:4434

cookies:
  domain: b.com
    
session:
  cookie:
    domain: b.com
```

debugging screenshot:  
![image](https://user-images.githubusercontent.com/300961/131256002-6fd45f6a-bed0-4268-a9ba-913b8180570f.png)

Cookies:

`name`: ory_kratos_session
`value`: MTYzMDIyMzMwMnxEdi1CQkFFQ180SUFBUkFCRUFBQVJfLUNBQUVHYzNSeWFXNW5EQThBRFhObGMzTnBiMjVmZEc5clpXNEdjM1J5YVc1bkRDSUFJSHBDWjJSbVFtUllkSEJvYUZrNWJFRmlSRGQyWTNWb2RGcENWVTR3Y1c1SHxhaMQZBwJ_qHbiNNFLeSAECM0gj0od7TH64WtwW1I4mg==
`domain`: .b.com
`expires`:  2021-08-30T07:48:23.368Z

**Environment**

- Environment: Windows, Docker, ...

Everything is fine if I test in the browser private mode. How can I solve this problem?

**Comment by aeneasr** [comment]
Thank you for the report - habe you followed the upgrade guide?

https://github.com/ory/kratos/blob/master/UPGRADE.md

**Comment by meotimdihia** [comment]
@aeneasr : I searched "upgrade" in the documentation but can't find anything. 
I just have updated Dockerfile, and run this command: `docker-compose -f quickstart.yml up --build --force-recreate`

**Comment by aeneasr** [comment]
Ok then check out the link above!

**Comment by meotimdihia** [comment]
@aeneasr I have found out how to reproduce this bug:
```
//  0.7.3 has new configuration:
cookies:  <-- step 1 remove this configuration 
  domain: b.com <-- step 1 remove this configuration 
    
session:
  cookie:
    domain: b.com
``` 

- Step 1:  remove configuration cookies.
- Step 2: access to public URL + `/self-service/login/browser` for set csrf_token with subdomain - auth.b.com
- Step 3: add cookies configuration that was removed at step 1 - re-create | update config for Kratos docker.

you can't log in again when the public URL Kratos has the cookies with the subdomain.
