### ISSUE TITLE
Goland (JetBrains) does not recognize `leak_sensitive_values` in `config.yml`

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1714]
**Describe the bug**

Goland (JetBrains) does not recognize `leak_sensitive_values` in `config.yml` both for `Kratos` and `Oathkeeper`.

**Reproducing the bug**

Open the project in Goland or Jetbrains (or VSCode I think).

See screenshot below.

_Server configuration_

```yaml
...
log:
  level: debug
  leak_sensitive_values: true
...
```

![image](https://user-images.githubusercontent.com/41120635/131883178-a3a9007f-4040-48f0-b8ed-97cc4e629965.png)
