### ISSUE TITLE
I need custom path in recovery email link

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1765]
**Describe the bug**

I need to use a custom URL for recovery and I'm using this env:

`SELFSERVICE_FLOWS_RECOVERY_UI_URL="http://my.domain/customPath/recovery"`

but if I use link method for recovery with the standard email template it sends an email with this link:

`http://my.domain/self-service/recovery?flow=...&token=...`

As you can see it creates a link with `self-service` in it.

_Server configuration_

```yaml
selfservice:
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false

    link:
      enabled: true

  flows:
    recovery:
      enabled: true

log:
  format: text
```

**Expected behavior**

It should create the link in mail (`.recoveryURL` var template) with `customPath` not `self-service`.

Is this my fault? Some config to override?

**Environment**

- Version: oryd/kratos:v0.7.6-alpha.1
- Environment: Docker, Linux, Windows
