### ISSUE TITLE
OIDC Config: restructure to be readable

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#1783]
**Is your feature request related to a problem? Please describe.**

The OIDC config in the schema is pretty messy.

**Describe the solution you'd like**

We should change it to be readable, something like:

```yml
allOf:
  - properties:
      label: ...
      id: ...
  - oneOf:
    - properties:
        provider:
          const: apple
        ... apple specific stuff
```

**Additional context**

#1782
