### ISSUE TITLE
Schema validation pretends ENV VARS optional keys in yaml config

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1785]
**Describe the bug**

I'm having these errors in Jetbrains IDEs:

```
Schema validation: One of the following property sets is required: property 'courier', property 'courier', property 'courier', property 'courier', property 'courier', or property 'courier' 

Schema validation: One of the following property sets is required: property 'default_browser_return_url', property 'default_browser_return_url', property 'default_browser_return_url', property 'default_browser_return_url', property 'default_browser_return_url', or property 'default_browser_return_url' 
```

but these config are also optionally configurable with ENV VARS which I'm using instead.

Is this my fault?

_Server configuration_

```yaml
selfservice:
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false

    link:
      enabled: true

  flows:
    recovery:
      enabled: true

log:
  format: text
```

**Environment**

- Version: oryd/kratos:v0.7.6-alpha.1
