### ISSUE TITLE
CORS Wildcard in Allowed Origins not working as expected

### ISSUE THREAD

**Issue by dan2kx** [ory/kratos#1842]
**Describe the bug**
According to the documentation : 
```
cors:
      ## allowed_origins ##
      #
      # A list of origins a cross-domain request can be executed from. If the special * value is present in the list, all origins will be allowed. An origin may contain a wildcard (*) to replace 0 or more characters (i.e.: http://*.domain.com). Only one wildcard can be used per origin.
      #
```
**Reproducing the bug**

Configure the kratos yaml file with a subdomain wildcard and try to access the the api service from the subdomain (i'm using the javascript client kratos.toSession()).

```
    cors:
      enabled: true
    allowed_origins:
      - https://*.sub.domain.com
    allowed_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
    allowed_headers:
      - Authorization
      - Cookie
    exposed_headers:
      - Content-Type
      - Set-Cookie
```

**Expected behavior**

I would expect this to work without issue

**Environment**

- Version: v0.7.6-alpha.1
- Environment: Docker

**Additional context**

The cookie is set to allow sub domains and the cookie is present. The request works if i switch the wildcard for an actual domain.
