### ISSUE TITLE
Unable to initialize OpenID Connect Provider (Google)

### ISSUE THREAD

**Issue by gammaSpeck** [ory/kratos#1893]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

While setting up Google Social Sign In flow, the request when made with npm `    "@ory/kratos-client": "0.0.0-next.059ed9c9cacb",` is getting cancelled

Pic of Chrome Network Logs
![image](https://user-images.githubusercontent.com/39631861/139216332-f641ed82-c0db-4a24-81c0-3b86c93d51e6.png)

Request headers
![image](https://user-images.githubusercontent.com/39631861/139216414-1ebd1186-0465-4917-bd08-6830c186a59e.png)

### Reproducing the bug

While making the OIDC Provider AJAX call from the Front end.

```typescript
const { data } = await kratosClient.initializeSelfServiceLoginFlowForBrowsers(
			undefined,
			undefined,
			undefined,
			{ withCredentials: true }
		);
		return data; 



const { data } = await kratosClient.submitSelfServiceLoginFlow(
				flowId, // Fetched earlier during initialize flow
				undefined,
				{ method: "oidc", provider: "google" },
				{ withCredentials: true }
			);
			return data;
```

### Relevant log output

```shell
time=2021-10-28T08:15:36Z level=error msg=An error occurred while handling a request func=github.com/ory/herodot.DefaultErrorReporter.func1 file=/go/pkg/mod/github.com/ory/herodot@v0.9.12/error_reporter.go:24 audience=application error=map[debug: message:An internal server error occurred, please contact the system administrator reason:Unable to initialize OpenID Connect Provider: Get "https://accounts.google.com/.well-known/openid-configuration": context canceled status:Internal Server Error status_code:500 trace:
github.com/ory/kratos/selfservice/strategy/oidc.(*ProviderGenericOIDC).provider
        /home/ory/selfservice/strategy/oidc/provider_generic_oidc.go:42
github.com/ory/kratos/selfservice/strategy/oidc.(*ProviderGenericOIDC).OAuth2
        /home/ory/selfservice/strategy/oidc/provider_generic_oidc.go:65
github.com/ory/kratos/selfservice/strategy/oidc.(*Strategy).Login
        /home/ory/selfservice/strategy/oidc/strategy_login.go:150
github.com/ory/kratos/selfservice/flow/login.(*Handler).submitFlow
        /home/ory/selfservice/flow/login/handler.go:575
github.com/ory/kratos/x.NoCacheHandler.func1
        /home/ory/x/nocache.go:18
github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387
github.com/ory/nosurf.(*CSRFHandler).handleSuccess
        /go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:201
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP
        /go/pkg/mod/github.com/ory/nosurf@v1.2.5/handler.go:152
github.com/urfave/negroni.Wrap.func1
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/kratos/x.glob..func1
        /home/ory/x/clean_url.go:12
github.com/urfave/negroni.HandlerFunc.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:198
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:68
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:76
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:165
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/ory/x/prometheusx.Metrics.instrumentHandlerStatusBucket.func1
        /go/pkg/mod/github.com/ory/x@v0.0.300/prometheusx/metrics.go:107
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2046
github.com/ory/x/prometheusx.(*MetricsManager).ServeHTTP
        /go/pkg/mod/github.com/ory/x@v0.0.300/prometheusx/middleware.go:30
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/x/metricsx.(*Service).ServeHTTP
        /go/pkg/mod/github.com/ory/x@v0.0.300/metricsx/middleware.go:255
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/x/reqlog.(*Middleware).ServeHTTP
        /go/pkg/mod/github.com/ory/x@v0.0.300/reqlog/middleware.go:134] http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-GB,en-US;q=0.9,en;q=0.8 connection:keep-alive content-length:37 content-type:application/json cookie:csrf_token_806060ca5bf70dff3caa0e5c860002aade9d470a5a4dce73bcfa7ba10778f481=gLnczfj3WcDrj/4VmPwMGv1vyvoAxJjcd1k8zQDyI4U= origin:http://127.0.0.1:8080 referer:http://127.0.0.1:8080/ sec-ch-ua:"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"macOS" sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-site user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36] host:127.0.0.1:4433 method:POST path:/self-service/login query:flow=908d7fca-5401-4d84-b88a-c9fd1142ac60 remote:172.24.0.1:55922 scheme:http] http_response=map[status_code:500] service_name=Ory Kratos service_version=v0.8.0-alpha.1.pre.3
```

### Relevant configuration

```yml
version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:8080
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - "*"
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:8080/
  whitelisted_return_urls:
    - http://127.0.0.1:8080

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: ...
            client_secret: ...
            mapper_url: file:///etc/config/oidc/google/oidc.google.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name: null
                hd: null 
          - id: microsoft 
            provider: microsoft
            client_id: ... 
            client_secret: ... 
            tenant: ... 
            mapper_url: file:///etc/config/oidc/microsoft/oidc.microsoft.jsonnet
            scope:
              - profile
              - email

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:8080/verify
      after:
        default_browser_return_url: http://127.0.0.1:8080/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:8080/login

    login:
      ui_url: http://127.0.0.1:8080/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:8080/signup
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - ...

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: ...
```

### Version

v0.8.0-alpha.1.pre.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
