### ISSUE TITLE
Oathkeeper access rules appear to be missing paths to get the UI working with quickstart-oathkeeper

### ISSUE THREAD

**Issue by theotherian** [ory/kratos#2048]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The configuration at https://github.com/ory/kratos/blob/0b426d2eb2960ca20f755ee6883e344a42654f84/contrib/quickstart/oathkeeper/access-rules.yml#L29 seems to exclude paths that are used by the UI when using quickstart-oathkeeper.

I believe this:

```
id: "ory:kratos-selfservice-ui-node:anonymous"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4435"
  match:
    url: "http://127.0.0.1:4455/<{error,recovery,verify,auth/*,**.css,**.js}{/,}>"
    methods:
      - GET
```

Should have the following value for `url`:
```
id: "ory:kratos-selfservice-ui-node:anonymous"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4435"
  match:
    url: "http://127.0.0.1:4455/<{welcome,registration,login,verification,error,recovery,verify,auth/*,**.css,**.js,**.png}{/,}>"
    methods:
      - GET
```

Adding those paths locally allows me to hit the http://127.0.0.1:4455/welcome resource specified in https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/

### Reproducing the bug

I literally just used the steps in https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/ and the UI wasn't working for paths like `http://127.0.0.1:4455/welcome` which returned a `404`

```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.8.0-alpha.3
docker-compose \
  -f quickstart.yml \
  -f quickstart-oathkeeper.yml \
  up --build --force-recreate
```

### Relevant log output

```shell
oathkeeper_1                  | {"audience":"application","error":{"debug":"","message":"Requested url does not match any rules","reason":"","status":"Not Found","status_code":404},"granted":false,"http_host":"127.0.0.1:4455","http_method":"GET","http_url":"http://127.0.0.1:4455/welcome","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36","level":"warning","msg":"Access request denied","service_name":"ORY Oathkeeper","service_version":"v0.38.15-beta.1","time":"2021-12-09T21:43:40Z"}
oathkeeper_1                  | {"code":404,"debug":"","details":{},"error":"Requested url does not match any rules","level":"error","msg":"An error occurred while handling a request","reason":"","request-id":"","status":404,"time":"2021-12-09T21:43:40Z","writer":"JSON"}
```
```


### Relevant configuration

```yml
I'm using the defaults from the linked quickstart page.
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
