### ISSUE TITLE
Specify email templates as separate configuration keys

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2054]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, you can override the whole directory of where email templates are mounted from using:

```
courier:
  template_override_path: /my/path
```

The problem with this is that we cannot use any remote locations, and it's difficult to specify precedence. 

### Describe your ideal solution

Instead, it should be possible to specify for each template the location:

```
courier:
  templates:
    recovery:
      invalid:
        email:
          plaintext: # base64://, https://, file://, ...
          html: # base64://, https://, file://, ...
        # In the future maybe:
        # sms: ...
    # recovery ...
```

### Workarounds or alternatives

None so far, if you have better ideas please LMK :)

### Version

master

### Additional Context

* [ ] Write migration guide
* [ ] Write breaking changes
* [ ] Document configuration with a guide / examples
* [ ] Document how to do translations ( https://github.com/ory-corp/cloud/issues/1695 )
