### ISSUE TITLE
Sqlite tables disappear?

### ISSUE THREAD

**Issue by kszafran** [ory/kratos#2059]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello! I have a docker-compose file with Kratos and I'm running some tests against it: creating an identity, going through the recovery flow, logging in and finally deleting the identity. In general, it works. But I've already gotten this 500 error twice:
```
{"error":{"code":500,"status":"Internal Server Error","message":"sqlite create: no such table: identities: Unable to locate the table"}
```
One time I also noticed that the Kratos container just stopped (I was not running mailslurper then and failures to resolve the mailslurper address were the last logged lines. Maybe it had something to do with it?)

This seems to happen when I let the Kratos container sit in the background, while I keep writing and running tests. After I `docker compose down` and `docker compose up -d`, everything is fine again.

I imagine this might be something specific to in-memory sqlite?

### Reproducing the bug

I can't reproduce it on reliably, but here's my docker-compose.yaml for reference:
```yaml
version: "3.7"
services:
  # ...some other containers

  kratos:
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    command:
      serve -c /etc/config/kratos/kratos.yml --watch-courier --dev
    volumes:
      - type: bind
        source: cmd/server/testdata/kratos
        target: /etc/config/kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 1025:1025
      - 4436:4436
      - 4437:4437
```

### Relevant log output

```shell
time=2021-12-13T17:44:26Z level=info msg=started handling request http_request=map[headers:map[accept-encoding:gzip content-length:79 content-type:application/json user-agent:Go-http-client/1.1] host:localhost:4434 method:POST path:/identities query:<nil> remote:172.23.0.1:63382 scheme:http]
time=2021-12-13T17:44:26Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:sqlite create: no such table: identities: Unable to locate the table reason: status:Internal Server Error status_code:500] http_request=map[headers:map[accept-encoding:gzip content-length:79 content-type:application/json user-agent:Go-http-client/1.1] host:localhost:4434 method:POST path:/identities query:<nil> remote:172.23.0.1:63382 scheme:http] http_response=map[status_code:500] service_name=Ory Kratos service_version=v0.8.0-alpha.3
time=2021-12-13T17:44:26Z level=info msg=completed handling request http_request=map[headers:map[accept-encoding:gzip content-length:79 content-type:application/json user-agent:Go-http-client/1.1] host:localhost:4434 method:POST path:/identities query:<nil> remote:172.23.0.1:63382 scheme:http] http_response=map[headers:map[content-type:application/json] size:137 status:500 text_status:Internal Server Error took:15.6455ms]
```

### Relevant configuration

```yml
version: v0.8.0-alpha.3

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  whitelisted_return_urls:
    - http://localhost:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:4455/recovery

    verification:
      enabled: true
      ui_url: http://localhost:4455/verification
      after:
        default_browser_return_url: http://localhost:4455/

    logout:
      after:
        default_browser_return_url: http://localhost:4455/login

    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:4455/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  argon2:
    parallelism: 4
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 32
    dedicated_memory: 1GB

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025?skip_ssl_verify=true
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
