### ISSUE TITLE
Self-service registration sends session even without hook (but no cookie)

### ISSUE THREAD

**Issue by meyfa** [ory/kratos#2093]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have configured Kratos without the `session` after hook (so no auto-login on registration). We are working with an SPA, so the client-side browser flow, via `@ory/kratos-client` NPM package.

Now, when going through the self-service registration flow, something strange happens.
According to the documentation (https://www.ory.sh/kratos/docs/self-service/flows/user-registration#client-side-browser-clients), I would expect that no cookie is sent (which is true), but also that the response body doesn't contain a session (but it does!).

Receiving such a session object is really impractical, since our code then assumes that the user was properly authenticated, when in actuality they were not and still require an additional login. It would be better if the session were not included, unless of course the hook was set.

### Reproducing the bug

1. Configure Kratos as shown below.
2. Submit the registration flow.
3. Receive a response containing a session object.

HTTP request:

```
POST /ory/self-service/registration?flow=9c9da010-8566-478b-b802-cfa83db8a502 HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/json
Content-Length: 217
Origin: http://localhost:3000
DNT: 1
Connection: keep-alive
Referer: http://localhost:3000/register
Cookie: csrf_token_ff5bad8bbeafffd9ae62e1fa1f82e796a17d8f76ede4a9a0f18a60d4a7656de8=lqy9T2P4vYslV4f5ipLZ050wkKAASnVNUSaL5xFEA6c=; csrf_token_e3592420e7a9c304ca6b13baf80fae0f1a46d2ebe86e641d9024fe33cf554027=8tGHPAVBACvaGb3V+Jir9Xs/+0PdecurOPzX9ogc/Q4=
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-GPC: 1
```

Response (proxied through Express, but I am pretty sure this is irrelevant for whether or not the session is sent as JSON):

```
HTTP/1.1 200 OK
X-Powered-By: Express
cache-control: private, no-cache, no-store, must-revalidate
content-type: application/json; charset=utf-8
Vary: Cookie, Accept-Encoding
date: Fri, 31 Dec 2021 13:18:16 GMT
connection: close
Content-Encoding: gzip
Transfer-Encoding: chunked
```

```json
{
  "session": {
    "id": "6b1ce070-7480-4407-a7dc-d72cdc357b11",
    "active": true,
    "expires_at": "2022-01-01T13:18:16.616489075Z",
    "authenticated_at": "2021-12-31T13:18:16.616489075Z",
    "authenticator_assurance_level": "aal1",
    "authentication_methods": [
      {
        "method": "password",
        "completed_at": "2021-12-31T13:18:16.616586327Z"
      }
    ],
    "issued_at": "2021-12-31T13:18:16.616489075Z",
    "identity": {
      "id": "37d46eb5-ea9d-499a-9fef-972ee5d06412",
      "schema_id": "default",
      "schema_url": "https://kratos-5968fff7cb-w9rgj:4433/schemas/default",
      "state": "active",
      "state_changed_at": "2021-12-31T13:18:16.607440908Z",
      "traits": {
        "email": "foo@example.com"
      },
      "verifiable_addresses": [
        {
          "id": "15b6a941-554a-4032-aa21-52ad36122c7f",
          "value": "foo@example.com",
          "verified": false,
          "via": "email",
          "status": "pending",
          "created_at": "2021-12-31T13:18:16.609826Z",
          "updated_at": "2021-12-31T13:18:16.609826Z"
        }
      ],
      "recovery_addresses": [
        {
          "id": "d3726725-583f-4c86-87bd-ee1b97a042c2",
          "value": "foo@example.com",
          "via": "email",
          "created_at": "2021-12-31T13:18:16.611217Z",
          "updated_at": "2021-12-31T13:18:16.611217Z"
        }
      ],
      "created_at": "2021-12-31T13:18:16.608482Z",
      "updated_at": "2021-12-31T13:18:16.608482Z"
    }
  },
  "identity": {
    "id": "37d46eb5-ea9d-499a-9fef-972ee5d06412",
    "schema_id": "default",
    "schema_url": "https://kratos-5968fff7cb-w9rgj:4433/schemas/default",
    "state": "active",
    "state_changed_at": "2021-12-31T13:18:16.607440908Z",
    "traits": {
      "email": "foo@example.com"
    },
    "verifiable_addresses": [
      {
        "id": "15b6a941-554a-4032-aa21-52ad36122c7f",
        "value": "foo@example.com",
        "verified": false,
        "via": "email",
        "status": "pending",
        "created_at": "2021-12-31T13:18:16.609826Z",
        "updated_at": "2021-12-31T13:18:16.609826Z"
      }
    ],
    "recovery_addresses": [
      {
        "id": "d3726725-583f-4c86-87bd-ee1b97a042c2",
        "value": "foo@example.com",
        "via": "email",
        "created_at": "2021-12-31T13:18:16.611217Z",
        "updated_at": "2021-12-31T13:18:16.611217Z"
      }
    ],
    "created_at": "2021-12-31T13:18:16.608482Z",
    "updated_at": "2021-12-31T13:18:16.608482Z"
  }
}
```

### Relevant log output

```shell
time=2021-12-31T13:50:50Z level=info msg=started handling request http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate accept-language:en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3 connection:close content-length:216 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". dnt:1 origin:http://localhost:3000 referer:http://localhost:3000/register sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin sec-gpc:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] host:localhost:8080 method:POST path:/self-service/registration query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:10.244.0.1:15267 scheme:http]
time=2021-12-31T13:50:51Z level=info msg=A new identity has registered using self-service registration. audience=audit http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate accept-language:en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3 connection:close content-length:216 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". dnt:1 origin:http://localhost:3000 referer:http://localhost:3000/register sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin sec-gpc:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] host:localhost:8080 method:POST path:/self-service/registration query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:10.244.0.1:15267 scheme:http] identity_id=c84a6fbd-0d7b-4981-940a-a093c8ecdf24 service_name=Ory Kratos service_version=v0.8.0-alpha.3
time=2021-12-31T13:50:51Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate accept-language:en-US,en;q=0.8,de-DE;q=0.5,de;q=0.3 connection:close content-length:216 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". dnt:1 origin:http://localhost:3000 referer:http://localhost:3000/register sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-origin sec-gpc:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0] host:localhost:8080 method:POST path:/self-service/registration query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:10.244.0.1:15267 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate content-type:application/json; charset=utf-8 vary:Cookie] size:1852 status:200 text_status:OK took:319.640835ms]
time=2021-12-31T13:50:51Z level=info msg=started handling request http_request=map[headers:map[accept:application/json, text/plain, */* connection:close cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:axios/0.21.4] host:localhost:8080 method:GET path:/sessions/whoami query:<nil> remote:10.244.0.1:7824 scheme:http]
time=2021-12-31T13:50:51Z level=info msg=No valid session cookie found. audience=audit error=map[debug: message:request does not have a valid authentication session reason:No active session was found in this request. status:Unauthorized status_code:401] http_request=map[headers:map[accept:application/json, text/plain, */* connection:close cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:axios/0.21.4] host:localhost:8080 method:GET path:/sessions/whoami query:<nil> remote:10.244.0.1:7824 scheme:http] service_name=Ory Kratos service_version=v0.8.0-alpha.3
time=2021-12-31T13:50:51Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:The request could not be authorized reason:No valid session cookie found. status:Unauthorized status_code:401] http_request=map[headers:map[accept:application/json, text/plain, */* connection:close cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:axios/0.21.4] host:localhost:8080 method:GET path:/sessions/whoami query:<nil> remote:10.244.0.1:7824 scheme:http] http_response=map[status_code:401] service_name=Ory Kratos service_version=v0.8.0-alpha.3
time=2021-12-31T13:50:51Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json, text/plain, */* connection:close cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". user-agent:axios/0.21.4] host:localhost:8080 method:GET path:/sessions/whoami query:<nil> remote:10.244.0.1:7824 scheme:http] http_response=map[headers:map[content-type:application/json vary:Cookie] size:137 status:401 text_status:Unauthorized took:1.058182ms]
```

### Relevant configuration

```yml
dsn: postgres://kratos:PASSWORD@POSTGRES_SVC:5432/kratos
serve:
  public:
    base_url: http://localhost:3000
selfservice:
  default_browser_return_url: http://localhost:3000
identity:
  default_schema_url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9xdWlja3N0YXJ0L2VtYWlsLXBhc3N3b3JkL2lkZW50aXR5LnNjaGVtYS5qc29uIiwKICAiJHNjaGVtYSI6ICJodHRwOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LTA3L3NjaGVtYSMiLAogICJ0aXRsZSI6ICJQZXJzb24iLAogICJ0eXBlIjogIm9iamVjdCIsCiAgInByb3BlcnRpZXMiOiB7CiAgICAidHJhaXRzIjogewogICAgICAidHlwZSI6ICJvYmplY3QiLAogICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAiZW1haWwiOiB7CiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgImZvcm1hdCI6ICJlbWFpbCIsCiAgICAgICAgICAidGl0bGUiOiAiRS1NYWlsIiwKICAgICAgICAgICJtaW5MZW5ndGgiOiAzLAogICAgICAgICAgIm9yeS5zaC9rcmF0b3MiOiB7CiAgICAgICAgICAgICJjcmVkZW50aWFscyI6IHsKICAgICAgICAgICAgICAicGFzc3dvcmQiOiB7CiAgICAgICAgICAgICAgICAiaWRlbnRpZmllciI6IHRydWUKICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICJ2ZXJpZmljYXRpb24iOiB7CiAgICAgICAgICAgICAgInZpYSI6ICJlbWFpbCIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInJlY292ZXJ5IjogewogICAgICAgICAgICAgICJ2aWEiOiAiZW1haWwiCiAgICAgICAgICAgIH0KICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJuYW1lIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICJ0aXRsZSI6ICJGdWxsIG5hbWUiCiAgICAgICAgfQogICAgICB9LAogICAgICAicmVxdWlyZWQiOiBbCiAgICAgICAgImVtYWlsIgogICAgICBdLAogICAgICAiYWRkaXRpb25hbFByb3BlcnRpZXMiOiBmYWxzZQogICAgfQogIH0KfQ==
courier:
  smtp:
    connection_uri: smtp://kratos:kratos@MAIL_SVC:1025
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

I have tried to obtain a newer helm chart release, but it seems v0.8.0-alpha.3 is the newest available via `https://k8s.ory.sh/helm/charts`.

Looking at the code yielded the following insights (though I am by no means familiar with this project or even the Go programming language):

* It seems tests only cover the case where the hook is set, never where it isn't: https://github.com/ory/kratos/blob/97f646f222ffcfd98b421777414856eafaa7fb8c/selfservice/strategy/password/registration_test.go#L495
* Account enumeration prevention seems to be harmed by this as well. Again, no tests from what I can see: https://github.com/ory/kratos/blob/97f646f222ffcfd98b421777414856eafaa7fb8c/selfservice/strategy/password/registration_test.go#L535
* With the condition that this is even the correct place to look, it seems the hook logic just always responds with identity and session: https://github.com/ory/kratos/blob/97f646f222ffcfd98b421777414856eafaa7fb8c/selfservice/flow/registration/hook.go#L187

Of course it is very possible I just made a mistake configuring everything. Figuring that out would be great, too, so I'd be delighted about any push in the right direction!
