### ISSUE TITLE
`Error: unknown flag: --config` when using docker image

### ISSUE THREAD

**Issue by jazoom** [ory/kratos#2144]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm following the instructions here and I cannot get Kratos to run: https://www.ory.sh/kratos/docs/guides/docker

### Reproducing the bug

I use the following command

`docker run --rm -it -e DSN="memory" --mount type=bind,source="$(pwd)",target=/home/ory oryd/kratos:v0.8.2-alpha.1 --config /home/ory/kratos.yml`

and get the following error message

```
Error: unknown flag: --config
Usage:
  kratos [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  courier     Commands related to the Ory Kratos message courier
  hashers     This command contains helpers around hashing
  help        Help about any command
  identities  Tools to interact with remote identities
  jsonnet     Helpers for linting and formatting JSONNet code
  migrate     Various migration helpers
  remote      Helpers and management for remote Ory Kratos instances
  serve       Run the Ory Kratos server
  version     Show the build version, build time, and git hash

```

This is what the linked documentation page says:

```
Note that in both cases, you must supply the location of the configuration file using the --config flag when running the container.

$ docker run <theimage> --config /home/ory/kratos.yml
```

### Relevant configuration

```yml
version: v0.8.2-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  whitelisted_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

I can't find any mention in release notes about the `--config` flag being removed.
