### ISSUE TITLE
Email address with leading/trailing whitespace treated as different identifier

### ISSUE THREAD

**Issue by meyfa** [ory/kratos#2158]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Suppose an account exists for `"foo@example.com"`, then it is not possible to log in using `"foo@example.com "` (same string but with trailing whitespace, which often happens on mobile phones with auto-completion) or `" foo@example.com"` (leading whitespace). In both cases, the error message reads `"The provided credentials are invalid, check for spelling mistakes in your password or username, email address, or phone number."`. I think whitespace around the identifier should be ignored.

Even worse, entirely new accounts can be registered for all of the following:

```json
" foo@example.com"
"  foo@example.com"
"   foo@example.com"
```

etc.

Interestingly, trying to register an account for `"foo@example.com "` (trailing space instead of leading) will fail, as it should. The error message there reads `"\"foo@example.com \" is not valid \"email\""`.

### Reproducing the bug

Create an account for `"foo@example.com"` and verify that logging into it works, then log out again.

At this point the following things will fail, although they should succeed:

* Logging in with `"foo@example.com "`
* Logging in with `" foo@example.com"`

The following will work, although it should fail:

* Creating an account for `" foo@example.com"`

The following will correctly fail:

* Creating an account for `"foo@example.com "`

(Note that the quotation marks are not part of user input. I had to add them to deal with Markdown formatting issues.)

### Relevant configuration

```yml
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "string",
          "title": "Full name"
        }
      },
      "required": [
        "email",
        "name"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
