### ISSUE TITLE
password policy settings are rejected

### ISSUE THREAD

**Issue by fboerman** [ory/kratos#2174]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I would like to change the password policy as stated here: https://www.ory.sh/kratos/docs/next/guides/password-policy/ but these config options are rejected on startup

### Reproducing the bug

set this in config:
```
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        min_password_length: 8
        identifier_similarity_check_enabled: true

```
and start kratos. observe it doesnt start

### Relevant log output

```shell
time=2022-01-26T17:01:29Z level=debug msg=Adding config files. func=github.com/ory/x/configx.(*Provider).createProviders file=/go/pkg/mod/github.com/ory/x@v0.0.310/configx/provider.go:154 audience=application files=[/etc/config/kratos/kratos.yml] service_name=Ory Kratos service_version=v0.8.2-alpha.1

The configuration contains values or keys which are invalid:
selfservice.methods.password.config: map[haveibeenpwned_enabled:false haveibeenpwned_host:api.pwnedpasswords.com identifier_similarity_check_enabled:true ignore_network_errors:true max_breaches:0 min_password_length:8]
                                     ^-- additionalProperties "min_password_length", "identifier_similarity_check_enabled" not allowed

time=2022-01-26T17:01:29Z level=fatal msg=Unable to instantiate configuration. func=github.com/ory/kratos/driver.NewWithoutInit file=/home/ory/driver/factory.go:26 audience=application error=map[message:I[#/selfservice/methods/password/config] S[#/properties/selfservice/properties/methods/properties/password/properties/config/additionalProperties] additionalProperties "min_password_length", "identifier_similarity_check_enabled" not allowed trace:stack trace could not be recovered from error type *jsonschema.ValidationError] service_name=Ory Kratos service_version=v0.8.2-alpha.1
```
```


### Relevant configuration

```yml

methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        min_password_length: 8
        identifier_similarity_check_enabled: true
```

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
