### ISSUE TITLE
when logging in with github for first time get redirected to login with no message

### ISSUE THREAD

**Issue by fboerman** [ory/kratos#2199]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

when logging in with github for the first time to the user it seems as nothing happens. That is not true in the background I can see that a new user is successfully created. However no message is given to the user, he/she needs to click login with github again and then successfully logs in.

### Reproducing the bug

1. setup github authentication with kratos
2. login for first time with github

### Relevant configuration

```yml
methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: snip
            client_secret: snip
            mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
            scope:
              - user:email
```

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

I run podman which is functionally equivalent to docker
