### ISSUE TITLE
Clicking on an old verification link redirects you to the default return url and not the return url specified with the initial verification flow

### ISSUE THREAD

**Issue by MilesNorton** [ory/kratos#2279]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I signed up with a new account using the following queries: `return_to` and `after_verification_return_to`, which are both different to the `default_return_to` url. Once I receive the email to verify my account and clicked on the link, I get redirected to the `after_verification_return_to` url which is expected. 
Now, when I go back to my email and click on the verification email again it redirects me to the `default_return_to` url.

 
Please note I have also tested this from the normal verification service flow and it also produces the same bug which means it isn't specific to the `after_verification_return_to` url.

### Reproducing the bug

1. Set up second domain that will be used for return to url's
2. Navigate to the registration page and make sure the second domain is set as the  `return_to` and `after_verification_return_to` query params.
3. Sign up
4. Click on verification email link 
5. Click on verification email link again

### Relevant configuration

```yml
serve:
  public:
    base_url: http://localhost:4433/
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:8100
  whitelisted_return_urls:
    - http://localhost:8101/
  flows:
    registration:
      ui_url: http://localhost:8100/registration
      lifespan: 1h
      before: {}
      after:
        default_browser_return_url: http://localhost:8100
        password:
          hooks:
            - hook: session
    verification:
      ui_url: http://localhost:8100/verification
      after:
        default_browser_return_url: http://localhost:8100
      lifespan: 1h
      enabled: true
```

### Version

v0.8.2-alpha.1
