### ISSUE TITLE
submitSelfServiceLoginFlowBody and submitSelfServiceSettingsFlowBody do not include LookupMethodBody or WebAuthnMethodBody

### ISSUE THREAD

**Issue by KajsaEklof** [ory/kratos#2287]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The type `submitSelfServiceSettingsFlow` do not include the `SubmitSelfServiceSettingsFlowWithLookupMethodBody` or `SubmitSelfServiceSettingsFlowWithWebAuthnMethodBody`. Similarly for the `submitSelfServiceLoginFlow` this does not include  `SubmitSelfServiceLoginFlowWithLookupSecretMethodBody` or `SubmitSelfServiceLoginFlowWithWebAuthnMethodBody`. 

We want to make a call using `submitSelfServiceSettingsFlow` to confirm the generated recover codes when the user clicks a button in the UI.

When we call `submitSelfServiceSettingsFlow` and pass in a `SubmitSelfServiceSettingsFlowWithLookupMethodBody` we get the error:
```
Argument of type '{ csrf_token: string; method: string; lookup_secret_confirm: boolean; }' is not assignable to parameter of type 'SubmitSelfServiceSettingsFlowBody | undefined'.
  Object literal may only specify known properties, and 'lookup_secret_confirm' does not exist in type 'SubmitSelfServiceSettingsFlowBody'
```

When we look at the type `SubmitSelfServiceSettingsFlowBody` it looks like `SubmitSelfServiceSettingsFlowWithLookupMethodBody` and `SubmitSelfServiceSettingsFlowWithWebAuthnMethodBody` are missing. See below.

```
export declare type SubmitSelfServiceSettingsFlowBody = SubmitSelfServiceSettingsFlowWithOidcMethodBody | SubmitSelfServiceSettingsFlowWithPasswordMethodBody | SubmitSelfServiceSettingsFlowWithProfileMethodBody | SubmitSelfServiceSettingsFlowWithTotpMethodBody;
```

### Reproducing the bug

1. Using the Settings Flow for client-side browser clients initialise the settings flow with  `kratos.initializeSelfServiceSettingsFlowForBrowsers()`
2. Submit the settings flow with: 
```
kratos
   .submitSelfServiceSettingsFlow(this.flowId, undefined, {
      csrf_token: this.csrfToken,
      method: 'lookup',
      lookup_secret_confirm: true,
   })
```
3. All works ok but there is a type error:
```
Argument of type '{ csrf_token: string; method: string; lookup_secret_confirm: boolean; }' is not assignable to parameter of type 'SubmitSelfServiceSettingsFlowBody | undefined'.
  Object literal may only specify known properties, and 'lookup_secret_confirm' does not exist in type 'SubmitSelfServiceSettingsFlowBody'
```

### Relevant configuration

```yml
selfservice:
  default_browser_return_url: http://127.0.0.1:8084/
  whitelisted_return_urls:
    - http://127.0.0.1:8084

  methods:
    profile:
      enabled: true
    password:
      enabled: true
    link:
      enabled: true
      config:
        lifespan: 15m
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: [REDACTED]
            client_secret: [REDACTED]
            mapper_url: file:///etc/config/kratos/oidc.github.jsonnet
            scope:
              - user:email
          - id: google
            provider: google
            client_id: [REDACTED
            client_secret: [REDACTED]
            mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name: null
                hd: null # If you want the G Suite domain
    totp:
      enabled: true
      config:
        issuer: Comnoco.io
    lookup_secret:
      enabled: true
```

### Version

0.8.2-alpha.1

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Docker Compose
