### ISSUE TITLE
After registration hook does not cancel user creation

### ISSUE THREAD

**Issue by lbanders** [ory/kratos#2289]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I use the after web_hook to cancel a user registration if the user is not allowed to create himself in the system.

From my frontends point of the view the call seems to fail, but the user is still created in Kratos and the verification email is sent.

I had expected the account not to be created.
I read in the documentation about pre persisting hooks, but I do not see anything about using those anywhere.

### Reproducing the bug

1. Setup a registration after hook
2. Fail the call
3. Observe that user is still created in the database

### Relevant configuration

```yml
registration:
      lifespan: 10m
      ui_url: http://client.local/registration
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://api.local/hooks/can_register_account
                method: POST
                body: file:///hookfiles/can_register_account.jsonnet
                auth:
                  type: api_key
                  config:
                    name: x-api-key
                    value: mysecretapikey
                    in: header
```

### Version

0.8.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

As a workaround I tried to delete the account from hook, but the email is still sent.
