### ISSUE TITLE
docs: how to set environment variables for the new IDENTITY_SCHEMAS

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#2361]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).

### Describe the bug

I'm upgrading from v0.8.0 to v0.9.0 and I cannot figure from docs how to set environment variables for the new `IDENTITY_SCHEMAS`.

With v0.8.0 I was using: `IDENTITY_DEFAULT_SCHEMA_URL=file://auth/config/identity.schema.json`.

Now what? I need to serialize the below list as string, but how?

```yml
identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file://auth/config/identity.schema.json
```

### Version

0.9.0-alpha.3
