### ISSUE TITLE
Recovery flow redirect after success not working as expected 

### ISSUE THREAD

**Issue by AlexandreBrg** [ory/kratos#2371]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

On a self-service instance of Kratos, using [http redirects](https://www.ory.sh/docs/kratos/concepts/browser-redirect-flow-completion), we can add `selfservice.flows.<login[registration|recovery...>.after.default_browser_return_url` to redirect the user after completing a flow. It works properly for flows like `login` or `registration` but doesn't for `recovery` flow. 

As explained in [documentation](https://www.ory.sh/docs/kratos/self-service/flows/account-recovery#successful-recovery), a successful recovery does a HTTP 303 redirect to a settings flow, however we can't override it.

### Reproducing the bug

1. Update your kratos configuration file with after keyword: 

```
selfservice:
   ...
   flows:
      ....
       recovery:
           enabled: true
           ui_url: ${kratos_ui_recovery}
           after:
               default_browser_return_url: ${kratos_ui_recovery_redirect}
      settings:
         ui_url: ${kratos_ui_settings}
```

2. Run a Kratos self-service instance with this configuration
3. Register yourself & request a password recovery 
4. When clicking mail link to recover password, you'll be redirected to `${kratos_ui_settings}` instead of `${kratos_ui_recovery_redirect}` 

### Relevant configuration

```yml
version: v0.8.0-alpha.3

dsn: memory

cookies:
  domain: localhost
  path: /
  same_site: None

serve:
  public:
    base_url: http://localhost:4433
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost
        - http://127.0.0.1:4455
        - http://localhost:4455
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Content-Type
        - Authorization
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      #options_passthrough: true
      debug: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/u/dashboard
  whitelisted_return_urls:
    - http://localhost:3000
    - http://localhost:4455

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: gitlab 
            provider: gitlab
            client_id: redacted
            client_secret: redacted
            mapper_url: file:///etc/config/kratos/oidc.gitlab.jsonnet
            scope:
              - api
              - openid
              - email


  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:3000/settingss
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery
      after:
        default_browser_return_url: http://localhost:3000/u/mysupertest

    verification:
      enabled: true
      ui_url: http://localhost:3000/u/verify 
      after:
        default_browser_return_url: http://localhost:4455/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/u/signin

    login:
      ui_url: http://localhost:3000/u/signin
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/u/signup
      after:
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE #TODO
  default:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  schemas:
    - id: default_identity
      url: file:///etc/config/kratos/identity.schema.json
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

Kratos version is `v0.8.0-alpha.3`, but after discussing with David Alexandre on [Slack](https://ory-community.slack.com/archives/C012RJ2MQ1H/p1649158475721149), it is the same on latest version.
