### ISSUE TITLE
Admin API identity update invalidates recovery link

### ISSUE THREAD

**Issue by martynas-openg** [ory/kratos#2433]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] #2646

### Describe the bug

Hey,

I encountered a problem: when an identity gets updated (via admin endpoint) during account recovery,
the recovery flow get invalidated. Is this working as expected?

### Reproducing the bug

1. Create an identity via admin endpoint
2. Initiate self service recovery flow so an email with recovery link gets sent out
3. Update same identity via admin endpoint with no changes (same traits, state == active, same schema)
4. Follow the recovery link received in email
5. Get a flow response that the recovery token is invalid

### Relevant configuration

```yml
identity schema:

{
  "$id": "identity0",
  "title": "Test",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            },
            "verification": {
              "via": "email"
            }
          }
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

If there is no identity update via admin endpoint between the recovery link getting sent out and clicked, the whole recovery and password reset flow works correctly.

If this is a problem because the admin endpoint updates the whole identity, maybe the recovery link could stay valid if there are no changes in the update.
