### ISSUE TITLE
Different Email templates based on identity traits (created_at and updated_at are always the same)

### ISSUE THREAD

**Issue by Quasarman** [ory/kratos#2480]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

As mentioned in this discussion: https://github.com/ory/kratos/discussions/2061 I hoped to have different email templates (supported with advanced email templates in >= v0.8) based on the state of the `Identity`. Foremost I wanted to display a "welcome message" when a user first registered and some sort of "email changed" message when the user decides to change their email address and receive the verification link again. As suggested in the discussion by @vinckr I tried the following:

```
{{- if eq .Identity.created_at .Identity.updated_at -}}
  <h1>Welcome</h1>
{{- else -}}
  <h1>Email Changed</h1>
{{- end -}}
```

I noticed that this always results in the first block being displayed even when changing the email address (multiple times). Then I had a look at the identity object and noticed no matter how often I would change the email address the `created_at` and `updated_at` fields always stayed the same.

### Reproducing the bug

1. Spin up a kratos version >= 0.8 (I used v0.8.2-alpha.1)
2. Configure at least the email trait as a credential password identifier (see configuration below)
3. Provide a simple email template that has the condition I showed above
4. Register a new Identity
5. Check if the welcome message is displayed in the email
6. Try to change the email
7. The welcome message will still be displayed in the email

Expected behavior would be that the email contains the "email changed" message.

### Relevant configuration

```yml
{
        "$id": "user.v1",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "User (v1)",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "minLength": 3,
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "verification": {
                    "via": "email"
                  },
                  "recovery": {
                    "via": "email"
                  }
                }
              },
              "username": {
                "type": "string",
                "title": "Username",
                "pattern": "^[0-9\\._\\-]*[a-z]{3}[a-z0-9\\._\\-]*$",
                "minLength": 3,
                "maxLength": 30,
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  }
                }
              },
              "first_name": {
                "type": "string",
                "title": "First Name",
                "minLength": 2,
                "maxLength": 30
              },
              "last_name": {
                "type": "string",
                "title": "Last Name",
                "minLength": 2,
                "maxLength": 30
              },
              "birthday": {
                "type": "string",
                "title": "Birthday",
                "format": "date"
              }
            },
            "required": [
              "email",
              "username",
              "tos_accepted"
            ],
            "additionalProperties": false
          }
        }
      }
```

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

I only mentioned the usage for `created_at` and `updated_at` inside email templates but I think this issue goes beyond a stylistic improvement.
