### ISSUE TITLE
Default email templates as well as custom ones add '\n' at the end of subject

### ISSUE THREAD

**Issue by alexeevaDariaIDT** [ory/kratos#2491]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I was testing out "recovery flow" and noticed how valid and invalid 'recovery' emails get a '\n' at the end of the message subject.

### Reproducing the bug

1. Spin up a kratos version v0.9.0-alpha.2
2. Enable verification via email
3. Go to the /recovery page and pass the email
4. Get the to the sent message, it will have an **Account access attempted\n** as subject

I'd expect the default and templated version of the mail to not add an extra symbol in the message subject.
<img width="414" alt="Screen Shot 2022-05-27 at 18 02 23" src="https://user-images.githubusercontent.com/60876391/170726788-3b7d94a8-3591-482b-834c-adda4c037131.png">

### Relevant log output

```shell
{"audience":"application","file":"/project/courier/smtp.go:189","func":"github.com/ory/kratos/courier.(*courier).dispatchEmail","level":"debug","message_id":"713cf496-2a8f-4011-8960-50f1502283eb","m │
│ essage_subject":"Account access attempted\n","message_template_type":"recovery_invalid","message_type":1,"msg":"Courier sent out message.","service_name":"Ory Kratos","service_version":"v0.9.0-alpha │
│ .2","time":"2022-05-27T14:44:24Z"}                                                                                                                                                                     │
│ {"audience":"application","file":"/project/courier/courier_dispatcher.go:37","func":"github.com/ory/kratos/courier.(*courier).DispatchMessage","level":"debug","message_id":"713cf496-2a8f-4011-8960-5 │
│ 0f1502283eb","message_subject":"Account access attempted\n","message_template_type":"recovery_invalid","message_type":1,"msg":"Courier sent out message.","service_name":"Ory Kratos","service_version │
│ ":"v0.9.0-alpha.2","time":"2022-05-27T14:44:24Z"}
```

### Relevant configuration

```yml
{
                "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
                "$schema": "http://json-schema.org/draft-07/schema#",
                "title": "Person",
                "type": "object",
                "properties": {
                  "traits": {
                    "type": "object",
                    "properties": {
                      "email": {
                        "type": "string",
                        "format": "email",
                        "title": "E-Mail",
                        "minLength": 3,
                        "ory.sh/kratos": {
                          "credentials": {
                            "password": {
                              "identifier": true
                            }
                          },
                          "verification": {
                            "via": "email"
                          },
                          "recovery": {
                            "via": "email"
                          }
                        }
                      },
                      "name": {
                        "type": "object",
                        "properties": {
                          "first": {
                            "title": "First Name",
                            "type": "string"
                          },
                          "last": {
                            "title": "Last Name",
                            "type": "string"
                          }
                        }
                      }
                    },
                    "required": [
                      "email"
                    ],
                    "additionalProperties": false
                  }
                }
              }
```

### Version

v0.9.0-alpha.2

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm
