### ISSUE TITLE
The Refresh and Extend Sessions Don't Work

### ISSUE THREAD

**Issue by Answerlord** [ory/kratos#2495]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I use the method that "PATCH https://{your-project-slug-here}.projects.oryapis.com/admin/sessions/{id}/refresh
Authorization: Bearer {your-personal-access-token}" according to the [https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions](url).
And i'd set the Authorization but it  shows that 403 security_csrf_violation

### Reproducing the bug

1. run kratos serve according to the quick-start
2. I create an HttpRequest in my goland project and set the Authorization in HttpRequest-Header
3. send the request

here are my codes
```
        url := fmt.Sprintf("MyKratosHost/admin/sessions/%v/refresh", SessionId)
	extendSessionRequest, _ := http.NewRequest(http.MethodPatch, url, nil)
	extendSessionRequest.Header.Set("Authorization", "Bearer "+SessionToken)
		client := &http.Client{}
	response, _ := client.Do(extendSessionRequest)
```

### Relevant log output

```shell
"error": {
        "id": "security_csrf_violation",
        "code": 403,
        "status": "Forbidden",
        "reason": "Please retry the flow and optionally clear your cookies. The request was 
        rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account 
        takeover, leaking personal information, and other serious security issues.",
        "details": {
            "docs": "https://www.ory.sh/kratos/docs/debug/csrf",
            "hint": "The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token).",
            "reject_reason": "The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow."
        },
        "message": "the request was rejected to protect you from Cross-Site-Request-Forgery"
    }
```

### Relevant configuration

```yml
{
                "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
                "$schema": "http://json-schema.org/draft-07/schema#",
                "title": "Person",
                "type": "object",
                "properties": {
                  "traits": {
                    "type": "object",
                    "properties": {
                      "email": {
                        "type": "string",
                        "format": "email",
                        "title": "E-Mail",
                        "minLength": 3,
                        "ory.sh/kratos": {
                          "credentials": {
                            "password": {
                              "identifier": true
                            }
                          },
                          "verification": {
                            "via": "email"
                          },
                          "recovery": {
                            "via": "email"
                          }
                        }
                      },
                      "name": {
                        "type": "object",
                        "properties": {
                          "first": {
                            "title": "First Name",
                            "type": "string"
                          },
                          "last": {
                            "title": "Last Name",
                            "type": "string"
                          }
                        }
                      }
                    },
                    "required": [
                      "email"
                    ],
                    "additionalProperties": false
                  }
                }
              }
```

### Version

v0.9.0-alpha.2

### Additional Context

NoResponse
