### ISSUE TITLE
Docker Image Healthcheck

### ISSUE THREAD

**Issue by halvardssm** [ory/kratos#2524]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I want to use dependency management with my Docker Compose setup, but I have to add the health check clause myself in the compose file, or extend the base Kratos image.

### Describe your ideal solution

I would like the health check to be included in the docker image so that I don't have to add it manually.

This line can be added to the bottom of the docker files:

```
HEALTHCHECK --interval=10s --timeout=10s --start-period=10s --retries=3 CMD curl -m 5 --silent --fail --request GET http://localhost:4433/health/ready
```

### Workarounds or alternatives

- Extend the Kratos base image
- Add the health check clause to the compose file

### Version

0.10.0

**Comment by aeneasr** [comment]
Since deployment environments as well as start up requirements vary a lot, I don't think this belongs into the main file. It's relatively trivial to add health checks to any platform (k8s, swarm, ...) so closing as wontfix

**Comment by muya** [comment]
For anyone interested, this `healthcheck` configuration is working well in a docker-compose file:

```yml
  kratos:
    ... # other configs
    healthcheck:
      test: ["CMD", "kratos", "remote",  "status", "-e",  "http://localhost:4434"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
```
