### ISSUE TITLE
Sign in with Apple ID - unsupported protocol scheme.

### ISSUE THREAD

**Issue by Urbansson** [ory/kratos#2558]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When configuring sign in with apple as described in the [documentation](https://www.ory.sh/docs/guides/social-signin/apple) you will encounter the following trying to authenticate with apple ID:
```
authentication_error
Unable to initialize OpenID Connect Provider: Get "/.well-known/openid-configuration": unsupported protocol scheme ""
```

### Reproducing the bug

Following the official documentation will result in this error https://www.ory.sh/docs/guides/social-signin/apple.

### Relevant configuration

```yml
---
id: apple
provider: apple
client_id: redacted
apple_team_id: redacted
apple_private_key_id: redacted
apple_private_key: |
  -----BEGIN PRIVATE KEY-----
  redacted
  -----END PRIVATE KEY-----
mapper_url: redacted
scope:
- email
- name
- openid
requested_claims:
  id_token:
    email:
      essential: true
    email_verified:
      essential: true
```

### Version

v0.10.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

### Additional Context

Adding: `"issuer_url": "https://appleid.apple.com"` to the provider config solves the problem. But it should not be needed when using a existing provider and not a generic one.
