### ISSUE TITLE
Global hook ordering

### ISSUE THREAD

**Issue by Sytten** [ory/kratos#2567]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

This is related to https://github.com/ory/kratos/issues/2377

Currently when using `global` hooks, it is not possible to order them correctly with `method` hooks.
This is problematic since the session hook will abort the flow early.

### Describe your ideal solution

The general way of solving that is allow the user to assign an ordering number to each item instead of relying on the array order. It could look like:
```yaml
password:
  hooks:
    - hook: session
      config:
        order: 100
oidc:
  hooks:
    - hook: session
      config:
        order: 100
hooks:
  - hook: web_hook
    config:
      order: 10
      url: http://host.docker.internal:6000/webhook/kratos/registration
      method: POST
      body: file:///etc/config/kratos/webhooks/registration.jsonnet
```

For backward compatibility, the `method` array ordering would be mapped to `1,2,3` and the `global` array ordering would be mapped to `1001, 1002, 1003` (just to be sure they are after).

This method is very flexible and allows for more complex flows down the line . For example a `jsonnet` hook that does some computation and sets the next order to skip/perform some more hooks.

### Workarounds or alternatives

Right now you have to copy the hook to both `method` hooks for it to work.

### Version

0.10.1
