### ISSUE TITLE
Hook Get \"http://127.0.0.1:3222/hook\": dial tcp 127.0.0.1:3222: connect: connection refused

### ISSUE THREAD

**Issue by LukaJaj** [ory/kratos#2587]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I cloned quickstart project and modified kratos.yml file to call external service (which just returns ok) before registration.
this external service exposed on http://127.0.0.1:3222/hook endpoint. 

When I go to Sign Up page I get this error :   "message": "GET http://127.0.0.1:3222/hook giving up after 3 attempt(s): Get \"http://127.0.0.1:3222/hook\": dial tcp 127.0.0.1:3222: connect: connection refused"

my kratos.yml file:

```yml
version: v0.7.1-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://127.0.0.1:3222
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  allowed_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m
    
    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      before:
        hooks:
          - hook: web_hook
            config: 
              url: http://127.0.0.1:3222/hook
              method: GET
              body: file:///etc/config/kratos/body.jsonnet




log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

```

my external service 
```golang

package main

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

func main() {

	e := echo.New()
	e.Use(middleware.CORS())

	e.GET("/hook", hello)

	e.Logger.Fatal(e.Start(":3222"))

}

func hello(ctx echo.Context) error {
	fmt.Println("received")
	return ctx.JSON(http.StatusOK, nil)
}


```

### Reproducing the bug

1. modify kratos/contrib/quickstart/email-password/kratos.yml with this config:
``` 
registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      before:
        hooks:
          - hook: web_hook
            config: 
              url: http://127.0.0.1:3222/hook
              method: GET
              body: file:///etc/config/kratos/body.jsonnet
```
2. create external service 
3. run docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate

### Version

v0.7.1-alpha.1

### On which operating system are you observing this issue?

macOS
