### ISSUE TITLE
Unable to change the SameSite cookie value in kratos.yaml

### ISSUE THREAD

**Issue by gradinarot** [ory/kratos#2617]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm unable to change the same_site value. No matter what I do in the kratos.yaml config file the SameSite cookie value is `Lax` and 'None' for the session cookie.

### Reproducing the bug

Use docker compose to run kratos.

### Relevant configuration

```yml
...
cookies:
  domain: kupon.local
  same_site: Strict

session:
  cookie:
    domain: kupon.local
    same_site: Strict
...
```

### Version

0.10.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

### Additional Context

docker_compose file

```
  kratos:
    image: oryd/kratos:v0.10.1
    depends_on:
      - kratos-migrate
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://${Some_DB_USER}:${Some_DB_PASSWORD}@Some-postgres:5432/kratosdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=debug
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./.config/kratos/email-password
        target: /etc/config/kratos
    networks:
      - Some_intranet

```
