### ISSUE TITLE
Can not pass JSON to environment variable

### ISSUE THREAD

**Issue by halvardssm** [ory/kratos#2659]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi! I am trying to overwrite the Kratos config file, specifically the self-service-registration-hooks-flow by providing the `SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS` environment variable, however, I only get errors when providing an array in JSON format as specified [here](https://www.ory.sh/docs/ecosystem/configuring#loading-configuration-from-environment-variables).

### Reproducing the bug

I have tried multiple versions of the env var, but neither of them works, here are all the versions I have tried (with and without quotes `'`):

```
SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS='[{}]'
SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS='[]'
SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS='[{"hook":"session"}]'
```

### Relevant log output

```shell
No matter what I try, I always get an error similar to this:


The configuration contains values or keys which are invalid:
selfservice.flows.registration.after: map[password:map[hooks:[{"hook":"sessions"}]]]
                                      ^-- doesn't validate with "#/definitions/selfServiceAfterRegistration"

The configuration contains values or keys which are invalid:
selfservice.flows.registration.after.password: map[hooks:[{"hook":"sessions"}]]
                                               ^-- doesn't validate with "#/definitions/selfServiceAfterRegistrationMethod"

The configuration contains values or keys which are invalid:
selfservice.flows.registration.after.password.hooks: [{"hook":"sessions"}]
                                                     ^-- expected array, but got string
```
```


### Relevant configuration

```yml
selfservice:
  flows:
    registration:
      lifespan: 10m
      ui_url: https://localhost:3000/register
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: https://localhost:3001/create-user
                method: POST
                body: file:///post-registration-hook.jsonnet
```

### Version

0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
