### ISSUE TITLE
Can't use env var to set hook url

### ISSUE THREAD

**Issue by auctumnus** [ory/kratos#2663]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello! As in #2625 I've tried to convert this:
```yaml
selfservice:
  flows:
    registration:
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://example.com/hooks/kratos/before_registration
```
into an env var `SELFSERVICE_FLOWS_REGISTRATION_BEFORE_HOOKS_0_CONFIG_URL`, but the URL doesn't get applied. (At the request of @vinckr I've made this into an issue.)

### Reproducing the bug

1. Set up hooks.
2. Attempt to override one with an environment variable.
3. Cause the hook to be triggered.
4. The hook will use the value from the config, not the environment.

### Version

Latest Docker image
