### ISSUE TITLE
Jaeger Tracing configuration not working

### ISSUE THREAD

**Issue by supercairos** [ory/kratos#2673]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

According to the documentation, Jaeger config should be able to select a propagation format and some sampling informations. (https://www.ory.sh/docs/kratos/reference/configuration)

But if you add these to your configuration, you will get an error telling you that those keys are forbiden... :(

Keys that are'nt allowed:

- tracing.providers.jaeger.propagation
- tracing.providers.jaeger.sampling.type
- tracing.providers.jaeger.sampling.value

### Reproducing the bug

Just add the configuration bellow and you will see the keys are not allowed. (No need to setup a Jaeger collector)

### Relevant log output

```shell
The configuration contains values or keys which are invalid:
tracing: map[provider:jaeger providers:map[jaeger:map[local_agent_address:jaeger-tracing-agent.monitoring:6831 propagation:b3 sampling:map[server_url:http://jaeger-tracing-agent.monitoring:5778/sampling]]] service_name:Ory Kratos]
         ^-- doesn't validate with "ory://tracing-config#"

The configuration contains values or keys which are invalid:
tracing.providers.jaeger: map[local_agent_address:jaeger-tracing-agent.monitoring:6831 propagation:b3 sampling:map[server_url:http://jaeger-tracing-agent.monitoring:5778/sampling]]
                          ^-- additionalProperties "propagation" not allowed

time=2022-08-16T09:11:00Z level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:I[#/tracing] S[#/properties/tracing/$ref] doesn't validate with "ory://tracing-config#"
  I[#/tracing/providers/jaeger] S[#/properties/providers/properties/jaeger/additionalProperties] additionalProperties "propagation" not allowed] service_name=Ory Kratos service_version=v0.10.1
```

### Relevant configuration

```yml
tracing:
  service_name: Ory Kratos
  providers:
    jaeger:
        propagation: b3
        sampling:
          type: const
          value: 1
          server_url: http://jaeger-tracing-agent.monitoring:5778/sampling
        local_agent_address: jaeger-tracing-agent.monitoring:6831
  provider: jaeger
```

### Version

0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by supercairos** [comment]
It seams that setting the ENV variables works:
```
TRACING_PROVIDERS_JAEGER_PROPAGATION=b3
TRACING_PROVIDERS_JAEGER_SAMPLING_TYPE=const
TRACING_PROVIDERS_JAEGER_SAMPLING_VALUE=1
```

**Comment by supercairos** [comment]
Any news on this ?

**Comment by aeneasr** [comment]
@icyphox could you PTAL?

**Comment by icyphox** [comment]
Hi there @supercairos, we've [changed the schema](https://github.com/ory/x/blob/master/otelx/config.schema.json) for tracing configuration in our [recent switch to OpenTelemetry](url) for tracing and those fields are no longer valid. Setting them as env vars works because the invalid ones are simply ignored. :)
You can try this config:
```yaml
tracing:
  service_name: Ory Kratos
  providers:
    jaeger:
        sampling:
          server_url: http://jaeger-tracing-agent.monitoring:5778/sampling
        local_agent_address: jaeger-tracing-agent.monitoring:6831
  provider: jaeger
```
Unfortunately, OpenTelemetry doesn't allow you to configure the sampling ratio directly for Jaeger—you will have to set that in your remote sampling configuration. Hope that helps!

**Comment by supercairos** [comment]
Hi, 

About the sampling, there is no problem about setting it on Jaeger side.
But for some legacy reason we're using the Zipkin span format (B3) and this needs to be setup from Kratos side 

Do you know how I can archive this using the Kratos config file ?
Previouly the key was named: `propagation: b3`

Thanks!

**Comment by adgang** [comment]
Looks like this is the best way to get the otel based jaeger backend working. Considering that jaeger is supporting [OTLP](https://www.jaegertracing.io/docs/1.39/client-libraries/#deprecating-jaeger-clients) as primary protocol, this seems to be future-proof as well. Make sure that otlp is enabled in your jaeger instance. The following works with the jaeger all-in-one docker image for example:
```
tracing:
  
  service_name: Ory Kratos

  providers:
    otlp:
      server_url: localhost:4318
      insecure: true
      sampling:
        sampling_ratio: 1
  provider: otel
```
