### ISSUE TITLE
can't write a proper config

### ISSUE THREAD

**Issue by DanteTheCreator** [ory/kratos#2707]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have a Next.js app that I have connected to kratos running on docker. I did not have the issues before, but after messing around in the config, I am getting all kinds of errors and it seems like I can't go back to the way it was.

It's giving me a network error as soon as the site loads, after that a few CORS errors and I am unable to do anything on the website. I have my config below, it is probably the problem, however, I could not find any sort of documentation about how to write that cinfig file.

### Reproducing the bug

1. Run kratos in docker on --4455
2. npm run dev --4455

### Relevant configuration

```yml
version: v0.7.1-alpha.1

dsn: memory
  
serve:
  public:
    base_url: http://localhost:4433/
    cors:
        enabled: true
        allow_credentials: true
        allowed_origins:
          - 'https://localhost:4455/'
          - 'https://localhost:3000/'
        allowed_methods:
          - POST
          - GET
          - PUT
          - PATCH
          - DELETE
        allowed_headers:
          - Authorization
          - Cookie
          - Content-Type
        exposed_headers:
          - Content-Type
          - Set-Cookie
                
  admin:
    base_url: http://localhost:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000/

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
        min_password_length: 8
        identifier_similarity_check_enabled: true
    profile:
      enabled: false

  flows:
    error:
      ui_url: http://localhost:3000/error

    settings:
      ui_url: http://localhost:3000/dashboard/changePassword/
      privileged_session_max_age: 1m

    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery

    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
      after:
        default_browser_return_url: http://localhost:3000/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login

    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m
      # after:
      #   password:
      #     hooks:
      #       - hook: require_verified_address

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/onboarding/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - XRhlCxFymN8l7/JgsYujFLoytBwVtjo1rJmxpXYO5GY=
  cipher:
    - bdWyFFJmGpih5cCvOHGhCUKbe7oDsv8f

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

session:
  cookie:
    name: "sid"
```

### Version

v0.10.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

### Additional Context

I am new to this and may be asking a stupid question, but I really need help. I have been stuck on this the whole week and my team needs results.
