### ISSUE TITLE
self_service_flow_expired error when signing in with Hydra

### ISSUE THREAD

**Issue by bar-amir** [ory/kratos#2743]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Using Hydra as the OIDC provider for Kratos, when trying to sign in Kratos redirects to a "self_service_flow_expired" error. Tried this with the configurations below, and also without the hook that signs in the user after signing them up.

**Request URL:** 
https://my-host/routes/consent?consent_challenge=0a2a242606df40dd83460d85a963df3c
**Response:**
Location: https://my-host/hydra/oauth2/auth?client_id=my-client-id&consent_verifier=75f0b221f3444b769989900cedb752df&redirect_uri=https%3A%2F%2my-host%2Fkratos%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fhydra&response_type=code&scope=openid+offline&state=77ae3adc-b5f5-4c3c-a354-794255d9ccef

**Request URL:**
https://my-host/hydra/oauth2/auth?client_id=agamon&consent_verifier=75f0b221f3444b769989900cedb752df&redirect_uri=https%3A%2F%2Fmy-host%2Fkratos%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fhydra&response_type=code&scope=openid+offline&state=77ae3adc-b5f5-4c3c-a354-794255d9ccef
**Response:**
Location: https://my-host/kratos/self-service/methods/oidc/callback/hydra?code=Ztx2M-Zlr9nR8N4opTcJNV9kfRw9oaV8xxeMogeoLEE.-CkZa9GzkIdkhNkiFenvsjIv8-lNOgoBTs-JS0uTWy4&scope=openid+offline&state=77ae3adc-b5f5-4c3c-a354-794255d9ccef

**Request URL:**
https://my-host/kratos/self-service/methods/oidc/callback/hydra?code=Ztx2M-Zlr9nR8N4opTcJNV9kfRw9oaV8xxeMogeoLEE.-CkZa9GzkIdkhNkiFenvsjIv8-lNOgoBTs-JS0uTWy4&scope=openid+offline&state=77ae3adc-b5f5-4c3c-a354-794255d9ccef
**Response:**
Location: https://my-host/error?id=459d1527-a8bf-4ebe-a2cc-47e58551c901
Set-Cookie: ory_kratos_continuity=MTY2MzgzNTIwNnxEdi1CQkFFQ180SUFBUkFCRUFBQUJQLUNBQUE9fNoE7plSjgfyAUYimULT8c1NMiFJGArXcxwwkWU6i-_X; Path=/; Expires=Sat, 22 Oct 2022 08:26:46 GMT; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax

Then the error itself:
```
curl --location --request GET 'http://localhost:4433/self-service/errors?error=459d1527-a8bf-4ebe-a2cc-47e58551c901'

{"id":"459d1527-a8bf-4ebe-a2cc-47e58551c901","error":{"id":"self_service_flow_expired","code":410,"reason":"The self-service flow expired 230.40 minutes ago, initialize a new one.","status":"Gone","message":"self-service flow expired"},"created_at":"2022-09-22T00:26:46.777804-04:00","updated_at":"2022-09-22T00:26:46.777804-04:00"}
```

1. Trying to do this several times on several days, I've noticed all error messages mention the service flow expired 230.XX minutes ago. Digits after the decimal varies, but it's always around 3.8 hours ago.
2. The self_service_flow_expired error is not specific enough to understand which flow is causing this, since this scenario involves 2 different flows - the login flow initialized seconds before signing in with Hydra, and maybe the registration flow initialized by Kratos for registering the user (not sure how it's implemented though, but I suggest differentiating the error ID of both).
3. All of my services run on the same host (Ubuntu 20.04, not inside containers), including the PostgreSQL server they're all using, so I've ruled out any time difference of 3.8 hours between services, unless Kratos is out of sync with itself.
4. Signing in an identity with a password works, and so is the other flow we're currently using ("user invite", with recovery -> (settings) -> login flow).
5. Consent endpoint is implemented in NodeJS with the Hydra SDK and seemingly works as expected. Consent is approved the the session object is passed with the claims back to Kratos.

### Reproducing the bug

1. Run Hydra and Kratos as systemd services on an Ubuntu 20.04 machine.
2. Create and implement an OAuth2 client
3. Configure Kratos to use this client as an OIDC sign in method.
4. Try to sign in with credentials approved by the client

### Relevant configuration

```yml
...

selfservice:
  default_browser_return_url: https://my-host
  allowed_return_urls: [allowed-return-urls]
  methods:
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: my-issuer
    oidc:
      enabled: true
      config:
        providers:
          - id: hydra
            provider: generic
            client_id: my-client-id
            client_secret: my-client-secret
            mapper_url: file:///opt/kratos/config/oidc.hydra.jsonnet
            issuer_url: http://localhost:4444/
            auth_url: https://my-host/hydra/oauth2/auth
            token_url: https://my-host/hydra/oauth2/token
            scope:
              - openid
              - offline

...

    login:
      ui_url: https://my-host/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://my-host/registration
      after:
        oidc:
          hooks:
            - hook: session
        password:
          hooks:
            - hook: session
```

### Version

0.10.1
