### ISSUE TITLE
Support pre-persist hook to better deal with blocking web hooks

### ISSUE THREAD

**Issue by refietlucius** [ory/kratos#2767]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

(I cloned master branch since flow interruption webhook is not released yet)
I am using flow interruption webhook for my registration flow but when flow is interrupted from external service it still creates identity in kratos database.

is there any way to prevent that? 

or is there any after registration before persisting webhook available?

### Reproducing the bug

1. clone main branch
2. build docker image out of it
3. add can_interrupt: true into kratos.yml file
4. interrupt registration flow by external service

### Version

v0.10.1

**Comment by aeneasr** [comment]
Hi, that's true, the current web hook runs after the identity is created. We will add an option to define when a hook runs (pre or post persisting) in the future!

**Comment by sthh** [comment]
If the webhook is registered for a specific credential type (e.g. `password`), the hook is currently called pre-persist and post-persist and the registration can be cancelled before an identity is created. This is kind of hacky and undocumented though.

```
flows:
          registration:
            after:
              password:
                hooks:
                  - hook: web_hook
                    config:
                      can_interrupt: true
                      url: ...
```

**Comment by aeneasr** [comment]
Yup that is correct

**Comment by sthh** [comment]
Hi @aeneasr,
would you accept a PR for this? Your PR https://github.com/ory/kratos/pull/2888 will break our flow, since we do have to check registration request pre persist but also have to update the identity meta data, which is only possible post persist.

I though about something like:

```
flows:
          registration:
            after:
              password:
                hooks:
                  - hook: web_hook
                    config:
                      url: ...
                      pre_persist: true (defaults to can_interrupt 
                      post_persist: true  (defaults to !can_interrupt)
```

If nothing is configured, this has the same behaviour as implemented in https://github.com/ory/kratos/pull/2888 but it would also allow the user to change the behaviour.

**Comment by sthh** [comment]
Ah yes thank you. I didn't think about this, because I planned it before https://github.com/ory/kratos/pull/2888/files was merged. An additional hook would provide more flexibility though. But I guess that's not worth the added complexity.

Should we clarify pre and post persist hooks in the docs? I think the concept is not explained anywhere. Maybe an additional sentence here: https://github.com/ory/docs/blob/master/docs/kratos/hooks/01_configure-hooks.mdx#flow-interrupting-webhooks I can create a PR next week if you agree.

**Comment by aeneasr** [comment]
> Should we clarify pre and post persist hooks in the docs? I think the concept is not explained anywhere. Maybe an additional sentence here: https://github.com/ory/docs/blob/master/docs/kratos/hooks/01_configure-hooks.mdx#flow-interrupting-webhooks I can create a PR next week if you agree.

That would be wonderful :)

**Comment by sthh** [comment]
@aeneasr I've created a PR https://github.com/ory/docs/pull/1142

**Comment by aeneasr** [comment]
Awesome, thank you so much!

**Comment by meysam81** [comment]
Alright, I looked through the comments on this issue, the referenced PRs, any other related issue as well as the documentations.

Here are my comments:

- [The Kratos Configuration documentation](https://www.ory.sh/docs/kratos/reference/configuration) doesn't have `response.parse` and `response.ignore`
- Neither of `response.ignore`, `response.parse` nor `can_interrupt` can in any way "interrupt" the actual persisting of a new user registration even if any of those webhooks return non-2xx (as of this date writing this comment using Kratos v1.0.0); which means there is absolutely no way to stop a registration from happening if you want certain checks to pass before that!

You need to reproduce this? Here's my demo config:

```yaml
selfservice:
...
...
...
    registration:
      before:
        hooks:
          - config:
              body: file:///etc/jsonnet/pre-registration.jsonnet
              method: POST
              response:
                ignore: true
                parse: false
              url: http://echo-server/
            hook: web_hook
      after:
        hooks:
          - config:
              body: file:///etc/jsonnet/registration.jsonnet
              method: POST
              response:
                ignore: true # working
              url: http://echo-server/ignore-true
            hook: web_hook
          - config:
              body: file:///etc/jsonnet/registration.jsonnet
              method: POST
              response:
                ignore: false # working
              url: http://echo-server/ignore-false
            hook: web_hook
          - config:
              body: file:///etc/jsonnet/registration.jsonnet
              method: POST
              response:
                parse: true # NOT working
              url: http://echo-server/parse-true
            hook: web_hook
          - config:
              body: file:///etc/jsonnet/registration.jsonnet
              method: POST
              response:
                parse: false # working
              url: http://echo-server/parse-false
            hook: web_hook
          - config:
              body: file:///etc/jsonnet/registration.jsonnet
              method: POST
              can_interrupt: true # NOT working
              url: http://echo-server/interrupt-true
            hook: web_hook
        default_browser_return_url: http://localhost:3000/verification
        oidc:
          default_browser_return_url: http://localhost:3000/
          hooks:
            - hook: session
...
...
...
```

Out of all those web-hooks, only these are actually being sent and the others are never sent at all!!!

- `ignore: true`
- `ignore: false`
- `parse: false`

And all these are just a one-way http request and if the upstream server responds with non-2xx, the Kratos will silently ignore and create the identity anyway!
