### ISSUE TITLE
Webhook error after registration leaks internal configuration

### ISSUE THREAD

**Issue by Sytten** [ory/kratos#2819]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

If the webhook fails because the target is down or not existant, it will leak the hostname and/or the DNS server IP.

### Reproducing the bug

1. Run Kratos with an invalid host with something like:
```yaml
    registration:
      lifespan: 10m
      ui_url: https://mysite.com
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://doesntexist:9000/kratos/registration
                method: POST
```
2. Try to register an account
3. Receive a 500 on the frontend with the following payload
```json
{
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "message": "POST  http://doesntexist:9000/kratos/registration giving up after 3 attempt(s): Post \"http://doesntexist:9000/kratos/registration\": dial tcp: lookup doesntexist on [DNS SERVER IP]:53: no such host"
    }
}
```

### Version

0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
