### ISSUE TITLE
Kratos Oauth2 integration in docker containers

### ISSUE THREAD

**Issue by roelvandergoot** [ory/kratos#2870]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am trying to test Kratos/Hydra integration within a docker (compose) environment, and am seeing some problems that originate on line 126 in `hydra/hydra.go`:
```go
    hlr, r, err := aa.GetLoginRequest(ctx).LoginChallenge(fmt.Sprintf("%x", hlc.UUID)).Execute()
```
This line produces the following errors in the log:
```
identity-kratos-1  | 2022/11/08 00:44:20 vvv
identity-kratos-1  | time=2022-11-08T00:44:20Z level=info msg=[DEBUG] GET http://hydra:4445/oauth2/auth/requests/login func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:20Z level=info msg=[ERR] GET http://hydra:4445/oauth2/auth/requests/login request failed: Get "http://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005": dial tcp 127.0.0.1:4445: connect: connection refused func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:20Z level=info msg=[DEBUG] GET http://hydra:4445/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005: retrying in 1s (2 left) func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:21Z level=info msg=[ERR] GET http://hydra:4445/oauth2/auth/requests/login request failed: Get "http://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005": dial tcp 127.0.0.1:4445: connect: connection refused func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:21Z level=info msg=[DEBUG] GET http://hydra:4445/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005: retrying in 2s (1 left) func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:23Z level=info msg=[ERR] GET http://hydra:4445/oauth2/auth/requests/login request failed: Get "http://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005": dial tcp 127.0.0.1:4445: connect: connection refused func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | 2022/11/08 00:44:23 ^^^
```

Most interestingly, request `http://hydra:4445/oauth2/auth/requests/login` gets "forwarded" to `http://localhost:4445/admin/oauth2/auth/requests/login`. Of course, `localhost:4445` does not exist in the Kratos docker container.

Is there an environment variable that I have to set in the kratos service of my `docker-compose.yaml` file? Or am I missing a setting in my `kratos.yml` file?

Let me know if I have to provide my `docker-compose.yaml` plus related files.

### Reproducing the bug

Complicated...

### Relevant log output

```shell
identity-kratos-1  | 2022/11/08 00:44:20 vvv
identity-kratos-1  | time=2022-11-08T00:44:20Z level=info msg=[DEBUG] GET http://hydra:4445/oauth2/auth/requests/login func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:20Z level=info msg=[ERR] GET http://hydra:4445/oauth2/auth/requests/login request failed: Get "http://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005": dial tcp 127.0.0.1:4445: connect: connection refused func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:20Z level=info msg=[DEBUG] GET http://hydra:4445/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005: retrying in 1s (2 left) func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:21Z level=info msg=[ERR] GET http://hydra:4445/oauth2/auth/requests/login request failed: Get "http://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005": dial tcp 127.0.0.1:4445: connect: connection refused func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:21Z level=info msg=[DEBUG] GET http://hydra:4445/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005: retrying in 2s (1 left) func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | time=2022-11-08T00:44:23Z level=info msg=[ERR] GET http://hydra:4445/oauth2/auth/requests/login request failed: Get "http://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=554eebae1a6641f8a4f87f7913cab005": dial tcp 127.0.0.1:4445: connect: connection refused func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.496-0.20221027133513-e86fadee7d2e/logrusx/helper.go:118 audience=application service_name=Ory Kratos service_version=
identity-kratos-1  | 2022/11/08 00:44:23 ^^^
```

### Relevant configuration

```yml
---
oauth2_provider:
  url: "http://hydra:4445"

serve:
  public:
    base_url: https://thermalidentity.com/

selfservice:
  default_browser_return_url: https://thermalidentity.com/ui/
  methods:
    oidc:
      enabled: true
      config:
        providers:
          - id: hydra
            label: Ory
            provider: generic
            client_id: kratos-client
            client_secret: kratos-secret
            issuer_url: http://hydra:4444/
            scope:
              - offline_access
            mapper_url: file://config/kratos/hydra.jsonnet

  flows:
    settings:
      privileged_session_max_age: 5m
      ui_url: https://thermalidentity.com/ui/settings

    logout:
      after:
        default_browser_return_url: https://thermalidentity.com/self-service/login

    registration:
      ui_url: https://thermalidentity.com/ui/registration
      after:
        oidc:
          hooks:
            - hook: session
        password:
          hooks:
            - hook: session

    login:
      ui_url: https://thermalidentity.com/ui/login

    error:
      ui_url: https://thermalidentity.com/ui/errors

    verification:
      ui_url: https://thermalidentity.com/ui/verify

    recovery:
      ui_url: https://thermalidentity.com/ui/recovery

hashers:
  algorithm: argon2
  argon2:
    memory: 1KB
    iterations: 1
    parallelism: 1

courier:
  smtp:
    connection_uri: smtps://test:test@localhost:1025/?skip_ssl_verify=true

identity:
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.traits.schema.json

secrets:
  cipher:
    - secret-thrity-two-character-long
```

### Version

Latest git repositories

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

oryd/hydra:v2.0.1
