### ISSUE TITLE
additionalProperties "code" not allowed

### ISSUE THREAD

**Issue by 8thblock** [ory/kratos#2880]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When following your docs to configure "code" type of recovery Kratos fails with the error saying that "code" is not allowed. Is there anything missing or is this feature not in the latest released version v0.10.1?

### Reproducing the bug

1. Get latest HELM
2. Use simple identity as in your docs and sample config
3. In the config enable: selfservice.methods.code as per your docs
4. Deploy helm

### Relevant log output

```shell
The configuration contains values or keys which are invalid:
selfservice.methods: map[code:map[config:map[lifespan:15m] enabled:true] link:map[config:map[lifespan:1h] enabled:true] lookup_secret:map[enabled:true] oidc:map[enabled:false] password:map[config:map[haveibeenpwned_enabled:true haveibeenpwned_host:api.pwnedpasswords.com identifier_similarity_check_enabled:true ignore_network_errors:true max_breaches:0 min_password_length:8] enabled:true] profile:map[enabled:true] totp:map[config:map[issuer:toggleblock.local:4200] enabled:true] webauthn:map[config:map[rp:map[display_name:www.toggleblock.local:4200 id:www.toggleblock.local origin:https://www.toggleblock.local:4200]] enabled:true]]
                     ^-- additionalProperties "code" not allowed

time=2022-11-09T12:55:23Z level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:I[#/selfservice/methods] S[#/properties/selfservice/properties/methods/additionalProperties] additionalProperties "code" not allowed] service_name=Ory Kratos service_version=v0.10.1
```

### Relevant configuration

```yml
kratos:
  config:
    selfservice:
      methods:
        code:
          enabled: true
          config:
            lifespan: 15m
```

### Version

v0.10.1

### In which environment are you deploying?

Kubernetes with Helm

**Comment by 8thblock** [comment]
Everything get deployed just fine if I remove the above section

**Comment by 8thblock** [comment]
anyone at all? :-)

**Comment by 8thblock** [comment]
Thank you. I shall wait :-)

**Comment by aeneasr** [comment]
:)

**Comment by 8thblock** [comment]
PS. I still owe you a promised Angular sample

**Comment by LukaGiorgadze** [comment]
@aeneasr I'm experiencing the same issue.
I enabled the code using helm config, but getting `additionalProperties "code" not allowed` in kratos courier service.
If I remove `"code": {..}` field from the below schema, then deployment works.

```yaml
{
  "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
  "title": "Identity",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              },
              "webauthn": {
                "identifier": true
              },
              "totp": {
                "account_name": true
              },
              "code": {
                "identifier": true,
                "via": "email"
              }
            },
            "recovery": {
              "via": "email"
            },
            "verification": {
              "via": "email"
            }
          },
          "maxLength": 300
        }
      },
      "required": ["email"],
      "additionalProperties": false
    }
  }
}

```
