### ISSUE TITLE
Invalid traits picked up during registration flow with OIDC

### ISSUE THREAD

**Issue by abhi204** [ory/kratos#2885]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

With the OIDC method enabled, when I fill in the registration form details but click on the google OIDC button, although I am registered through the google sign-in. The identity traits are picked up from the registration form data instead of google (including the email)

### Reproducing the bug

Steps to reproduce the bug

- enable Google OIDC self-service method in the configuration file.
- In the registration page template make every input field optional (So that the form submission can be done even without filling the complete registration form)
- start the Kratos service
- Open the registration page and fill out the form (just the trait fields). Instead of clicking the 'Sign up' button click the 'Sign up with google' button
- complete the google login
- now the user registration is complete but the values filled in the registration form page overrides the traits provided by google.

### Relevant configuration

```yml
version: v0.10.1

dsn: sqlite:///project/kratos/some-db.sqlite?_fk=true&mode=rwc

serve:
  public:
    base_url: http://localhost:4999/
    host: localhost
    port: 4999
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4998/
    host: localhost
    port: 4998

identity:
  default_schema_id: user
  schemas:
    - id: user
      url: file:///project/kratos/identity.schema.json
log:
  level: debug
  format: text
  leak_sensitive_values: true

selfservice:
  default_browser_return_url: http://localhost:5000
  allowed_return_urls:
    - http://localhost:5000
  methods:
    password:
      enabled: true
    link:
      enabled: true
    oidc:
      config:
        providers:
          - id: google
            provider: google
            client_id: <CLIENT_ID>
            client_secret: <CLIENT_SECRET>
            mapper_url: file:///project/kratos/identity.jsonnet
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name:
                  essential: true
      enabled: true
  flows:
    registration:
      lifespan: 24h
      ui_url: http://localhost:5000/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session
    login:
      ui_url: http://localhost:5000/login
    recovery:
      enabled: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - wer89werwer0wer0wirewer9we@@#Ar2

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

### Additional Context

This is security as the user can register with any email he enters in the registration form (although he logs in using another email with the OIDC method enabled)
