### ISSUE TITLE
Sending emails fails silently

### ISSUE THREAD

**Issue by nitedani** [ory/kratos#2915]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Sending emails fail silently, without logging any error.

### Reproducing the bug

None of these config logs an error, yet none of them will send the email.

```
log:
    level: debug
    format: text
    leak_sensitive_values: true
courier:
    smtp:
        connection_uri: smtp://asdasd
        from_address: asd@asd.asd
        from_name: asdasd
```
```
courier:
    smtp:
        connection_uri: smtp://AKIA...:...@email-smtp.eu-central-1.amazonaws.com
        from_address: some@name.co
        from_name: Somename
```
```
courier:
    smtp:
        connection_uri: smtp://AKIA...:...@email-smtp.eu-central-1.amazonaws.com:465
        from_address: some@name.co
        from_name: Somename
```
```
courier:
    smtp:
        connection_uri: smtp://AKIA...:...@email-smtp.eu-central-1.amazonaws.com:587
        from_address: some@name.co
        from_name: Somename
```
```
courier:
    smtp:
        connection_uri: smtps://AKIA...:...@email-smtp.eu-central-1.amazonaws.com
        from_address: some@name.co
        from_name: Somename
```
```
courier:
    smtp:
        connection_uri: smtps://AKIA...:...@email-smtp.eu-central-1.amazonaws.com:465
        from_address: some@name.co
        from_name: Somename
```
```
courier:
    smtp:
        connection_uri: smtps://AKIA...:...@email-smtp.eu-central-1.amazonaws.com:587
        from_address: some@name.co
        from_name: Somename
```

### Relevant log output

```shell
time=2022-11-28T18:40:48Z level=info msg=Sending out recovery email with recovery link. func=github.com/ory/kratos/selfservice/strategy/link.(*Sender).SendRecoveryTokenTo file=/project/selfservice/strategy/link/sender.go:142 audience=audit email_address=nitedani@gmail.com identity_id=91e4f5c1-b373-48ff-91f3-754d2f89c3ce recovery_link_id=77c47685-d91f-4c6f-a053-7efcb3f2a6ce recovery_link_token=ItsduX97KOEEuqV8oXbCUOiiXDaymwGX service_name=Ory Kratos service_version=v0.10.1 via=email

no errors logged
```

### Version

v0.10.1

### On which operating system are you observing this issue?

Linux

### Additional Context

Using the github.com/ory/mail the email is sent successfully and I receive the email. 
```go
package main

import (
	"crypto/tls"

	"github.com/ory/mail"
)

func main() {
	d := mail.NewDialer("email-smtp.eu-central-1.amazonaws.com", 465, "AKIA...", "...") <- works with ports 465 and 587 too
	d.TLSConfig = &tls.Config{InsecureSkipVerify: true} <- works with or without this line
	m := mail.NewMessage()
	m.SetBody("text/html", "Hello <b>Bob</b> and <i>Cora</i>!")
	m.SetHeader("From", "...")
	m.SetHeader("To", "...")
	err := d.DialAndSend(m)
	if err != nil {
		panic(err)
	}

}
```
