### ISSUE TITLE
Active session after logout

### ISSUE THREAD

**Issue by drev74** [ory/kratos#2921]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After clicking a `logout` button in Vue3 TS client, my browser session is still active. This breaks an auth logic, because my client is still signed in after being signed out.

### Reproducing the bug

```bash
 "dependencies": {
    "@ory/client": "^1.0.1",
    "vue": "^3.2.41"
  },
```

```typescript
const config = new Configuration({
  basePath: import.meta.env.VITE_KRATOS_API_URL,
  baseOptions: {
    withCredentials: true,
    timeout: 10000, // 10 sec
  },
});

const ory = {
  identity: new IdentityApi(config),
  frontend: new FrontendApi(config),
  oauth2: new OAuth2Api(config),
};

const session: Ref<Session | null> = ref(null);

const logoutURL = ref('');
...
onMounted(() =>
  // Fetch the session directly from Ory
  ory.frontend
    .toSession()
    .then(({ data }) => {
      session.value = data;
    })
    .catch((err) => {
      console.log(err);
      // If the user is logged in, we want to show a logout link!
      ory.frontend.createBrowserLogoutFlow().then(({ data }) => {
        logoutURL.value = data.logout_url + `?return_to=${APPHOME}`;
      });
    })
);
```

### Relevant log output

```shell
session:Reactive
id:"73dfec8a-1d22-4276-a89c-a7b58e105077"
active:true <<------------------------------------------------------    ACTIVE SESSION !
expires_at:"2022-12-02T17:53:41.658277Z"
authenticated_at:"2022-12-01T17:53:41.658277Z"
authenticator_assurance_level:"aal1"
authentication_methods:Array[1]
issued_at:"2022-12-01T17:53:41.658277Z"
identity:Object
created_at:"2022-12-01T16:54:22.202059Z"
id:"58638b4c-843a-443b-a250-cd48eb748494"
metadata_public:null
recovery_addresses:Array[1]
schema_id:"preset://email"
schema_url:"http://localhost:4433/schemas/cHJlc2V0Oi8vZW1haWw"
state:"active"
state_changed_at:"2022-12-01T16:54:22.197581Z"
traits:Object
updated_at:"2022-12-01T16:54:22.202059Z"
verifiable_addresses:Array[1]
devices:Array[1]
0:Object
id:"9904a7d0-de1f-4931-9878-54d3a281b0fc"
ip_address:"172.21.0.1:57590"
location:""
user_agent:"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

### Relevant configuration

```yml
version: v0.10.1

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
      allowed_methods:
        - GET
        - OPTIONS
        - PUT
        - PATCH
        - DELETE
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  allowed_return_urls:
    - http://localhost:3000
    - http://localhost:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://localhost:4455/error

    settings:
      ui_url: http://localhost:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:4455/recovery

    verification:
      enabled: true
      ui_url: http://localhost:4455/verification
      after:
        default_browser_return_url: http://localhost:4455/

    logout:
      after:
        default_browser_return_url: http://localhost:4455/login

    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:4455/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: preset://email
  schemas:
    - id: preset://email
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

0.11.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

POSTGRES_VER=15.1-alpine                                                       
KRATOS_VER=v0.11.0
KRATOS_UI_VER=v0.11.0-alpha.0.pre.2
OATHKEEPER_VER=v0.40.0
KETO_VER=v0.10.0
