### ISSUE TITLE
The `updateVerificationFlowBody` OpenAPI type is missing the `code` enum variant

### ISSUE THREAD

**Issue by thehabbos007** [ory/kratos#2943]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hey, with the recent update to v0.11.0 and the additional `code` method for the `verification` flow, it seems that the OpenAPI type enum hasn't been updated, which means downstream clients are not able to pass `updateVerificationFlowWithCodeMethod` to the `updateVerificationFlowBody` operation.

From what I've gathered, it seems that operation is missing a patch to allow the other variant of the enum at 
https://github.com/ory/kratos/blob/master/.schema/openapi/patches/selfservice.yaml#L79-L88
which I think should look something like this?
```yaml
- op: add
  path: /components/schemas/updateVerificationFlowBody/oneOf
  value:
    - "$ref": "#/components/schemas/updateVerificationFlowWithLinkMethod"
    - "$ref": "#/components/schemas/updateVerificationFlowWithCodeMethod"
- op: add
  path: /components/schemas/updateVerificationFlowBody/discriminator
  value:
    propertyName: method
    mapping:
      link: "#/components/schemas/updateVerificationFlowWithLinkMethod"
      code: "#/components/schemas/updateVerificationFlowWithCodeMethod"
```

### Reproducing the bug

N/A, but the resulting codegen that is wrong is https://github.com/ory/sdk/blob/627c129c69423e9246a21cb86fdfe54fedd87721/clients/kratos/typescript/api.ts#L3183 which should be
`export type UpdateVerificationFlowBody = UpdateVerificationFlowWithLinkMethod | UpdateVerificationFlowWithCodeMethodBody;`.

This is apparaent when consuming the SDK and not being able to update a verification flow with the `code` method.

### Relevant configuration

```yml
selfservice:
  flows:
    verification:
      use: code
      ui_url: http://localhost:3000/verification
      enabled: true
```

### Version

v0.11.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other
