### ISSUE TITLE
different behavior Ory v0.10.1 and v0.11

### ISSUE THREAD

**Issue by nicolasburtey** [ory/kratos#2944]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It's not possible to update an identity from active to inactive.

relevant code: 

```
export const deactivateUser = async (
  kratosUserId: UserId,
): Promise<void | KratosError> => {
  let identity: KratosIdentity
  try {
    const res = await kratosAdmin.getIdentity({ id: kratosUserId })
    identity = res.data
  } catch (err) {
    return new UnknownKratosError(err)
  }

  try {
    baseLogger.warn({ identity }, "identity")
    const res = await kratosAdmin.updateIdentity({
      id: kratosUserId,
      updateIdentityBody: {
        ...identity,
        state: IdentityState.Inactive,
      },
    })
    console.log({ res }, "res")
  } catch (err) {
    console.log({ err }, "err")
    return new UnknownKratosError(err)
  }
}
```

the identity been shown in the console:
```
    identity: {
      "id": "932b5f48-3280-4e12-8dab-9e142ef6d472",
      "credentials": {
        "password": {
          "type": "password",
          "identifiers": [
            "+1415177297"
          ],
          "version": 0,
          "created_at": "2022-12-11T17:24:46.805215Z",
          "updated_at": "2022-12-11T17:24:46.805215Z"
        }
      },
      "schema_id": "phone_no_password_v0",
      "schema_url": "http://127.0.0.1:4433/schemas/cGhvbmVfbm9fcGFzc3dvcmRfdjA",
      "state": "active",
      "state_changed_at": "2022-12-11T17:24:46.80106Z",
      "traits": {
        "phone": "+1415177297"
      },
      "metadata_public": null,
      "metadata_admin": null,
      "created_at": "2022-12-11T17:24:46.80368Z",
      "updated_at": "2022-12-11T17:24:46.80368Z"
    }
```

the same tests running with v0.10.1 didn't run into this issue

### Reproducing the bug

the full code to run our test suite are here: https://github.com/GaloyMoney/galoy/pull/1975

### Relevant log output

```shell
{"audience":"application","error":{"debug":"","message":"The request was malformed or contained invalid parameters","reason":"The imported password does not match any known hash format. For more information see https://www.ory.sh/dr/2","stack_trace":"\ngithub.com/ory/kratos/identity.(*Handler).importPasswordCredentials\n\t/project/identity/handler_import.go:52\ngithub.com/ory/kratos/identity.(*Handler).importCredentials\n\t/project/identity/handler_import.go:23\ngithub.com/ory/kratos/identity.(*Handler).update\n\t/project/identity/handler.go:531\ngithub.com/ory/kratos/x.NoCacheHandle.func1\n\t/project/x/nocache.go:21\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:284\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:142\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:92\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:104\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:234\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/ory/x/prometheusx.Metrics.instrumentHandlerStatusBucket.func1\n\t/go/pkg/mod/github.com/ory/x@v0.0.513/prometheusx/metrics.go:111\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/ory/x/prometheusx.(*MetricsManager).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.513/prometheusx/middleware.go:39\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.513/metricsx/middleware.go:278\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/kratos/x.HTTPLoaderContextMiddleware.func1\n\t/project/x/httploadermiddleware.go:23\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/kratos/x.RedirectAdminMiddleware\n\t/project/x/http_redirect_admin.go:25\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/reqlog.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.513/reqlog/middleware.go:142","status":"Bad Request","status_code":400},"http_request":{"headers":{"accept":"application/json, text/plain, */*","connection":"close","content-length":"558","content-type":"application/json","user-agent":"axios/0.21.4"},"host":"localhost:4434","method":"PUT","path":"/admin/identities/71492183-885d-4a9a-b9b7-7a5fd8359046","query":null,"remote":"172.19.0.1:62938","scheme":"http"},"http_response":{"status_code":400},"level":"info","msg":"An error occurred while handling a request","service_name":"Ory Kratos","service_version":"v0.11.0","time":"2022-12-11T17:20:36.080483231Z"}
```

### Relevant configuration

```yml
version: "3"
services:
  e2e-deps:
    image: busybox
    depends_on:
      - kratos
      - price
      - price-history
      - price-history-migrate
      - stablesats
      - redis
      - mongodb
      - postgres-price-history
      - bitcoind
      - lnd1
      - lnd2
      - lnd-outside-1
      - lnd-outside-2
      - otel-agent
      - oathkeeper
    restart: on-failure:10
  integration-deps:
    image: busybox
    depends_on:
      - redis
      - mongodb
      - bitcoind
      - stablesats
      - lnd1
      - lnd2
      - lnd-outside-1
      - lnd-outside-2
      - otel-agent
    restart: on-failure:10
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.61.0
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml
  price:
    image: us.gcr.io/galoy-org/price:edge
  price-history:
    image: us.gcr.io/galoy-org/price-history:edge
    command: ./scripts/run-servers-dev.sh
    environment:
      - DB_HOST=postgres-price-history
      - DB_PORT=5432
      - DB_USER=galoy-price-usr
      - DB_PWD=galoy-price-pwd
      - DB_DB=galoy-price-history
      - DB_POOL_MIN=1
      - DB_POOL_MAX=5
      - DB_DEBUG=false
    depends_on:
      - postgres-price-history
      - price-history-migrate
  price-history-migrate:
    image: us.gcr.io/galoy-org/price-history-migrate:edge
    environment:
      - DB_HOST=postgres-price-history
      - DB_PORT=5432
      - DB_USER=galoy-price-usr
      - DB_PWD=galoy-price-pwd
      - DB_DB=galoy-price-history
      - DB_POOL_MIN=1
      - DB_POOL_MAX=5
      - DB_DEBUG=false
    depends_on: [postgres-price-history]
  redis:
    image: bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  mongodb-migrate:
    depends_on: [mongodb]
    build:
      context: .
      dockerfile: Dockerfile-migrate
    environment:
      - MONGODB_ADDRESS=mongodb
  mongodb:
    image: bitnami/mongodb:4.4.6-debian-10-r0
    environment:
      - MONGODB_PASSWORD=password
      - MONGODB_USERNAME=testGaloy
      - MONGODB_DATABASE=galoy
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_REPLICA_SET_KEY=replicasetkey
  postgres-price-history:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=galoy-price-usr
      - POSTGRES_PASSWORD=galoy-price-pwd
      - POSTGRES_DB=galoy-price-history
  bitcoind:
    image: lncm/bitcoind:v24.0
    volumes:
      - ${PWD}/dev/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
  lnd1:
    image: lightninglabs/lnd:v0.15.4-beta
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd1.wallet.db:/root/.lnd/wallet.db
      - ${PWD}/dev/lnd/regtest/lnd1.macaroons.db:/root/.lnd/macaroons.db
      - ${PWD}/dev/lnd/regtest/lnd1.admin.macaroon:/root/.lnd/admin.macaroon
    depends_on: [bitcoind]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /root/.lnd/data/chain/bitcoin/regtest/
        cp /root/.lnd/wallet.db /root/.lnd/data/chain/bitcoin/regtest/wallet.db
        cp /root/.lnd/macaroons.db /root/.lnd/data/chain/bitcoin/regtest/macaroons.db
        cp /root/.lnd/admin.macaroon /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
        /bin/lnd
  lnd2:
    image: lightninglabs/lnd:v0.15.4-beta
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd2.wallet.db:/root/.lnd/wallet.db
      - ${PWD}/dev/lnd/regtest/lnd2.macaroons.db:/root/.lnd/macaroons.db
      - ${PWD}/dev/lnd/regtest/lnd2.admin.macaroon:/root/.lnd/admin.macaroon
    depends_on: [bitcoind]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /root/.lnd/data/chain/bitcoin/regtest/
        cp /root/.lnd/wallet.db /root/.lnd/data/chain/bitcoin/regtest/wallet.db
        cp /root/.lnd/macaroons.db /root/.lnd/data/chain/bitcoin/regtest/macaroons.db
        cp /root/.lnd/admin.macaroon /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
        /bin/lnd
  lnd-outside-1:
    image: lightninglabs/lnd:v0.15.4-beta
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd-outside-1.wallet.db:/root/.lnd/wallet.db
      - ${PWD}/dev/lnd/regtest/lnd-outside-1.macaroons.db:/root/.lnd/macaroons.db
      - ${PWD}/dev/lnd/regtest/lnd-outside-1.admin.macaroon:/root/.lnd/admin.macaroon
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /root/.lnd/data/chain/bitcoin/regtest/
        cp /root/.lnd/wallet.db /root/.lnd/data/chain/bitcoin/regtest/wallet.db
        cp /root/.lnd/macaroons.db /root/.lnd/data/chain/bitcoin/regtest/macaroons.db
        cp /root/.lnd/admin.macaroon /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
        /bin/lnd
    depends_on: [bitcoind]
  lnd-outside-2:
    image: lightninglabs/lnd:v0.15.4-beta
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd-outside-2.wallet.db:/root/.lnd/wallet.db
      - ${PWD}/dev/lnd/regtest/lnd-outside-2.macaroons.db:/root/.lnd/macaroons.db
      - ${PWD}/dev/lnd/regtest/lnd-outside-2.admin.macaroon:/root/.lnd/admin.macaroon
    depends_on: [bitcoind]
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mkdir -p /root/.lnd/data/chain/bitcoin/regtest/
        cp /root/.lnd/wallet.db /root/.lnd/data/chain/bitcoin/regtest/wallet.db
        cp /root/.lnd/macaroons.db /root/.lnd/data/chain/bitcoin/regtest/macaroons.db
        cp /root/.lnd/admin.macaroon /root/.lnd/data/chain/bitcoin/regtest/admin.macaroon
        /bin/lnd
  loopserver:
    image: lightninglabs/loopserver:v0.9.52-beta
    restart: unless-stopped
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/loop/server/regtest:/root/.lnd/data/chain/bitcoin/regtest
    depends_on:
      - lnd-outside-1
    command:
      - "daemon"
      - "--maxamt=5000000"
      - "--lnd.host=lnd-outside-1:10009"
      - "--lnd.macaroondir=/root/.lnd/data/chain/bitcoin/regtest"
      - "--lnd.tlspath=/root/.lnd/tls.cert"
  loopd1:
    image: lightninglabs/loop:v0.20.1-beta
    restart: unless-stopped
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd1.admin.macaroon:/root/.lnd/lnd1.admin.macaroon
      - ${PWD}/dev/lnd/loop/regtest/loopd1-1.macaroons.db:/root/.loop/tmp/macaroons.db
      - ${PWD}/dev/lnd/loop/regtest/loopd1-1.loop.db:/root/.loop/tmp/loop.db
      - ${PWD}/dev/lnd/loop/regtest/loopd1-1.tls.key:/root/.loop/tmp/tls.key
      - ${PWD}/dev/lnd/loop/regtest/loopd1-1.tls.cert:/root/.loop/tmp/tls.cert
      - ${PWD}/dev/lnd/loop/regtest/loopd1-1.loop.macaroon:/root/.loop/tmp/loop.macaroon
    depends_on:
      - lnd1
      - loopserver
    environment:
      - LOOP_SERVER_INTERNAL_IP=${LOOP_SERVER_INTERNAL_IP}
    command: bash -c "
      mkdir -p /root/.loop/regtest/ &&
      cp /root/.loop/tmp/* /root/.loop/regtest/ &&
      loopd\
      --network=regtest\
      --debuglevel=debug\
      --server.host=${LOOP_SERVER_INTERNAL_IP}:11009\
      --server.notls --lnd.host=lnd1:10009\
      --lnd.macaroonpath=/root/.lnd/lnd1.admin.macaroon\
      --lnd.tlspath=/root/.lnd/tls.cert\
      --tlsautorefresh\
      --restlisten=0.0.0.0:8081\
      --rpclisten=0.0.0.0:11010"
  loopd2:
    image: lightninglabs/loop:v0.20.1-beta
    restart: unless-stopped
    volumes:
      - ${PWD}/dev/lnd/lnd.conf:/root/.lnd/lnd.conf
      - ${PWD}/dev/lnd/tls.key:/root/.lnd/tls.key
      - ${PWD}/dev/lnd/tls.cert:/root/.lnd/tls.cert
      - ${PWD}/dev/lnd/regtest/lnd2.admin.macaroon:/root/.lnd/lnd2.admin.macaroon
      - ${PWD}/dev/lnd/loop/regtest/loopd2-1.macaroons.db:/root/.loop/tmp/macaroons.db
      - ${PWD}/dev/lnd/loop/regtest/loopd2-1.loop.db:/root/.loop/tmp/loop.db
      - ${PWD}/dev/lnd/loop/regtest/loopd2-1.tls.key:/root/.loop/tmp/tls.key
      - ${PWD}/dev/lnd/loop/regtest/loopd2-1.tls.cert:/root/.loop/tmp/tls.cert
      - ${PWD}/dev/lnd/loop/regtest/loopd2-1.loop.macaroon:/root/.loop/tmp/loop.macaroon
    depends_on:
      - lnd2
      - loopserver
    environment:
      - LOOP_SERVER_INTERNAL_IP=${LOOP_SERVER_INTERNAL_IP}
    command: bash -c "
      mkdir -p /root/.loop/regtest/ &&
      cp /root/.loop/tmp/* /root/.loop/regtest/ &&
      loopd\
      --network=regtest\
      --debuglevel=debug\
      --server.host=${LOOP_SERVER_INTERNAL_IP}:11009\
      --server.notls --lnd.host=lnd2:10009\
      --lnd.macaroonpath=/root/.lnd/lnd2.admin.macaroon\
      --lnd.tlspath=/root/.lnd/tls.cert\
      --tlsautorefresh\
      --restlisten=0.0.0.0:8081\
      --rpclisten=0.0.0.0:11010"
  e2e-tests:
    image: us.gcr.io/galoy-org/nodejs-concourse
    depends_on:
      - e2e-deps
    command: ["make", "execute-e2e-from-within-container"]
    working_dir: /repo
    env_file:
      - ${TMP_ENV_CI:-.env.ci}
    volumes:
      - ./:/repo
  integration-tests:
    image: us.gcr.io/galoy-org/nodejs-concourse
    depends_on:
      - integration-deps
    command: ["make", "execute-integration-from-within-container"]
    working_dir: /repo
    env_file:
      - ${TMP_ENV_CI:-.env.ci}
    volumes:
      - ./:/repo
  stablesats:
    image: us.gcr.io/galoy-org/stablesats-rs:latest
    command: ["stablesats", "run"]
    working_dir: /repo/dev
    depends_on:
      - otel-agent
      - redis
      - mongodb
    restart: on-failure:10
    volumes:
      - ./:/repo
  oathkeeper:
    image: oryd/oathkeeper:v0.40
    command: serve -c /home/ory/oathkeeper.yml --sqa-opt-out
    volumes:
      - type: bind
        source: dev/ory
        target: /home/ory
  kratos:
    image: oryd/kratos:v0.11.0
    entrypoint: sh -c
    command: '"kratos migrate sql up -y -e && kratos serve -c /home/ory/kratos.yml --sqa-opt-out"'
    environment:
      DSN: postgres://dbuser:secret@kratos-pg:5432/default?sslmode=disable
    links:
      - kratos-pg:kratos-pg
    volumes:
      - type: bind
        source: dev/ory
        target: /home/ory
    extra_hosts:
      - "host.docker.internal:host-gateway"
  kratos-pg:
    image: postgres:14.1
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=default
```

### Version

0.11

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
