### ISSUE TITLE
shutdown doesn't complete

### ISSUE THREAD

**Issue by Gibheer** [ory/kratos#295]
**Describe the bug**

When stopping serving kratos it doesn't shutdown completely and just hangs around. I have to kill -9 the process to make it stop.

**Reproducing the bug**

1. Run `./kratos serve --config kratos.yaml` with minimal settings
2. Press ctrl+c to stop the daemon

*Server logs*

```
./kratos serve --config kratos.yaml
INFO[0002] Config file loaded successfully.              path=kratos.yaml
INFO[0002] Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa 
INFO[0002] Starting the admin httpd on: 0.0.0.0:4434    
INFO[0002] Starting the public httpd on: 0.0.0.0:4433   
^CINFO[0009] Public httpd was shutdown gracefully         
INFO[0009] Admin httpd was shutdown gracefully          
^C^C^C
```

*Server configuration*

```yaml
---
dsn: "postgres://kratos:@pg1.example.org/iam?sslmode=disable"

hashers:
  argon2:
    memory: 1048576
    iterations: 2
    parallelism: 4
    salt_length: 16
    key_length: 32

courier:
  smtp:
    connection_uri: smtps://localhost/
    from_address: iam@example.org

identity:
  traits:
    default_schema_url: http://gibheer.zero-knowledge.org/default_identity.json

selfservice:
  logout:
    redirect_to: https://example.org

urls:
  profile_ui: https://iam.example.org
  mfa_ui: https://iam.example.org/mfa
  login_ui: https://iam.example.org/login
  registration_ui: https://iam.example.org/register
  error_ui: https://iam.example.org/failed
  verify_ui: https://iam.example.org/verify
  default_return_to: https://example.org
  self:
    public: "http://0.0.0.0:8080"
    admin: "http://0.0.0.0:9292"
```

**Expected behavior**

I should be able to stop the daemon either with ctrl-c or using a normal kill.

**Environment**

* Version: master, 537d496
* Environment: FreeBSD 12.1-RELEASE-p2, Go 1.14
