### ISSUE TITLE
Errors on json-schema validation for traits always returns 4000001 as message id

### ISSUE THREAD

**Issue by eschmittel** [ory/kratos#2974]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The message code of traits  with failed  with for example validation minLength or pattern always results in 4000001 = ErrorValidationGeneric. 

According to https://www.ory.sh/docs/kratos/concepts/ui-user-interface#ui-message-codes 
and https://github.com/ory/kratos/blob/master/text/id.go I would expect a 4000003 = ErrorValidationMinLength
if I defined a minLength or 4000004 = ErrorValidationInvalidFormat for a given trait in json schema.

If this is expected behavior it would be still nice to find a way to differentiate the different validation messages by some sort of identifier.

### Reproducing the bug

1. create new ory project
2. change identity to the schema defined down below 
3. try to update the registration flow with invalid values for trait name.last or name.first 

examples:
name.first = "" // invalid minLength requirement
name.last = "invalidname?" // invalid pattern

View Full example: https://github.com/eschmittel/ory_validation_bug

### Relevant log output

```shell
// this is the resulting flow
{
    "id": "fba7c40b-76b1-4582-8ca0-71b8d6699566",
    "oauth2_login_challenge": null,
    "type": "browser",
    "expires_at": "2022-12-20T17:43:56.338554Z",
    "issued_at": "2022-12-20T16:43:56.338554Z",
    "request_url": "http://localhost:4000/self-service/registration/browser",
    "ui": {
        "action": "http://localhost:4000/self-service/registration?flow=fba7c40b-76b1-4582-8ca0-71b8d6699566",
        "method": "POST",
        "nodes": [
            ... // removed invalid fields
            {
                "type": "input",
                "group": "password",
                "attributes": {
                    "name": "traits.name.first",
                    "type": "text",
                    "value": "asdfsadf??",
                    "required": true,
                    "pattern": "^[a-zA-ZäöüÄÖÜ.éíáóúêîâôûèìàòùÉÍÁÓÚÊÎÂÔÛÈÌÀÒÙÃÅÇËÏÑÕØÝãåçëïñõøýÿ ß-]*$",
                    "disabled": false,
                    "node_type": "input"
                },
                "messages": [
                    {
                        "id": 4000001,
                        "text": "does not match pattern \"^[a-zA-ZäöüÄÖÜ.éíáóúêîâôûèìàòùÉÍÁÓÚÊÎÂÔÛÈÌÀÒÙÃÅÇËÏÑÕØÝãåçëïñõøýÿ ß-]*$\"",
                        "type": "error"
                    }
                ],
                "meta": {
                    "label": {
                        "id": 1070002,
                        "text": "Vorname",
                        "type": "info"
                    }
                }
            },
            {
                "type": "input",
                "group": "password",
                "attributes": {
                    "name": "traits.name.last",
                    "type": "text",
                    "value": "",
                    "required": true,
                    "pattern": "^[a-zA-ZäöüÄÖÜ.éíáóúêîâôûèìàòùÉÍÁÓÚÊÎÂÔÛÈÌÀÒÙÃÅÇËÏÑÕØÝãåçëïñõøýÿ ß-]*$",
                    "disabled": false,
                    "node_type": "input"
                },
                "messages": [
                    {
                        "id": 4000001,
                        "text": "length must be >= 1, but got 0",
                        "type": "error"
                    }
                ],
                "meta": {
                    "label": {
                        "id": 1070002,
                        "text": "Nachname",
                        "type": "info"
                    }
                }
            },
            ...
        ]
    }
}
```

### Relevant configuration

```yml
// default schema extended with first and last name
{
  "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              },
              "webauthn": {
                "identifier": true
              },
              "totp": {
                "account_name": true
              }
            },
            "recovery": {
              "via": "email"
            },
            "verification": {
              "via": "email"
            }
          },
          "maxLength": 320
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "type": "string",
              "title": "Vorname",
              "maxLength": 64,
              "pattern": "^[a-zA-ZäöüÄÖÜ.éíáóúêîâôûèìàòùÉÍÁÓÚÊÎÂÔÛÈÌÀÒÙÃÅÇËÏÑÕØÝãåçëïñõøýÿ ß-]*$",
              "minLength": 1
            },
            "last": {
              "type": "string",
              "title": "Nachname",
              "maxLength": 64,
              "pattern": "^[a-zA-ZäöüÄÖÜ.éíáóúêîâôûèìàòùÉÍÁÓÚÊÎÂÔÛÈÌÀÒÙÃÅÇËÏÑÕØÝãåçëïñõøýÿ ß-]*$",
              "minLength": 1
            }
          },
          "required": [
            "first",
            "last"
          ]
        }
      },
      "required": [
        "email",
        "name"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

ory network & @ory/client 1.1.2

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

Ory Network

### Additional Context

The core issue is that I want to map the errors by message id to an alternate error message, but this is not possible if all validation errors have the same id.
