### ISSUE TITLE
open courier/builtin/templates/recovery/valid/email.subject.gotmpl: The system cannot find the path specified.

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#3003]
### Describe the bug

Upgrading from 0.10.1 to 0.11.0 I'm getting:

```shell
open courier/builtin/templates/recovery/valid/email.subject.gotmpl: The system cannot find the path specified.
```

Why?

I would like to use the default templates.

### Version

0.11.0

### Config

```yml
version: v0.11.0

dsn: ""

courier:
  smtp:
    connection_uri: smtps://something:pass@smtp.gmail.com:465/

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file://./identity.schema.json

log:
  format: text
  leak_sensitive_values: true
  # level: debug # 5 panic, 4 fatal, 3 error, 2 warning, 1 info, 0 debug (default), -1 trace

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

selfservice:
  default_browser_return_url: http://localhost:8080
  allowed_return_urls:
    - http://localhost:8080

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    link:
      enabled: true
    profile:
      enabled: false

  flows:
    error:
      ui_url: http://localhost:8080/auth/error
    login:
      ui_url: http://localhost:8080/auth
    logout:
      after:
        default_browser_return_url: http://localhost:8080
    recovery:
      enabled: true
      ui_url: http://localhost:8080/auth/recovery
    settings:
      ui_url: http://localhost:8080/auth/settings

serve:
  admin:
    base_url: http://localhost:4434
  public:
    base_url: http://localhost:3000
```

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Binary
