### ISSUE TITLE
template_override_path not working after migrate from 0.10.1 to 0.11.0 self hosted

### ISSUE THREAD

**Issue by miniben-90** [ory/kratos#3022]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After the migration from Kratos version 0.10.1 to 0.11.0, the replacement of e-mail templates no longer works.
We try with env. variable `COURIER_TEMPLATE_OVERRIDE_PATH`, also to set `template_override_path` but nothing change.

Also try to write the template with env. directly with `COURIER_TEMPLATES_RECOVERY_CODE_VALID_EMAIL_SUBJECT` (and others...) with base64 but same nothing change, it use the default templates.

Nothing in the logs.

### Reproducing the bug

`docker-compose.yml`:
```yaml
version: '3.8'
services:
#[...]
  kratos:
    image: oryd/kratos:latest
    #[...]
    environment:
      COURIER_TEMPLATE_OVERRIDE_PATH: /conf/courier-templates
      #[...]
    volumes:
      - './conf/courier-templates:/conf/courier-templates'
      #[...]
    #[...]
#[...]
```

### Version

0.11.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Docker Compose
