### ISSUE TITLE
Google Offline OAuth Config Missing

### ISSUE THREAD

**Issue by tdipadova3rd** [ory/kratos#3031]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I’m configuring Google OIDC for Kratos and running into an issue getting a refresh token. The kratos [docs](https://www.ory.sh/docs/kratos/reference/configuration) give an example where offline access (to get a refresh_token ) requires the config:

```
scope:
   - offline_access
 ```

However, when. using this config Google throws an error saying this scope doesn’t exist. [Google docs](https://developers.google.com/identity/openid-connect/openid-connect#:~:text=A%20refresh%20token%20provides%20your,offline%20in%20your%20authentication%20request) specify that you just need a param `access_type=offline` during the auth request. Is there any existing way to configure this param in Kratos? If so, can we add it to the docs? And if not, can we add the ability to add arbitrary params to the auth request?

### Reproducing the bug

Steps to reproduce:

1. Add a Google OIDC provider to Kratos self-hosted.
2. Add the suggested `offline_access` (or `offline`) scope.
3. Login via Google.
4. Expected behavior is a that an `initial_refresh_token` will attach to the identity. Result is that Google throws an error saying whatever included scope isn't allowed/doesn't exist.

### Relevant configuration

```yml
selfservice:
  default_browser_return_url: http://127.0.0.1:3000/
  allowed_return_urls:
    - http://127.0.0.1:3000

  methods:
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: "" 
            mapper_url: file:///etc/config/kratos/oidc.google.jsonnet
            client_secret: "" 
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://www.googleapis.com/oauth2/v4/token
            scope:
              - openid
              - email
              - profile
              - offline_access
              - https://www.googleapis.com/auth/drive.readonly
            requested_claims:
              id_token:
                email:
                email_verified:
            label: ""
        base_redirect_uri: http://127.0.0.1:4433
```

### Version

0.11.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
