### ISSUE TITLE
2fa settings ask for confirmation if no authentication methods are configured

### ISSUE THREAD

**Issue by woylie** [ory/kratos#3131]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I ran into an issue when a new user is created via the admin API. After the user logs in for the first time by using the verification code from the email, they are asked to set up a password within the next five minutes. However, the TOTP form fields are also returned with the flow. If the user now submits the TOTP form without setting a password first, they are asked to confirm by "Please confirm this action by verifying that it is you." However, since no authentication method is available yet, no inputs are rendered in that form and the user is stuck.

I would expect one of two things: Either the user is not asked to confirm via the login flow if the user does not have a first factor authentication method yet (meh), or the settings form groups that require confirmation are not included in the settings flow if there is no first factor.

I tried to find a way to hide the TOTP form in that case on the client side, but I couldn't find a way to determine whether we are in that state. Would it be correct to assume the user needs to set up a password if the `authentication_methods` of the current session include either `link_recovery` or `code_recovery`?

### Reproducing the bug

1. Enable `password` and `totp` authentication methods and verification flow in Kratos.
2. Configure an email trait with

```json
"ory.sh/kratos": {
  "credentials": {
  "password": {
     "identifier": true
   },
   "totp": {
      "account_name": true
   },
```

4. Create a new identity via `POST /admin/identities`.
5. Enter verification code received via email
6. You are logged in and should see the settings form and a message asking you to set up a password.
7. Scan QR code, enter TOTP code and submit.
8. You should now see the login form with the message `Please confirm this action by verifying that it is you.` and no form inputs.

### Relevant configuration

```yml
selfservice:
  methods:
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: someone.com
    link:
      enabled: true
      config:
        lifespan: 15m

  flows:
    settings:
      privileged_session_max_age: 5m
  
    recovery:
      enabled: true
      lifespan: 15m

    verification:
      enabled: true

    login:
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: require_verified_address

    registration:
      lifespan: 10m
```

### Version

0.11.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
