### ISSUE TITLE
Kratos cleanup sql -e gives a panic

### ISSUE THREAD

**Issue by codexetreme** [ory/kratos#3159]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I get this error when I run
kratos cleanup sql -e , I have checked the DB and nothing was executed.
I can’t quite find out why it panics, iirc everything is setup correctly and working fine in local and staging, but the panic still shows up in both places

### Reproducing the bug

1. Get the docker kratos version 
`oryd/kratos:v0.11.1`

2. get it up and running with postgres. 

here is the complete docker compose file to this 

```yaml
version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v0.11.1
    environment:
      - DSN=postgres://kratos:<password>@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos/config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.11.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:<password>@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./kratos/config
        target: /etc/config/kratos
    networks:
      - intranet


  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet
 postgres:
    image: postgres:latest
    networks:
      - intranet
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - dev_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <password>
      POSTGRES_USER: test_user

networks:
  intranet:
volumes:
  kratos-sqlite:
```

then execute the script into kratos container with 

docker exec -it <container-id> /bin/sh -c "kratos cleanup sql -e"

you will see the panic as attached above

### Relevant log output

```shell
panic: nid must be not nil [recovered]
        panic: nid must be not nil

goroutine 1 [running]:
github.com/ory/x/otelx.End({0x1c63f80?, 0x2a17f70}, 0x4000a37888)
        /go/pkg/mod/github.com/ory/x@v0.0.531/otelx/withspan.go:52 +0x118
panic({0x14c5240, 0x1c48a70})
        /usr/local/go/src/runtime/panic.go:884 +0x20c
github.com/ory/x/contextx.(*Default).Network(0x40007c2410?, {0x40003acb40?, 0x98?}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        /go/pkg/mod/github.com/ory/x@v0.0.531/contextx/default.go:20 +0x8c
github.com/ory/kratos/persistence/sql.(*Persister).NetworkID(0x4000e4c720, {0x1c5c0b8, 0x4000e5a510})
        /project/persistence/sql/persister.go:72 +0x7c
github.com/ory/kratos/persistence/sql.(*Persister).DeleteExpiredSessions(0x4000e4c720, {0x1c5c048, 0x4000040058}, {0x22?, 0x4000a37b10?, 0x29e6a40?}, 0x1?)
        /project/persistence/sql/persister_session.go:406 +0x17c
github.com/ory/kratos/persistence/sql.(*Persister).CleanupDatabase(0x4000e4c720, {0x1c5c048, 0x4000040058}, 0x1c53150?, 0x0, 0x4000010040?)
        /project/persistence/sql/persister.go:147 +0x144
github.com/ory/kratos/cmd/cliclient.(*CleanupHandler).CleanupSQL(0x0?, 0x4000962600, {0x40004312f0, 0x0, 0x0?})
        /project/cmd/cliclient/cleanup.go:61 +0x42c
github.com/ory/kratos/cmd/cleanup.NewCleanupSQLCmd.func1(0x4000962600?, {0x40004312f0?, 0x1?, 0x1?})
        /project/cmd/cleanup/sql.go:35 +0x38
github.com/spf13/cobra.(*Command).execute(0x4000962600, {0x4000431290, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0x4000187b00)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/ory/kratos/cmd.Execute()
        /project/cmd/root.go:61 +0x24
main.main()
        /project/main.go:21 +0x64
```

### Relevant configuration

```yml
version: v0.11.1

# set this on the Env variables instead
#dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
#        this is needed because the email recovery link generates it at this IP and not localhost
#        - https://*.example.org
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000
    - http://localhost:3000/dashboard

  methods:
    password:
      enabled: true
    # this is disabled for now
    oidc:
      enabled: false

  flows:
    error:
      ui_url: http://localhost:3000/error

    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery

    verification:
      enabled: true
      ui_url: http://localhost:3000/verification
      after:
        default_browser_return_url: http://localhost:3000/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/login

    login:
      ui_url: http://localhost:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/signup
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

session:
  cookie:
    name: users

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

0.11.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
