### ISSUE TITLE
require_verified_address and web_hook together cause startup failure

### ISSUE THREAD

**Issue by Balinth** [ory/kratos#3161]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

In simple password login flow after hook, using either just the `require_verified_address` or the `web_hook` works correctly, BUT if both are provided, service startup fails with the below error message.
If I comment out either of the 2 hooks (and modify / remove the url env variable), then everything works correctly, but if they are there together, then I get the error.
On further investigation, the order matters, the error is only present, if `require_verified_address` is the first hook.
### Reproducing the bug

1. Create kratos.yml with self service login flow after hooks containing a webhook and a require_verified_address
2. try to start the service

### Relevant log output

```shell
[docker] 4x-by-decree-kratos-1          | time=2023-03-12T23:15:39Z level=debug msg=Adding config files. func=github.com/ory/x/configx.(*Provider).createProviders file=/go/pkg/mod/github.com/ory/x@v0.0.531/configx/provider.go:156 au
dience=application files=[/etc/config/kratos/kratos.yml] service_name=Ory Kratos service_version=v0.11.1
[docker] 4x-by-decree-kratos-1          |         I[#/selfservice/flows/login/after/password/hooks/0] S[#/definitions/selfServiceWebHook/type] expected object, but got null stack_trace:stack trace could not be recovered from error t
ype *jsonschema.ValidationError] service_name=Ory Kratos service_version=v0.11.1
```

### Relevant configuration

```yml
# relevant parts of kratos.yml
selfservice:
  methods:
    password:
      enabled: true

  flows:
    login:
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: require_verified_address
            - hook: web_hook
              config:
                method: PATCH
                body: file:///etc/config/kratos/update_user_in_api_webhook_body.jsonnet
                response:
                  ignore: true
                #url: from env variable, SELFSERVICE_FLOWS_LOGIN_AFTER_PASSWORD_HOOKS_1_CONFIG_URL
```

### Version

v0.11.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
