### ISSUE TITLE
Modify identities in after settings webhook does not work

### ISSUE THREAD

**Issue by ChrisLahaye** [ory/kratos#3192]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

According to the docs at https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#modify-identities it should be possible to modify the identity in an after registration and settings webhook. This only works for the registration and not the settings webhook.

### Reproducing the bug

1. Apply the provided configuration
2. Update your profile or password and have the webhook return `{ identity: { metadata_admin: { test: true } } }`
3. Observe that the identity does not get updated for traits, metadata_admin, and metadata_public

### Relevant configuration

```yml
selfservice:
  flows:
    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://127.0.0.1:8080/ory/settings?type=password
                method: POST
                body: file:///etc/kratos/config/webhook.body.jsonnet
                response:
                  parse: true
        profile:
          hooks:
            - hook: web_hook
              config:
                url: http://127.0.0.1:8080/ory/settings?type=profile
                method: POST
                body: file:///etc/kratos/config/webhook.body.jsonnet
                response:
                  parse: true
```

### Version

master (b69981a2cfa68de6e47561d9f4e3a04d9297557e)

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
