### ISSUE TITLE
Flow interrupting in after recovery webhook does not work

### ISSUE THREAD

**Issue by ChrisLahaye** [ory/kratos#3193]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

According to the docs at https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#flow-interrupting-webhooks it should be possible to interrupt a flow by returning an error code from the webhook. This works for the registration but not the recovery flow.

### Reproducing the bug

1. Apply the provided configuration
2. Perform the recovery flow and have the webhook return a 400 status code (with a properly formatted error payload)
3. Observe that the flow does not get interrupted

### Relevant log output

```shell
time=2023-03-28T11:26:39Z level=debug msg=A recovery flow is being retried because a validation error occurred. audience=application error=map[message:1 validation errors occurred:
(0) I[#/traits/email] S[] a webhook target returned an error stack_trace:
github.com/ory/kratos/schema.NewValidationListError
	/go/src/github.com/ory/kratos/schema/errors.go:274
github.com/ory/kratos/selfservice/hook.parseWebhookResponse
```

### Relevant configuration

```yml
selfservice:
  flows:
    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://127.0.0.1:8080/ory/recovery
              method: POST
              body: file:///etc/kratos/config/webhook.body.jsonnet
              response:
                parse: true
```

### Version

master (b69981a2cfa68de6e47561d9f4e3a04d9297557e)

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
