### ISSUE TITLE
CORS Error on Admin

### ISSUE THREAD

**Issue by aydinnyunus** [ory/kratos#3223]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

There is no problem on adding cors on public but when i added it to admin it gets error

### Reproducing the bug

I follow the quickstart.yml for creating Kratos. I change the localhost and 127.0.0.1 IP addresses to another Public IP which has Kratos. I use kratos-admin-ui dashboard and wanted to access API but I got Cors Error. I send it on log output. 

There is no problem on adding cors on public but when i added it to admin it gets error

### Relevant log output

```shell
kratos_1                      | Error: I[#/serve/admin] S[#/properties/serve/properties/admin/additionalProperties] additionalProperties "cors" not allowed
kratos_1                      | Usage:
kratos_1                      |   kratos serve [flags]
kratos_1                      | 
kratos_1                      | Flags:
kratos_1                      |   -c, --config strings   Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
kratos_1                      |       --dev              Disables critical security features to make development easier
kratos_1                      |   -h, --help             help for serve
kratos_1                      |       --sqa-opt-out      Disable anonymized telemetry reports - for more information please visit https://www.ory.sh/docs/ecosystem/sqa
kratos_1                      |       --watch-courier    Run the message courier as a background task, to simplify single-instance setup
kratos_1                      | 
kratos_1                      | I[#/serve/admin] S[#/properties/serve/properties/admin/additionalProperties] additionalProperties "cors" not allowed
kratos_kratos_1 exited with code 1
```

### Relevant configuration

```yml
version: v0.11.0

dsn: memory

serve:
  public:
    base_url: http://REDACTED_ADMIN:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://ADMIN_UI:3000/
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
  admin:
    base_url: http://REDACTED_ADMIN:4434/

selfservice:
  default_browser_return_url: http://REDACTED_ADMIN:4455/
  allowed_return_urls:
    - http://REDACTED_ADMIN:4455

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://REDACTED_ADMIN:4455/error

    settings:
      ui_url: http://REDACTED_ADMIN:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://REDACTED_ADMIN:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://REDACTED_ADMIN:4455/verification
      use: code
      after:
        default_browser_return_url: http://REDACTED_ADMIN:4455/

    logout:
      after:
        default_browser_return_url: http://REDACTED_ADMIN:4455/login

    login:
      ui_url: http://REDACTED_ADMIN:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://REDACTED_ADMIN:4455/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

v1.11.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
