### ISSUE TITLE
Webhook config parse: true doesn't work on flow settings

### ISSUE THREAD

**Issue by jossbnd** [ory/kratos#3252]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi, 
I did bump to 0.13.0 and updated my config with the parse: true. I used to have the can_interrupt before.
Does work with registration but failed with settings.

I see that the parse: true is not managed in case of settings (see below) - on the other way, I understood that can_interrupt will be deprecated.

`ExecuteSettingsPostPersistHook`:
https://github.com/ory/kratos/blob/1064b3296faccf66301d412bf0f7c3d6da09c8ef/selfservice/hook/web_hook.go#L247

while `ExecutePostRegistrationPostPersistHook`
https://github.com/ory/kratos/blob/1064b3296faccf66301d412bf0f7c3d6da09c8ef/selfservice/hook/web_hook.go#L211

same with `ExecuteSettingsPrePersistHook`
https://github.com/ory/kratos/blob/1064b3296faccf66301d412bf0f7c3d6da09c8ef/selfservice/hook/web_hook.go#L263

`ExecutePostRegistrationPrePersistHook`
https://github.com/ory/kratos/blob/1064b3296faccf66301d412bf0f7c3d6da09c8ef/selfservice/hook/web_hook.go#L194

### Reproducing the bug

```
settings:
      ui_url: http://localhost:1234
      after:
        profile:
          hooks:
            - hook: web_hook
              config:
                url: http://host.docker.internal:3211/email/check
                method: POST # GET, DELETE, etc
                body: file:///etc/config/cio.check.email.jsonnet
                response:
                  parse: true
```

### Version

0.13.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by gleandroj** [comment]
up

**Comment by aeneasr** [comment]
Thank you for the report - this requires some investigation :) Fixes welcomed

**Comment by meotimdihia** [comment]
I confirm the problem.

![image](https://github.com/ory/kratos/assets/300961/f2c6d18d-d3c8-4d34-80b4-e8919217120c)
settings:
   after hook doesn't work too.
   
 ```yaml
     registration:
      lifespan: 10m
      ui_url: https://mac.local/user/registration
      after: # When the user starts the flow
        hooks:
          - hook: web_hook
            config:
              url: http://host.docker.internal:3002/user/after_registration_hook
              method: POST
              response:
                ignore: false
                parse: true
              body: file:///etc/config/kratos/segment_identify.jsonnet
              auth:
                type: api_key
                config:
                  name: Authorization
                  value: "dfsfsfdsff"
                  in: header # alternatively "cookie"
 ```
   
 Even though it returned 400, the update request was still saved.

**Comment by Rozkipz** [comment]
Hey still having some issues with this on v1.0.0. 

Kratos posts back just fine to the API, until you add parsing to the webhook, at which point it creates a customer in Kratos but doesn't seem to call the endpoint at all.

Running this in kubernetes, deployed with the ory Kratos helm chart, tested on both `v0.38.1` and `v0.39.1`

```
➜  ~ curl  -L "127.0.0.1:4434/version"
{"version":"v1.0.0"}
➜  ~ 
```

---

Posts back to the API:
```
          registration:
            after:
              default_browser_return_url: [MY_URL]
              hooks:
                - hook: web_hook
                  config:
                    url: [API_URL]
                    method: POST
                    body: "base64://base64string"
```

Doesn't post back to the API:
```
          registration:
            after:
              default_browser_return_url: [MY_URL]
              hooks:
                - hook: web_hook
                  config:
                    url: [API_URL]
                    method: POST
                    body: "base64://base64string"
                    response:
                      parse: true
```
