### ISSUE TITLE
After-verification hook payload does not reflect updated state

### ISSUE THREAD

**Issue by zorba128** [ory/kratos#3254]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After-verification hook seems to be triggered before identity state is updated - wrongly notifying `"verified": false`.

Sample payload:
```
"identity": {
    "verifiable_addresses": [
      {
        "created_at": "2023-04-24T09:41:38.718726Z",
        "id": "a6bb375f-7d5a-4c48-9a82-af459a29a2dc",
        "status": "sent",
        "updated_at": "2023-04-24T09:41:38.718726Z",
        "value": "test4@test.test",
        "verified": false,
        "via": "email"
      }
    ]
  }
```

### Reproducing the bug

- register new account
- successfully verify e-mail address
- observe after-verification hook payload

### Relevant configuration

```yml
verification:
      enabled: true
      use: code
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://...
              method: POST
              response:
                ignore: true
              # function(ctx) { identity: ctx.identity }
              body: base64://ZnVuY3Rpb24oY3R4KSB7IGlkZW50aXR5OiBjdHguaWRlbnRpdHkgfQ==
              can_interrupt: false
```

### Version

0.13.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
