### ISSUE TITLE
Webhook failing with timeout while it never failed before

### ISSUE THREAD

**Issue by hugotiburtino** [ory/kratos#3258]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When our kratos was deployed on this [custom commit](https://github.com/serlo/kratos/tree/next) the post registration webhook never failed and that was from 12 December 2022 until 8 April. Impressive 1461 times in which it always worked.

Since 23 April we are using the version 0.13.0 and it failed 2 times out of 60. 

For more info see https://github.com/serlo/infrastructure-modules-shared/issues/43

Maybe side effect of https://github.com/ory/kratos/pull/3200

### Reproducing the bug

It is hard to reproduce, even though I think some actions can be taken, like reverting it to the previous behavior without timeout. And is it doing retry?

### Relevant log output
Both had timeout
>```"time=2023-04-24T14:29:35Z level=error msg=Webhook request failed audience=application duration=5m0.00090309s error=map[message:context deadline exceeded] otel=map[span_id:0000000000000000 trace_id:00000000000000000000000000000000] service_name=Ory Kratos service_version=v0.13.0"```

Nevertheless, I doubt that the response took so long from the webhook endpoint.

### Relevant configuration

```yml
      registration:
          lifespan: 10m
          ui_url: https://serlo-staging.dev/auth/registration
          after:
            hooks:
              - hook: web_hook
                config:
                  url: https://api.serlo-staging.dev/kratos/register
                  method: POST
                  # function (ctx) { userId: ctx.identity.id }
                  body: base64://ZnVuY3Rpb24gKGN0eCkgeyB1c2VySWQ6IGN0eC5pZGVudGl0eS5pZCB9Cg==
                  auth:
                    type: api_key
                    config:
                      name: x-kratos-key
                      value: ${kratos_secret}
                      in: header
```
See https://github.com/serlo/infrastructure-modules-shared/blob/main/kratos/values.yaml#L99-L115

### Version

0.13.0

### In which environment are you deploying?

Kubernetes with Helm
