### ISSUE TITLE
Unauthorized whoami request after a successfully login

### ISSUE THREAD

**Issue by malagon91** [ory/kratos#3296]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After we log in a user with the browser login flow we redirect the user to the logged page and on that page, we make the request to get the user  information `https://my-kratos.app/sessions/whoami`  that request returns a 401 error (unauthorized) 

We are running the app on the k8s cluster we found that if we set the replica set to 1 the error is gone but with multiple pods we got the error.

### Reproducing the bug

1.  Access to the login browser flow
2. Set a correct user credentials (email and password)
3. Click to login button and wait to finish the login flow 
4. The success page calls the whoami endpoint and got an 401 error

### Relevant configuration

```yml
selfservice:
      default_browser_return_url: https://my-kratos.app/
      methods:
        oidc:
          config:
            providers:
              - id: google # this is `<provider-id>` in the Authorization callback URL. DO NOT CHANGE IT ONCE SET!
                provider: google
                client_id: client_id
                client_secret: client_secret
                mapper_url: "base64:data"
                scope:
                  - email
                requested_claims:
                  id_token:
                    email:
                      essential: true
                    email_verified:
                      essential: true
            base_redirect_uri: https://my-kratos.app/kratos   
          enabled: true
        password:
          enabled: true
      flows:
        error:
          ui_url: https://my-kratos.app/cand/inicia-sesion/kratos/error/
        login:
          ui_url: https://my-kratos.app/cand/inicia-sesion/kratos/login
          # lifespan: 10m
          after:
            default_browser_return_url: https://my-kratos.app/cand/success
            oidc:
              default_browser_return_url: https://my-kratos.app/cand/success


        registration:
          ui_url: https://my-kratos.app/cand/cuenta-nueva/kratos/register
          # lifespan: 10m
          after:
            default_browser_return_url: https://my-kratos.app/cand/success
            oidc:
              default_browser_return_url: https://my-kratos.app/candidatos/success
              hooks: 
                - hook: session
        
    cookies:
      domain: .my-kratos.app
      same_site: Lax
      # secure: false
    session:
      cookie:
        domain: .my-kratos.app/
        same_site: Lax
        # secure: false
    serve:
      public:
        port: 4433
        base_url: https://my-kratos.app/kratos/
        cors:
          allowed_origins:
            - https://my-kratos.app/
            - https://*.my-kratos.app/
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed_headers:
            - Authorization
            - Cookie
            - Content-Type
            - X-Session-Token
          exposed_headers:
            - Content-Type
            - Set-Cookie
          enabled: true
          debug: true
          allow_credentials: true
      admin:
        port: 4434
```

### Version

v0.11.1

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Kubernetes with Helm
