### ISSUE TITLE
Unable to enforce email verification after registration when authenticating with Ory Kratos

### ISSUE THREAD

**Issue by blackbird-simon** [ory/kratos#3320]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello I’m running into a problem with the Ory network and showing a user the email verification screen after they register.
I’ve configured our ory project using the instructions [here](https://www.ory.sh/docs/identities/sign-in/actions#show-verification-after-successful-registration) to add the show_verification_ui
 hook to run after registration. The relevant part of our identity config then looks like

```
    login:
      after:
        hooks: []
        oidc:
          hooks: []
        password:
          hooks:
          - hook: require_verified_address
        webauthn:
          hooks: []
      before:
        hooks: []
      lifespan: 30m0s
      ui_url: /ui/login    

    registration:
      after:
        default_browser_return_url: https://editor.bbeng.dev/
        hooks: []
        oidc:
          hooks:
          - hook: show_verification_ui
          - hook: session
        password:
          hooks:
          - hook: show_verification_ui
        webauthn:
          hooks:
          - hook: show_verification_ui
          - hook: session
```

Notably I can’t seem to remove the “session” hook from the “oidc” and “webauthn” parts of the registration config.
We are using Oauth2 to manage a user’s login state - with them starting the process by sending them to the Oauth2 authorization endpoint when they are not logged in. A user starts the signup by clicking the Don't have an account? Sign up link on the login ui.

**What happens**

When a user registers with this method they are redirected to our oauth redirect URL with a valid code which can be exchanged for an access_token for our APIs, without being prompted to validate their email address.
This only is the behaviour on initial registration, if the user logs in again they are taken to the verification flow as I would expect.

**What I would expect to happen**
Before being redirect back to our application I would expect them to be prompted to validate their email address.
I can work around this by detecting that the user has an unverified email address and sending them to login again, but this isn’t a particularly good user experience.

### Reproducing the bug

An example ory network project which exhibits the behaviour is at `vigorous-colden-7ny5zqli19`

An example react app that can be used to repro the bug and is here: https://github.com/blackbird-simon/ory-registration-verification-reproduction

### Version

Ory Network

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

Ory Network
