### ISSUE TITLE
Traits from the Update Registration API Flow payload with OIDC get lost

### ISSUE THREAD

**Issue by openscript** [ory/kratos#3417]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When a user registers via the [self-service registration](https://www.ory.sh/docs/kratos/reference/api#tag/frontend/operation/updateRegistrationFlow) flow with OIDC and traits are provided, the user will be created, but the traits are missing.

![image](https://github.com/ory/kratos/assets/1105080/590b9b58-631e-4597-a930-bd2af49be9dd)

### Reproducing the bug

1. Have a identity schema which has additional traits. (example below)
1. Initialize registration flow:
    ```
    curl --request GET \
      --url 'https://example.com/.ory/kratos/public/self-service/registration/api?return_session_token_exchange_code=true&return_to=example%3A%2F%2Fregistration
    ```
1. Submit registration flow:
    ```
    curl --request POST \
      --url 'https://example.com/.ory/kratos/public/self-service/login?flow=dac5c20f-20ba-4357-8163-edb2e60a5216' \
      --header 'content-type: application/json' \
      --data '{
      "method": "oidc",
      "provider": "google",
      "traits": {
        "lang": "de-CH",
        "tac": "1234",
        "dp": "4321"
      }
    }'
    ```
1. Kratos redirects you to the OIDC provider. Open the provided link inside a browser.
1. Authenticate successfully with an account
1. Check via [admin api](https://www.ory.sh/docs/kratos/reference/api#tag/identity/operation/listIdentities) if the new identity contains the traits

### Relevant configuration

```yml
My identity schema looks like this:


{
  "$id": "https://example.com/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Customer",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "lang": {
          "type": "string",
          "title": "Language"
        },
        "tac": {
          "type": "string",
          "title": "Terms and Conditions"
        },
        "dp": {
          "type": "string",
          "title": "Data Protection"
        },
        "email": {
          "type": "string",
          "format": "email",
          "title": "Email",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

This topic was discussed here too: https://github.com/ory/kratos/discussions/3413

It worked with 0.12 for many months, but it doesn't with version 1.0.0. We directly migrated from 0.12 to 1.0.0.
