### ISSUE TITLE
Confusing alterations of identities database metadata fields following changes in user settings

### ISSUE THREAD

**Issue by mserikov** [ory/kratos#3432]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After the user updates settings (e.g., by changing the username from the settings page), the fields `metadata_public` and `metadata_admin` in the identities DB table store values of 'null' as strings.

### Reproducing the bug

Steps to reproduce:

1. Execute the following command: docker-compose -f quickstart.yml -f quickstart-selinux.yml -f quickstart-postgres.yml -f quickstart-standalone.yml up --build --force-recreate.
2. Register 2 new users using the default implementation of ory-kratos_kratos-selfservice-ui-node.
3. Access the kratos database and observe the `identities` table, focusing on the `metadata_public` and `metadata_admin` fields. You will notice that the actual values are [NULL].
4. Log in as one of these users.
5. Navigate to the settings page and modify the First Name/Last Name.
6. Access the kratos database again and observe the `identities` table, paying attention to the `metadata_public` and `metadata_admin` fields. The actual values will appear as 'null', represented as a string.

### Relevant log output

![image](https://github.com/ory/kratos/assets/17761509/8e54beb4-5458-4078-b221-1e6f91b27161)

### Relevant configuration

```yml
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "title": "First Name",
              "type": "string"
            },
            "last": {
              "title": "Last Name",
              "type": "string"
            }
          }
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

### Version

1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
