### ISSUE TITLE
Fix broken schema tests

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#347]
**Describe the bug**

For some reason, this definition

```
  login:
    request_lifespan: 10m
    before:
      hooks: "#/definitions/selfServiceBefore"
```

fails with

```
=== RUN   TestSchemas
=== RUN   TestSchemas/test_.schema/config.schema.json
=== RUN   TestSchemas/test_.schema/config.schema.json/case=schema_main_test_case_allKeys_expects_success
    TestSchemas/test_.schema/config.schema.json/case=schema_main_test_case_allKeys_expects_success: schema_test.go:150: 
        	Error Trace:	schema_test.go:150
        	Error:      	Received unexpected error:
        	            	there were validation errors: I[#/selfservice] S[#/properties/selfservice] validation failed
        	            	  I[#/selfservice/login] S[#/properties/selfservice/properties/login] validation failed
        	            	    I[#/selfservice/login/before] S[#/properties/selfservice/properties/login/properties/before/const] value must be "#/definitions/selfServiceBefore"
```

Changing it to

```
  login:
    request_lifespan: 10m
    before:
      hooks:
        const: "#/definitions/selfServiceBefore"
```

makes this pass but looks strange?

We should also add some docs how this module works. I have disabled / skipped the tests for now.
