### ISSUE TITLE
Identity `state_changed_at` and `metadata_` fields get unset after recovery & update settings

### ISSUE THREAD

**Issue by matthiastz** [ory/kratos#3473]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The identity fields `state_changed_at`, `metadata_public` and `metadata_admin` get unset (either empty string or `null`) after a successful recovery flow (including update on settings page).

![Bildschirmfoto 2023-09-01 um 08 52 33](https://github.com/ory/kratos/assets/23010759/c07ddd7d-03bf-46e7-8d43-3110b4a65be8)

1) green box: normal identities that we created via API (HTTP POST), login works normally as it should
2) red box: identities where we did a password recovery flow and as a direct followup step we redirected the client to the settings page, where the user did update either userName/mail (method [profile](https://www.ory.sh/docs/kratos/self-service/flows/user-settings#update-profile)) or (we even tried another [method password](https://www.ory.sh/docs/kratos/self-service/flows/user-settings#update-password) here) the user updated the password. In both cases the same effect: The identity fields `state_changed_at`, `metadata_public` and `metadata_admin` get unset 🐛 

### Reproducing the bug

1. Start Password recovery flow
![Bildschirmfoto 2023-09-01 um 09 02 14](https://github.com/ory/kratos/assets/23010759/73b5db5c-a0cd-424b-9ec5-cf549b71d792)

2. Enter your email
![Bildschirmfoto 2023-09-01 um 09 02 29](https://github.com/ory/kratos/assets/23010759/91c064f4-9b61-4501-8384-e41ceae5cb27)

3. Enter recovery code & submit
![Bildschirmfoto 2023-09-01 um 09 02 43](https://github.com/ory/kratos/assets/23010759/ba439405-5b1f-4221-be71-73a3aad8af05)

4. Get redirected to the Settings page and update either userName/email or password. Submit
(API call in use: https://www.ory.sh/docs/kratos/reference/api#tag/frontend/operation/updateSettingsFlow)

### Relevant log output

```shell
2023-08-31 11:37:32	d5051cd1825bc34d606039d14e9b3e08 POST /self-service/settings completed handling request

2023-08-31 11:37:32	d5051cd1825bc34d606039d14e9b3e08 POST /self-service/settings Completed all PostSettingsPrePersistHooks and PostSettingsPostPersistHooks.

2023-08-31 11:37:32	d5051cd1825bc34d606039d14e9b3e08 POST /self-service/settings An identity's settings have been updated.

2023-08-31 11:37:32	d5051cd1825bc34d606039d14e9b3e08 POST /self-service/settings 	
Running PostSettingsPrePersistHooks.
```

### Relevant configuration

```yml
data:
  identity.email.and.username.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/identity.email.and.username.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "username": {
              "type": "string",
              "minLength": REDACTED,
              "title": "Username",
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                }
              }
            },
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  },
                  "webauthn": {
                    "identifier": true
                  },
                  "totp": {
                    "account_name": true
                  }
                },
                "recovery": {
                  "via": "email"
                },
                "verification": {
                  "via": "email"
                }
              },
              "maxLength": REDACTED
            }
          },
          "required": [],
          "additionalProperties": false
        }
      }
    }


  kratos:
      config:          
        identity:
          schemas:
            - id: email_un_v1
              url: file:///etc/config/kratos/identity.email.and.username.schema.json
            - id: default
              url: file:///etc/config/kratos/identity.email.and.username.schema.json

        selfservice:
          default_browser_return_url: /
          flows:
            registration:
              enabled: false
            recovery:
              enabled: true
            settings:
              ui_url: /settings
```

### Version

v1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
