### ISSUE TITLE
Public API endpoint `/sessions/whoami` doesn't recognise Authorization header

### ISSUE THREAD

**Issue by mikebevz** [ory/kratos#3497]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Public API endpoint `/sessions/whoami` doesn't recognise Authorization header (bearer session token). According to [docs](https://www.ory.sh/docs/identities/sign-in/check-session-token-cookie-api) it should be working.

If I set `Cookie` header then it works as expected.

In case Authorization header is used the service returns

```json
{
    "error": {
        "code": 401,
        "status": "Unauthorized",
        "request": "1ab02e6b-4b8f-46dc-a8ca-5f0e9a0d094e",
        "reason": "No valid session credentials found in the request.",
        "message": "The request could not be authorized"
    }
}
```

### Reproducing the bug

1. Get a Kratos session token
2. Send a GET request to `/sessions/whoami` endpoint using `Authorization` header (`Authorization: Bearer {session_token}`
3. Service returns 401
4. Send a GET request to `/sessions/whoami` endpoint using `Cookie` header (`Cookie: cookie_name={session_token}`
5. The endpoint returns user's session data

### Relevant log output

```shell
{
  "audience": "audit",
  "error": {
    "debug": "",
    "message": "request does not have a valid authentication session",
    "reason": "No active session was found in this request.",
    "status": "Unauthorized",
    "status_code": 401
  },
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "authorization": "[redacted]",
      "cache-control": "no-cache",
      "x-envoy-expected-rq-timeout-ms": "3000",
      "x-envoy-external-address": "[redacted]",
      "x-envoy-original-path": "/.auth/idp/public/sessions/whoami",
      "x-forwarded-for": "[redacted]",
      "x-request-id": "1ab02e6b-4b8f-46dc-a8ca-5f0e9a0d094e"
    },
    "host": "[redacted]",
    "method": "GET",
    "path": "/sessions/whoami",
    "query": null,
    "remote": "[redacted]",
    "scheme": "http"
  },
  "level": "info",
  "msg": "No valid session found.",
  "service_name": "Ory Kratos",
  "service_version": "v1.0.0",
  "time": "2023-09-13T09:47:22.857553395Z"
}

{
  "audience": "application",
  "error": {
    "debug": "",
    "message": "The request could not be authorized",
    "reason": "No valid session credentials found in the request.",
    "status": "Unauthorized",
    "status_code": 401
  },
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "authorization": "[redacted]",
      "cache-control": "no-cache",
      "postman-token": "",
      "user-agent": "[redacted]",
      "x-envoy-original-path": "/.auth/idp/public/sessions/whoami",
      "x-forwarded-for": "[redacted]",
      "x-request-id": "1ab02e6b-4b8f-46dc-a8ca-5f0e9a0d094e"
    },
    "host": "[redacted]",
    "method": "GET",
    "path": "/sessions/whoami",
    "query": null,
    "remote": "[redacted]",
    "scheme": "http"
  },
  "http_response": {
    "status_code": 401
  },
  "level": "info",
  "msg": "An error occurred while handling a request",
  "service_name": "Ory Kratos",
  "service_version": "v1.0.0",
  "time": "2023-09-13T09:47:22.857627342Z"
}

{
  "http_request": {
    "headers": {
      "accept": "*/*",
      "accept-encoding": "gzip, deflate, br",
      "authorization": "[redacted]",
      "cache-control": "no-cache",
      "x-envoy-original-path": "/.auth/idp/public/sessions/whoami",
      "x-forwarded-for": "[redacted]",
      "x-request-id": "1ab02e6b-4b8f-46dc-a8ca-5f0e9a0d094e"
    },
    "host": "[redacted]",
    "method": "GET",
    "path": "/sessions/whoami",
    "query": null,
    "remote": "[redacted]",
    "scheme": "http"
  },
  "http_response": {
    "headers": {
      "cache-control": "private, no-cache, no-store, must-revalidate",
      "content-type": "application/json",
      "vary": "Origin"
    },
    "size": 206,
    "status": 401,
    "text_status": "Unauthorized",
    "took": 961101
  },
  "level": "info",
  "msg": "completed handling request",
  "time": "2023-09-13T09:47:22.857736829Z"
}
```

### Relevant configuration

```yml
kratos:
  config:
    dsn: 
    secrets:
      cookie: []
      cipher: []
      default: []
    hashers:
      argon2:
        iterations: 1
        # parallelism: 1
        salt_length: 16
        key_length: 32
        expected_duration: 500ms
        expected_deviation: 500ms
        dedicated_memory: 1GB
        memory: 128MB
      bcrypt:
        cost: 12
      algorithm: argon2
    ciphers:
      algorithm: xchacha20-poly1305

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: [redacted]
        from_address: hello@[redacted]
        from_name: [redacted]
    selfservice:
      default_browser_return_url: https://${auth_ui_domain_name}/
      ## flows ##
      #
      flows:
        logout:
          after:
            default_browser_return_url: https://${auth_ui_domain_name}
        registration:
          enabled: true
          lifespan: 10m
          ui_url: https://${auth_ui_domain_name}/registration
          after:
            password:
              hooks:
                - hook: session
                - hook: show_verification_ui
        login:
          lifespan: 1h
          ui_url: https://${auth_ui_domain_name}/login

        ## Email and Phone Verification and Account Activation Configuration ##
        #
        verification:
          ui_url: https://${auth_ui_domain_name}/verification
          after:
            default_browser_return_url: https://${auth_ui_domain_name}
          lifespan: 1h
          use: link
          notify_unknown_recipients: false
          enabled: true
        ## Account Recovery Configuration ##
        #
        recovery:
          ui_url: https://${auth_ui_domain_name}/recovery
          lifespan: 1h
          use: link
          notify_unknown_recipients: false
          enabled: true

        error:
          ui_url: https://${auth_ui_domain_name}/error


        settings:
          lifespan: 1h
          privileged_session_max_age: 15m
          required_aal: highest_available
          ui_url: https://${auth_ui_domain_name}/settings
      ## methods ##
      #
      methods:
        link:
          config:
            lifespan: 1h
            base_url: https://${auth_ui_domain_name}/
          enabled: true
        code:
          config:
            lifespan: 1h
          enabled: true
        password:
          config:
            haveibeenpwned_enabled: true
            max_breaches: 0
            ignore_network_errors: true
            min_password_length: 8
            identifier_similarity_check_enabled: true
            haveibeenpwned_host: api.pwnedpasswords.com
          enabled: true
        totp:
          config:
            issuer: "${auth_ui_domain_name}"
          enabled: true
        lookup_secret:
          enabled: true
        webauthn:
          config:
            rp:
              id: [redacted]
              display_name: [redacted]
              icon: https://www.ory.sh/an-icon.png
              origin: https://${auth_ui_domain_name}
            passwordless: true
          enabled: true
        oidc:
          config:
            base_redirect_uri: https://${auth_ui_domain_name}/oauth/callback
          enabled: true
        profile:
          enabled: true
      allowed_return_urls:
        - https://${auth_ui_domain_name}
        - http://${auth_ui_domain_name}
        - https://${domain_name}
        - http://${domain_name}
    oauth2_provider:
      url: ${hydra_admin_k8s_uri}
    serve:
      public:
        cors:
          allowed_origins:
            - https://${auth_ui_domain_name}
            - http://${auth_ui_domain_name}
          enabled: true
        base_url: https://${auth_ui_domain_name}/.auth/idp/public/
        request_log:
          disable_for_health: true
      admin:
        base_url: ${kratos_admin_k8s_url}
        request_log:
          disable_for_health: true
    log:
      leak_sensitive_values: false
      redaction_text: "[redacted]"
      format: json
      level: info
    cookies:
    #   path: "/"
    #   same_site: Lax
      domain: "${auth_ui_domain_name}"

    session:
      lifespan: 1h
      cookie:
        name: "smak_dev_mid_session"
        domain: ${auth_ui_domain_name}
        persistent: false
        path: "/"
        same_site: Lax
      earliest_possible_extend: 1h
      whoami:
        required_aal: highest_available
    version: v1.0.0
    dev: false
    help: true
    sqa-opt-out: false
    watch-courier: false
    expose-metrics-port: 4435
    database:
      cleanup:
        sleep:
          tables: 1m
        older_than: 0ns
        batch_size: 1
  automigration:
    enabled: true
  identitySchemas:
    "identity.default.schema.json": |
      {
        "$id":"https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
        "$schema":"http://json-schema.org/draft-07/schema#",
        "title":"Person",
        "type":"object",
        "properties":{
            "traits":{
              "type":"object",
              "properties":{
                  "email":{
                    "type":"string",
                    "format":"email",
                    "title":"E-Mail",
                    "minLength": 3,
                    "maxLength": 512,
                    "ory.sh/kratos":{
                        "credentials":{
                          "password":{
                              "identifier":true
                          },
                          "webauthn": {
                            "identifier": true
                          },
                          "totp": {
                            "account_name": true
                          }
                        },
                        "recovery":{
                          "via":"email"
                        },
                        "verification":{
                          "via":"email"
                        }
                    }
                  },
                  "phone":{
                    "type":"string",
                    "title":"Phone Nr",
                    "format":"tel",
                    "ory.sh/kratos":{
                        "credentials":{
                          "password":{
                              "identifier":true
                          }
                        }
                    }
                  },
                  "codename":{
                    "type":"string",
                    "title":"Codename",
                    "minLength":3,
                    "maxLength":128,
                    "ory.sh/kratos":{
                        "credentials":{
                          "password":{
                              "identifier":true
                          }
                        }
                    }
                  }
              },
              "required":[],
              "additionalProperties":false
            }
        }
      }
      
# Default values for kratos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# -- Number of replicas in deployment
replicaCount: 1
# -- Deployment update strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: "25%"
service:
  admin:
    enabled: true
    type: ClusterIP
    # -- Load balancer IP
    # loadBalancerIP: ""
    port: 80
    # -- The service port name. Useful to set a custom service port name if it must follow a scheme (e.g. Istio)
    name: http
    # -- Provide custom labels. Use the same syntax as for annotations.
    labels: {}
    # -- If you do want to specify annotations, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  public:
    enabled: true
    type: ClusterIP
    # -- Load balancer IP
    # loadBalancerIP: ""
    port: 80
    # -- The service port name. Useful to set a custom service port name if it must follow a scheme (e.g. Istio)
    name: http
    # -- Provide custom labels. Use the same syntax as for annotations.
    labels: {}
    # -- If you do want to specify annotations, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
```

### Version

v1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm
