### ISSUE TITLE
Invalidate all other sessions when password is changed

### ISSUE THREAD

**Issue by dreksx** [ory/kratos#3513]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Context and scope

Currently, the Kratos system does not automatically log out or invalidate other active sessions when a user changes their password. This poses a significant security risk as it allows potentially unauthorized individuals to maintain access to the account even after the password has been updated.

One possible approach to solve this - could be to attach a `web_hook` to `settings` actions, like this, and implement invalidation of sessions on the client side.
```
selfservice:
  settings:
    after:
      password:
        hooks:
          - hook: web_hook
            config:
              url: http://client-service/settings/callback
 ```

However, Kratos already implemented a `revoke_active_sessions ` hook for this case, but we cannot use this hook inside the settings after actions.

### Goals and non-goals

The primary goal is to enhance the security of user accounts by ensuring that a password change automatically invalidates all other active sessions.

### The design

Provide the option to add the  `revoke_active_sessions` hook to the actions sections of the self-service settings.

```
selfservice:
  settings:
    after:
      password:
        hooks:
          - hook: revoke_active_sessions
 ```
