### ISSUE TITLE
Native flow ignores redirect_to in oidc flow if session in browser already established

### ISSUE THREAD

**Issue by luflow** [ory/kratos#3543]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

selfhosted

### Describe the bug

We found a strange behavior in Kratos thats somehow leading to ignoring our set `redirect_to` URL and always falling back to the `default_browser_return_url`. It happens in the case where a session in a browser is already established, but afterwards an API native flow is started with a 3rd-party Login. The app opens the browser, the session at the 3rd party is still valid so redirects are taking place and then I suddenly land on `default_browser_return_url` instead of the `redirect_to` specified in the API call.

### Reproducing the bug

Steps to reproduce behavior:

Precondition: You need a native app where the native login flow can be executed with the Kratos API

1. Setup kratos with an OIDC flow e.g. with GitHub including some simple mapping (email and firstname)
2. Setup correct `allowed_return_urls` and `default_browser_return_url` for your selfservice flows
3. Use an android device (where sessions in browser are shared between a native app and browser)
4. Open the android browser and login to your website with the GitHub OIDC integration, stay logged in
5. Go to your native app and start a login flow via the API with the GitHub OIDC integration with a `redirect_to` to `myapp://module/login`
6. After the flows redirects in the browser are done, now you will not be redirected to `myapp://module/login` but instead to `default_browser_return_url`

Somehow it looks like the redirect_to information gets lost on the way?

As soon as I logout in the browser manually and start from Step 5 again - everything works as intended and the native app flow gets completed correctly.

### Relevant log output

```shell
no errors shown in logs.
```

### Relevant configuration

```yml
selfservice:
  default_browser_return_url: https://yourwebsite.com
  allowed_return_urls:
    - https://yourwebsite.com/auth
    - https://yourwebsite.com/

    # App Links
    - myapp://
    - myapp://module/login
  methods:
    profile:
      enabled: true
    password:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      config:
        providers:
          - id: github
            provider: github
            client_id: <enter client id>
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogIGVtYWlsX3ZlcmlmaWVkOiBmYWxzZSwKfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOwp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogewogICAgICBbaWYgJ2VtYWlsJyBpbiBjbGFpbXMgJiYgY2xhaW1zLmVtYWlsX3ZlcmlmaWVkIHRoZW4gJ2VtYWlsJyBlbHNlIG51bGxdOiBjbGFpbXMuZW1haWwsCiAgICAgIFtpZiAnbmFtZScgaW4gY2xhaW1zIHRoZW4gJ25hbWUnIGVsc2UgbnVsbF06IHsKICAgICAgICBmaXJzdDogY2xhaW1zLm5hbWUsCiAgICAgIH0sCiAgICB9LAogIH0sCn0="
            scope:
              - user:email
```

### Version

Kratos v1.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes
