### ISSUE TITLE
SMTP Connection URI is required on HTTP delivery strategy

### ISSUE THREAD

**Issue by albertilagan** [ory/kratos#3559]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

`smtp.connection_uri` is still required even though `delivery_strategy` is set to `http`

### Reproducing the bug

Config
```
courier:
  delivery_strategy: http
  http:
    request_config:
      url: http://localhost:3000/api/webhook/kratos
      method: POST
      auth:
        type: api_key
        config:
          name: "token"
          value: "abcd1234"
          in: header
```

### Relevant log output

```shell
`courier.smtp.connection_uri: <nil>`
                                 ^-- one or more required properties is missing
```

### Relevant configuration

```yml
courier:
  delivery_strategy: http
  http:
    request_config:
      url: http://localhost:3000/api/webhook/kratos
      method: POST
      auth:
        type: api_key
        config:
          name: "token"
          value: "abcd1234"
          in: header
```

### Version

master

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Other

### Additional Context

workaround, adding dummy smtp connection uri.

```
courier:
  delivery_strategy: http
  http:
    request_config:
      url: http://localhost:3000/api/webhook/kratos
      method: POST
      auth:
        type: api_key
        config:
          name: "token"
          value: "abcd1234"
          in: header
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
```

**Comment by reginbald** [comment]
Encountered this as well

**Comment by matthiastz** [comment]
the issue seems not to be fixed, still. would be cool to re-open this issue

when I try to run kratos with docker-compose and kratos v1.1.0

`kratos.yml`
```
...
courier:
  delivery_strategy: http
  http:
    request_config:
      url: http://localhost:8080/api/someUri
```

I still get this error:

```
The configuration contains values or keys which are invalid:
courier.smtp.connection_uri: <nil>
                             ^-- one or more required properties are missing

time=2024-03-19T15:22:01Z level=error msg=Unable to instantiate configuration. audience=application error=map[message:I[#/courier/smtp] S[#/properties/courier/properties/smtp/required] missing properties: "connection_uri"] service_name=Ory Kratos service_version=v1.1.0
Error: I[#/courier/smtp] S[#/properties/courier/properties/smtp/required] missing properties: "connection_uri"
```

same issue occurs when I try to deploy it on k8s with v1.1.0 (tried both chart version 0.35.0 and 0.40.0):

kratos config:
```
....
        courier:
          delivery_strategy: http
          http:
            request_config:
              url: <REDACTED>
              headers:
                ...
```
kratos pod log:
```
The configuration contains values or keys which are invalid:
courier.smtp.connection_uri: <nil>
^-- one or more required properties are missing

time=2024-03-19T14:54:59Z level=error msg=Unable to instantiate configuration. audience=application error=map[message:I[#/courier/smtp] S[#/properties/courier/properties/smtp/required] missing properties: "connection_uri"] service_name=Ory Kratos service_version=v1.1.0
Error: I[#/courier/smtp] S[#/properties/courier/properties/smtp/required] missing properties: "connection_uri"
Usage:
kratos serve [flags]

Flags:
-c, --config strings Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
--dev Disables critical security features to make development easier
-h, --help help for serve
--sqa-opt-out Disable anonymized telemetry reports - for more information please visit https://www.ory.sh/docs/ecosystem/sqa
--watch-courier Run the message courier as a background task, to simplify single-instance setup

I[#/courier/smtp] S[#/properties/courier/properties/smtp/required] missing properties: "connection_uri"
```
