### ISSUE TITLE
Error if mail courier responds with HTTP code 202

### ISSUE THREAD

**Issue by reginbald** [ory/kratos#3582]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I've configured Kratos to send emails via HTTP requests to Sendgrid. 
Sendgrid responds with the HTTP code 202 whitch causes Kratos to throw an error.

### Reproducing the bug

Use the following configuration
```
    courier:
      delivery_strategy: http
      http:
        request_config:
          url: https://api.sendgrid.com/v3/mail/send
          method: POST
          body: base64://__EMAIL_JSONNET__
          headers:
            Content-Type: application/json
          auth:
            type: api_key
            config:
              name: Authorization
              value: Bearer __SENDGRID_API_KEY__
              in: header
      smtp: # Kratos bug, see: https://github.com/ory/kratos/issues/3559
        connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
```

### Relevant log output

```shell
{"audience":"application","level":"info","msg":"[DEBUG] POST https://api.sendgrid.com/v3/mail/send","service_name":"Ory Kratos","service_version":"v1.0.0","time":"2023-10-18T14:42:01.306963577Z"}
{"audience":"application","error":{"message":"unable to dispatch mail delivery because upstream server replied with status code 202","stack_trace":"stack trace could not be recovered from error type *errors.errorString"},"level":"error","message_id":"a90cccfc-4b4f-421d-9194-8ac60f393dbf","message_subject":"Please verify your email address","message_template_type":"verification_code_valid","message_type":"email","msg":"sending mail via HTTP failed.","service_name":"Ory Kratos","service_version":"v1.0.0","time":"2023-10-18T14:42:01.314791402Z"}
```

### Version

oryd/kratos:v1.0.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
