### ISSUE TITLE
OTEL tracing in configuration does not work

### ISSUE THREAD

**Issue by rauanmayemir** [ory/kratos#3626]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Kratos does not send traces when setting the tracing in config.
It validates it during pod boot, but then it's silent.

### Reproducing the bug

Try with this config:

```
tracing:
  service_name: auth-kratos
  provider: otel
  providers:
    otlp:
      insecure: true
      server_url: collector-opentelemetry-collector.observability.svc.cluster.local:4318
```

`server_url` is valid, I tried sending other traces to it.

### Version

v1.0.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
