### ISSUE TITLE
Can't add phone number when phone-based verification is on

### ISSUE THREAD

**Issue by aran** [ory/kratos#3632]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am setting up sms based verification for a phone identity field. When adding a phone number to a profile that is registered through another mechanism (google oidc in this case), I encounter an error from Kratos, detailed in the log output below. It looks like the system is using an email verification code path.

### Reproducing the bug

Repro steps:
1. Register a user with oidc, oidc provider provides email but not phone
2. Visit settings page and add a phone number and hit save
3. Observe log messages below and 500 response from Ory. 

### Relevant log output

```shell
[kratos] time=2023-11-19T06:40:25Z level=debug msg=An identity's settings have been updated. func=github.com/ory/kratos/selfservice/flow/settings.(*HookExecutor).PostSettingsHook <snip>

[kratos] time=2023-11-19T06:40:25Z level=info msg=Sending out verification email with verification code. func=github.com/ory/kratos/selfservice/strategy/code.(*Sender).SendVerificationCodeTo file=/project/selfservice/strategy/code/code_sender.go:210 audience=audit email_address=+18885555555 identity_id=b37ac690-0bcc-4c69-aaf0-bc9db4317f68 service_name=Ory Kratos service_version=v1.0.0 verification_code_id=613773ab-0be8-4a88-9952-e20cc180a2a5 verification_link_token=996923 via=phone

[kratos] time=2023-11-19T06:40:25Z level=info msg=Encountered self-service settings error. func=github.com/ory/kratos/selfservice/flow/settings.(*ErrorHandler).WriteFlowError file=/project/selfservice/flow/settings/error.go:148 audience=audit error=map[message:expected one of [email] but got phone stack_trace:stack trace could not be recovered from error type stringsx.errUnknownCase]
```

### Relevant configuration

```yml
Relevant kratos.yaml:

courier:
  sms:
    enabled: true
    from: ""
    request_config:
      method: "POST"
      url: "http://...
      
  ...
      verification:
      after:
        default_browser_return_url: "http://localhost:8000/"
      enabled: true
      ui_url: "http://localhost:8000/verification"
      use: "code"
...
  methods:
    code:
      enabled: true
    link:
      enabled: false
...
version: "v1.0.0"
                
  
      
example schema.json:


{
    "title": "Person",
    "type": "object",
    "properties": {
        "traits": {
            "type": "object",
            "properties": {
                "name": {
                    "title": "Name",
                    "type": "string"
                },
                "given_name": {
                    "title": "Given Name",
                    "type": "string"
                },
                "phone": {
                    "title": "Phone",
                    "type": "string",
                    "format": "tel",
                    "ory.sh/kratos": {
                        "credentials": {
                            "password": {
                                "identifier": true
                            }
                        },
                        "verification": {
                            "via": "phone"
                        }
                    }
                },
                "email": {
                    "title": "Email",
                    "type": "string",
                    "format": "email",
                    "ory.sh/kratos": {
                        "credentials": {
                            "password": {
                                "identifier": true
                            }
                        }
                    }
                }
            },
            "anyOf": [
                {
                    "required": ["email"]
                },
                {
                    "required": ["phone"]
                }
            ],
            "additionalProperties": false
        }
    }
}
```

### Version

1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes
