### ISSUE TITLE
LinkedIn social login oidc broken for new setups

### ISSUE THREAD

**Issue by schlauerlauer** [ory/kratos#3655]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi,

I ran into an issue after setting up the oidc login flow using linkedin:

LinkedIn returns a `401 Unauthorized` on `https://api.linkedin.com/v2/me`, Kratos errors and the User can't login using LinkedIn.

This is because Linkedin changed the userinfo endpoints.
Specificly the `ProfileUrl` and `EmailUrl` in `selfservice/strategy/oidc/provider_linkedin.go` is not valid anymore for new oauth2 apps registered in linkedin.

They may still work in old apps, I'm not sure!

I've got it working [with these changes](https://github.com/ory/kratos/compare/master...schlauerlauer:kratos:master).

Thank you :)

### Reproducing the bug

1. follow the [documentation](https://www.ory.sh/docs/kratos/social-signin/linkedin) to setup a oidc login with linkedin
2. click `login with linkedin` and authorize login in linkedin
3. user get's redirected to error page with error `500 internal server error`

### Relevant configuration

```yml
selfservice:
  oidc:
    config:
      providers:
        - id: "linkedin"
          provider: "linkedin"
          client_id: "REDACTED"
          client_secret: "REDACTED"
          issuer_url: "https://www.linkedin.com"
          auth_url: "https://www.linkedin.com/oauth/v2/authorization"
          token_url: "https://www.linkedin.com/oauth/v2/accessToken"
          mapper_url: "file:///etc/config/kratos/jsonnet/linkedin.data-mapper.jsonnet"
          scope:
            - "email" # these are the new scopes given by linkedin
            - "profile"
            - "openid"
```

### Version

v1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

Relevant thread by another product which ran into the same issue: [auth0 forum](https://community.auth0.com/t/the-linkedin-login-is-deprecated-updating-to-the-new-scopes-is-necessary/113696)
