### ISSUE TITLE
`/version` endpoint giving 404 error on Public API

### ISSUE THREAD

**Issue by chrispump** [ory/kratos#3715]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The `/version` endpoint of Kratos only seems to work within requests via the admin API, other than documented here:
https://www.ory.sh/docs/kratos/reference/api#tag/metadata/operation/getVersion

If the endpoint is called via the public API, a 404 error is returned.

### Reproducing the bug

1. `docker compose -f quickstart.yml up -d`
2. `curl 'http://127.0.0.1:4433/version'`
3. `404 page not found` is returned
4. `curl 'http://127.0.0.1:4434/admin/version'`
5. `{"version":"v1.0.0"}` is returned

### Relevant configuration

```yml
version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v1.0.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
```

### Version

1.0.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose
