### ISSUE TITLE
 Getting error on email submission on recovery - "message": "named insert: ERROR: column \"channel\" of relation \"courier_messages\" does not exist (SQLSTATE 42703)"

### ISSUE THREAD

**Issue by tanmayvaij** [ory/kratos#3952]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am using your ory kratos react native example, and I have also setup the ory kratos server. When I go to the recovery page and enter email, I get internal server error

```
 error details: {
  "code": 500,
  "status": "Internal Server Error",
  "message": "named insert: ERROR: column \"channel\" of relation \"courier_messages\" does not exist (SQLSTATE 42703)"
}

```

### Reproducing the bug

I am using your ory kratos react native example  https://github.com/ory/kratos-selfservice-ui-react-native/

And I am using docker compose  and kratos yml to setup ory kratos. This is my docker-compose.yml
```
version: "3.9"
services:
  postgres-tanmayvaij:
    image: postgres:9.6-alpine
    restart: unless-stopped
    hostname: kratos-database-tanmayvaij
    container_name: kratos-database-tanmayvaij
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres-dump:/dump
      - postgres-data-kratos:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  kratos-migrate-tanmayvaij:
    image: oryd/kratos:v1.1.0
    hostname: kratos-migrate-tanmayvaij
    container_name: kratos-migrate-tanmayvaij
    depends_on:
      - postgres-tanmayvaij
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: "no"

  kratos-tanmayvaij:
    image: oryd/kratos:v1.1.0
    hostname: kratos-tanmayvaij
    container_name: kratos-tanmayvaij
    depends_on:
      - kratos-migrate-tanmayvaij
    environment:
      - DSN=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - ${KRATOS_EXPOSE_PORT}:4433
      - ${KRATOS_ADMIN_EXPOSE_PORT}:4434
    volumes:
      - ./kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier --sqa-opt-out
    restart: unless-stopped

  kratos-selfservice-ui-node-tanmayvaij:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    hostname: kratos-selfservice-ui-node-tanmayvaij
    container_name: kratos-selfservice-ui-node-tanmayvaij
    depends_on:
      - kratos-migrate-tanmayvaij
    environment:
      - KRATOS_PUBLIC_URL=http://kratos-tanmayvaij:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:${KRATOS_EXPOSE_PORT}/
    ports:
      - ${KRATOS_UI_EXPOSE_PORT}:3000
    restart: unless-stopped

volumes:
  postgres-data-kratos:
  kratos:

networks:
  default:
    name: kratos-tanmayvaij-net

```

When I go to the recovery page and enter email, I get internal server error
```
 error details: {
  "code": 500,
  "status": "Internal Server Error",
  "message": "named insert: ERROR: column \"channel\" of relation \"courier_messages\" does not exist (SQLSTATE 42703)"
}
```

Is there anything I am missing ??
@aeneasr @vinckr  @zepatrik

### Version

1.9.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
