### ISSUE TITLE
Required fields aren't actually required

### ISSUE THREAD

**Issue by koenmtb1** [ory/kratos#400]
**Describe the bug**
My schema has email, firstName and lastName as required values but when requesting the registration their required values is set to false.

**Reproducing the bug**
1. Setup your schema to have a required field.
2. Initiate a registration request by redirecting browser to Kratos.
3. Use the request queryParam to get the registration request.
4. See the response of that request.

_Server configuration_
Kratos Configuration
```yaml
dsn: OMITTED
identity:
  traits:
    default_schema_url: file://home/ory/user.schema.json
selfservice:
  strategies:
    password:
      enabled: true
  logout:
    redirect_to: OMITTED
  settings:
    request_lifespan: 1h
    privileged_session_max_age: 1h
    after:
      password:
        default_return_to: OMITTED
      profile:
        default_return_to: OMITTED
  verify:
    request_lifespan: 1h
    link_lifespan: 24h
  login:
    request_lifespan: 1h
    after:
      default_return_to: OMITTED
  registration:
    request_lifespan: 10m
    after:
      default_return_to: OMITTED
      password:
        hooks:
        - hook: verify
        - hook: session
courier:
  smtp:
    connection_uri: OMITTED
    from_address: OMITTED
serve:
  admin:
    host: 0.0.0.0
    port: 4434
  public:
    host: 0.0.0.0
    port: 4433
urls:
  self:
    public: OMITTED
    admin: OMITTED
  mfa_ui: OMITTED
  login_ui: OMITTED
  settings_ui: OMITTED
  registration_ui: OMITTED
  error_ui: OMITTED
  verify_ui: OMITTED
  default_return_to: OMITTED
  whitelisted_return_to_urls: OMITTED
secrets:
  session:
    - OMITTED
hashers:
  argon2:
    OMITTED
```
User Schema
```json
{
    "$id": "file:///home/ory/user.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "User",
    "type": "object",
    "properties": {
        "email": {
            "title": "E-Mail",
            "type": "string",
            "format": "email",
            "ory.sh/kratos": {
                "credentials": {
                    "password": {
                        "identifier": true
                    }
                },
                "verification": {
                    "via": "email"
                }
            }
        },
        "firstName": {
            "type": "string"
        },
        "lastName": {
            "type": "string"
        }
    },
    "required": [
        "email",
        "firstName",
        "lastName"
    ],
    "additionalProperties": false
}
```
**Expected behavior**
To have the required fields set as required.

**Environment**

- Version: v0.2.1-alpha.1
- Environment: Kubernetes using oryd/kratos:latest docker image.

**Additional context**
![image](https://user-images.githubusercontent.com/7266861/81480763-e7e4c500-922b-11ea-9693-c86953b11236.png)
