### ISSUE TITLE
Cookie setting SameSite not applied when accessing provider from iframe hosted app in MS Dynamics environment

### ISSUE THREAD

**Issue by Saibot27** [ory/kratos#4006]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

We are running an app as communication widget within MS Dynamics using Dynamics 365 Channel Integration Framework 2.0 and are self-hosting Ory Kratos. Ory Kratos service has been started in production mode by omitting the --dev flag, all traffic runs over HTTPS.

We configured Kratos to use **same_site: None** for cookies.

```
cookies:
  domain: xxx.net
  same_site: None

session:
  lifespan: 1m
  cookie:
    same_site: None
```
    
When redirecting to the choosen provider we get an error message.

_"code": 400,
"debug": "key ory_kratos_oidc_auth_code_session does not exist in cookie: ory_kratos_continuity\...
"reason": "The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!",
"status": "Bad Request",
"message": "no resumable session found"_

We can see from ChromeDev tools that cookie _ory_kratos_continuity_ was set but with **SameSite=Lax**.

Why are cookie settings not applied?

### Reproducing the bug

1. add/edit cookie setting same_site in kratos.yml
2. restart kratos service in production mode (omitt --dev flag)
3. tail -f /var/log/kratos/kratos.log
5. link to Ory Kratos
6. select provider

### Relevant log output

```shell
time=2024-07-17T13:33:41+02:00 level=info msg=started handling request http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 accept-encoding:gzip, deflate, br, zstd accept-language:de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 cache-control:max-age=0 connection:close content-length:126 content-type:application/x-www-form-urlencoded cookie:[csrf_token_zzzz=] correlationid:tst-mmmm dnt:1 origin:https://my.domain.net referer:https://my.domain.net/auth/login?flow=4437d641-e2eb-4ec5-af4d-185c0ce33e14 sec-ch-ua:"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Windows" sec-fetch-dest:iframe sec-fetch-mode:navigate sec-fetch-site:same-origin sec-fetch-user:?1 upgrade-insecure-requests:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 x-forwarded-for:10.30.32.126, 10.2.50.145 x-forwarded-proto:https x-real-ip:10.2.50.145] host:my.domain.net method:POST path:/self-service/login query:flow=4437d641-e2eb-4ec5-af4d-185c0ce33e14 remote:127.0.0.1:47326 scheme:http]
time=2024-07-17T13:33:41+02:00 level=info msg=completed handling request http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 accept-encoding:gzip, deflate, br, zstd accept-language:de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 cache-control:max-age=0 connection:close content-length:126 content-type:application/x-www-form-urlencoded cookie:[csrf_token_zzzz=] correlationid:tst-mmmm dnt:1 origin:https://my.domain.net referer:https://my.domain.net/auth/login?flow=4437d641-e2eb-4ec5-af4d-185c0ce33e14 sec-ch-ua:"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Windows" sec-fetch-dest:iframe sec-fetch-mode:navigate sec-fetch-site:same-origin sec-fetch-user:?1 upgrade-insecure-requests:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 x-forwarded-for:10.30.32.126, 10.2.50.145 x-forwarded-proto:https x-real-ip:10.2.50.145] host:my.domain.net method:POST path:/self-service/login query:flow=4437d641-e2eb-4ec5-af4d-185c0ce33e14 remote:127.0.0.1:47326 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate location:https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=87bf4998-298c-41b5-abd0-1fdf70b16ab3&redirect_uri=https%3A%2F%2Fmy.domain.net%2Fauth%2Fapi%2Fself-service%2Fmethods%2Foidc%2Fcallback%2Fmicrosoft&response_type=code&scope=profile+email+openid&state=91f3db40-5ca0-4a44-ab4c-d1180a30c5d8 set-cookie:[ory_kratos_continuity=ssss; Path=/; Expires=Fri, 16 Aug 2024 11:33:41 GMT; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax] vary:Origin] size:0 status:303 text_status:See Other took:70.6453ms]
time=2024-07-17T13:33:41+02:00 level=info msg=started handling request http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 accept-encoding:gzip, deflate, br, zstd accept-language:de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 cache-control:max-age=0 connection:close cookie:[csrf_token_zzzz=] correlationid:tst-dddd dnt:1 referer:https://my.domain.net/ sec-ch-ua:"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Windows" sec-fetch-dest:iframe sec-fetch-mode:navigate sec-fetch-site:cross-site sec-fetch-user:?1 upgrade-insecure-requests:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 x-forwarded-for:10.30.32.126, 10.2.50.145 x-forwarded-proto:https x-real-ip:10.2.50.145] host:my.domain.net method:GET path:/self-service/methods/oidc/callback/microsoft query:code=0.xxxx.yyyy remote:127.0.0.1:47340 scheme:http]
time=2024-07-17T13:33:41+02:00 level=error msg=An error occurred and is being forwarded to the error user interface. audience=application error=map[debug:key ory_kratos_oidc_auth_code_session does not exist in cookie: ory_kratos_continuity
github.com/ory/kratos/x.SessionGetString.func1
        /project/x/cookie.go:27
github.com/ory/kratos/x.SessionGetString
        /project/x/cookie.go:46
github.com/ory/kratos/continuity.(*ManagerCookie).sid
        /project/continuity/manager_cookie.go:97
github.com/ory/kratos/continuity.(*ManagerCookie).container
        /project/continuity/manager_cookie.go:109
github.com/ory/kratos/continuity.(*ManagerCookie).Continue
        /project/continuity/manager_cookie.go:64
github.com/ory/kratos/selfservice/strategy/oidc.(*Strategy).validateCallback
        /project/selfservice/strategy/oidc/strategy.go:254
github.com/ory/kratos/selfservice/strategy/oidc.(*Strategy).handleCallback
        /project/selfservice/strategy/oidc/strategy.go:298
github.com/ory/kratos/selfservice/strategy.disabledWriter
        /project/selfservice/strategy/handler.go:25
github.com/ory/kratos/selfservice/strategy.IsDisabled.func1
        /project/selfservice/strategy/handler.go:30
github.com/ory/kratos/x.NoCacheHandle.func1
        /project/x/nocache.go:18
github.com/ory/kratos/x.NoCacheHandle.func1
        /project/x/nocache.go:18
github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387
github.com/ory/nosurf.(*CSRFHandler).handleSuccess
        /go/pkg/mod/github.com/ory/nosurf@v1.2.7/handler.go:234
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP
        /go/pkg/mod/github.com/ory/nosurf@v1.2.7/handler.go:191
github.com/urfave/negroni.Wrap.func1
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/kratos/x.glob..func1
        /project/x/clean_url.go:12
github.com/urfave/negroni.HandlerFunc.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
        /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2047
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:198
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2047
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2047
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:68
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2047
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:76
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2047
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1
        /go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:165
net/http.HandlerFunc.ServeHTTP
        /usr/local/go/src/net/http/server.go:2047
github.com/ory/x/prometheusx.Metrics.instrumentHandlerStatusBucket.func1
        /go/pkg/mod/github.com/ory/x@v0.0.392/prometheusx/metrics.go:108 message:no resumable session found reason:The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again! status:Bad Request status_code:400] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 accept-encoding:gzip, deflate, br, zstd accept-language:de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 cache-control:max-age=0 connection:close cookie:[csrf_token_zzzz=] correlationid:tst-dddd dnt:1 referer:https://my.domain.net/ sec-ch-ua:"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Windows" sec-fetch-dest:iframe sec-fetch-mode:navigate sec-fetch-site:cross-site sec-fetch-user:?1 upgrade-insecure-requests:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 x-forwarded-for:10.30.32.126, 10.2.50.145 x-forwarded-proto:https x-real-ip:10.2.50.145] host:my.domain.net method:GET path:/self-service/methods/oidc/callback/microsoft query:code=0.xxxx.yyyy remote:127.0.0.1:47340 scheme:http] service_name=Ory Kratos service_version=v0.10.0
time=2024-07-17T13:33:41+02:00 level=info msg=completed handling request http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 accept-encoding:gzip, deflate, br, zstd accept-language:de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 cache-control:max-age=0 connection:close cookie:[csrf_token_zzzz=] correlationid:tst-dddd dnt:1 referer:https://my.domain.net/ sec-ch-ua:"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126" sec-ch-ua-mobile:?0 sec-ch-ua-platform:"Windows" sec-fetch-dest:iframe sec-fetch-mode:navigate sec-fetch-site:cross-site sec-fetch-user:?1 upgrade-insecure-requests:1 user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 x-forwarded-for:10.30.32.126, 10.2.50.145 x-forwarded-proto:https x-real-ip:10.2.50.145] host:my.domain.net method:GET path:/self-service/methods/oidc/callback/microsoft query:code=0.xxxx.yyyy remote:127.0.0.1:47340 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate content-type:text/html; charset=utf-8 location:https://my.domain.net/auth/error?id=jjjj vary:Origin] size:113 status:303 text_status:See Other took:12.757112ms]
time=2024-07-17T13:33:41+02:00 level=info msg=started handling request http_request=map[headers:map[accept:application/json, text/plain, */* connection:close user-agent:axios/0.21.4] host:localhost:4433 method:GET path:/self-service/errors query:id=jjjj remote:127.0.0.1:47352 scheme:http]
time=2024-07-17T13:33:41+02:00 level=info msg=completed handling request http_request=map[headers:map[accept:application/json, text/plain, */* connection:close user-agent:axios/0.21.4] host:localhost:4433 method:GET path:/self-service/errors query:id=jjjj remote:127.0.0.1:47352 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate content-type:application/json; charset=utf-8 set-cookie:[csrf_token_pppp; Path=/; Domain=sysnodes.net; Max-Age=31536000; HttpOnly; Secure; SameSite=Lax] vary:Origin] size:4116 status:200 text_status:OK took:8.851186ms]
```

### Relevant configuration

```yml
kratos.yml

version: v0.10.0

dsn: postgres://...

cookies:
  domain: xxx.net
  same_site: None

session:
  lifespan: 1m
  cookie:
    same_site: None

serve:
  public:
    base_url: https://yyy.xxx.net/auth/api/
    host: localhost
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - https://yyy.xxx.net
      allowed_methods:
        - GET
        - OPTIONS
        - PUT
        - PATCH
        - DELETE

selfservice:
  default_browser_return_url: https://yyy.xxx.net/auth/zzz
  methods:
    oidc:
      config:
        providers:
          - client_id: ...
            client_secret: ...
            id: microsoft
            label: Microsoft
            mapper_url: base64://...      
			microsoft_tenant: organizations
            provider: microsoft
            scope:
			- profile
            - email

      enabled: true
    password:
      enabled: false

  flows:
    error:
      ui_url: https://yyy.xxx.net/auth/error

    settings:
      ui_url: https://yyy.xxx.net/auth/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: false
      ui_url: https://yyy.xxx.net/auth/recovery
	  
	  - profile
            - email

      enabled: true
    password:
      enabled: false

  flows:
    error:
      ui_url: https://yyy.xxx.net/auth/error

    settings:
      ui_url: https://yyy.xxx.net/auth/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: false
      ui_url: https://yyy.xxx.net/auth/recovery
```

### Version

Ory Kratos service_version v0.10.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other
