### ISSUE TITLE
Settings flow unable to update password and vulnerability discovered 

### ISSUE THREAD

**Issue by dextercodo** [ory/kratos#4065]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

When trying to update settings flow to using password / profile methods, I get the following error
```
{
    "id": 4000007,
    "text": "An account with the same identifier (email, phone, username, ...) exists already.",
    "type": "error"
}
```

Unable to perform either operation. 
what's more interesting is that when using "profile" method and parsing a new email address, that gets a 200 response and adds a new email identifier record. 

### Reproducing the bug

1. start a registration flow: GET  https://api.loopin.io/public/auth/self-service/registration/browser
2. complete the registration flow: POST https://api.loopin.io/public/auth/self-service/registration?flow=<id>

```
registration body
{
    "csrf_token": "<token>",
    "method": "password",
    "password" "anythingYouLike" 
    "traits": {
        "email":"example@gmail.com",
        "name": {
            "first":"John",
            "last":"Doe"
        }
    }
}
```

3. start a settings flow: GET https://api.loopin.io/public/auth/self-service/settings/browser
4. complete the settings flow: POST https://api.loopin.io/public/auth/self-service/settings?flow=<id>

```
settings flow fail body
{
    "csrf_token": "<token>",
    "method": "password",
    "password" "anythingYouLike" 
}
```

### Relevant log output

```shell
level=info msg=Encountered self-service settings error. func=github.com/ory/kratos/selfservice/flow/settings.(*ErrorHandler).WriteFlowError file=/go/src/github.com/ory/kratos/selfservice/flow/settings/error.go:148 audience=audit error=map[message:I[#/] S[] an account with the same identifier (email, phone, username, ...) exists already stack_trace:
github.com/ory/kratos/schema.NewDuplicateCredentialsError
/go/src/github.com/ory/kratos/schema/errors.go:168
github.com/ory/kratos/selfservice/flow/settings.(*HookExecutor).PostSettingsHook
/go/src/github.com/ory/kratos/selfservice/flow/settings/hook.go:224
github.com/ory/kratos/selfservice/flow/settings.(*Handler).updateSettingsFlow
/go/src/github.com/ory/kratos/selfservice/flow/settings/handler.go:622
github.com/ory/kratos/selfservice/flow/settings.(*Handler).RegisterPublicRoutes.(*Handler).IsAuthenticated.func7
/go/src/github.com/ory/kratos/session/handler.go:853
github.com/ory/kratos/x.(*RouterPublic).POST.NoCacheHandle.func1
/go/src/github.com/ory/kratos/x/nocache.go:21
github.com/ory/kratos/x.(*RouterPublic).Handle.NoCacheHandle.func1
/go/src/github.com/ory/kratos/x/nocache.go:21
github.com/julienschmidt/httprouter.(*Router).ServeHTTP
/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387
github.com/ory/nosurf.(*CSRFHandler).handleSuccess
/go/pkg/mod/github.com/ory/nosurf@v1.2.7/handler.go:234
github.com/ory/nosurf.(*CSRFHandler).ServeHTTP
/go/pkg/mod/github.com/ory/nosurf@v1.2.7/handler.go:185
github.com/ory/kratos/cmd/daemon.servePublic.MaxBytesHandler.func4
/usr/local/go/src/net/http/server.go:3846
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
github.com/urfave/negroni.(*Negroni).UseHandler.Wrap.func1
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/kratos/x.init.func1
/go/src/github.com/ory/kratos/x/clean_url.go:15
github.com/urfave/negroni.HandlerFunc.ServeHTTP
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/rs/cors.(*Cors).ServeHTTP
/go/pkg/mod/github.com/rs/cors@v1.11.0/cors.go:324
github.com/ory/kratos/cmd/daemon.servePublic.func1
/go/src/github.com/ory/kratos/cmd/daemon/serve.go:114
github.com/urfave/negroni.HandlerFunc.ServeHTTP
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1
/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:284
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:142
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1
/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:92
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:104
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func1
/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/instrument_server.go:234
net/http.HandlerFunc.ServeHTTP
/usr/local/go/src/net/http/server.go:2171
```

### Relevant configuration

```yml
cookies:
  same_site: Lax
serve:
  public:
    base_url: https://api.loopin.io/public/auth/
    cors:
      enabled: true
      allowed_origins:
        - https://app.loopin.io
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie

selfservice:
  default_browser_return_url: https://app.loopin.io
  allowed_return_urls:
    - https://app.loopin.io

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: https://app.loopin.io/error

    settings:
      ui_url: https://app.loopin.io/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    logout:
      after:
        default_browser_return_url: https://app.loopin.io/login

    login:
      ui_url: https://app.loopin.io/login
      lifespan: 30m

    registration:
      lifespan: 30m
      ui_url: https://app.loopin.io/registration
      after:
        password:
          hooks:
            - hook: session
```

### Version

1.2.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes
