### ISSUE TITLE
Before verification webhook not called

### ISSUE THREAD

**Issue by camero2734** [ory/kratos#4110]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Ory Network Project
Self-hosted

### Describe the bug

I have set up a `before` verification `web_hook`, but it doesn't seem to be fired in most circumstances. It doesn't seem to be fired:
- Upon initial registration
- When I update `settings` to add a new email

In both situations, I receive the verification email -- once I verify my email, the `after` verification webhook _is_ fired, but in neither case is the `before` fired.

The only situation in which it is fired is if I manually create a new verification (`GET /self-service/verification/browser`), but the expected behavior (for me at least) would be for it to be fired anytime a verification flow is created, even if it's implicitly as part of another flow.

### Reproducing the bug

1. Configure kratos with `before` verification hook
2. Register an account
3. The webhook will not be triggered

### Relevant configuration

```yml
selfservice:
  flows:
    verification:
      use: code
      enabled: true
      ui_url: https://localhost:8080/ui
      lifespan: 30m
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://localhost:3000/before_verification
              method: POST
              body: file:///before_verification.jsonnet # this just returns { ctx: ctx }
```

### Version

1.2.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Docker Compose

### Additional Context

I was able to get the desired behavior by adding
```go
if err := e.r.VerificationExecutor().PreVerificationHook(w, r, verificationFlow); err != nil {
  return err
}
```

before `CreateVerificationFlow` in `selfservice/hook/verification.go`. Happy to put up a PR if this is indeed the desired behavior for Kratos.
