### ISSUE TITLE
Courier channel config: templated URL

### ISSUE THREAD

**Issue by renom** [ory/kratos#4159]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

Some SMS services require sending `GET` requests with phone, message etc. in a query string to send SMS.

### Describe your ideal solution

Support templating URL:
```yaml
request_config:
  url: "https://domain.com/send_sms?phone={recipient}&text={body}"
  method: "GET"
```

### Workarounds or alternatives

\-

### Version

1.3.0
