### ISSUE TITLE
Support for go templating in config files

### ISSUE THREAD

**Issue by BierDav** [ory/kratos#4165]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

When configuring kratos for selfhosting it is often quite useful to have the ability of using go templating. A usage example would be that it is more clean to use environment variables from the config file than using the very long environment variable names to directly influence the config.

```yaml
dsn: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?search_path=${POSTGRES_SCHEMA},public&sslmode=disable&max_conns=20&max_idle_conns=4
serve:
  public:
    base_url:  ${SITE_URL}/kratos
  admin:
    base_url: http://kratos:4434/
```

Currently my config looks something like this and I run `eval` on every container start:
```yaml
 entrypoint:
      - sh
      - -c
      - |
        eval "echo \"$(cat /home/ory/temp-config.yml)\"" > /home/ory/config.yml \
        && echo "==========" \
        && cat /home/ory/config.yml \
        && echo "==========" \
        && kratos -c /home/ory/config.yml migrate sql -e --yes \
        && kratos serve -c /home/ory/config.yml --watch-courier
```

But unfortunately this also breaks config hot reload.

### Describe your ideal solution

With the ability of go templating the same as  `traefik` for example does. It could look like this:
 ```yaml
dsn: postgres://{{ env "POSTGRES_USER" }}:{{ env "POSTGRES_PASSWORD" }}@{{ env "POSTGRES_HOST" }}:{{ evn "POSTGRES_PORT" }}/{{ env "POSTGRES_DB" }}?search_path={{ env "POSTGRES_SCHEMA" }},public&sslmode=disable&max_conns=20&max_idle_conns=4
serve:
  public:
    base_url:  {{ env "SITE_URL" }}/kratos
  admin:
    base_url: http://kratos:4434/
```

Without any additional configuration for the container required you now get also hot reload like in `traefik`.

Actually I am not a go developer, but I suppose that it is a quite small change to support this, because this should be basically be already be built into go.

Btw. this should actually at best be supported accross all ory products

### Workarounds or alternatives

For this specific use case a special syntax could also be introduced that is replaced with the environment variables.

### Version

1.3.0
