### ISSUE TITLE
Kratos doesn't trigger web_hook after login (OIDC)

### ISSUE THREAD

**Issue by kimnh-0823** [ory/kratos#4172]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

I am using Kratos self-hosted and have successfully configured OIDC login with Google and GitHub. I have been able to log in with Google. Currently, I need to set up a Kratos webhook so that after a successful login, it will call a webhook to create an account for another service. However, Kratos does not trigger the webhook on the first login. If I continue to log out and then log back in, I will see Kratos trigger the webhook.

### Reproducing the bug

1. Deploy Kratos + Self-service (Kratos Node UI)
2. Login with Google
3. Check Kratos trace logs, it doesn't trigger the webhook after a successful login
4. Logout Kratos and then log back in with same Google account
5. Check Kratos trace logs, it triggers the webhook successfully

### Relevant configuration

```yml
selfservice:
  default_browser_return_url: http://${ACCOUNT_DOMAIN}
  allowed_return_urls:
    - http://${ACCOUNT_DOMAIN}
    - http://${MY_APP_DOMAIN}
  methods:
    password:
      enabled: false
    totp:
      enabled: true
      config:
        issuer: My Account
    lookup_secret:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: "${OIDC_GITHUB_CLIENT_ID}"
            client_secret: "${OIDC_GITHUB_CLIENT_SECRET}"
            issuer_url: https://github.com
            mapper_url: "base64://${OIDC_GITHUB_MAPPER_BASE64}"
            scope:
              - user:email
              - read:user
          - id: google
            provider: google
            client_id: "${OIDC_GOOGLE_CLIENT_ID}"
            client_secret: "${OIDC_GOOGLE_CLIENT_SECRET}"
            issuer_url: http://accounts.google.com
            mapper_url: "base64://${OIDC_GOOGLE_MAPPER_BASE64}"
            scope:
              - openid
              - email
              - profile
  flows:
    error:
      ui_url: http://${ACCOUNT_DOMAIN}/error
    settings:
      ui_url: http://${ACCOUNT_DOMAIN}/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://${ACCOUNT_DOMAIN}/recovery
    verification:
      enabled: true
      ui_url: http://${ACCOUNT_DOMAIN}/verification
      after:
        default_browser_return_url: http://${ACCOUNT_DOMAIN}
    logout:
      after:
        default_browser_return_url: http://${ACCOUNT_DOMAIN}/login
    login:
      ui_url: http://${ACCOUNT_DOMAIN}/login
      lifespan: 10m
      after:
        hooks:
          - hook: web_hook
            config:
              url: ${MY_APP_DOMAIN}/api/rest/upsert-user
              method: POST
              body: base64://${CREATE_USER_BASE64}
              can_interrupt: false
              emit_analytics_event: true
              response:
                ignore: true
                parse: false
              auth:
                type: api_key
                config:
                  name: Authorization
                  value: ${WEBHOOK_SECRET}
                  in: header
    registration:
      lifespan: 10m
      ui_url: http://${ACCOUNT_DOMAIN}/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session
```

### Version

1.1.0, 1.3.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by akkie** [comment]
Works for me as expected with this config:
```

...
    login:
      ui_url: https://${ACCOUNT_DOMAIN}/login
      lifespan: 1h

    registration:
      lifespan: 1h
      ui_url: https://${ACCOUNT_DOMAIN}/signup
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://api:5300/hooks/kratos/registration
                method: POST
                body: file:///etc/config/kratos/hooks/registration.jsonnet
                response:
                  ignore: false
                  parse: true
            - hook: session
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://api:5300/hooks/kratos/registration
                method: POST
                body: file:///etc/config/kratos/hooks/registration.jsonnet
                response:
                  ignore: false
                  parse: true
            - hook: session
```
