### ISSUE TITLE
Setting Subject Source to 'oid' crashes kratos

### ISSUE THREAD

**Issue by mustafacansevinc** [ory/kratos#4269]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

When `oid` is used as the `subject_source` for Microsoft in the OIDC provider configuration, kratos crashes and stops running.

### Reproducing the bug

1. Define `subject_source: oid` in the configuration under `selfservice.methods.oidc.config.providers[].subject_source`
2. Run kratos

### Relevant log output

```shell
I[#/selfservice/methods/oidc/config/providers/0] S[#/properties/selfservice/properties/methods/properties/oidc/properties/config/properties/providers/items/$ref] doesn't validate with "#/definitions/selfServiceOIDCProvider"
2025-01-16 10:15:08   I[#/selfservice/methods/oidc/config/providers/0/subject_source] S[#/definitions/selfServiceOIDCProvider/properties/subject_source/enum] value must be one of "userinfo", "me"
```

### Relevant configuration

```yml
selfservice:
  methods: 
    oidc:
      enabled: true
      config:
        providers:
          - id: microsoft
            provider: microsoft
            subject_source: oid
```

### Version

1.3.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Docker Compose

### Additional Context

Related to https://github.com/ory/kratos/issues/4170
