### ISSUE TITLE
Login via OIDC skips email verification for unverified address

### ISSUE THREAD

**Issue by atif-konasl** [ory/kratos#4283]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

I am encountering an issue with my self-hosted Ory Kratos setup. When a user registers using the Microsoft OIDC provider login and does not complete the email verification step during the registration flow, subsequent login attempts with the same email account bypass the email verification process. This allows the user to log in successfully, even though their email address remains unverified.

The expected behaviour is for the system to enforce email verification before allowing the user to log in. However, the verification step is being skipped entirely during subsequent logins.

### Reproducing the bug

Steps to reproduce the behaviour:

1. Navigate to the login page and select Partner Login with Microsoft as the login method.
2. You are redirected to the Microsoft login page, where you log in using a valid Microsoft account that has not been previously registered in the system.
3. After successfully logging in on the Microsoft side, you are redirected back to the system's email verification step to verify your email address.
4. Close the browser or page without completing the email verification process.
5. Open a new login page (ensure the browser cache is cleared or use a private/incognito window) and attempt to log in again using the Partner Login with Microsoft, using the same account as above.

**Result:** You are logged in successfully without being prompted for email verification, despite the email address remaining unverified.

### Relevant log output

```shell

```

### Relevant configuration

```yml
flows:
    login:
      lifespan: 2h
      after:
        hooks:
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=login # sets via SELFSERVICE_FLOWS_LOGIN_AFTER_HOOKS_0_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                ignore: true
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=login # sets via SELFSERVICE_FLOWS_LOGIN_AFTER_HOOKS_1_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                ignore: true
        password:
          hooks:
            - hook: web_hook
              config:
                # url: http://localhost:10805/foo?flow=login # sets via SELFSERVICE_FLOWS_LOGIN_AFTER_PASSWORD_HOOKS_0_CONFIG_URL
                method: "POST"
                body: file:///app/hook.segment_identify.jsonnet
                response:
                  ignore: true
            - hook: web_hook
              config:
                # url: http://localhost:10805/foo?flow=login # sets via SELFSERVICE_FLOWS_LOGIN_AFTER_PASSWORD_HOOKS_1_CONFIG_URL
                method: "POST"
                body: file:///app/hook.segment_identify.jsonnet
                response:
                  ignore: true
            - hook: require_verified_address
        oidc:
          hooks:
            - hook: require_verified_address

    settings:
      lifespan: 2h
      privileged_session_max_age: 15m
      required_aal: highest_available
      after:
        hooks:
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=settings # sets via SELFSERVICE_FLOWS_SETTINGS_AFTER_HOOKS_0_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                ignore: true

    recovery:
      enabled: true
      use: code
      lifespan: 2h
      notify_unknown_recipients: false
      after:
        hooks:
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=recovery # sets via SELFSERVICE_FLOWS_RECOVERY_AFTER_HOOKS_0_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                ignore: true

    verification:
      enabled: true
      use: code
      lifespan: 2h
      after:
        hooks:
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=verification # sets via SELFSERVICE_FLOWS_VERIFICATION_AFTER_HOOKS_0_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                ignore: true

    registration:
      lifespan: 2h
      enabled: true
      after:
        hooks:
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=registration # sets via SELFSERVICE_FLOWS_REGISTRATION_AFTER_HOOKS_0_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                parse: true
          - hook: web_hook
            config:
              # url: http://localhost:10805/foo?flow=registration # sets via SELFSERVICE_FLOWS_REGISTRATION_AFTER_HOOKS_1_CONFIG_URL
              method: "POST"
              body: file:///app/hook.segment_identify.jsonnet
              response:
                ignore: true
        password:
          hooks:
            - hook: web_hook
              config:
                # url: http://localhost:10805/foo?flow=registration # sets via SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS_0_CONFIG_URL
                method: "POST"
                body: file:///app/hook.segment_identify.jsonnet
                response:
                  ignore: false
                  # parse: true # TODO: find the solution, this does not work currently
            - hook: web_hook
              config:
                # url: http://localhost:10805/foo?flow=registration # sets via SELFSERVICE_FLOWS_REGISTRATION_AFTER_PASSWORD_HOOKS_1_CONFIG_URL
                method: "POST"
                body: file:///app/hook.segment_identify.jsonnet
                response:
                  ignore: true
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: web_hook
              config:
                # url: http://localhost:10805/foo?flow=registration # sets via SELFSERVICE_FLOWS_REGISTRATION_AFTER_OIDC_HOOKS_0_CONFIG_URL
                method: "POST"
                body: file:///app/hook.segment_identify.jsonnet
                response:
                  ignore: false
                  # parse: true # TODO: find the solution, this does not work currently
            - hook: web_hook
              config:
                # url: http://localhost:10805/foo?flow=registration # sets via SELFSERVICE_FLOWS_REGISTRATION_AFTER_OIDC_HOOKS_1_CONFIG_URL
                method: "POST"
                body: file:///app/hook.segment_identify.jsonnet
                response:
                  ignore: true
            - hook: show_verification_ui

    error:
      ui_url: /.ory/kratos/self-service/errors
```

### Version

v1.3.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
