### ISSUE TITLE
Can not update an identity using PUT /identities/{id}

### ISSUE THREAD

**Issue by avamonitoring** [ory/kratos#435]
**Describe the bug**
When using the identity schema below, I can not update an identity using the `PUT /identities/{id} `endpoint:

```
{
  "$id": "https://example.com/registration.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "email": {
      "type": "string",
      "format": "email",
      "ory.sh/kratos": {
        "credentials": {
          "password": {
            "identifier": true
          }
        },
        "verification": {
          "via": "email"
        }
      }
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string"
    },
    "mobileNumber": {
      "type": "string"
    },
    "timeZone": {
      "type": "string"
    },
    "language": {
      "type": "string"
    }
  }
}
```

**Reproducing the bug**

To reproduce, first create an identity:

```
curl -v -X POST http://localhost:4434/identities -d "{\"traits_schema_id\":\"default\",\"traits\":{\"email\":\"john.doe2@acme.com\",\"lastName\":\"Doe\",\"firstName\":\"John\"}}"
< HTTP/1.1 201 Created
< Content-Type: application/json; charset=utf-8
< Location: http://127.0.0.1:4434/identities/be0ab6e6-25b0-453a-af33-f6a2efbb2ea4
< Date: Wed, 27 May 2020 09:08:27 GMT
< Content-Length: 395
<
{"id":"be0ab6e6-25b0-453a-af33-f6a2efbb2ea4","traits_schema_id":"default","traits_schema_url":"http://127.0.0.1:4433/schemas/default","traits":{"email":"john.doe2@acme.com","lastName":"Doe","firstName":"John"},"addresses":[{"id":"5b2806ea-658d-4c07-a161-b2f4efe4bce1","value":"john.doe2@acme.com","verified":false,"via":"email","verified_at":null,"expires_at":"2020-05-28T09:08:27.084960997Z"}]}
```

Then, take the response body as request body and try to update the identity:

```
curl -v -X PUT http://localhost:4434/identities/be0ab6e6-25b0-453a-af33-f6a2efbb2ea4 -d "{\"id\":\"be0ab6e6-25b0-453a-af33-f6a2efbb2ea4\",\"traits_schema_id\":\"default\",\"traits_schema_url\":\"http://127.0.0.1:4433/schemas/default\",\"traits\":{\"email\":\"john.doe2@acme.com\",\"lastName\":\"Doe\",\"firstName\":\"John\"},\"addresses\":[{\"id\":\"5b2806ea-658d-4c07-a161-b2f4efe4bce1\",\"value\":\"john.doe2@acme.com\",\"verified\":false,\"via\":\"email\",\"verified_at\":null,\"expires_at\":\"2020-05-28T09:08:27.084960997Z\"}]}"
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< Date: Wed, 27 May 2020 09:17:36 GMT
< Content-Length: 363
<
{"error":{"code":403,"status":"Forbidden","reason":"A field was modified that updates one or more credentials-related settings. This action was blocked because an unprivileged method was used to execute the update. This is either a configuration issue or a bug and should be reported to the system administrator.","message":"The requested action was forbidden"}}
```

_Server logs_

time="2020-05-27T09:27:54Z" level=info msg="started handling request" method=PUT name="admin#http://127.0.0.1:4434" remote="127.0.0.1:56402" request=/identities/be0ab6e6-25b0-453a-af33-f6a2efbb2ea4
time="2020-05-27T09:27:54Z" level=error msg="An error occurred while handling a request" code=403 debug= details="map[]" error="The requested action was forbidden" reason="A field was modified that updates one or more credentials-related settings. This action was blocked because an unprivileged method was used to execute the update. This is either a configuration issue or a bug and should be reported to the system administrator." request-id= status=403 writer=JSON
time="2020-05-27T09:27:54Z" level=info msg="completed handling request" method=PUT name="admin#http://127.0.0.1:4434" remote="127.0.0.1:56402" request=/identities/be0ab6e6-25b0-453a-af33-f6a2efbb2ea4 status=403 text_status=Forbidden took=31.68649ms

_Server configuration_

```
courier:
      smtp:
        connection_uri: smtps://<user-password>@<host>:465?skip_ssl_verify=true
        from_address: <from>
    dsn: <dsn>
    hashers:
      argon2:
        iterations: 2
        key_length: 32
        memory: 1048576
        parallelism: 4
        salt_length: 16
    identity:
      traits:
        default_schema_url: file:///etc/config/default_identity_schema.json
        schemas:
        - id: other
          url: http://test.kratos.ory.sh/other-identity.schema.json
    log:
      format: text
      level: debug
    secrets:
      session:
      - <key-1>
      -<key-2>
    security:
      session:
        cookie:
          same_site: Lax
    selfservice:
      login:
        after:
          default_return_to: https://self-service/login/return_to
          oidc:
            hooks:
            - hook: revoke_active_sessions
          password:
            default_return_to: https://self-service/login/password/return_to
            hooks:
            - hook: revoke_active_sessions
        request_lifespan: 99m
      logout:
        redirect_to: http://127.0.0.1:4435/auth/login
      registration:
        after:
          default_return_to: https://self-service/registration/return_to
          password:
            hooks:
            - hook: session
            - hook: verify
        request_lifespan: 98m
      settings:
        after:
          default_return_to: https://self-service/settings/return_to
          password:
            default_return_to: https://self-service/settings/password/return_to
          profile:
            hooks:
            - hook: verify
        privileged_session_max_age: 5m
        request_lifespan: 99m
      strategies:
        oidc:
          config:
            providers:
            - client_id: a
              client_secret: b
              id: github
              mapper_url: http://test.kratos.ory.sh/default-identity.schema.json
              provider: github
          enabled: false
        password:
          enabled: true
      verify:
        link_lifespan: 24h
        request_lifespan: 1h
        return_to: https://self-service/verification/return_to
    serve:
      admin:
        host: 0.0.0.0
      public:
        host: 0.0.0.0
    urls:
      default_return_to: http://localhost:4000/login
      error_ui: <error-ui>
      login_ui: <login-ui>
      mfa_ui: http://127.0.0.1:4435/mfa
      registration_ui: http://127.0.0.1:4435/auth/registration
      self:
        admin: http://127.0.0.1:4434
        public: http://127.0.0.1:4433
      settings_ui: http://127.0.0.1:4435/settings
      verify_ui: http://127.0.0.1:4435/verify
      whitelisted_return_to_urls:
      - http://localhost:4000/login
```

**Expected behavior**

I expect it would be possible to update the identity. It should also be possible to update only the traits of the identity, without having to send the verifiable addresses.

**Environment**

- Ory Kratos: v0.3.0-alpha.1
- Database: Postgres 11
- Kubernetes 1.17.1 running in AWS
