### ISSUE TITLE
General after registration hooks running after method specific post registration hooks

### ISSUE THREAD

**Issue by FaeyUmbrea** [ory/kratos#4367]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

If I configure ory kratos to run hooks, I expect hooks configured in the general "hooks" section of the configuration to be run before the hooks in the method specific sections i.e. "oidc -> hooks" are executed. However, due to the oidc hook executing the "session" hook, the hooks in the "hooks" section do no longer execute. Implying that the execution order is inverted.

### Reproducing the bug

1. Configure kratos to use a web_hook after registration hook. 
2. Configure kratos to use the session hook in the after registration oidc event
3. Attempt to register using oidc
4. Behold as the webhook does not execute

### Relevant log output

```shell

```

### Relevant configuration

```yml
registration:
      lifespan: 10m
      ui_url: http://localhost:5173/registration
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://targeturl.com
              method: ""
              body: base64://jsonnet
        oidc:
          hooks:
            - hook: session
```

### Version

v1.3.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker
