### ISSUE TITLE
authentication_methods.provider not set on initial linked oidc session

### ISSUE THREAD

**Issue by peades** [ory/kratos#4417]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

Hi all,

When you have logged in using OIDC, `session.authentication_methods[].provider` should (and normally does) specify which OIDC provider you used.

However, the first time you log in with OIDC to a pre-existing account, you will have two `authentication_methods` set: one `oidc` and one `password` or `code`. However, `provider` is not set on either, in particular it's not set on the `oidc` method.

We user `authentication_methods` to determine if a user has signed in via one of our trusted partners, and give them certain elevated permissions if they have. This bug means that on their _first_ login with oidc, they do not get these elevated permissions.

Thanks!

### Reproducing the bug

- create a new identity using `code` method, with email as your identifier, immediately log out
- log in using `oidc` (generic) method with the same email as previous step
- need to pass a login challenge to link oidc to your account - use `code` method, linking complete
- go to /sessions/whoami
- `session.authentication_methods[].provider` is not defined

- log out, log back in using oidc
- `session.authentication_methods[].provider` is defined, and shows which OIDC provider you logged in with

### Relevant log output

```shell
OBSERVED /sessions/whoami
{
 ...
 "authentication_methods": [
    {
      "method": "code",
      "aal": "aal1",
      "completed_at": "2025-05-20T06:04:15.624797379Z"
    },
    {
      "method": "oidc",
      "aal": "aal1",
      "completed_at": "2025-05-20T06:04:15.667709066Z"
    }
  ],
...
}

EXPECTED /sessions/whoami
{
 ...
 "authentication_methods": [
    {
      "method": "code",
      "aal": "aal1",
      "completed_at": "2025-05-20T06:04:15.624797379Z"
    },
    {
      "method": "oidc",
      "provider": "REDACTED",
      "aal": "aal1",
      "completed_at": "2025-05-20T06:04:15.667709066Z"
    }
  ],
...
}
```

### Relevant configuration

```yml
kratos.yml
----------
oidc:
  config:
    providers:
      - id: headspace
        provider: generic
        client_id: REDACTED
        client_secret: REDACTED
        issuer_url: REDACTED
        mapper_url: file:///opt/kratos/config/REDACTED.mapper.jsonnet
        scope:
          - openid
          - profile
          - email
          - offline_access

REDACTED.mapper.jsonnet
-----------------------
local claims = std.extVar('claims');
local tokens = std.splitLimit(claims.name, " ", 1);

{
  identity: {
    traits: {
      email: claims.email,
      firstName: tokens[0],
      lastName: if std.length(tokens) > 1 then tokens[1] else ""
    },
  },
}
```

### Version

1.3.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary
