### ISSUE TITLE
Non-privileged traits require privileged session with verified email

### ISSUE THREAD

**Issue by dro-sh** [ory/kratos#4435]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

Updating of non-privileged also requires privileged session when user has verified email.

### Reproducing the bug

I use quickstart from [kratos repository](https://github.com/ory/kratos/blob/master/quickstart.yml) using [email-password schema](https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password/identity.schema.json). 
Do next steps:

1. In **kratos.yml** change [selfservice.flows.settings.privileged_session_max_age](https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password/kratos.yml#L40) to 1m and remove `required_aal: highest_available`, disable `haveibeenpwned_enabled` to set simplest password.
2. Run quickstart
```
git checkout v1.3.1
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --force-recreate
```
3. In http://localhost:4455/registration register user. Email: `test@example.com`. First Name: `First`. Last name: `Last`. Password: `test12345`.
4. Verify account in http://localhost:4436/
5. Open settings http://127.0.0.1:4455/settings
6. Try to change **First Name** and/or **Last Name** after privileged_session_max_age which equals 1m. System requires me to reauthenticate.
7. Change email and dont verify it.
8. Try to change **First Name** and/or **Last Name** after privileged_session_max_age which equals 1m. Fields successfully will be updated.

### Relevant log output

```shell

```

### Relevant configuration

```yml
version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  allowed_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    profile:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 1m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

### Version

1.3.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

### Additional Context

I found issue. See on second condition in method [requiresPrivilegedAccess](https://github.com/ory/kratos/blob/master/identity/manager.go#L428), it uses `reflect.DeepEqual` for deep `VerifiableAddresses` comparation. I create [gist](https://gist.github.com/dro-sh/2d339c5d5b6b22da50d6087ab3b22bc6) for testing deep comparation of `VerifiableAddresses`. And turn out that slices are not deeply equal then `VerifiedAt` is not nil.

So if email (the identifier for example below) not verified, user can change not protected traits without privileged session, because. But then email verified user must reauthenticate to get privileged session.
