### ISSUE TITLE
Linking an external account to newly added provider results in an internal server error

### ISSUE THREAD

**Issue by adrianmxb** [ory/kratos#532]
**Describe the bug**

Linking an external account for social logins to an identity that existed **prior** to adding the provider for said external account results in an 500 internal server error.

**Reproducing the bug**

1. Setup everything with the quickstart guide & ui-node app (don't setup any oidc providers yet!)
2. Register an account
3. Stop kratos/oathkeeper/...
4. Add an oidc provider
5.  Start kratos/oathkeeper/...
6. Try linking with the now added oidc provider
7. Request fails with response:
```json
[
  {
    "code": 500,
    "status": "Internal Server Error",
    "message": "identity does not have credential type oidc"
  }
]
```

**Expected behavior**

The external account should be linked.

**Environment**

- Version: latest
- Environment: Docker (Macbook Pro macOS 10.15.5)

**Additional context**

snippet of my .kratos.yml:

don't worry about the provider, i created it (pull request incoming, wink wink).
happens with **every** provider not just my custom one.

```yml
selfservice:
  strategies:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: discord
            provider: discord
            client_id: xxx
            client_secret: xxx
            mapper_url: file:///etc/config/kratos/oidc.discord.jsonnet
```
