### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by drwatsno** [ory/kratos#722]
**The problem**

We have been using Kratos in production for about a month and have faced the problem of periodic service restarts. According to the metrics, Kratos eats up all the memory available to it, and then restarts.

_Server configuration_

```yaml
selfservice:
  default_browser_return_url: http://***
  whitelisted_return_urls:
    - http://***
    - http://***/api/v1/oauth2/auth/login
  strategies:
    password:
      enabled: true

    oidc:
      enabled: true
      config:
        providers:
          - id: adfs
            provider: generic
            mapper_url: file:///etc/config/oidc-adfs-jsonet/oidc.adfs.jsonnet
            auth_url: http://***/api/v1/oauth2/auth
            token_url: http:/***/api/v1/oauth2/token
            client_id: ""
            client_secret: ""
            scope:
              - openid
              - profile
              - email
            issuer_url: https://fs.*.ru/adfs
  flows:
    error:
      ui_url: http://***/auth/error

    settings:
      ui_url: http://***/auth/settings
      privileged_session_max_age: 1m
      after:
        profile:
          hooks:
            - hook: verify

    recovery:
      enabled: false
      ui_url: http://***/auth/recovery

    verification:
      enabled: false
      ui_url: http://***/auth/verify
      after:
        default_browser_return_url: http://***/auth/

    logout:
      after:
        default_browser_return_url: http://***/auth/login

    login:
      ui_url: http://***/auth/login
      request_lifespan: 10m

    registration:
      request_lifespan: 10m
      ui_url: http://***/auth/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/identity-traits/identity.traits.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

```

**Environment**

- Version: 3c8d5e02b04686a1e0bfbd28caa0bc536e3414e4
- Environment: Docker

**Prometheus metrics**

![golang-generic-services4](https://user-images.githubusercontent.com/5576912/94793706-93f99900-03e3-11eb-8365-d6a043b470e2.png)
![golang-generic-services3](https://user-images.githubusercontent.com/5576912/94793710-952ac600-03e3-11eb-93b2-8fea19ce0367.png)
![golang-generic-services2](https://user-images.githubusercontent.com/5576912/94793714-952ac600-03e3-11eb-9e5d-bcda70a37e1c.png)
![golang-generic-services1](https://user-images.githubusercontent.com/5576912/94793715-95c35c80-03e3-11eb-842b-64292be534c8.png)
