### ISSUE TITLE
contrib/quickstart/access-rules.yml is missing 'recovery'

### ISSUE THREAD

**Issue by c0depwn** [ory/kratos#762]
**Describe the bug**

The oathkeeper configuration for the examples is missing 'recovery' inside `"ory:kratos-selfservice-ui-node:anonymous"` in the `match.url` string. This results in a `404` caused by oathkeeper on the `/recovery` of the selfservice-kratos-ui-node.

**Reproducing the bug**

1. follow the guide from the docs https://www.ory.sh/kratos/docs/guides/zero-trust-iap-proxy-identity-access-proxy/#running-ory-kratos-and-the-ory-oathkeeper-identity-and-access-proxy
2. Launch the recovery page on http://127.0.0.1:4455/recovery
3. JSON error:
```
{"error":{"code":404,"status":"Not Found","message":"Requested url does not match any rules"}}
```

**Expected behavior**

Proper redirect and initialisation of the recovery flow as describe in the kratos documentation.

**Environment**

- Version: latest
- Environment: macOS 10.15.6, Docker 2.4.0.0, Compose 1.27.4

**Suggested fix**

Change contrib/oathkeeper/access-rules.yml on line 24
```
-
  id: "ory:kratos-selfservice-ui-node:anonymous"
  upstream:
    preserve_host: true
    url: "http://kratos-selfservice-ui-node:4435"
  match:
    url: "http://127.0.0.1:4455/<{error,verify,auth/*,**.css,**.js}{/,}>" # add 'recovery' here
...
```
