### ISSUE TITLE
Failed to start: unable to connect to database, wrong retrying to connect sqlite3

### ISSUE THREAD

**Issue by wuhuizuo** [ory/kratos#771]
**Describe the bug**

**Reproducing the bug**

1. run `go build`
2. run `./kratos serve -c contrib/quickstart/kratos/email-password/kratos.yml` 
3.  check the server log, found loop retring but not finished starting.
 
_Server logs_

```
WARN[2020-10-16T21:56:11+08:00]/data/apps/github.com/ory/kratos/driver/registry_default.go:495 github.com/ory/kratos/driver.(*RegistryDefault).Init.func1() Unable to connect to database, retrying.      audience=application error=map[message:unsupported dialect 'sqlite3' trace:
github.com/gobuffalo/pop/v5.(*ConnectionDetails).withURL
        /data/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/connection_details.go:72
github.com/gobuffalo/pop/v5.(*ConnectionDetails).Finalize
        /data/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/connection_details.go:118
github.com/gobuffalo/pop/v5.NewConnection
        /data/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/connection.go:50
github.com/ory/kratos/driver.(*RegistryDefault).Init.func1
        /data/apps/github.com/ory/kratos/driver/registry_default.go:488
github.com/cenkalti/backoff.RetryNotify
        /data/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37
github.com/cenkalti/backoff.Retry
        /data/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/ory/kratos/driver.(*RegistryDefault).Init
        /data/apps/github.com/ory/kratos/driver/registry_default.go:486
github.com/ory/kratos/driver.NewDefaultDriver
        /data/apps/github.com/ory/kratos/driver/driver_default.go:40
github.com/ory/kratos/driver.MustNewDefaultDriver
        /data/apps/github.com/ory/kratos/driver/driver_default.go:57
github.com/ory/kratos/cmd/serve.glob..func1
        /data/apps/github.com/ory/kratos/cmd/serve/root.go:59
github.com/spf13/cobra.(*Command).execute
        /data/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
        /data/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /data/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/ory/kratos/cmd.Execute
        /data/apps/github.com/ory/kratos/cmd/root.go:30
main.main
        /data/apps/github.com/ory/kratos/main.go:27
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374] service_name=kratos service_version=
^[
```

_Server configuration_

As same as [contrib/quickstart/kratos/email-password/kratos.yml](contrib/quickstart/kratos/email-password/kratos.yml)

```yaml
version: v0.4.6-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  whitelisted_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verify
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/auth/login

    login:
      ui_url: http://127.0.0.1:4455/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: trace
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

```

**Expected behavior**

server started ok.

**Environment**

- golang version:  go1.15.2 linux/amd64
- Version: master,  ff3d0c75457a15598de535def47be1cfba4576ac
- Environment: Centos 7

**Additional context**
