### ISSUE TITLE
Kratos API flows behind oathkeeper using the kratos SDK results in an error 

### ISSUE THREAD

**Issue by xlanor** [ory/kratos#794]
**Describe the bug**

Connecting to kratos directly using the SDK with an API flow as demonstrated in ORY's react native sample works as expected.

However, when attempting to connect to kratos behind oathkeeper, the following error is returned.

` The HTTP Request Header included the "Cookie" key, indicating that this request was made by a Browser. The flow however was initiated as an API request. To prevent potential misuse and mitigate several attack vectors including CSRF, the request has been blocked. Please consult the documentation`

**Reproducing the bug**

Kratos' yml has the following under public:
```
serve:
  public:
    cors:
      enabled: true
      allowed_origins:
        - https://127.0.0.1:3000
        - https://127.0.0.1:3001
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
    base_url: http://127.0.0.1:4455/.ory/kratos/public/
  admin:
    base_url: http://kratos:4434/
```
Oathkeeper's access rules is set as the following

```
-
  id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /.ory/kratos/public
  match:
    url: "http://127.0.0.1:4455/.ory/kratos/public/<.*>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    -
      handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
```

Execute a `completeSelfServiceLoginFlowWithPasswordMethod` after retrieving the flowID with `initializeSelfServiceLoginViaAPIFlow`

**Expected behavior**

A cookie header should not be present as it is initalised using kratos' SDK.

**Environment**
- Docker
  Kratos: kratos:v0.5.3-alpha.1-sqlite (tried on 0.5.0, 0.5.1, 0.5.2)
  Oathkeeper: oathkeeper:v0.38.4-beta.1-alpine
