### ISSUE TITLE
Both return_to and default_browser_return_url are ignored

### ISSUE THREAD

**Issue by antons1** [ory/kratos#822]
**Describe the bug**

I am trying to set up a solution where kratos runs under identity.mydomain.com, but where other subdomains can identify through kratos (for instance local.mydomain.com when running locally). However, not matter what I do, my requests are always redirected to the ui_url configured for each flow.

I have tried removing all flow configuration, and in that instance I am redirected to https://www.ory.sh/kratos/docs/fallback/registration rather than the URL configured in default_browser_return_url

I have listed the needed URLs under whitelisted_return_urls, but there seems to be no validation at all - no matter what i put in the redirect_to query, I am just redirected either to ui_url or https://www.ory.sh/kratos/docs/fallback/registration

**Reproducing the bug**

1. Build server from the attached Dockerfile (running against a postgres DB)
2. Run the container
3. Call any self-service endpoint, e.g `curl http://localhost:4433/self-service/registration/browser?return_to=some.url`

Response is invariably: `<a href="[default_browser_return_url]/auth/registration?flow=[flow]">Found</a>` or `<a href="https://www.ory.sh/kratos/docs/fallback/registration=[flow]">Found</a>`

_Server logs_

```
time=2020-11-12T10:36:57Z level=info msg=Config file loaded successfully. audience=application path=/home/ory/.kratos.yaml service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=warning msg=
YOU ARE RUNNING ORY KRATOS IN DEV MODE.
SECURITY IS DISABLED.
DON'T DO THIS IN PRODUCTION!

audience=application service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=info msg=Courier worker started. audience=application service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=info msg=Starting the public httpd on: 0.0.0.0:4433 audience=application service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=kratos service_version=
time=2020-11-12T10:36:57Z level=info msg=Starting the admin httpd on: 0.0.0.0:4434 audience=application service_name=kratos service_version=
time=2020-11-12T10:36:59Z level=info msg=started handling request method=GET name=public#[url] remote=172.19.0.1:46442 request=/self-service/registration/browser?return_to=abc.d
time=2020-11-12T10:36:59Z level=info msg=completed handling request method=GET name=public#[url] remote=172.19.0.1:46442 request=/self-service/registration/browser?return_to=abc.d status=302 text_status=Found took=99.9µs
```

_Server configuration_

```yaml
serve:
  public:
    base_url: [url]
    cors:
      enabled: true
      allowed_origins:
        - [url]
        - [url]
        - [url]
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
        - HEAD
  admin:
    base_url: [url]

selfservice:
  default_browser_return_url: [url]
  whitelisted_return_urls:
    - [url]
    - [url]
    - [url]
  
  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: [url]

    settings:
      ui_url: [url]
      privileged_session_max_age: 5m

    recovery:
      enabled: true
      ui_url: [url]

    verification:
      enabled: true
      ui_url: [url]
      after:
        default_browser_return_url: [url]

    logout:
      after:
        default_browser_return_url: [url]

    login:
      ui_url: [url]
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: [url]
      after:
        password:
          hooks:
            -
              hook: session
session:
  cookie:
    domain: [url]

log:
  level: debug
  format: text
  leak_sensitive_values: true

identity:
  default_schema_url: file:/home/ory/identity.traits.schema.json

courier:
  smtp:
    connection_uri: [url]

version: v0.5.4-alpha.1
```

_Dockerfile_
```
FROM oryd/kratos:v0.5.4-alpha.1-sqlite
ENV DSN "postgres://postgres:testpostgrespwd@[docker-hostname]:5432/postgres?sslmode=disable&max_conns=20"
COPY kratos.yaml /home/ory/.kratos.yaml
COPY identity.traits.schema.json /home/ory/
CMD ["serve", "--dev"]
```

**Expected behavior**

In the case where `?return_to=url` is set to a value in `whitelisted_return_urls`, I expect the redirect location to be that URL, and in the case where there is no set ui_url, I expect to be redirected to the default url, not to a fallback error page.

**Environment**

- Version: v0.5.4
- Environment: Ubuntu (WSL) 18.04
- Docker Desktop (docker engine v19.03.13
