### ISSUE TITLE
Kratos v0.5.4-alpha.1 docker compose problems

### ISSUE THREAD

**Issue by hrstoyanov** [ory/kratos#846]
**Describe the bug**

Creating a simple dev environment with Docker compose, Kratos and Postgres is a real pain! 
The reason is that Postgres is know to be hard to detect when ready to accept db request on tcp port 5432 and this trips Kratos. For example, the below docker compose file does not work, because Kratos attempts to connect to Postgres which is not ready yet. And notice that the use of **depends on** is of no help and misleading:

```
version: '3.8'

services:
  kratos:
    image: oryd/kratos:v0.5.4-alpha.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    depends_on:
      - postgresd
    command:
        serve -c /etc/config/kratos/kratos.yml --dev
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    networks:
      - intranet

  postgresd:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
    intranet:
```

**Reproducing the bug**

_Server logs_

**Expected behavior**

Kratos should document a way to set up Postgres dev environment quickly and painlessly.

**Environment**

- Version: Kratos v0.5.4-alpha.1
- Environment: MacOS, Docker latest

**Additional context**

This is a well know, nasty issue with Postgres, workarounds are suggested [here](https://stackoverflow.com/questions/35069027/docker-wait-for-postgresql-to-be-running). Basically, the Kratos container can implement a trivial shell wait cycle and only launch once Postgres port 5432 is open:
```
...
    command:
        /bin/ash -c 'while !</dev/tcp/db/5432; do sleep 1; done; serve -c /etc/config/kratos/kratos.yml --dev'
```
Unfortunately, this is not possible, because the Kratos alpine image was built without **/bin/ash**   shell (or any shell really!), unlike the classic Alpine image:
```
docker run -it oryd/kratos:v0.5.4-alpha.1 /bin/ash
Error: unknown command "/bin/ash" for "kratos"
Run 'kratos --help' for usage.
unknown command "/bin/ash" for "kratos"
 docker run -it alpine /bin/ash
/ # 
```
Here are possible solutions I see:
- Just add the /bin/ash shell to the Kratos image, document the wait trick for Postgres users.
- People can burn their own docker image with /bin/ash added, but why?
- [I use this] Separate out the Postgres container into another docker compose or run it in Docker straight. Run Kratos and Postgres independently, waiting for Postgres to become available. Pretty ugly!
- Implement some wait capability in Kratos to depend on port (or wait fixed time). This is just for this Postgres workaround ...
