### ISSUE TITLE
Kratos Admin API return 409 when createIdentity is called simultaneously

### ISSUE THREAD

**Issue by ab316** [ory/kratos#861]
When the Kratos Typescript client Admin API's createIdentity method is called simultaneously with a freshly started Kratos instance (without any identities in the database), error 409 is returned as follows:

```
error: {
  code: 409,
  status: 'Conflict',
  message: 'failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already'
}
```

It seems like when Kratos creates the first user, it inserts the entry for the credential type (in my case it's "password") in the identity_credential_types table. With multiple requests at the same time, it tries to insert the same entry multiple times and fails.

**Reproducing the bug**

1. Start Kratos
1. Call the Kratos createIdentity client simulatenously e.g. using the example code below
1. Most of the time but not always, Kratos throws the error

Client code that makes requests to my server that then calls Kratos:
```
  await Promise.all(usersToAdd.map(async (user) => {
    console.log('Adding user', user);
    return await graphQl('createLocalUser', {
      input: {
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        type: 'local',
        password: user.password || 'secret',
      },
    }, token);
  }));
```

Method in my server that calls Kratos:
```
  public async createIdentity(email: string, firstName: string, lastName: string): Promise<string> {
    try {
      const id: CreateIdentity = {
        schema_id: `default`,
        traits: {
          name: {
            last: lastName,
            first: firstName,
            // second: 'hello',
          },
          email: email,
        },
      };
      logger.debug('Create Kratos identity: %O', id);
      const response = await this.adminEndpoint.createIdentity(id);
      return response.data.id;
    } catch (error) {
      if (error?.statusCode==409) {
        logger.error('User already exist in Kratos');
        throw new Error('User already exist in Kratos');
      }
      logger.error('Could not create Kratos user: %O', error.response?.data?.error?.message);
      throw new Error(error.response?.data?.error?.message);
    }
  }
```

_Server logs_
```
ion=
kratos_1             | time=2020-11-28T22:44:29Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:44:29Z level=info msg=Starting the public httpd on: 0.0.0.0:4433 audience=application service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:44:29Z level=info msg=Starting the admin httpd on: 0.0.0.0:4434 audience=application service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43526 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43528 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43530 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43532 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43542 request=/identities
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43526 request=/identities status=201 text_status=Created took=46.1414ms
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43530 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43532 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43532 request=/identities status=409 text_status=Conflict took=46.0482ms
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43530 request=/identities status=409 text_status=Conflict took=45.9592ms
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43528 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43528 request=/identities status=409 text_status=Conflict took=49.5882ms
kratos_1             | time=2020-11-28T22:45:16Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "identity_credential_types_name_idx" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* user-agent:axios/0.19.2] host:kratos:4434 method:POST path:/identities query:<nil> remote:192.168.16.7:43542 scheme:http] http_response=map[status_code:409] service_name=kratos service_version=
kratos_1             | time=2020-11-28T22:45:16Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=192.168.16.7:43542 request=/identities status=409 text_status=Conflict took=27.7992ms

```

_Server configuration_

```yaml
log:
  level: debug
  format: text

dsn: postgres://kratos:kratos@postgres:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://localhost:10020/.ory/kratos/public/
  admin:
    base_url: http://kratos:4434/

identity:
  default_schema_url: file:///etc/config/kratos/identity.traits.schema.json

selfservice:
  default_browser_return_url: http://localhost:10020/
  whitelisted_return_urls:
    - http://localhost:10020

  methods:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: azure-ad
            provider: microsoft
            client_id: SECRET
            client_secret: SECRET
            tenant: common
            mapper_url: file:///etc/config/kratos/oidc.azure-ad.jsonnet
            scope:
              - profile
              - email

  flows:
    error:
      ui_url: http://localhost:10020/error
    settings:
      ui_url: http://localhost:10020/settings
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: http://localhost:10020/recovery
    verification:
      enabled: false
      ui_url: http://localhost:10020/verify
      after:
        default_browser_return_url: http://localhost:10020/
    logout:
      after:
        default_browser_return_url: http://localhost:10020/auth/login
    login:
      ui_url: http://localhost:10020/auth/login
      lifespan: 100m
    registration:
      lifespan: 100m
      ui_url: http://localhost:10020/auth/register
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 16384
    iterations: 4
    salt_length: 16
    key_length: 16

courier:
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
```

**Traits Schema**
```
{
  "$id": "https://myrandomcompany.com/server/kratos/default/identity.traits.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "type": "string"
            },
            "last": {
              "type": "string"
            }
          }
        },
        "phone_number": {
          "type": "string"
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    }
  }
}
```

**Expected behavior**
The users should have been created without errors.

**Environment**
WSL-2
Docker compose

**Additional context**
Kratos image tag: v0.5.4
Kratos typescript client version: 0.5.4-alpha.1
