### ISSUE TITLE
Encountered self-service settings error is causing a crash

### ISSUE THREAD

**Issue by egimbernat** [ory/kratos#895]
**Describe the bug**
I'm integrating ORY suite in my app, so far was working good, but on password reset/recovery is crashing before returning password policiy validation error. This with super easy password that appear in multiple breaches. After all the flow is not updated and no error is returning to broswer.

**Reproducing the bug**

_Server logs_

```
kratos_1          | time=2020-12-10T18:19:19Z level=info msg=Encountered self-service settings error. func=github.com/ory/kratos/selfservice/flow/settings.(*ErrorHandler).WriteFlowError file=/home/ory/selfservice/flow/settings/error.go:107 audience=audit error=map[message:I[#/password] S[] the password does not fulfill the password policy because: the password has been found in at least 24230577 data breaches and must no longer be used. trace:
kratos_1          | github.com/ory/kratos/schema.NewPasswordPolicyViolationError
kratos_1          |     /home/ory/schema/errors.go:60
kratos_1          | github.com/ory/kratos/selfservice/strategy/password.(*Strategy).validateCredentials
kratos_1          |     /home/ory/selfservice/strategy/password/registration.go:224
kratos_1          | github.com/ory/kratos/selfservice/strategy/password.(*Strategy).continueSettingsFlow
kratos_1          |     /home/ory/selfservice/strategy/password/settings.go:201
kratos_1          | github.com/ory/kratos/selfservice/strategy/password.(*Strategy).submitSettingsFlow
kratos_1          |     /home/ory/selfservice/strategy/password/settings.go:140
kratos_1          | github.com/ory/kratos/x.NoCacheHandler.func1
kratos_1          |     /home/ory/x/nocache.go:18
kratos_1          | github.com/julienschmidt/httprouter.(*Router).ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334
kratos_1          | github.com/ory/nosurf.(*CSRFHandler).handleSuccess
kratos_1          |     /go/pkg/mod/github.com/ory/nosurf@v1.2.3/handler.go:197
kratos_1          | github.com/ory/nosurf.(*CSRFHandler).ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/ory/nosurf@v1.2.3/handler.go:148
kratos_1          | github.com/urfave/negroni.Wrap.func1
kratos_1          |     /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
kratos_1          | github.com/urfave/negroni.HandlerFunc.ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
kratos_1          | github.com/urfave/negroni.middleware.ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
kratos_1          | github.com/ory/kratos/x.glob..func1
kratos_1          |     /home/ory/x/clean_url.go:12
kratos_1          | github.com/urfave/negroni.HandlerFunc.ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
kratos_1          | github.com/urfave/negroni.middleware.ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
kratos_1          | github.com/urfave/negroni.(*Negroni).ServeHTTP
kratos_1          |     /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96
kratos_1          | github.com/rs/cors.(*Cors).Handler.func1
kratos_1          |     /go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207
kratos_1          | net/http.HandlerFunc.ServeHTTP
kratos_1          |     /usr/local/go/src/net/http/server.go:2042
kratos_1          | github.com/gorilla/context.ClearHandler.func1
kratos_1          |     /go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141
kratos_1          | net/http.HandlerFunc.ServeHTTP
kratos_1          |     /usr/local/go/src/net/http/server.go:2042
kratos_1          | net/http.serverHandler.ServeHTTP
kratos_1          |     /usr/local/go/src/net/http/server.go:2843
kratos_1          | net/http.(*conn).serve
kratos_1          |     /usr/local/go/src/net/http/server.go:1925
kratos_1          | runtime.goexit
kratos_1          |     /usr/local/go/src/runtime/asm_amd64.s:1374] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8 accept-encoding:gzip, deflate accept-language:en-US,en;q=0.5 cookie:csrf_token=yNZ2cQy+/H06zYP7rNOFXw200+q17FyVYJQdBSS/rdc=; ory_kratos_session=MTYwNzYyNDMyM3xEdi1CQkFFQ180SUFBUkFCRUFBQVJfLUNBQUVHYzNSeWFXNW5EQThBRFhObGMzTnBiMjVmZEc5clpXNEdjM1J5YVc1bkRDSUFJR05XUm1ScWNERXdOM2h2UTA1UlIxRm1ZMlpVTjNSVlJVUjRhWFY1VGxwWHyo4X6sIWdGTiXkib2nbxO07hDP2yNqxRdTUw1HMdxoAw== origin:http://127.0.0.1:8000 referer:http://127.0.0.1:8000/auth/profile?flow=9bc5ecd8-1ba1-4e44-9578-2f695427c99d user-agent:Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0 x-forwarded-for:172.26.0.4 x-forwarded-proto:http x-request-id:0e92a8d7-aa06-4c04-8f76-2509ebd2112d] host:127.0.0.1:8000 method:POST path:/self-service/settings/methods/password query:flow=9bc5ecd8-1ba1-4e44-9578-2f695427c99d remote:172.26.0.3:42818 scheme:http] service_name=ORY Kratos service_version=v0.5.5-alpha.1 settings_flow=&{9bc5ecd8-1ba1-4e44-9578-2f695427c99d browser 2020-12-10 19:18:43.879436409 +0000 UTC 2020-12-10 18:18:43.879436409 +0000 UTC http://127.0.0.1:8000/self-service/recovery/methods/link?flow=f1d0ba1b-d426-4035-bef6-98bdddb2fa8a&token=SUThjPYtJFWAtiQ30j465l3h6wHbDXW3  [{1060001 You successfully recovered your account. Please change your password or set up an alternative login method (e.g. social sign in) within the next 5.00 minutes. info [123 34 112 114 105 118 105 108 101 103 101 100 83 101 115 115 105 111 110 69 120 112 105 114 101 115 65 116 34 58 34 50 48 50 48 45 49 50 45 49 48 84 49 56 58 50 51 58 52 51 46 56 57 56 52 51 54 53 54 90 34 125]}] map[password:0xc000a91ea0 profile:0xc000a91f10] [] 0xc000acb5f0 show_form 10931f0b-b1f2-4edb-9a8f-f643bae36eb5 2020-12-10 18:18:43.879815 +0000 UTC 2020-12-10 18:18:43.899077 +0000 UTC}
```

_Server configuration_

```yaml
version: v0.5.4-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:8000/
  whitelisted_return_urls:
    - http://127.0.0.1:8000

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:8000/auth/500

    settings:
      ui_url: http://127.0.0.1:8000/auth/profile
      privileged_session_max_age: 5m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:8000/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verify
      after:
        default_browser_return_url: http://127.0.0.1:8000/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:8000/auth/login

    login:
      ui_url: http://127.0.0.1:8000/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:8000/auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 3
    salt_length: 16
    key_length: 32

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

```

**Expected behavior**

Return error to browser

**Environment**

- Docker compose
- Last available version till' now
- Envoy as reverse proxy

**Comment by aeneasr** [comment]
Thank you for the report, what do you mean by "crashing"? Does the process exit unexpectedly?

**Comment by aeneasr** [comment]
The logs do not indicate that there is a proper crash - they show that a validation error occurred. If it crashes, could you please share the full log?

**Comment by egimbernat** [comment]
That's all I got, let me try to reproduce it outside Docker and I'll keep you posted

**Comment by jfelten** [comment]
I believe I may be hitting this as well: https://github.com/ory/k8s/issues/206. I can reproduce this on both login and new registration whenever there is a database issue - ex: trying to insert a login that already exists. The init flows work fine, and registration forms render. I observe a memory leak in the kubernetes kratos container that eventually causes it to die and restart whenever this error is encountered after a few minutes.  As noted above this does not leave anything significant in the logs.

Looking at the code is appears from first glance that a database error causes an empty return: https://github.com/ory/kratos/blob/eb0399c2788c39a53c9f53233184fb420453bec2/selfservice/flow/registration/handler.go#L78. Could this be causing infinite retry recursions that break a running process?

**Comment by aeneasr** [comment]
https://www.ory.sh/kratos/docs/debug/performance-out-of-memory-password-hashing-argon2

**Comment by jfelten** [comment]
I adjusted the container memory as follow:
```
deployment:
  resources:
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 500m
     memory: 128Mi

```
and the kratos hasher memory to 1 MB:
```
kratos:
  hashers:
    argon2:
      memory: 1024000
```

Same issue. Other suggestions?

**Comment by jfelten** [comment]
One other thing - I notice the documentation advises against, but doesn't forbid, using subdomains ex: kratos.domain.com, secureapp.domain.com. Subdomains is how I am running and I was wondering if this could be contributing to the problem. Should my kubernetes ingress be setup security.domain.com/kratos, secrity.domain.com/secureapp? I will try running in dev mode and changing the ingress setup when time permits.

**Comment by jfelten** [comment]
logs:
```
time=2020-12-23T21:05:36Z level=info msg=started handling request method=GET name=public#https://kratos.domain.com remote=10.36.0.0 request=/self-service/registration/flows?id=6aacaf85-58fb-4e8c-b7dd-49d3aed34f3b
time=2020-12-23T21:05:36Z level=info msg=completed handling request method=GET name=public#https://kratos.domain.com remote=10.36.0.0 request=/self-service/registration/flows?id=6aacaf85-58fb-4e8c-b7dd-49d3aed34f3b status=410 text_status=Gone took=155.424µs
time=2020-12-23T21:05:36Z level=info msg=started handling request method=GET name=public#https://kratos.domain.com remote=10.36.0.0 request=/self-service/registration/browser
time=2020-12-23T21:05:36Z level=info msg=completed handling request method=GET name=public#https://kratos.domain.com remote=10.36.0.0 request=/self-service/registration/browser status=302 text_status=Found took=315.478µs
time=2020-12-23T21:05:36Z level=info msg=started handling request method=GET name=public#https://kratos.domain.com remote=10.36.0.0 request=/self-service/registration/flows?id=959d08c3-c984-4c1b-ab0d-38da8562fe40
time=2020-12-23T21:05:36Z level=info msg=completed handling request method=GET name=public#https://kratosdomain.com remote=10.36.0.0 request=/self-service/registration/flows?id=959d08c3-c984-4c1b-ab0d-38da8562fe40 status=200 text_status=OK took=125.121µs
time=2020-12-23T21:06:33Z level=debug msg=Running PostRegistrationPrePersistHooks. audience=application flow_method=password http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.9 cache-control:max-age=0 cookie:csrf_token=0ybLdATLOvM9Cykf1tzPf8c4ey4f/BmLFsyfUa0P81Y= origin:https://kratosui.domain.com referer:https://kratosui.domain.com/auth/registration?flow=959d08c3-c984-4c1b-ab0d-38da8562fe40 user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 x-forwarded-for:10.36.0.0 x-forwarded-proto:https x-request-id:90e86991e786bf935d8d842044f2950c] host:kratos.domain.com method:POST path:/self-service/registration/methods/password query:flow=959d08c3-c984-4c1b-ab0d-38da8562fe40 remote:10.34.0.5:47100 scheme:http] identity_id=4c3b00b0-cebb-4bd9-89f4-3f4cd0b9a87a service_name=kratos service_version=
time=2020-12-23T21:06:33Z level=info msg=Encountered self-service flow error. audience=audit error=map[message:I[#/] S[] an account with the same identifier (email, phone, username, ...) exists already] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.9 cache-control:max-age=0 cookie:csrf_token=0ybLdATLOvM9Cykf1tzPf8c4ey4f/BmLFsyfUa0P81Y= origin:https://kratosui.domain.com referer:https://kratosui.domain.com/auth/registration?flow=959d08c3-c984-4c1b-ab0d-38da8562fe40 user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 x-forwarded-for:10.36.0.0 x-forwarded-proto:https x-request-id:90e86991e786bf935d8d842044f2950c] host:kratos.domain.com method:POST path:/self-service/registration/methods/password query:flow=959d08c3-c984-4c1b-ab0d-38da8562fe40 remote:10.34.0.5:47100 scheme:http] registration_flow=&{959d08c3-c984-4c1b-ab0d-38da8562fe40 browser 2020-12-23 22:05:36.407106 +0000 UTC 2020-12-23 21:05:36.407106 +0000 UTC http://kratos.domain.com/self-service/registration/browser  [] map[oidc:0xc0008f0930 password:0xc0008f08c0] [] 2020-12-23 21:05:36.41038 +0000 UTC 2020-12-23 21:05:36.410399 +0000 UTC yDcWthLfv4LjdTNh0WeUEmIq9NGv75CuNUDvrKc1z78bEd3CFhSFcd5+Gn4Hu1ttpRKP/7ATiSUjjHD9Cjo86Q==} service_name=ORY Kratos service_version=v0.5.5-alpha.1
time=2020-12-23T21:06:33Z level=info msg=started handling request method=POST name=public#https://kratosdomian.com remote=10.36.0.0 request=/self-service/registration/methods/password?flow=959d08c3-c984-4c1b-ab0d-38da8562fe40
time=2020-12-23T21:06:33Z level=info msg=completed handling request method=POST name=public#https://kratos.domain.com remote=10.36.0.0 request=/self-service/registration/methods/password?flow=959d08c3-c984-4c1b-ab0d-38da8562fe40 status=302 text_status=Found took=258.035µs

```

**Comment by aeneasr** [comment]
```
kratos:
  hashers:
    argon2:
      memory: 1024000
```

sets the memory consumption to 1000 MB, not 1 MB. The minimum amount of memory is 16MB for Argon2.

**Comment by aeneasr** [comment]
> I notice the documentation advises against, but doesn't forbid, using subdomains ex: kratos.domain.com, secureapp.domain.com. 

Please share a link.

However, the observed issue is not a memory leak, it is caused by Argon2 which is set to a memory which k8s does not provide, which in turn causes k8s to kill the pod. You can probably see this in k8s logs and the pod status.

**Comment by jfelten** [comment]
changed to:
```
kratos:
  hashers:
    argon2:
      memory: 32000
```
no effect. Since this is an error scenario where it is trying to insert a duplicate record into the db, I don't believe this is caused by a hasher issue. I pasted the logs in a comment above. and am going through the code now.
