### ISSUE TITLE
Missing courier.smtp configuration property

### ISSUE THREAD

**Issue by b3j0f** [ory/kratos#903]
**Describe the bug**

Once I start the last docker image of kratos, with following configuration file :

```yaml
// ...
version: v0.5.5-alpha.1
courier:
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false

    from_address: no-reply@blabla.com

  template_override_path: /conf/courier-templates
```

I have this error message : ` courier.smtp: <nil> one or more required properties are missing`

**Reproducing the bug**

1. Copy past the default configuration file from documentation : https://www.ory.sh/kratos/docs/reference/configuration
2. Apply version and courier props upper
3. Make a docker file with this conf then start this container
4. Watch wonderful logs

_Server logs_

```
courier.smtp: <nil> one or more required properties are missing
```

_Server configuration_

```yaml
// ...
version: v0.5.5-alpha.1
courier:
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false

    from_address: no-reply@blabla.com

  template_override_path: /conf/courier-templates
```

**Expected behavior**

A server happy to start for me

**Environment**

- Version: v0.5.5-alpha1
- Environment: Debian, Docker, ...

**Additional context**

I have a good sunny day 😎
