### ISSUE TITLE
Can not set cookies config

### ISSUE THREAD

**Issue by Zippersk** [ory/kratos#927]
**Describe the bug**

I can't change cookies config via environment variables or config file.

**Reproducing the bug**

1. Run this simplified docker-compose from quickstart:
```yml
version: "3.7"

services:
  kratos:
    image: oryd/kratos:v0.5.5-alpha.1-sqlite
    ports:
      - "4433:4433" # public
    restart: unless-stopped
    environment:
      - SESSION_COOKIE_SAME_SITE=None
      - SESSION_COOKIE_DOMAIN=test
    command: serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      - ./contrib/quickstart/kratos/email-password:/etc/config/kratos
```
2. you can see that I set `SESSION_COOKIE_SAME_SITE` and `SESSION_COOKIE_DOMAIN` as env variables.
3. Go to http://localhost:4433/ and check http response from Kratos.
4. Same site policy and domain are not changed in `Set-Cookie` header

**Raw response:**
```
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Set-Cookie: csrf_token=ONX/mUdaxNVEcxKKcjvdWKIgEs/vA38HE8F8zFIv4PA=; Path=/; Domain=127.0.0.1; Max-Age=31536000; HttpOnly; SameSite=Lax
Vary: Origin
Vary: Cookie
X-Content-Type-Options: nosniff
Date: Sun, 20 Dec 2020 17:43:48 GMT
Content-Length: 19
```

**Image:**
![image](https://user-images.githubusercontent.com/6651236/102720285-b8cf1f80-42f3-11eb-9c8f-58400b7c4e44.png)

5. This also happens when you try change cookies settings with yml config.

_Server logs_

```
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=Config file loaded successfully. audience=application path=/etc/config/kratos/kratos.yml service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=warning msg=
kratos_1  |
kratos_1  | YOU ARE RUNNING ORY KRATOS IN DEV MODE.
kratos_1  | SECURITY IS DISABLED.
kratos_1  | DON'T DO THIS IN PRODUCTION!
kratos_1  |
kratos_1  |  audience=application service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=debug msg=Ignoring migration file sql because it does not match the file pattern. audience=application service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=debug msg=Ignoring migration file .gitignore because it does not match the file pattern. audience=application service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=Kratos is running migrations on every startup as DSN is memory.
kratos_1  |  audience=application service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=This means your data is lost when Kratos terminates.
kratos_1  |  audience=application service_name=kratos service_version=
kratos_1  | [POP] 2020/12/20 17:47:56 info - > identities
kratos_1  | [POP] 2020/12/20 17:47:56 info - > requests
kratos_1  | [POP] 2020/12/20 17:47:56 info - > sessions
kratos_1  | [POP] 2020/12/20 17:47:56 info - > errors
kratos_1  | [POP] 2020/12/20 17:47:56 info - > courier
kratos_1  | [POP] 2020/12/20 17:47:56 info - > errors
kratos_1  | [POP] 2020/12/20 17:47:56 info - > selfservice_verification
kratos_1  | [POP] 2020/12/20 17:47:56 info - > errors
kratos_1  | [POP] 2020/12/20 17:47:56 info - > courier_body_type
kratos_1  | [POP] 2020/12/20 17:47:56 info - > login_request_forced
kratos_1  | [POP] 2020/12/20 17:47:56 info - > create_profile_request_forms
kratos_1  | [POP] 2020/12/20 17:47:56 info - > continuity_containers
kratos_1  | [POP] 2020/12/20 17:47:56 info - > rename_profile_flows
kratos_1  | [POP] 2020/12/20 17:47:56 info - > create_recovery_addresses
kratos_1  | [POP] 2020/12/20 17:47:56 info - > create_messages
kratos_1  | [POP] 2020/12/20 17:47:56 info - > messages
kratos_1  | [POP] 2020/12/20 17:47:56 info - > settings
kratos_1  | [POP] 2020/12/20 17:47:56 info - > rename_identities_schema
kratos_1  | [POP] 2020/12/20 17:47:56 info - > flow_type
kratos_1  | [POP] 2020/12/20 17:47:56 info - > flow_rename
kratos_1  | [POP] 2020/12/20 17:47:56 info - > flow_fields_rename
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_session_token
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_session_revoke
kratos_1  | [POP] 2020/12/20 17:47:56 info - > update_recovery_token
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_verification_methods
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_verification_methods
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_verification_methods
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_verification_methods
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_verification_methods
kratos_1  | [POP] 2020/12/20 17:47:56 info - > add_verification_token
kratos_1  | [POP] 2020/12/20 17:47:56 info - > recovery_token_expires
kratos_1  | time=2020-12-20T17:47:56Z level=warning msg=Config version is 'v0.4.6-alpha.1' but kratos runs on version 'v0.5.5-alpha.1' audience=application service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=Courier worker started. audience=application service_name=kratos service_version=
kratos_1  | [POP] 2020/12/20 17:47:56 info - > identity_verifiable_address_remove_code
kratos_1  | [POP] 2020/12/20 17:47:56 info - Successfully applied 32 migrations.
kratos_1  | [POP] 2020/12/20 17:47:56 info - 0.1556 seconds
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name=kratos service_version=
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=kratos service_version= 
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=Starting the public httpd on: 0.0.0.0:4433 audience=application service_name=kratos service_version=    
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=kratos service_version= 
kratos_1  | time=2020-12-20T17:47:56Z level=info msg=Starting the admin httpd on: 0.0.0.0:4434 audience=application service_name=kratos service_version=     
kratos_1  | time=2020-12-20T17:47:59Z level=info msg=started handling request method=GET name=public#http://127.0.0.1:4433/ remote=192.168.160.1:46748 request=/
kratos_1  | time=2020-12-20T17:47:59Z level=info msg=completed handling request method=GET name=public#http://127.0.0.1:4433/ remote=192.168.160.1:46748 request=/ status=404 text_status=Not Found took=134.8µs
```

_Server configuration_

Same as quickstart.

```yaml
version: v0.4.6-alpha.1

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  whitelisted_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verify
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/auth/login

    login:
      ui_url: http://127.0.0.1:4455/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/auth/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

session:
  cookie:
    domain: test
    same_site: None
```

**Expected behavior**

Cookies settings should change when set as environment variables or in config file.
